### ISSUE TITLE
Pre-compiled AUR binary

### ISSUE THREAD

**Issue by koalagang** [PolyMC/PolyMC#100]
### Role

I use it on Arch.

### Suggestion

I'd like there to be a binary of PolyMC available on the AUR.

### Benefit

It would be a lot more convenient to be able to update PolyMC with my AUR helper but also not have to compile PolyMC.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

I am aware that PolyMC provides a binary which I can use to install it using `pacman -U` but this doesn't allow pacman to manage updates. The alternative is to download it from the Arch user repository but then I have to compile the binary myself. Seeing as you already provide a pre-compiled binary, could you please start maintaining it on the AUR? At the moment, there is a MultiMC binary available on the AUR so I feel like that is actually more convenient than using PolyMC.

**Comment by Scrumplex** [comment]
I would be willing to maintain such a package, though right now the binary is built with no specific version. That makes it hard to package.

**Comment by LennyMcLennington** [comment]
wdym "built with no specific version"?

> I would be willing to maintain such a package, though right now the binary is built with no specific version. That makes it hard to package.

**Comment by Scrumplex** [comment]
Well it's just versioned as `latest`: https://packages.polymc.org/latest/arch/

It's hard to package this, as there is no unique URL per version. You generally verify the files needed to build an Arch package using checksums. In this case you can't really do that as the file will change over time.

**Comment by Scrumplex** [comment]
Though looking into the package itself, I can see that the the package has an actual version. It's just the package file itself, that needs a version number attached.

**Comment by LennyMcLennington** [comment]
> Well it's just versioned as `latest`: https://packages.polymc.org/latest/arch/
> 
> It's hard to package this, as there is no unique URL per version. You generally verify the files needed to build an Arch package using checksums. In this case you can't really do that as the file will change over time.

There are unique URLs per version.

**Comment by Scrumplex** [comment]
![Screenshot](https://scrumplex.rocks/img/1643139602.png)

I would expect a version number in place of `latest`

**Comment by LennyMcLennington** [comment]
> I would expect a version number in place of `latest`

those exist

**Comment by Scrumplex** [comment]
Oh I see... :D

https://packages.polymc.org/

**Comment by LennyMcLennington** [comment]
Polymc-bin is on the AUR now. If you want to help maintain it leave a comment on https://aur.archlinux.org/packages/polymc-bin/
