### ISSUE TITLE
In-luncher java.

### ISSUE THREAD

**Issue by elchupe123** [PolyMC/PolyMC#1001]
### Role

I play minecraft in general 

### Suggestion

My suggestion is to creat a folder called java that contains java 8 and java 17 pre-installed in the luncher so new users would’t have to install java manually. Obiously to implement this, first we have to have an automatic java selector. 

### Benefit

This would make easier to install polyMc  and also with the java selector we wouldn’t have to select the right version of java in new instances.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by flowln** [comment]
See #7, #595 and #586. Those should cover the use-case you're proposing.
