### ISSUE TITLE
add Account setting for each instance

### ISSUE THREAD

**Issue by pcal43** [PolyMC/PolyMC#1022]
### Role

I use PolyMC to launch multiple modded MC instances for split screen play

### Suggestion

Provide a dropdown in the instance configuration for choosing an Account.  If chosen, the instance will always be launched using that user (ignoring the setting in the application dropdown)

### Benefit

I can more easily maintain multiple instances for different users.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

I have multiple instances for different users.  I have to remember to change the user before launching each one; forgetting to do so can result in player inventories getting lost.

Thanks.  I love PolyMC!

**Comment by pcal43** [comment]
Update here: I just realized that PolyMC has a CLI parameter for what I want (--profile).  That's perfect - I actually want to write a script that launches the instances together.  That's a better approach for my specific use case than what I describe above.

Or almost perfect: I'm hitting a different issue in that I don't seem to be able to launch multiple minecraft instances via PolyMC that way.  I assume this is by design so multiple PolyMCs don't step on one another.  I guess in my perfect world, the PolyMC cli could fork the minecraft process and then exit immediately.  I might do some digging.

UPDATE: yeah, it looks like #285 is what I would want.  That would so great.  Thanks again for everything you're doing here!

**Comment by SirLotsaLocks** [comment]
Bumping this, was about to request the same thing
