### ISSUE TITLE
authlib-injector integration

### ISSUE THREAD

**Issue by catfromplan9** [PolyMC/PolyMC#1027]
### Role

Custom self hosted authentication server

### Suggestion

Additional option for account type (next to offline/mojang/microsoft) which will authenticate through custom authentication server that is configured using authlib-injector

### Benefit

I like to say racial slurs, transphobic slurs, homophobic slurs, encourage suicide, and make antisemetic or other kinds of hateful bigoted comments in chat, but the new chat reports system makes this a liability. I know there are workarounds, but a workaround as advanced as custom auth server will fully prevent mojang from having any authority over it.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Make it similar to the add offline account button, that you need to have a premium account added already to access this feature. The github page for it is here so you can figure out how it works and implement that. The english documentation is not as good so you might need to learn mandarin chinese before you begin work on it. https://github.com/yushijinhun/authlib-injector

**Comment by Scrumplex** [comment]
We won't implement this.

See similar request at #943

**Comment by catfromplan9** [comment]
> We won't implement this.
> 
> See similar request at #943

Oh, but how is it against EULA? Just require legit account to be added.

**Comment by Scrumplex** [comment]
Not on our roadmap.

From my POV you should just install one of the mods that disable message signing or circumvent the system in a different way

**Comment by catfromplan9** [comment]
> Not on our roadmap.
> 
> From my POV you should just install one of the mods that disable message signing or circumvent the system in a different way

Those mods can get patched, yk. Mojang tries to fix it and make it faultproof. But alright thanks

**Comment by DikeKike** [comment]
PolyMC is SUPPOSED to be free software.
Implementing or even encouraging DRM makes it nonfree software, which is literally fascism.
I paid for Minecraft, so i have the right to do whatever i want with my copy of the game, including decompiling it, modifying it, running it in any way and under any circumstances i desire.
If I play on a private server with my friends, we have the RIGHT to call each other "nigger" as much as we like to. Neither Microsoft, nor Mojang, or anybody else has the right to stop us from doing so on our own server.
I demand that #50 gets merged in again, and that you add support for "custom auth server" accounts, customizable per account.
Another good idea is to add an option for choosing a default account per instance.
If you refuse to implement those things, we will do it and open a pull request.
If you reject it, we will fork PolyMC, and PolyMC's bearer token with it; then publish it.
If you try to combat our actions, you are violating the GNU general public license.

**Comment by DioEgizio** [comment]
> I like to say racial slurs, transphobic slurs, homophobic slurs, encourage suicide, and make antisemetic or other kinds of hateful bigoted comments in chat, but the new chat reports system makes this a liability. I know there are workarounds, but a workaround as advanced as custom auth server will fully prevent mojang from having any authority over it.

You should *really* work on yourself then

**Comment by DioEgizio** [comment]
> PolyMC is SUPPOSED to be free software. Implementing or even encouraging DRM makes it nonfree software, which is literally fascism. I paid for Minecraft, so i have the right to do whatever i want with my copy of the game, including decompiling it, modifying it, running it in any way and under any circumstances i desire. If I play on a private server with my friends, we have the RIGHT to call each other racial slurs as much as we like to. Neither Microsoft, nor Mojang, or anybody else has the right to stop us from doing so on our own server. I demand that #50 gets merged in again, and that you add support for "custom auth server" accounts, customizable per account. Another good idea is to add an option for choosing a default account per instance. If you refuse to implement those things, we will do it and open a pull request. If you reject it, we will fork PolyMC, and PolyMC's bearer token with it; then publish it. If you try to combat our actions, you are violating the GNU general public license.

what the hell, no you don't, and stop trolling

**Comment by Scrumplex** [comment]
That escalated quickly.

@DikeKike 
Do whatever the fuck you want. Stop being a Karen, just because we didn't want to implement a feature you want.
PolyMC will not gain functionality for authlib-injector or any other alternative authentication system for now. I described why in #943.

**Comment by catfromplan9** [comment]
> > I like to say racial slurs, transphobic slurs, homophobic slurs, encourage suicide, and make antisemetic or other kinds of hateful bigoted comments in chat, but the new chat reports system makes this a liability. I know there are workarounds, but a workaround as advanced as custom auth server will fully prevent mojang from having any authority over it.
> 
> You should _really_ work on yourself then

Nothing to work on, it's just my sense of humor.

**Comment by Scrumplex** [comment]
Quick reminder that you don't have any basis to "demand" anything here.

**Comment by DioEgizio** [comment]
> > > I like to say racial slurs, transphobic slurs, homophobic slurs, encourage suicide, and make antisemetic or other kinds of hateful bigoted comments in chat, but the new chat reports system makes this a liability. I know there are workarounds, but a workaround as advanced as custom auth server will fully prevent mojang from having any authority over it.
> > 
> > 
> > You should _really_ work on yourself then
> 
> Nothing to work on, it's just my sense of humor.

Well, if you use that """""sense of humor""""" here, it's a violation of our CoC

**Comment by DikeKike** [comment]
> what the hell, no you don't, and stop trolling

I do, i live in a free country and have the right to say whatever i want, whenever i want.
Free software implies absolute freedom, and not "freedom expect for these things and those things".
Please refrain from calling PolyMC "free software" if it is not actually free software, thank you.

**Comment by Scrumplex** [comment]
If you want absolute freedom (whatever that is), then go play Minetest.

Minecraft does not offer you that freedom.

**Comment by DioEgizio** [comment]
> > what the hell, no you don't, and stop trolling
> 
> I do, i live in a free country and have the right to say whatever i want, whenever i want. Free software implies absolute freedom, and not "freedom expect for these things and those things". Please refrain from calling PolyMC "free software" if it is not actually free software, thank you.

no you don't, read the Minecraft EULA, and stop trolling since you don't even know what free software means

**Comment by catfromplan9** [comment]
> > > > I like to say racial slurs, transphobic slurs, homophobic slurs, encourage suicide, and make antisemetic or other kinds of hateful bigoted comments in chat, but the new chat reports system makes this a liability. I know there are workarounds, but a workaround as advanced as custom auth server will fully prevent mojang from having any authority over it.
> > > 
> > > 
> > > You should _really_ work on yourself then
> > 
> > 
> > Nothing to work on, it's just my sense of humor.
> 
> Well, if you use that """""sense of humor""""" here, it's a violation of our CoC

Yeah I keep it in my server dont worry bro

**Comment by catfromplan9** [comment]
> If you want absolute freedom (whatever that is), then go play Minetest.
> 
> Minecraft does not offer you that freedom.

Technically speaking minecraft does offer that freedom since it is java so everything can be reverse engineered and modified. We have mod loaders for all that stuff as you know and of course the authlib injector project

**Comment by Scrumplex** [comment]
> > what the hell, no you don't, and stop trolling
> 
> Please refrain from calling PolyMC "free software" if it is not actually free software, thank you.

The software license does not cover what we do and don't accept into the codebase. You are free to maintain your own fork of the launcher. There is nothing preventing you from that.

**Comment by DikeKike** [comment]
> That escalated quickly.
> 
> @DikeKike Do whatever the fuck you want. Stop being a Karen, just because we didn't want to implement a feature you want. PolyMC will not gain functionality for authlib-injector or any other alternative authentication system for now. I described why in #943.



> Quick reminder that you don't have any basis to "demand" anything here.

Correct.
It would be easier for users and developers to merge in pull requests to make PolyMC free software, but if you insist that your project remains nonfree, I can't stop you.
We will simply fork PolyMC.
Trying to stop us from forking your project and your bearer token, is a GPL violation.


> > > what the hell, no you don't, and stop trolling
> > 
> > 
> > I do, i live in a free country and have the right to say whatever i want, whenever i want. Free software implies absolute freedom, and not "freedom expect for these things and those things". Please refrain from calling PolyMC "free software" if it is not actually free software, thank you.
> 
> no you don't, read the Minecraft EULA, and stop trolling since you don't even know what free software means

The Minecraft EULA does not say that you aren't allowed to reverse engineer, decompile, and hack the game for your own personal use.
If that was the case, Minecraft mods wouldn't be possible as they are.

**Comment by Scrumplex** [comment]
> > If you want absolute freedom (whatever that is), then go play Minetest.
> > Minecraft does not offer you that freedom.
> 
> Technically speaking minecraft does offer that freedom since it is java so everything can be reverse engineered and modified. We have mod loaders for all that stuff as you know and of course the authlib injector project

Minecraft is not free software. I didn't know there were any doubts about that.
If you think you can do whatever you want with Minecraft's codebase, then why don't you upload the decompiled (or better yet, mapped) codebase to GitHub or something?

**Comment by Scrumplex** [comment]
This is dumb. I am not sure if you actually understand what free software is. You are using "freedom" and "free software" as a front for piracy.

This issue has drifted off-topic.
