### ISSUE TITLE
CurseForge beta versions dosent shows on modpacks

### ISSUE THREAD

**Issue by OveR1337XD** [PolyMC/PolyMC#1029]
### Operating System

Windows

### Version of PolyMC

PolyMC 1.4.1

### Version of Qt

6.3.0

### Description of bug

As titled say CurseForge beta versions doesn't shows on modpacks. I am trying to download Enigmatica 2: Expert - Extended (E2E-E) but it doesn't show any version available for download and on curse forge its available but they are all betas.

### Steps to reproduce

Button

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by flowln** [comment]
That modpack doesn't allow third-party distribution, so PolyMC can't get it directly from the API. You'll need to get the modpack directly from CF and import it into PolyMC instead.
