### ISSUE TITLE
Version workarounds for mod updater

### ISSUE THREAD

**Issue by ryanccn** [PolyMC/PolyMC#1031]
### Role

Blah blah

### Suggestion

I want the mod updater to have the same options as the mod downloader, having options for minor version matches or any version.

### Benefit

So that some mods can be updated on previous versions that actually work on later versions

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

yes

**Comment by TechPro424** [comment]
Yes please

**Comment by Taryro55** [comment]
yes

**Comment by Dlanis** [comment]
I want this feature too
