### ISSUE TITLE
Improve UX in About Window

### ISSUE THREAD

**Issue by TayouVR** [PolyMC/PolyMC#1051]
### Role

I use PolyMC

### Suggestion

The PolyMC About window is very tall and the `About Qt` button is all the way at the bottom left. It should be somewhere at the top, maybe as a new tab

### Benefit

Some people with high DPI scaling or generally small displays can't see the `About Qt` button and have difficulties providing that information in support & issues therefore.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

![image](https://user-images.githubusercontent.com/31988415/184478925-bb846e7c-777d-4442-96f5-df4ff23b53c1.png)
Mockup:
![PolyMC-about-ui-edit](https://user-images.githubusercontent.com/31988415/184479059-23ef37b6-b58d-4ccc-bf38-3e2c73d1cfd0.png)

**Comment by Scrumplex** [comment]
Not sure if that's possible. The "About Qt" button just triggers an in-built dialog of Qt

**Comment by DioEgizio** [comment]
Yeah
However what we could do is resizing the window
Also I've seen some apps showing the Qt version that was used at compile time, maybe we could do that

**Comment by TayouVR** [comment]
I suppose just decreasing the default window size would be enough to avoid the button being off screen, yeah

**Comment by ZekeZDev** [comment]
Ill have a look into this issue
