### ISSUE TITLE
add a button to make a Roly Poly appear and roll

### ISSUE THREAD

**Issue by DioEgizio** [PolyMC/PolyMC#1057]
### Role

i use polymc

### Suggestion

I'd like a button to make a Roly Poly appear and start rolling

### Benefit

yes

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by RandomPrimary2004** [comment]
hmm.. seems like spam /j

**Comment by RaptaG** [comment]
It’s rollin’ time

**Comment by Madis0** [comment]
Just replace the cat image with a gif 😄

**Comment by LennyMcLennington** [comment]
> Just replace the cat image with a gif 😄

Gif is the worst image format that's still widely used today, no thanks.

**Comment by Madis0** [comment]
> Gif is the worst image format that's still widely used today, no thanks.

I agree, but anything else would require extra development.

**Comment by ZekeZDev** [comment]
I will look into adding this once I start working on custom backgrounds for now I am going to close this issue.
