### ISSUE TITLE
Newest Action-Build reloads Minecraft-Library every time

### ISSUE THREAD

**Issue by jitoxx** [PolyMC/PolyMC#1071]
### Operating System

Linux

### Version of PolyMC

PolyMc 1.4.0-da70a3a4 AppImage Version

### Version of Qt

Qt 6.2.4

### Description of bug

Every Time when i start one of my instances, Polymc reloads the Librarys and it semms that the Launcher has some saving problems

### Steps to reproduce

Just open PolyMC and try to launch an instance.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by DioEgizio** [comment]
known issue with develop

**Comment by jitoxx** [comment]
I see that PolyMC create a new Library folder inside of the instance. Maybe is that the Problem

**Comment by DioEgizio** [comment]
no, the issue was caused by #920
