### ISSUE TITLE
Ability to update mods compatible with the major version of the instance

### ISSUE THREAD

**Issue by TechPro424** [PolyMC/PolyMC#1072]
### Role

I play modded Minecraft.

### Suggestion

I want the ability to update mods compatible with the major version of the instance.

### Benefit

So that I can update mods that are marked as 1.19/1.19.1 compatible but work on 1.19.2

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Many 1.19 mods are not marked for 1.19.2 specifically, but do work on 1.19.2. However, when I try to update those mods (I downloaded them using the "major version" filter in the mod browser), I get this: `No valid version found for this mod. It's probably unavailable for the current game version / mod loader.` 

The only way to currently update them is to manually redownload each mod that has updates using the "major version" filter in the mod browser or change the instance version to 1.19, update all mods, and then change it back to 1.19.2, and then update them again (as some mods do have versions marked specifically for 1.19.2). However, both the methods take a lot of time.

Hence why I request the PolyMC devs to let us update the mods that are compatible with the major version of the instance.

**Comment by DioEgizio** [comment]
Duplicate of #1031

**Comment by TechPro424** [comment]
My bad; I only used the title of this issue while searching for duplicates. I probably shouldn't do that again.
