### ISSUE TITLE
Texts is poorly rendered like space in-between

### ISSUE THREAD

**Issue by Taskeren** [PolyMC/PolyMC#1074]
### Operating System

Windows

### Version of PolyMC

PolyMC 1.4.1

### Version of Qt

Qt 6.3.0

### Description of bug

![image](https://user-images.githubusercontent.com/17310943/185731885-39727970-791d-4ec8-98d9-46218a352db8.png)
![image](https://user-images.githubusercontent.com/17310943/185731923-e209b10a-616a-40ef-9612-ca0cbebf2f01.png)

The English texts are poorly rendered like space in-between, which cannot reproduce in MultiMC.

### Steps to reproduce

/

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by DioEgizio** [comment]
Cannot reproduce

**Comment by ZekeZDev** [comment]
Are you using a custom font or larger text scaling?

**Comment by Taskeren** [comment]
I didn't change any setting about fonts or text scaling.
I don't know if it's related to ClearType or something?
