### ISSUE TITLE
Process exited with code 1.

### ISSUE THREAD

**Issue by ghost** [PolyMC/PolyMC#1075]
### Version of PolyMC

PolyMC 1.4.1

### Version of Qt

QT 6.3.0

### Description of bug

Any 1.17+ version doesn't work. Launcher crashes immediately, even before getting any assets from Mojang. I have jdk-18.0.2.1 installed from Oracle website.

`PolyMC version: 1.4.1

Launched instance in offline mode

Minecraft folder is:
C:/Users/sxvcm/AppData/Roaming/PolyMC/instances/1.19.2/.minecraft

Java path is:
C:/Program Files/Java/jdk-18.0.2.1/bin/javaw.exe

Checking Java version...
Java is version 18.0.2.1, using 64 (amd64) architecture, from Oracle Corporation.

Main Class:
  

Native path:
  C:/Users/sxvcm/AppData/Roaming/PolyMC/instances/1.19.2/natives

Libraries:

Native libraries:

Params:
  

Window size: 854 x 480

Failed to reconstruct Minecraft assets.
Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms307m, -Xmx3072m, -Duser.language=en]

Minecraft process ID: 8512

Aug 18, 2022 8:57:43 PM org.polymc.EntryPoint listen
SEVERE: Exception caught from launcher.
java.lang.UnsupportedOperationException
	at java.base/java.util.AbstractList.add(AbstractList.java:153)
	at java.base/java.util.AbstractList.add(AbstractList.java:111)
	at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:162)
	at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:185)
	at org.polymc.EntryPoint.listen(EntryPoint.java:144)
	at org.polymc.EntryPoint.main(EntryPoint.java:74)

Aug 18, 2022 8:57:43 PM org.polymc.EntryPoint main
INFO: Exiting with 1
Process exited with code 1.`

### Steps to reproduce

Launch Minecraft 1.17 or higher.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by DioEgizio** [comment]
What CPU, what gpu, what OS

**Comment by ghost** [comment]
> What CPU, what gpu, what OS

Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz   2.00 GHz
Intel(R) HD Graphics 520
Windows 10

**Comment by DioEgizio** [comment]
Try redoing the instance, it can't find any game asset or library

**Comment by ghost** [comment]
Somehow it helped to launch Minecraft in Online mode. I tried to do it Offline and it worked for older versions.
