### ISSUE TITLE
bug when installing fabric for 1.16 combat 6

### ISSUE THREAD

**Issue by TimTheDestroyer** [PolyMC/PolyMC#1077]
### Version of PolyMC

PolyMC 1.4.1

### Version of Qt

Qt 6.3.0

### Description of bug

When I try to get fabric for 1.16 combat snasphot 6 the fabric loader works fine but it give an error saying net.fabricmc.intermediary has issues!
Error: Patch is not loaded yet.

### Steps to reproduce

Have an existing instance for 1.16 combat snapshot 6 or create a new one. Insall fabric into it by clickign the install fabric option after you click edit instance and it will give an error for  net.fabricmc.intermediary and it will have an x in a red circle next to it meanning the issue is there

![Bug report](https://user-images.githubusercontent.com/98670582/185765076-a6542ee4-05ec-4179-91e2-9c99086988d5.png)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Scrumplex** [comment]
There are no official intermediary mappings for that version, which is why the launcher fails to load there.
See https://github.com/FabricMC/intermediary/pull/20

**Comment by Scrumplex** [comment]
I should add that there is a workaround, by using the Intermediary Mappings provided by the Combat Reforged server.

1. Remove Fabric and Intermediary Mappings from your instance
2. On the sidebar click on `Add Empty`
3. Set the name to `Intermediary Mappings`
4. Set the UID to `net.fabricmc.intermediary`
5. On the sidebar click on `Customize` then `Edit`
6. Paste the code attached below
7. Save and close the editor
8. Add Fabric using the `Install Fabric` button normallt
9. Start the instance

Make sure you trust the JAR file that's provided by Combat Reforged. This is effectively like installing a mod, so you should make sure, that you trust its source.

```json
{
    "formatVersion": 1,
    "libraries": [
        {
            "name": "net.fabricmc:intermediary:1.16_combat-6",
            "url": "https://maven.combatreforged.com"
        }
    ],
    "name": "Intermediary Mappings",
    "order": 11,
    "releaseTime": "2020-10-15T21:22:36+00:00",
    "requires": [
        {
            "equals": "1.16_combat-6",
            "uid": "net.minecraft"
        }
    ],
    "type": "release",
    "uid": "net.fabricmc.intermediary",
    "version": "1.16_combat-6",
    "volatile": true
}
```
