### ISSUE TITLE
Sort Mods by Disabled

### ISSUE THREAD

**Issue by bassistracer** [PolyMC/PolyMC#1082]
### Role

I play funny block game

### Suggestion

Be able to sort mods by Disabled first

### Benefit

So that I can share my PolyMC instances with friends and allow them to easily select optional mods.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

This idea kinda popped up in my head while making a very specific and niche modpack for my tastes and I wanted to share it with friends; but I have no clue if said friends are able to handle the needed amount of RAM allocated to it to run it or what-have-you.
So, I figured I'd only leave the core mods enabled with the rest of the fluff disabled and able to enable at their ability; but then that'd just leave a bunch of random unchecked mods scattered all around the place. So, if we could group mods by what's disabled and what's enabled, that'd be very excellent. Thanks for reading.

**Comment by flowln** [comment]
you need to click the header thing on the enabled / disabled column, and it sorts it for you o.O
![sorting mods by enabled/disabled](https://user-images.githubusercontent.com/9145768/186030661-8d748680-02d5-4343-b5e9-af9f6f16c22f.png)

**Comment by bassistracer** [comment]
oh, my bad lmao
