### ISSUE TITLE
Better warning than "No Valid Version Found"

### ISSUE THREAD

**Issue by kubo6472** [PolyMC/PolyMC#1084]
### Operating System

Windows

### Version of PolyMC

PolyMC 1.4.1

### Version of Qt

6.3.0

### Description of bug

https://www.curseforge.com/minecraft/mc-mods/first-person-model/ This mod shows no compatible version for 1.18.2, while there is a download with 1.18 as the main version.

### Steps to reproduce

* Create an instance with some subversion: 1.18.2 in this case
* Open mods menu
* Click download mods
* Search for first-person-model
* Try to download it

### Suspected cause

Not treating subversions as compatible

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by DioEgizio** [comment]
?????
Not every mod made for 1.18 is automatically compatible with 1.18.2
Actually, 1.18.2 did a lot of breaking changes so most mods for 1.18 do *not* work on 1.18.2, so I don't get your point

If you want a less strict match click filter options and choose a less strict one

**Comment by kubo6472** [comment]
Oh, yeah, I see. It is there, but the less strict filter should match the version, yet it does not.

**Comment by DioEgizio** [comment]
Oh I get what you mean, that mod blocked access to third party launchers, we can't do anything about it

**Comment by kubo6472** [comment]
> Oh I get what you mean, that mod blocked access to third party launchers, we can't do anything about it

Only think I can imagine is show that error, that some modpacks show instead of "No Valid Version Found"

**Comment by DioEgizio** [comment]
then this is a duplicate of #697

**Comment by kubo6472** [comment]
Aight then, thanks for prompt support though :)
