### ISSUE TITLE
Aborting a download operation causes the application to hang

### ISSUE THREAD

**Issue by JuiceyBeans** [PolyMC/PolyMC#1085]
### Operating System

Linux

### Version of PolyMC

PolyMC 1.4.1

### Version of Qt

Qt 6.3.0

### Description of bug

When you press the "Abort" button quickly when launching an instance (even when the libraries have already been downloaded), downloading a mod/modpack, or exporting an instance the operation gets suspended, cannot be aborted, and the application as a whole becomes stuck and cannot be closed except by using xkill or restarting. This is really annoying when you accidentally download something you didn't mean to or clicked Launch Instance on accident

### Steps to reproduce

1. Launch an instance / Download a mod / Download a modpack / Export an instance
2. Press Abort immediately

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by ryanccn** [comment]
Can replicate

**Comment by DioEgizio** [comment]
Can reproduce too

**Comment by slendidev** [comment]
I am a bit confused, why is this closed? Has this been resolved?

**Comment by JuiceyBeans** [comment]
> I am a bit confused, why is this closed? Has this been resolved?

It was resolved a year ago but I'm not sure if it was on Poly or Prism
