### ISSUE TITLE
"Install Legacy Fabric" support

### ISSUE THREAD

**Issue by DioEgizio** [PolyMC/PolyMC#109]
### Role

I play modded mc

### Suggestion

I would like to have that feature. There's a currently open pr on multimc meta for that (https://github.com/MultiMC/meta/pull/5), but it was never merged

### Benefit

It would be nice

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by ZekeZDev** [comment]
This seems like a good idea.

**Comment by ghost** [comment]
Open this in [PolyMC/meta](https://github.com/PolyMC/meta) as well, so I remember to add the changes to the script. @DioEgizio

**Comment by ZekeZDev** [comment]
would it make sense to close this issue? I cant see any interest and legacy fabric seems to have some issues.

**Comment by Scrumplex** [comment]
If anyone actually wants to work on this feel free. It can probably be loosely based off #185
