### ISSUE TITLE
Auto-Backup Instance

### ISSUE THREAD

**Issue by AustinKautz** [PolyMC/PolyMC#1097]
### Role

Modded minecraft

### Suggestion

Auto-backup of instance would be neat

### Benefit

Broken mods / incompatibilities cause a headache at best and lost data at worst.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### TL;DR
Manual backups are neat, but auto backups are neater (and get me back into the game faster). Every time I tinker or update my mod list, I want to be assured data won't be lost, while also cutting the overhead of copying / moving instance files myself.

### Suggested implementation
* Periodically auto-backup an instance
  + Perform regular backups at toggleable run-times (before launching, after closing or before mod updates)
    + Compatibility / error warning before backup is saved
  + Toggle a backup as persistent with no deletion
  + Toggle how many backups to keep before oldest is deleted
* Right-click an instance for "Restore" option

### Issue Tracker
There is a 9 day old request for auto-backup of worlds; However, an auto-backup of instances would be a more PolyMC oriented feature IMO.

**Comment by ZekeZDev** [comment]
Seems to mostly duplicate #1076 I am going to close this so discussion can be continued there.
