### ISSUE TITLE
Provide a UI for setting a custom Client ID at runtime

### ISSUE THREAD

**Issue by oldherl** [PolyMC/PolyMC#11]
### Role

to use MS auth on non-official builds

### Suggestion

provide a UI (such as a text input box) for a custom Client ID to use at runtime instead of a compiled one

### Benefit

so that a PolyMC compiled and distributed by a distro can have the MS auth feature complied in without actually distributing the client ID. Let the user to register an ID from microsoft and use it.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Same as here:
https://github.com/MultiMC/Launcher/issues/4360

**Comment by ghost** [comment]
PolyMC already defaults to our Client ID. It works even if compiled without specifying a client ID.

**Comment by oldherl** [comment]
That leaves the default Client ID distributed, which may bring risks for PolyMC since malicious third-party clients may also use that Client ID.

**Comment by ghost** [comment]
understood, I'll work on this later if MultiMC doesn't implement it first.

**Comment by d-513** [comment]
I mean, what MultiMC is doing in their binaries is basically the same. You can extract the api key and use it maliciously from the binary.

**Comment by ghost** [comment]
that's what I was thinking, no reason to not include it now. We can always make a new one and if people consistently abuse then we can switch over to this.

**Comment by Jan200101** [comment]
MultiMC uses a secret system to store the Client ID and possibly obfuscates it at compile time.
Not once is it publicly exposed, and finding it requires a lot of digging and reversing data

**Comment by d-513** [comment]
> MultiMC uses a secret system to store the Client ID and possibly obfuscates it at compile time. Not once is it publicly exposed, and finding it requires a lot of digging and reversing data

its still public and easy to extract, https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=multimc-git#n55

**Comment by Jan200101** [comment]
"public" is a questionable statement
its unobfuscated within the binary but nothing is stopping the devs to add a layer of encryption ontop that could make the effort of getting the ID harder.

**Comment by d-513** [comment]
That is still public. When its on the client machine, its just a matter of time to get it back.

**Comment by Jan200101** [comment]
At the end there is no good way to do this
Either you setup a proxy that stores the client ID, but then the user is essentially MITM'd
or you put the client ID in the program but then you suffer from people using it to impersonate the project.

The solution that the MultiMC project took was keeping the ClientID in the public, until that was abused
Then it was put into a dedicated secret subproject with the ID, which won't stop those that try hard enough yes but it will stop most of those trying.

I won't doubt that the MultiMC project might put more work into that in the future to ensure things like the AUR situation won't happen
