### ISSUE TITLE
Bug when trying to start forge instance: No file detector is enabled 

### ISSUE THREAD

**Issue by Trial97** [PolyMC/PolyMC#1101]
### Operating System

Linux

### Version of PolyMC

$ polymc --version
Version 5.0-develop
Git ba3ac85356802130842c6ad6fb0c09b6f3c672c5

### Version of Qt

Qt 6.3.1

### Description of bug

Can't start any forge instance.

### Steps to reproduce

- Create a new instance
- Install recommended forge version
- Launch that instance
- The instance will fail to start with `No file detector is enabled`
The logs can be found here: https://mclo.gs/O60jjEW

Also is reproduced with any already installed forge instances 

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by DioEgizio** [comment]
I can reproduce. I think #1067 broke forgewrapper

**Comment by Scrumplex** [comment]
Very possible. I am thinking about reverting this change. I don't know right now why this causes issues with ForgeWrapper

**Comment by DioEgizio** [comment]
that pr also broke Quilt

**Comment by Scrumplex** [comment]
Sad

**Comment by Trial97** [comment]
Thanks!
