### ISSUE TITLE
Error while loading shared libraries: libfmt.so.8

### ISSUE THREAD

**Issue by hi563145** [PolyMC/PolyMC#1102]
### Operating System

Linux

### Version of PolyMC

Polymy 1.4.1

### Version of Qt

Qt 6.3.1-1

### Description of bug

When launching the game polymc would attempt to get libraries and login like usual but after that the game crashes and 
`Error while loading shared libraries: libfmt.so.8: cannot open shared object file: No such file or directory`.

### Steps to reproduce

A few seconds after hitting launch.

### Suspected cause

An archlinux update on the [fmt](https://archlinux.org/packages/extra/x86_64/fmt/) package yesterday. I can try to downgrade to previous version but there are some packages that rely on the latest version.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Scrumplex** [comment]
You probably have MangoHud enabled. Rebuilding your mangohud package should fix it. (It did for me a few weeks ago, when fmt 9 was in Arch testing)

**Comment by DioEgizio** [comment]
I think this can be closed, because it's definitely not in our end

**Comment by roworu** [comment]
Confirmed! After cleanbuild mangohud package, issue resolves. Thank you, @Scrumplex

**Comment by hi563145** [comment]
Yup it worked after a clean rebuild. I should have checked other things before creating this. Thanks.
