### ISSUE TITLE
PolyMC built on Asahi Linux (Linux on M1 Mac) don't let run Minecraft supposing different architecture between java and system

### ISSUE THREAD

**Issue by cmalvi** [PolyMC/PolyMC#1106]
### Operating System

Linux

### Version of PolyMC

PolyMC 1.4.1

### Version of Qt

Qt 6.3.1

### Description of bug

Checking Java version...
Java is version 18.0.2, using 64 (aarch64) architecture, from N/A.

Your Java architecture is not matching your system architecture. You might want to install a 64bit Java version.

### Steps to reproduce

Build PolyMC adding aarch64 to platform
it build successfully
try to run the game after initial setup

### Suspected cause

Maybe a proper support for aarch64 from PolyMC could help? because the launcher seems to recognize itselves as different from aarch64

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by r58Playz** [comment]
> ### Operating System
> 
> Linux
> ### Version of PolyMC
> 
> PolyMC 1.4.1
> ### Version of Qt
> 
> Qt 6.3.1
> ### Description of bug
> 
> Checking Java version... Java is version 18.0.2, using 64 (aarch64) architecture, from N/A.
> 
> Your Java architecture is not matching your system architecture. You might want to install a 64bit Java version.
> ### Steps to reproduce
> 
> Build PolyMC adding aarch64 to platform it build successfully try to run the game after initial setup
> ### Suspected cause
> 
> Maybe a proper support for aarch64 from PolyMC could help? because the launcher seems to recognize itselves as different from aarch64
> ### This issue is unique
> 
>     * [x]  I have searched the issue tracker and did not find an issue describing my bug.

~~Most likely due to graphics acceleration. Send logs~~
EDIT: You also need LWJGL for Linux aarch64. See https://github.com/PolyMC/PolyMC/pull/1033.

**Comment by Scrumplex** [comment]
This is fixed in #1033

**Comment by cmalvi** [comment]
> EDIT: You also need LWJGL for Linux aarch64. See https://github.com/PolyMC/PolyMC/pull/1033.

I can't see any direct info about, however I've installed it from aur but how can I add it to PolyMC?

**Comment by cmalvi** [comment]
> This is fixed in #1033 

So I just need to wait right?

**Comment by r58Playz** [comment]
> > EDIT: You also need LWJGL for Linux aarch64. See #1033.
> 
> I can't see any direct info about, however I've installed it from aur but how can I add it to PolyMC?

You need to manually build https://github.com/Scrumplex/PolyMC/tree/multi-arch-support (you should be able to modify the pkgbuild to clone from there) and use https://r58playz.github.io/meta-polymc/ as the metaserver (do note it is a fair bit out of date so it doesn't have 1.19.2)

**Comment by cmalvi** [comment]
> > > EDIT: You also need LWJGL for Linux aarch64. See #1033.
> > 
> > 
> > I can't see any direct info about, however I've installed it from aur but how can I add it to PolyMC?
> 
> You need to manually build https://github.com/Scrumplex/PolyMC/tree/multi-arch-support (you should be able to modify the pkgbuild to clone from there) and use https://r58playz.github.io/meta-polymc/ as the metaserver (do note it is a fair bit out of date so it doesn't have 1.19.2)

I don't kown how to modify pkgbuild correctly for this, but i'm building now a portable version so i can test it.
How can i change the metaserver?

**Comment by DioEgizio** [comment]
> > > > EDIT: You also need LWJGL for Linux aarch64. See #1033.
> > > 
> > > 
> > > I can't see any direct info about, however I've installed it from aur but how can I add it to PolyMC?
> > 
> > 
> > You need to manually build https://github.com/Scrumplex/PolyMC/tree/multi-arch-support (you should be able to modify the pkgbuild to clone from there) and use https://r58playz.github.io/meta-polymc/ as the metaserver (do note it is a fair bit out of date so it doesn't have 1.19.2)
> 
> I don't kown how to modify pkgbuild correctly for this, but i'm building now a portable version so i can test it. How can i change the metaserver?

go in settings - APIs and change the metaserver there
also remove the meta folder on your polymc data dir

**Comment by cmalvi** [comment]
Doesn’t work for me but no problem, I’ll wait for a better compatibility because Is just for testing.

Thanks for help

**Comment by DioEgizio** [comment]
This can probably be closed

**Comment by Scrumplex** [comment]
Completed in #1033
