### ISSUE TITLE
MangoHud not working on the Flatpak version

### ISSUE THREAD

**Issue by C-512L** [PolyMC/PolyMC#1112]
### Operating System

Linux

### Version of PolyMC

PolyMC 1.4.1

### Version of Qt

Qt 5.15

### Description of bug

The mangohud option doesn't show up when the game is running. Also it floods the logs with:
```
ERROR: ld.so: object 'libMangoHud_dlsym.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libMangoHud.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
```

### Steps to reproduce

1. Install both PolyMC and MangoHud through Flathub
2. Open the launcher
3. Add an account
4. Create a new instance
5. Enable MangoHud  through the Settings menu
6. Launch it

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by orowith2os** [comment]
Could you give [this](https://github.com/flathub/org.polymc.PolyMC/issues/13#issuecomment-1141368225) a try? Also, might be a good idea for PolyMC to integrate this launch script as the default option inside of a Flatpak environment.

**Comment by C-512L** [comment]
Yes, it works fine adding `/usr/lib/extensions/vulkan/MangoHud/bin/mangohud --dlsym` (Gamemode works fine on flatpak)  as the wrapper command. I think the launcher should check wether the mangohud binary is available in path or his flatpak location before showing the checkbox as clickable.

**Comment by Scrumplex** [comment]
> I think the launcher should check wether the mangohud binary is available in path or his flatpak location before showing the checkbox as clickable.

The launcher doesn't use the mangohud helper script you mentioned, but sets the necessary environment variables itself. There is a PR, that will disable/enable the checkboxes depending on if the necessary tools/libraries were found: https://github.com/PolyMC/PolyMC/pull/1034
