### ISSUE TITLE
Automatically refresh account on session expiry

### ISSUE THREAD

**Issue by LostLuma** [PolyMC/PolyMC#1124]
### Role

I play vanilla and lightly modded Minecraft

### Suggestion

Automatically refresh account on session expiry

### Benefit

Users can keep the launcher open for 24+ hours and start a new instance without needing to go to the accounts menu to manually hit "refresh"

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Minecraft sessions seem to expire after 24 hours, meaning that keeping the launcher open and starting a new instance on a previously used account will start the game with an already expired session. I think it would make more sense to keep track of the expiry time for every account and fetch a new session when it's close to or already expired, as to not require restarting the game an extra time trying to log into a multiplayer server.

**Comment by SmilerRyan** [comment]
To fix one of the issues (preventing restart of the launcher), it could refresh the selected account when launching an instance.
Regarding the in-game expiry, I've used [mods like these](https://www.curseforge.com/minecraft/mc-mods/oauth) to re-login ingame, not too sure what the launcher can do here though.

**Comment by LostLuma** [comment]
> it could refresh the selected account when launching an instance

This is what I'm looking for, as I close the game instance I use with my main account and on re-open the next day the session is expired.
