### ISSUE TITLE
[Arch Linux] Can't launch any instance in online mode (Microsoft account)

### ISSUE THREAD

**Issue by Jorma17** [PolyMC/PolyMC#1132]
### Operating System

Linux

### Version of PolyMC

PolyMC 1.4.2

### Version of Qt

Qt 6.3.2

### Description of bug

This has been happening ever since I updated to 1.4.2. Whenever I try to launch an instance in online mode, the loading screen says "Getting the library files from Mojang..." and after that it tells that the game failed to launch. 

```
Instance update failed because: Game update failed: it was impossible to fetch the required libraries.
Reason:
Job 'Libraries for instance PvP' failed to process:
https://files.multimc.org/maven/org/apache/logging/log4j/log4j-api/2.16.0/log4j-api-2.16.0.jar
https://files.multimc.org/maven/org/apache/logging/log4j/log4j-core/2.16.0/log4j-core-2.16.0.jar
https://files.multimc.org/maven/org/apache/logging/log4j/log4j-slf4j18-impl/2.16.0/log4j-slf4j18-impl-2.16.0.jar
```
This happens on Vanilla, Fabric and Forge. Tested on version 1.19.2 (fresh instance), 1.18.2, 1.17.1 and 1.12.2
I tried to relogin to my account and reinstall the app but it still didn't work. Package is polymc-bin from the AUR

### Steps to reproduce

Install the polymc-bin package from the AUR
Log into your account and create a new instance
Try to launch the instance
It tries to get some library files from Mojang and fails to launch 

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by r58Playz** [comment]
Remove meta directory from the parent directory of the instances folder and it will work

**Comment by Jorma17** [comment]
Works now, thanks!
