### ISSUE TITLE
Launching any rd pre-classic version fails with exception

### ISSUE THREAD

**Issue by Strultz** [PolyMC/PolyMC#1145]
### Operating System

Windows

### Version of PolyMC

PolyMC 1.4.1, 1.4.2, develop

### Version of Qt

Qt 6.3.1

### Description of bug

When trying to launch any preclassic (rd-) version, the launch fails with exception:
```
Sep 15, 2022 12:03:47 AM org.polymc.EntryPoint listen
SEVERE: Exception caught from launcher.
java.lang.UnsupportedOperationException
	at java.util.AbstractList.add(AbstractList.java:148)
	at java.util.AbstractList.add(AbstractList.java:108)
	at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:162)
	at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:185)
	at org.polymc.EntryPoint.listen(EntryPoint.java:144)
	at org.polymc.EntryPoint.main(EntryPoint.java:74)
Sep 15, 2022 12:03:47 AM org.polymc.EntryPoint main
INFO: Exiting with 1
```

### Steps to reproduce

1. Create an instance with any pre-classic version
2. Launch the instance
3. ...

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Scrumplex** [comment]
Technical background:

This happens with any Minecraft version that does not take any parameters. In that case we initialize an empty list using `Collections.<String>emptyList()` (<https://github.com/PolyMC/PolyMC/blob/1ca2be0039c64f53631a15f72e7c3739cae3e562/libraries/launcher/org/polymc/impl/OneSixLauncher.java#L61>), which doesn't allow later modification, when later down the line, `--width` and `--height` parameters are added.

**Comment by Scrumplex** [comment]
@Strultz As a workaround for now you can tick the "Start Minecraft maximized" setting for your instance which should prevent this error from happening.
