### ISSUE TITLE
Ability to set Useragent string

### ISSUE THREAD

**Issue by cyber01** [PolyMC/PolyMC#1147]
### Role

modded minecraft

### Suggestion

New settings

### Benefit

Access to all curseforge mods (mimic to curseforge launcher)

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

As you know, some mods cannot be downloaded through third-party launchers. the owners have banned the ability to download through third-party launchers. And since Curseforge and PolyMC both use the Curseforge API, which means the validation can be by useragent. Alternatively, you can add the ability to specify the useragent field and then we will access the Curseforge API supposedly on behalf of the curseforge launcher and perhaps this will help download all mods without restrictions

**Comment by DioEgizio** [comment]
alrready there tbh. but cf doesn't check per-user agent, but per-api key. anyways, it's all in settings- APIs. this can be closed.

**Comment by flowln** [comment]
Indeed, you can already set the UA in the API page.
