### ISSUE TITLE
[develop] viewing some rpacks like classic 3d from cf causes a segmentation fault

### ISSUE THREAD

**Issue by DioEgizio** [PolyMC/PolyMC#1153]
### Operating System

Windows, macOS, Linux, Other

### Version of PolyMC

develop

### Version of Qt

Qt 6.3.0

### Description of bug

viewing some rpacks like classic 3d from cf causes a segmentation fault

### Steps to reproduce

- download classic-3d from cf, e.g. https://www.curseforge.com/minecraft/texture-packs/classic-3d/files/3898577
- add it to the rpack section of an instance
- click on it

### Suspected cause

weird symbols in the zip name maybe?

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Scrumplex** [comment]
This is because that pack uses color codes we don't support. I can try to implement some of them and ignore the ones we can't support

**Comment by DioEgizio** [comment]
we could just ignore it, better than like, seeing the launcher segfaulting :p
