### ISSUE TITLE
Crashing when trying to install FTB Modpack

### ISSUE THREAD

**Issue by nitrog0d** [PolyMC/PolyMC#1155]
### Operating System

Windows

### Version of PolyMC

PolyMC 1.4.2

### Version of Qt

Qt 6.3.1

### Description of bug

Crashing when trying to Install FTB pack

### Steps to reproduce

* Add Instance
* Select FTB
* Choose one of their packs (Tested with FTB One and FTB OceanBlock, both crashes)
* Click OK to install the modpack

### Suspected cause

fileIds array is empty on request to CurseForge
![image](https://user-images.githubusercontent.com/31241699/191348484-c41a772f-a556-4764-af92-ca5889f60be0.png)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by genshinBLANK** [comment]
seems like a skill issue to me.

**Comment by TheLostTree** [comment]
omg genshinBLANK

**Comment by DioEgizio** [comment]
Are you telling me they broke their API **AGAIN**?


AAAAAAAAAAAAAAAAA

**Comment by DioEgizio** [comment]
Seems to work now though

**Comment by nitrog0d** [comment]
Nope, it doesn't, just tried again.

**Comment by DioEgizio** [comment]
Did you change user agent?

**Comment by nitrog0d** [comment]
Yes, to match CurseForge's
Looks like that was the issue, sorry lol, thanks
