### ISSUE TITLE
Mod icons look weird/blurred in 125% display scale

### ISSUE THREAD

**Issue by DerpDerpling** [PolyMC/PolyMC#1159]
### Operating System

Windows

### Version of PolyMC

PolyMC 1.4.1

### Version of Qt

Qt 6.3.0

### Description of bug

Mod icons look blurred/weird on a monitor with 125% windows scale in the mod downloader

an example of the image with 125% windows scale
![image](https://user-images.githubusercontent.com/57187871/191658377-6f85dd88-1a2c-4be2-8e79-ffbab09325b9.png)

and an example with 100%
![image](https://user-images.githubusercontent.com/57187871/191658468-c0fb5c4b-1831-4594-a69c-4c5a8a5910ec.png)

### Steps to reproduce

go to display settings and change your display scale to 125%, then go to the mod downloader, then the mod icons will look weird

### Suspected cause

i feel like ([#818](https://github.com/PolyMC/PolyMC/pull/818)) might be the cause of the issue, but im not sure

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by DioEgizio** [comment]
I can reproduce
