### ISSUE TITLE
PolyMC is not written in Rust

### ISSUE THREAD

**Issue by cozyGalvinism** [PolyMC/PolyMC#116]
### Operating System

Other

### Description of bug

I expected to find a launcher written in chad Rust but was met with disappointment when I saw that it's written it lame old virgin C++. If you follow the reproduction steps, you can see that the first command lists an alarming amount of `*.cpp` files. These are source code written in C++, an obsolete and dangerous programming language. The second command produces no output at all, which suggests that PolyMC is, in fact, not written in Rust. Rust is a modern, safe programming language, featuring fearless abstractions and zero-cost concurrency. It's objectively superior to C++ and every other language in every way, therefore PolyMC should be rewritten in Rust as soon as possible.

### Steps to reproduce

1. In the PolyMC source directory, run `find -name '*.cpp'`, followed by `find -name '*.rs'`.

### Suspected cause

An alarming hostility against Rust.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Scrumplex** [comment]
based

**Comment by d-513** [comment]
* PolyMC blocked cozyGalvinism
* PolyMC has locked and limited conversation to collaborators

**Comment by Scrumplex** [comment]
Wait I *am* a collaborator.

**Comment by Scrumplex** [comment]
@cozyGalvinism try asking upstream if they wanna move to Rust

**Comment by d-513** [comment]
`find` is not a tool developed by PolyMC. Please consult your coreutils vendor's issue tracker for assistance.

**Comment by ghost** [comment]
If 1 more person suggests to write PolyMC in Rust I'm unironically going to rewrite it in C

**Comment by d-513** [comment]
@binex-dsk you should rewrite it in rust

**Comment by DioEgizio** [comment]
lmao

**Comment by Sightem** [comment]
NO

**Comment by LennyMcLennington** [comment]
if you really loved rust you would be using fd not find
also the fact that it's not written in rust is a feature not a bug

**Comment by d-513** [comment]
> if you really loved rust you would be using fd not find
> 
> also the fact that it's not written in rust is a feature not a bug

this was ironic lenny

**Comment by LennyMcLennington** [comment]
> this was ironic lenny

I know, so I'm not sure why you said that

**Comment by d-513** [comment]
@LennyMcLennington because yes
Also you need to unpin this issue because it's still pinned

**Comment by cozyGalvinism** [comment]
Please reopen this issue, as it is not resolved. PolyMC is still not written in Rust :(

**Comment by d-513** [comment]
Based swurl

**Comment by NyaomiDEV** [comment]
cringe, rewrite this in raw x86 assembly language then we'll talk

**Comment by unexploredtest** [comment]
Is this a troll?

**Comment by d-513** [comment]
> Is this a troll?

Yes everybody here is meming

**Comment by LennyMcLennington** [comment]
Sorry fun is banned now
![big-brother-1984](https://user-images.githubusercontent.com/28272981/151867325-29885ee3-d5e1-4bbe-9ad1-21b26ee22c91.jpg)

**Comment by Scrumplex** [comment]
this is not a troll

**Comment by unexploredtest** [comment]
> Operating System
Other

Are they using an OS written in Rust? /j

**Comment by d-513** [comment]
> > Operating System
> 
> Other
> 
> 
> 
> Are they using an OS written in Rust? /j

https://www.redox-os.org

**Comment by unexploredtest** [comment]
> > > Operating System
> > 
> > 
> > Other
> > Are they using an OS written in Rust? /j
> 
> https://www.redox-os.org

Wow, they're playing Minecraft on that? What a chad /j

**Comment by ghost** [comment]
rule 1: please respect the janitorial staff

this includes not joking about rewrites in rust. Yes I am big brother, cope seethe mald

**Comment by ghost** [comment]
rule 2: Rewrite PolyMC in Rust

**Comment by LennyMcLennington** [comment]
rule 14: do not disagree with the moderators or we will ban you

**Comment by ghost** [comment]
rule 83: do not do anything without seeking approval from me

**Comment by LennyMcLennington** [comment]
1.

**Comment by lovetocode999** [comment]
Y'all are clogging up the inboxes of everyone who is following this
issue or following the repo: please **shush**.

On Mon Jan 31, 2022 at 8:00 PM MST, LennyMcLennington wrote:
> Closed #116.
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/PolyMC/PolyMC/issues/116#event-5985288066
> You are receiving this because you are subscribed to this thread.
>
> Message ID: ***@***.***>

--
~ Lovetocode999

**Comment by NyaomiDEV** [comment]
jesus flippin christ

**Comment by DoubleHypercube** [comment]
this is a :popcorn: moment

**Comment by korewaChino** [comment]
Update: the PolyMC core is now being rewritten in Rust https://github.com/korewaChino/libpolymc

**Comment by DioEgizio** [comment]
based

**Comment by ghost** [comment]
> Update: the PolyMC core is now being rewritten in Rust https://github.com/korewaChino/libpolymc

No

**Comment by d-513** [comment]
Yes

**Comment by DioEgizio** [comment]
libpolymc based

**Comment by obj-obj** [comment]
If you want to rewrite it in Rust do it yourself

I like Rust myself but QT support right now is ass, it needs to mature more

**Comment by d-513** [comment]
> If you want to rewrite it in Rust do it yourself
> 
> I like Rust myself but QT support right now is ass, it needs to mature more

<h1>Joke</h1>

**noun**
something said or done to provoke laughter or cause amusement, as a witticism, a short and amusing anecdote, or a prankish act: He tells very funny jokes. She played a joke on him.
something that is amusing or ridiculous, especially because of being ludicrously inadequate or a sham; a thing, situation, or person laughed at rather than taken seriously; farce: Their pretense of generosity is a joke. An officer with no ability to command is a joke.

**verb (used without object), joked, jok·ing.**
to speak or act in a playful or merry way: He was always joking with us.
to say something in fun or teasing rather than in earnest; be facetious: He didn't really mean it, he was only joking.

**verb (used with object), joked, jok·ing.**
to subject to jokes; make fun of; tease.
to obtain by joking: The comedian joked coins from the audience.

**Comment by obj-obj** [comment]
> > If you want to rewrite it in Rust do it yourself
> > I like Rust myself but QT support right now is ass, it needs to mature more
> 
> # Joke
> 
> **noun** something said or done to provoke laughter or cause amusement, as a witticism, a short and amusing anecdote, or a prankish act: He tells very funny jokes. She played a joke on him. something that is amusing or ridiculous, especially because of being ludicrously inadequate or a sham; a thing, situation, or person laughed at rather than taken seriously; farce: Their pretense of generosity is a joke. An officer with no ability to command is a joke.
> 
> **verb (used without object), joked, jok·ing.** to speak or act in a playful or merry way: He was always joking with us. to say something in fun or teasing rather than in earnest; be facetious: He didn't really mean it, he was only joking.
> 
> **verb (used with object), joked, jok·ing.** to subject to jokes; make fun of; tease. to obtain by joking: The comedian joked coins from the audience.

I throw
