### ISSUE TITLE
Option to add a Microsoft account is disabled on first launch of PolyMC

### ISSUE THREAD

**Issue by TheMCNerd2017** [PolyMC/PolyMC#1160]
### Operating System

Windows

### Version of PolyMC

PolyMC 5.0-develop

### Version of Qt

Qt 5.15.5

### Description of bug

Upon first launching PolyMC and going through initial config, the option to add a Microsoft account is entirely unavailable. Upon closing and reopening the launcher, the option is enabled and works as expected.

### Steps to reproduce

1. Launch PolyMC for the first time.
2. Complete the initial setup.
3. Go to accounts setting page.
4. Notice that 'Add Microsoft' is grayed out and right-click menu does not show option to add a Microsoft Account.
5. Close PolyMC and reopen it.
6. Go back to accounts setting page.
7. Notice that the disabled Microsoft Account options are now re-enabled and work correctly.

### Suspected cause

Hovering over the grayed out Microsoft Account button states that "No Microsoft Authentication client ID was set", despite the fact that the API key is present in CMakeLists.txt. I'm guessing either the API key is not being properly detected upon first launch of PolyMC, or the Microsoft Account options are not unlocked properly upon first launch.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by DioEgizio** [comment]
I can reproduce. Maybe regression in https://github.com/PolyMC/PolyMC/pull/1034 ?

**Comment by TheMCNerd2017** [comment]
> I can reproduce. Maybe regression in #1034 ?

Not sure. Also manually adding the API key in the settings does not unlock the Microsoft Account options either while this issue is occurring (though I'm not sure if doing that requires a restart of PolyMC).

**Comment by DioEgizio** [comment]
This also happens with curseforge

**Comment by DioEgizio** [comment]
It's like capabilities aren't checked at first launch
