### ISSUE TITLE
[Feature Request] Download blocked curseforge mods with popup browser

### ISSUE THREAD

**Issue by codefreak558** [PolyMC/PolyMC#1161]
### Role

I play many curseforge modpacks

### Suggestion

Automatic download of blocked mods like how GDLauncher does there download's of blocked mods. They open up a web browser and then get it to auto download like that

### Benefit

Make downloading curseforge modpacks easier

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Currently GDLauncher will open up a web browser when it comes to a mod that is blocked due to the updated api. Once it opens the browser it sends it directly to the download page for the mod that is blocked and then downloads it.

I found this issue on there Github where they discuss the issue https://github.com/gorilla-devs/GDLauncher/pull/1345

**Comment by DioEgizio** [comment]
We're most likely not gonna do this because it requires to embed an entire browser. But you can hope on https://github.com/PolyMC/PolyMC/issues/918

**Comment by codefreak558** [comment]
Okay thanks didn't know that it would require an embedded browser
