### ISSUE TITLE
Move the authentication method to a standalone package

### ISSUE THREAD

**Issue by skillman623** [PolyMC/PolyMC#1166]
### Goal

Migrate the authentication code to a separate module for use in similar projects.

### Motivation

Since the Microsoft login has started, multiple third party clients have had to pay for relatively expensive API keys for their users to be able to login. PolyMC manages it differently by letting the official launcher handle authentication. This is a brilliant solution and I'd like to port this to a separate module so that other projects can use it should they choose.

Some projects, such as one that I'm working on [Leafish](https://github.com/Lea-fish/Leafish) has 17 different authors, many of whom are long since gone inactive. This is the main reason why I inquire about possible relicensing the module, as rewriting many of the core features of an application is sometimes infeasible for smaller projects.

### Specification

Should this be considered there are two parts that are independent of each other:

 - [ ] Port the existing code to a different repo and make it into a library for other projects to use
 - [ ] Look into relicensing the module or write a specification for reimplementation under a different license (if desirable)

### Drawbacks

For many projects, there are licensing restrictions that can't be easily gotten around.
For wider adoption, it would be preferable to have more permissible license (one that doesn't require relicensing as GPL)

### Unresolved Questions

I don't know how feasible it would be to relicense the required code.

### Alternatives Considered

The only alternative is hosting an API key for each projects users.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by Scrumplex** [comment]
> Since the Microsoft login has started, multiple third party clients have had to pay for relatively expensive API keys for their users to be able to login. PolyMC manages it differently by letting the official launcher handle authentication. This is a brilliant solution and I'd like to port this to a separate module so that other projects can use it should they choose.

Can you elaborate? Getting an API key for MSA is free. You just need a valid Azure account.
PolyMC does not deal with the official launcher at all. We just use ordinary OAuth flows for logging in.

Most code lies in [libraries/katabasis](https://github.com/PolyMC/PolyMC/tree/develop/libraries/katabasis) which itself is a fork of [o2](https://github.com/pipacs/o2).
Anything beyond that library is GPL and PolyMC-specific. It is pretty unlikely that we would be able to relicense this code anyway, as it's GPL.

**Comment by DioEgizio** [comment]
> Anything beyond that library is GPL and PolyMC-specific. It is pretty unlikely that we would be able to relicense this code anyway, as it's GPL.

We could ask who contributed to it to relicense, but at that point you might just as well use multimc code for that which is apache 2 

apart from that, I agree with you, I don't get the "paying for API key" thingy either

**Comment by skillman623** [comment]
> 

Correct me if I'm wrong but don't you get charged per API call?
I realize that getting the key itself is free, but am pretty sure there's an additional charge once you start using it..

**Comment by DioEgizio** [comment]
> > 
> 
> Correct me if I'm wrong but don't you get charged per API call? I realize that getting the key itself is free, but am pretty sure there's an additional charge once you start using it..

No, you're misinformed here, there's no charge at all

**Comment by skillman623** [comment]
> > > 
> > 
> > 
> > Correct me if I'm wrong but don't you get charged per API call? I realize that getting the key itself is free, but am pretty sure there's an additional charge once you start using it..
> 
> No, you're misinformed here, there's no charge at all

Okay. Thanks for your help.
Also it turns out that this was a duplicate of the following discussion:
https://github.com/PolyMC/PolyMC/discussions/491

**Comment by Scrumplex** [comment]
After reading through the issue over at Leafish, I should clarify, that we are using our own client id for authentication, not the one of the official launcher. You can check it here: https://github.com/PolyMC/PolyMC/blob/c01b475cbfc706612991deb795a30644f002b72f/CMakeLists.txt#L120-L134
