### ISSUE TITLE
Cannot copy/paste in custom curseforge api/microsoft api key box

### ISSUE THREAD

**Issue by MenacingPerson** [PolyMC/PolyMC#1168]
### Operating System

Linux

### Version of PolyMC

1.4.2

### Version of Qt

6.3.2

### Description of bug

The custom CurseForge API key box is there, but it does not let me copy/paste. Manual typing works

### Steps to reproduce

1. Click Settings -> APIs -> API Keys

2. Try to type in CurseForge core API key

3. See that you can't use copy/paste

Same thing for Microsoft API or paste service box

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by ryanccn** [comment]
You need to type according to the format in order for it to show up. It uses a regex to validate the input.

**Comment by DioEgizio** [comment]
yeah, as Ryan said, you need to input a correct key

**Comment by MenacingPerson** [comment]
Ok well copy/paste with valid key still doesn't work, I even tried the key in this repo's cmakelists to ensure that it wasn't my key

**Comment by MenacingPerson** [comment]
Manually typing works, no copypaste though, modifying the issue

**Comment by DioEgizio** [comment]
Are you sure you don't have spaces or stuff like that?

**Comment by MenacingPerson** [comment]
I have a newline char at the end. Without that it works.

You guys should probably fix that
