### ISSUE TITLE
creating a macos-legacy package

### ISSUE THREAD

**Issue by DioEgizio** [PolyMC/PolyMC#1173]
### Goal

creating a macos-legacy package

### Motivation

Currently, using PolyMC on old macOS version is a nightmare. You have to build and download stuff from different sources too.

### Specification

We could provide a macOS-Legacy package that uses qt5, the llvm brew package for using std::filesystem features and that points macos 10.13 for compatibility with these old macos versions.

### Drawbacks

- more official packages to maintain

### Unresolved Questions

- how to integrate that with the updater?

### Alternatives Considered

- telling people to use the opencore legacy patcher or similar software
  some people don't want to use stuff like that 

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by stantios** [comment]
I agree with this after all the issues I had with trying to build it (mostly me being dumb but still).

**Comment by DioEgizio** [comment]
It's definitely not easy and straightforward

**Comment by stantios** [comment]
Oh

**Comment by DioEgizio** [comment]
(i meant compiling polymc on those old macOS versions, for us doing the package would be simple if you exclude updater)

**Comment by stantios** [comment]
Ah, so compiling with the updater would be harder than compiling without the updater?

**Comment by DioEgizio** [comment]
More than that, making the package work with the updating infrastructure. I already got the package to build/work, but I have no idea on how to make it work with the updating infrastructure

**Comment by stantios** [comment]
Maybe that could be a disadvantage of being on an old mac, you don't get the updater included.

**Comment by DioEgizio** [comment]
> More than that, making the package work with the updating infrastructure. I already got the package to build/work, but I have no idea on how to make it work with the updating infrastructure

Anyways, for who is interested, [this is the patch](https://github.com/DioEgizio/PolyMC/commit/c3d9e9ee55e254675afb6228bdadd81647fc3f0f.patch) and you can try the build out [here](https://nightly.link/DioEgizio/PolyMC/actions/runs/3163809022/PolyMC-macOS-Legacy-c3d9e9e-Debug.zip)

**Comment by stantios** [comment]
> > More than that, making the package work with the updating infrastructure. I already got the package to build/work, but I have no idea on how to make it work with the updating infrastructure
> 
> Anyways, for who is interested, [this is the patch](https://github.com/DioEgizio/PolyMC/commit/c3d9e9ee55e254675afb6228bdadd81647fc3f0f.patch) and you can try the build out [here](https://nightly.link/DioEgizio/PolyMC/actions/runs/3163707479/PolyMC-macOS-Legacy-fcbc054-Debug.zip)

I'll make sure to try this out when I get home.

**Comment by stantios** [comment]
> > More than that, making the package work with the updating infrastructure. I already got the package to build/work, but I have no idea on how to make it work with the updating infrastructure
> 
> Anyways, for who is interested, [this is the patch](https://github.com/DioEgizio/PolyMC/commit/c3d9e9ee55e254675afb6228bdadd81647fc3f0f.patch) and you can try the build out [here](https://nightly.link/DioEgizio/PolyMC/actions/runs/3163809022/PolyMC-macOS-Legacy-c3d9e9e-Debug.zip)

I got this error when trying to launch PolyMC: 
![image](https://user-images.githubusercontent.com/98621617/193411508-48cea0c2-b67b-4047-b40d-6cab74269371.png)

**Comment by DioEgizio** [comment]
Click report and send what it says

**Comment by stantios** [comment]
It says this: 
![image](https://user-images.githubusercontent.com/98621617/193411592-9c341a2c-a39c-44c0-b4bf-0566f22802ba.png)
![image](https://user-images.githubusercontent.com/98621617/193411628-f94cb999-5246-44eb-87e0-0b76d65877ee.png)
![image](https://user-images.githubusercontent.com/98621617/193411741-c53fb90c-7c64-45ba-8d85-11148d369e11.png)
![image](https://user-images.githubusercontent.com/98621617/193411759-2fd4fd4b-1875-45d7-b64d-8b3cbd25623a.png)
![image](https://user-images.githubusercontent.com/98621617/193411647-8fe1d32d-c582-4b2b-b8bc-40562c1aad62.png)

**Comment by DioEgizio** [comment]
Try [this](https://nightly.link/DioEgizio/PolyMC/actions/artifacts/383060792.zip) instead ([this](https://github.com/DioEgizio/PolyMC/commit/701b6b2b8d323160c3ff6c2224c3189ca155cb06.patch) is the updated patch if it works btw)

**Comment by stantios** [comment]
> Try [this](https://nightly.link/DioEgizio/PolyMC/actions/artifacts/383060792.zip) instead ([this](https://github.com/DioEgizio/PolyMC/commit/701b6b2b8d323160c3ff6c2224c3189ca155cb06.patch) is the updated patch if it works btw)

This worked!

**Comment by DioEgizio** [comment]
nice

**Comment by stantios** [comment]
I tried to remove a mod and I got this error: 
![image](https://user-images.githubusercontent.com/98621617/193429174-2ce5df6b-5f27-4dc6-bb73-d456c0311767.png)
![image](https://user-images.githubusercontent.com/98621617/193429185-251bc9d6-ba66-4307-9a9a-7944a260f9c3.png)
![image](https://user-images.githubusercontent.com/98621617/193429218-b038c5d8-c32a-4e1f-ade0-acc7b56ad569.png)
![image](https://user-images.githubusercontent.com/98621617/193429237-5a69e17c-6bb1-4195-abf3-b39a86a64f81.png)
![image](https://user-images.githubusercontent.com/98621617/193429287-38003b72-13f7-4491-a69c-5429dc309a4e.png)

**Comment by stantios** [comment]
I tried to use the Voice Chat mod and my game crashed: 
![Screenshot 1](https://user-images.githubusercontent.com/98621617/193429372-4225e411-f9e9-4519-a3b8-3fd94bce0aeb.png)
![image](https://user-images.githubusercontent.com/98621617/193429360-bd9d6ff1-36b4-4543-8bc7-ccff3148a4f1.png)
![image](https://user-images.githubusercontent.com/98621617/193429388-e62e158b-5249-4345-9c63-e261e18c682a.png)

**Comment by stantios** [comment]
Mods seem to duplicate when updating to new a version of the mod: 
![image](https://user-images.githubusercontent.com/98621617/193429431-be98b1c9-ff6e-4478-8a6e-fc413f4053ff.png)

**Comment by DioEgizio** [comment]
> I tried to use the Voice Chat mod and my game crashed: ![Screenshot 1](https://user-images.githubusercontent.com/98621617/193429372-4225e411-f9e9-4519-a3b8-3fd94bce0aeb.png) ![image](https://user-images.githubusercontent.com/98621617/193429360-bd9d6ff1-36b4-4543-8bc7-ccff3148a4f1.png) ![image](https://user-images.githubusercontent.com/98621617/193429388-e62e158b-5249-4345-9c63-e261e18c682a.png)

that mod seems to use binaries compiled againist macOS 11

**Comment by DioEgizio** [comment]
> I tried to remove a mod and I got this error: ![image](https://user-images.githubusercontent.com/98621617/193429174-2ce5df6b-5f27-4dc6-bb73-d456c0311767.png) ![image](https://user-images.githubusercontent.com/98621617/193429185-251bc9d6-ba66-4307-9a9a-7944a260f9c3.png) ![image](https://user-images.githubusercontent.com/98621617/193429218-b038c5d8-c32a-4e1f-ade0-acc7b56ad569.png) ![image](https://user-images.githubusercontent.com/98621617/193429237-5a69e17c-6bb1-4195-abf3-b39a86a64f81.png) ![image](https://user-images.githubusercontent.com/98621617/193429287-38003b72-13f7-4491-a69c-5429dc309a4e.png)

i think your errors are unsolvable. Basically, polymc uses features of the c++ standard library which are only available on macOS 10.15 or higher. I'll try a different workaround

**Comment by DioEgizio** [comment]
Try [this](https://nightly.link/DioEgizio/PolyMC/actions/artifacts/383487453.zip)

**Comment by stantios** [comment]
I recieved a crash when trying to look at my mods: https://paste.gg/p/anonymous/d5aba63b9ead4fc5950386d61e1efe29

**Comment by DioEgizio** [comment]
yeah, as i thought, it's trying to access a feature of the c++ standard library that isn't there on that version. I guess until a workaround for this is found, this can't be done

**Comment by stantios** [comment]
Alright, that's fine. I got another crash when trying to remove a mod: https://paste.gg/p/anonymous/8dc87ca280c946029ed35bcfc20acca9

**Comment by DioEgizio** [comment]
It's the same reason, you don't have to repost every time lol

**Comment by stantios** [comment]
Oh ok, my bad.

**Comment by stantios** [comment]
> yeah, as i thought, it's trying to access a feature of the c++ standard library that isn't there on that version. I guess until a workaround for this is found, this can't be done

Is there no alternative to the c++ library? Can't you use a different library instead?

**Comment by DioEgizio** [comment]
The [c++ standard library](https://en.m.wikipedia.org/wiki/C%2B%2B_Standard_Library) is the core library of c++, so no

While we could statically link it, it wouldn't work on those old versions because it's linked for newer ones, so I don't know what can we do

**Comment by stantios** [comment]
Oh ok

**Comment by DioEgizio** [comment]
[this](https://nightly.link/DioEgizio/PolyMC/actions/artifacts/398314958.zip) should work, but exclude the weird cmake stuff, still have to figure that out
