### ISSUE TITLE
windows build is still using paste.ee and it has the "PolyMC 5" thing. Also it doesn't have colored icons by default

### ISSUE THREAD

**Issue by DioEgizio** [PolyMC/PolyMC#118]
### Operating System

Windows

### Description of bug

![immagine](https://user-images.githubusercontent.com/83089242/151861089-05710c1b-c3ad-4e90-a882-3dd3bdc281a2.png)

### Steps to reproduce

install polymc on windows and see

### Suspected cause

no idea

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by ghost** [comment]
This is because a tag has not been made with these changes.

When we finish #64, #79, #92, #108, #113, and close #54 and #56 (by merging `feature/better_java_checking`, a new tag will be made (1.1.0).

**Comment by DioEgizio** [comment]
Oh my bad then, I always used bleeding edge builds
