### ISSUE TITLE
BitDefender Flagging PolyMC for SuspiciousBehavior.F6DDD6BB1D7CB5F0 Act4.Detection

### ISSUE THREAD

**Issue by PaxJaromeMalues** [PolyMC/PolyMC#1187]
### Operating System

Windows

### Version of PolyMC

1.4.2

### Version of Qt

6.3.1

### Description of bug

BitDefender Flagging PolyMC for SuspiciousBehavior.F6DDD6BB1D7CB5F0 Act4.Detection

### Steps to reproduce

1. Start PolyMC
2. Start Explorer
3. Options->Add Shaderpack ZIP
4. Toggle Shaders

Sadly BitDefender does not specify which action exactly trigger the Malware Protection

### Suspected cause

No idea

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by DioEgizio** [comment]
I don't think here it's flagging polymc, probably flagging the shadermod you're using. Anyways, just use Windows defender

**Comment by PaxJaromeMalues** [comment]
> I don't think here it's flagging polymc, probably flagging the shadermod you're using. Anyways, just use Windows defender

Yeah... Windows Defender... I'd rather shoot myself in the foot with sawed off shot gun while singing the Patriot Act text in reverse. BitDefender is already shitty, but damn... that does top.

**Comment by DioEgizio** [comment]
Windows defender is better than any other standalone antivirus software. At this point there's no reason to use those weird standalone antiviruses, windows defender works fine

**Comment by LennyMcLennington** [comment]
You should report BitDefender problems to BitDefender, not to us. Alternatively, just use Windows defender. Like DioEgizio said, Windows Defender hasn't been shit for years now. Sure, it used to be shit, but now it's the best antivirus software for Windows. (Assuming you're not still on Windows Vista)
