### ISSUE TITLE
Add a 'Storage' page in Settings

### ISSUE THREAD

**Issue by flowln** [PolyMC/PolyMC#1189]
### Role

I used PolyMC before the hostile takeover :slightly_smiling_face: 

### Suggestion

Add a page to show information about current disk space usage and options for cache control and stuff

### Benefit

More useful information and better control of caches.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Instances can use gigabytes of disk space, considering game assets, mod jars, resource packs, etc etc. Also, the cache used by PolyMC can grow as much as it wants, and there's no good way to see what is cached and how much of it is done.

So, I think it would be quite cool if we had a page in the global settings that would allow you to see things such as a list of instances and their respective disk space usage, and also see meta cache basis, how much each takes, and additionally allow you to evict certain (or all) of those if you'd like to. It would also make a comfy home for the 'Clear metadata' button added in #1188.

For the future, if we do improve the cache to allow you to set limits on how much a specific cache base can grow, this page would also allow you to add a UI for that :)

Also, it would be really cool if the code for that doesn't suck, but I know it can be very hard, so it's not a hard requirement if you can't ^-^

**Comment by DioEgizio** [comment]
this is a good idea. Probably would be even better with #339

**Comment by LordMZTE** [comment]
This has been implemented, we should close the issue.

**Comment by Kaydax** [comment]
Mark as finished - PR: #1504
