### ISSUE TITLE
"PolyMc" is already being used by another project

### ISSUE THREAD

**Issue by Felix14-v2** [PolyMC/PolyMC#119]
[PolyMC](https://github.com/TheEpicBlock/PolyMc) is a project that makes Minecraft mods compatible with a vanilla client, being developed by TheEpicBlock since 25 May 2020. To avoid confusion, it is worth making at least some difference in the name of the projects.

**Comment by ghost** [comment]
I've already registered polymc.org and gotten permission to use the PolyMC name for this project. It would be very hard to change now and I don't really feel like undertaking that whole ordeal.
