### ISSUE TITLE
Be able to install mods unsupported on 3rd party launcher.

### ISSUE THREAD

**Issue by DovydasTEDS** [PolyMC/PolyMC#1195]
### Role

I download modpacks,

### Suggestion

I want the ability to auto-download mods that cannot be downloaded through the launcher / api. This feature is also in another open-source launcher called GD Launcher.

### Benefit

So that players do not need to download / store unecessary files.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by DioEgizio** [comment]
gdlauncher just opens the cf website and downloads from there. We won't integrate an embedded browser, but https://github.com/PolyMC/PolyMC/issues/918 is what you're gonna look for.

**Comment by DovydasTEDS** [comment]
oh ok
