### ISSUE TITLE
AppStream MetaInfo

### ISSUE THREAD

**Issue by d-513** [PolyMC/PolyMC#12]
AppStream offeres info about the app. This is useful for app stores (like gnome-software, if we make a repo with debs for example) and flatpak. This should be maintained in PolyMC instead of the flatpak

spec: https://www.freedesktop.org/software/appstream/docs/index.html
should be installed just like the .desktop files by cmake, in /usr/share/metainfo/org.polymc.PolyMC.metainfo.xml
I made the thing in the flatpak repo, https://github.com/dada513/flathub/blob/org.polymc.PolyMC/org.polymc.PolyMC.metainfo.xml, however I have no idea how to add that to cmake.

**Comment by ghost** [comment]
should it be stored as just PolyMC.metainfo.xml for regular debs?

**Comment by d-513** [comment]
> should it be stored as just PolyMC.metainfo.xml for regular debs?

I'm assuming it should be rDNS because `<id>` is rDNS

**Comment by ghost** [comment]
alright then. When home I can add it to CMake.

Additionally we're gonna eventually switch to Meson, in case you know that and not CMake, but it'll be a very big task so don't expect it soon.

**Comment by d-513** [comment]
Updated meta info https://github.com/flathub/org.polymc.PolyMC/blob/master/org.polymc.PolyMC.metainfo.xml
