### ISSUE TITLE
Hovering over icon in Windows says "A Minecraft Launcher"

### ISSUE THREAD

**Issue by helpimnotdrowning** [PolyMC/PolyMC#121]
### Operating System

Windows

### Description of bug

Pinning the icon to the taskbar and hovering over it (while no polymc windows are open) shows a text box that says "A Minecraft Launcher" instead of PolyMC branding
![image](https://user-images.githubusercontent.com/35247379/152097288-4a5251ee-b6d1-4c1d-a834-b19cf3309912.png)

### Steps to reproduce

* Pin PolyMC exe to taskbar
* Hover over it
* Read text

### Suspected cause

Unchanged default string from MultiMC debranding

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by helpimnotdrowning** [comment]
Right clicking on the taskbar icon shows another place that still says "A Minecraft Launcher"
![image](https://user-images.githubusercontent.com/35247379/152474340-7d4dc024-1763-4006-bea1-83db8928a04b.png)

**Comment by ghost** [comment]
Are you on 1.0.6?

This was only implemented into develop. When we finish Java checking and stuff 1.1.0 will be released with this fix.

**Comment by helpimnotdrowning** [comment]
Yes, I updated the day cf3c2482c9e7f743088b590f8c90cc3be1308718 was pushed. I updated just now to the latest win32 build on jenkins (by getting the zip and extracting over the existing files) and repinned it to taskbar to make sure it wasn't some weird caching problem, but it still shows. I got the build from [the last github actions run ](https://github.com/PolyMC/PolyMC/actions/runs/1794961584) and repinned it too, but now it doesn't even start, no log or anything.

**Comment by ghost** [comment]
Sounds like an issue with GH actions. Contact txtsd and scrumplex on matrix/discord for help

**Comment by txtsd** [comment]
@helpimnotdrowning Can you start the exe from a terminal and paste the log?

**Comment by helpimnotdrowning** [comment]
It just returns instantly. Doing some funny command work (`wt -p "Powershell Core" -d . "C:\Users\owo\Desktop\pmc'\polymc.exe"`), I can squeeze out `[process exited with code 3221225477]`.

**Comment by txtsd** [comment]
That's not enough to work with :(
Does it also happen when you run it when installed in a clean folder without all your settings and instance folders?

Also, try the Windows build from here:
https://github.com/PolyMC/PolyMC/actions/runs/1806588054

**Comment by helpimnotdrowning** [comment]
I forgot to mention that the first time I tried it was over the existing install, but that last one was clean.

This time (also clean install), it takes a bit longer to "start", but still returns `3221225477`. Is there some sort of super-debug logging I could enable?

**Comment by txtsd** [comment]
Did you try the linked build too?

**Comment by helpimnotdrowning** [comment]
Yep, thats the one I tried in my last comment. I tried with some cli flags to see if maybe I could get something at all to print, but I still get nothing out of it.

**Comment by txtsd** [comment]
> Is there some sort of super-debug logging I could enable?

You're already running a debug build. If you can get us a `gdb` trace, that might help.

Do you run Avast by any chance?

**Comment by txtsd** [comment]
It's a actually different issue. We're working on it.

**Comment by helpimnotdrowning** [comment]
If it's still at all useful, gdb says
```gdb
Thread 1 received signal SIGSEGV, Segmentation fault.
0x000000000068148f in Config::Config (this=0x9cb160 <BuildConfig>)
    at D:/a/PolyMC/PolyMC/build/buildconfig/BuildConfig.cpp:6
6       D:/a/PolyMC/PolyMC/build/buildconfig/BuildConfig.cpp: No such file or directory.
```

**Comment by txtsd** [comment]
Yea that's what we were seeing too. Try the build from the latest Action run. It should work fine.

**Comment by helpimnotdrowning** [comment]
Yep, works great now!
