### ISSUE TITLE
@LennyMcLeggington should eat dry wall

### ISSUE THREAD

**Issue by skye5000** [PolyMC/PolyMC#1218]
@LennyMcLennington should eat dry wall
@LennyMcLennington should eat dry wall
@LennyMcLennington should eat dry wall
@LennyMcLennington should eat dry wall
@LennyMcLennington should eat dry wall

![emu-otori-otori-emu](https://user-images.githubusercontent.com/54551194/196270162-1de738b4-b1e7-4661-aef9-bdcbcec5f62d.gif)

**Comment by skye5000** [comment]
@LennyMcLennington eat dry wall

**Comment by skye5000** [comment]
@LennyMcLennington eat dry wall

**Comment by skye5000** [comment]
@LennyMcLennington eat dry wall

**Comment by skye5000** [comment]
@LennyMcLennington eat dry wall

**Comment by skye5000** [comment]
@LennyMcLennington eat dry wall

**Comment by Amerylis** [comment]
@LennyMcLennington eat dry wall
![image](https://user-images.githubusercontent.com/113071230/196270995-0a7517e3-0661-4412-b928-018f32270798.png)

**Comment by skye5000** [comment]
@LennyMcLennington you should also put 10mg of cyanide into your tea and eat it, i heard it tastes very good!
@LennyMcLennington you should also put 10mg of cyanide into your tea and eat it, i heard it tastes very good!
@LennyMcLennington you should also put 10mg of cyanide into your tea and eat it, i heard it tastes very good!
@LennyMcLennington you should also put 10mg of cyanide into your tea and eat it, i heard it tastes very good!
@LennyMcLennington you should also put 10mg of cyanide into your tea and eat it, i heard it tastes very good!
@LennyMcLennington you should also put 10mg of cyanide into your tea and eat it, i heard it tastes very good!
@LennyMcLennington you should also put 10mg of cyanide into your tea and eat it, i heard it tastes very good!
@LennyMcLennington you should also put 10mg of cyanide into your tea and eat it, i heard it tastes very good!
@LennyMcLennington you should also put 10mg of cyanide into your tea and eat it, i heard it tastes very good!
@LennyMcLennington you should also put 10mg of cyanide into your tea and eat it, i heard it tastes very good!

**Comment by skye5000** [comment]
@LennyMcLennington you should also put 10mg of cyanide into your tea and eat it, i heard it tastes very good!
@LennyMcLennington you should also put 10mg of cyanide into your tea and eat it, i heard it tastes very good!
@LennyMcLennington you should also put 10mg of cyanide into your tea and eat it, i heard it tastes very good!
@LennyMcLennington you should also put 10mg of cyanide into your tea and eat it, i heard it tastes very good!

**Comment by skye5000** [comment]
@LennyMcLennington you should also put 10mg of cyanide into your tea and eat it, i heard it tastes very good!
@LennyMcLennington you should also put 10mg of cyanide into your tea and eat it, i heard it tastes very good!
@LennyMcLennington you should also put 10mg of cyanide into your tea and eat it, i heard it tastes very good!

**Comment by ajddavid452** [comment]
> What's going on?

I am just as confused as you

**Comment by ApolloDatapacks** [comment]
> What's going on?

Repository owner of PolyMC has gone rogue and/or has been hacked. All contributors have been removed because of "spreading radical leftist ideologies".

**Comment by luclu7** [comment]
I really doubt he has been hacked, sadly

**Comment by ApolloDatapacks** [comment]
If you are currently using PolyMC, it is recommended you **uninstall it immediately**. If you still want/need to use it for some reason, **do NOT update** PolyMC. Go to APIs and set the Metadata Server to something random.

**Comment by gurrrrrrett3** [comment]
![image](https://user-images.githubusercontent.com/61361654/196272926-bf3edcdf-7ff5-4146-821e-b26b13aca202.png)
change this

**Comment by VTArxelus** [comment]
Issue of compromise was reported at 2:55 on ShadowNode.

**Comment by orowith2os** [comment]
@LennyMcLennington cope and seethe, fascist 


![unknown-30.png](https://user-images.githubusercontent.com/93224879/196273403-3936ffbb-9663-4bff-a9ec-1f4475171f9c.png)

**Comment by flleeppyy** [comment]
cope cope cope cope cope cope cope cope cope cope

**Comment by flleeppyy** [comment]
what is even happening

**Comment by Pixydidnothingwrong** [comment]
rise against the rainbows it looks like.

**Comment by Optinux** [comment]
Custom Launcher Developer try not to become racist or homophobic challenge (99.99% IMPOSSIBLE 😮😱)

**Comment by LennyMcSpammington** [comment]
> Custom Launcher Developer try not to become racist or homophobic challenge (99.99% IMPOSSIBLE open_mouthscream)

thanks for this im going to spam it

**Comment by flleeppyy** [comment]
oh god damn... french moment

**Comment by Optinux** [comment]
> thanks for this im going to spam it

I live inside your walls
