### ISSUE TITLE
Add Gay Sex to Launcher for Pride Month

### ISSUE THREAD

**Issue by KFAQ** [PolyMC/PolyMC#1236]
### Operating System

Windows, macOS, Linux

### Version of PolyMC

Latest

### Version of Qt

Latest

### Description of bug

just wondering if gay sex will be added to the launcher in time for Pride month?

### Steps to reproduce

moneypox

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by orowith2os** [comment]
![unknown-30.png](https://user-images.githubusercontent.com/93224879/196273715-7b75df3d-93d1-4d16-9cc5-8eadd018aec2.png)

**Comment by a-weeb-programmer** [comment]
![image](https://user-images.githubusercontent.com/65640526/196274227-5455dd4b-f332-450f-be82-f7ac778ceb3f.png)

**Comment by KFAQ** [comment]
as long as you identify as a male its all pro gay man supremacy round there parts

**Comment by Patrosi73** [comment]
i approve of this cahneg my guy

**Comment by Patrosi73** [comment]
my gay*

**Comment by a-weeb-programmer** [comment]
g a y

**Comment by Sterophonick** [comment]
![meme](https://user-images.githubusercontent.com/34801996/196275253-d1d1e4ea-bbdb-491a-b4a7-66891caa95a7.png)
