### ISSUE TITLE
@everyone

### ISSUE THREAD

**Issue by sunglocto** [PolyMC/PolyMC#1238]
### Operating System

Windows, macOS, Linux

### Version of PolyMC

@everyone

### Version of Qt

@everyone

### Description of bug

@everyone

### Steps to reproduce

@everyone

### Suspected cause

@everyone

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by CesiumCs** [comment]
i dont think it works like that

**Comment by sunglocto** [comment]
> i dont think it works like that

it didnt even work on the server lol
