### ISSUE TITLE
polymc explod mah pee cee!

### ISSUE THREAD

**Issue by sunglocto** [PolyMC/PolyMC#1240]
### Operating System

Other

### Version of PolyMC

PolyMC 69.420

### Version of Qt

Qt 0.0

### Description of bug

i ran poly emm cee and it literally broke ma pee cee here is screen shot:
![image](https://user-images.githubusercontent.com/76428041/196274557-ed99dfa3-fc0b-4fb4-b1cc-503ca1d1b088.png)
pls fix

### Steps to reproduce

run polymc

### Suspected cause

idk

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by TheFruxz** [comment]
can confirm, seems related to ccf282593dcdbe189c99b81b8bc90cb203aed3ee

**Comment by eepy-goddess** [comment]
oh no
not the pee cee D:

**Comment by TheFruxz** [comment]
![image](https://user-images.githubusercontent.com/28064149/196276352-3019a0e4-6e65-4488-929f-7e08f34192e2.png)
This issue seems also be related, to some old MaakBoooks exploooooouuuuding

**Comment by fuzzy-bit** [comment]
the EeePeeCee
