### ISSUE TITLE
Rename Loader Mods to just Mods

### ISSUE THREAD

**Issue by cozyGalvinism** [PolyMC/PolyMC#128]
### Role

I use PolyMC to play various mod packs

### Suggestion

Rename Loader mods to just mods

### Benefit

It's easier to understand, while "Loader mods" could be interpreted as "oh Forge/Fabric is listed in here"

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by djmattyg007** [comment]
Just "Mods" would definitely be better for non-technical users.
