### ISSUE TITLE
Desktop file should use reverse-dns

### ISSUE THREAD

**Issue by d-513** [PolyMC/PolyMC#13]
it wasn't ever enforced, but according to the spec https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html name should be like `org.polymc.PolyMC`
Also to make it easier I think icon should be too rDNS although the spec doesnt require that, because that way both icon and desktop file can be maintained in PolyMC and not in flathub.

**Comment by ghost** [comment]
How do you use rDNS with icons?

Additionally, do we rename the desktop file itself or the application name in the file?

**Comment by d-513** [comment]
> How do you use rDNS with icons?
> 
> Additionally, do we rename the desktop file itself or the application name in the file?

file itself
rDNS with icons: just set icon name to org.polymc.PolyMC.svg and icon to org.polymc.PolyMC in desktop

**Comment by ghost** [comment]
Alright, not home right now (will be around 3PM EST), but once I am I can add this change.
