### ISSUE TITLE
Slackware package

### ISSUE THREAD

**Issue by glowiak** [PolyMC/PolyMC#130]
### Role

have slackware packages

### Suggestion

I made a package for slackware

### Benefit

gain Slackware users

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Here's the SlackBuild (source version): https://codeberg.org/glowiak/SlackBuilds/src/branch/master/repository/polymc.md

and binary package: https://codeberg.org/attachments/0547129b-3910-4b46-89fb-50b3221576b1

requires qt5 (on 15.0 installed by default), java if you want to play minecraft (from here for example: https://codeberg.org/glowiak/SlackBuilds/src/branch/master/repository/oracle-jre8.md ), and for build on 14.2 you need to compile newer cmake yourself

**Comment by ghost** [comment]
Submit a PR to README.md containinf:

- a slackware section (using the slackware logo, just like the other distro sections):
  * Note that it's available in your repo
  * Instructions to build and install, or use the binary version.

**Comment by glowiak** [comment]
okay
