### ISSUE TITLE
ninja fortnite

### ISSUE THREAD

**Issue by Sterophonick** [PolyMC/PolyMC#1309]
### Version of PolyMC

![ninja-fortnite](https://user-images.githubusercontent.com/34801996/196276841-c2748a1c-e33c-4e65-af60-a972ae0ab964.gif)![ninja-fortnite](https://user-images.githubusercontent.com/34801996/196276841-c2748a1c-e33c-4e65-af60-a972ae0ab964.gif)![ninja-fortnite](https://user-images.githubusercontent.com/34801996/196276841-c2748a1c-e33c-4e65-af60-a972ae0ab964.gif)![ninja-fortnite](https://user-images.githubusercontent.com/34801996/196276841-c2748a1c-e33c-4e65-af60-a972ae0ab964.gif)![ninja-fortnite](https://user-images.githubusercontent.com/34801996/196276841-c2748a1c-e33c-4e65-af60-a972ae0ab964.gif)![ninja-fortnite](https://user-images.githubusercontent.com/34801996/196276841-c2748a1c-e33c-4e65-af60-a972ae0ab964.gif)

### Version of Qt

![ninja-fortnite](https://user-images.githubusercontent.com/34801996/196276841-c2748a1c-e33c-4e65-af60-a972ae0ab964.gif)![ninja-fortnite](https://user-images.githubusercontent.com/34801996/196276841-c2748a1c-e33c-4e65-af60-a972ae0ab964.gif)![ninja-fortnite](https://user-images.githubusercontent.com/34801996/196276841-c2748a1c-e33c-4e65-af60-a972ae0ab964.gif)![ninja-fortnite](https://user-images.githubusercontent.com/34801996/196276841-c2748a1c-e33c-4e65-af60-a972ae0ab964.gif)![ninja-fortnite](https://user-images.githubusercontent.com/34801996/196276841-c2748a1c-e33c-4e65-af60-a972ae0ab964.gif)![ninja-fortnite](https://user-images.githubusercontent.com/34801996/196276841-c2748a1c-e33c-4e65-af60-a972ae0ab964.gif)

### Description of bug

![ninja-fortnite](https://user-images.githubusercontent.com/34801996/196276841-c2748a1c-e33c-4e65-af60-a972ae0ab964.gif)![ninja-fortnite](https://user-images.githubusercontent.com/34801996/196276841-c2748a1c-e33c-4e65-af60-a972ae0ab964.gif)![ninja-fortnite](https://user-images.githubusercontent.com/34801996/196276841-c2748a1c-e33c-4e65-af60-a972ae0ab964.gif)![ninja-fortnite](https://user-images.githubusercontent.com/34801996/196276841-c2748a1c-e33c-4e65-af60-a972ae0ab964.gif)![ninja-fortnite](https://user-images.githubusercontent.com/34801996/196276841-c2748a1c-e33c-4e65-af60-a972ae0ab964.gif)![ninja-fortnite](https://user-images.githubusercontent.com/34801996/196276841-c2748a1c-e33c-4e65-af60-a972ae0ab964.gif)

### Steps to reproduce

![ninja-fortnite](https://user-images.githubusercontent.com/34801996/196276841-c2748a1c-e33c-4e65-af60-a972ae0ab964.gif)![ninja-fortnite](https://user-images.githubusercontent.com/34801996/196276841-c2748a1c-e33c-4e65-af60-a972ae0ab964.gif)![ninja-fortnite](https://user-images.githubusercontent.com/34801996/196276841-c2748a1c-e33c-4e65-af60-a972ae0ab964.gif)![ninja-fortnite](https://user-images.githubusercontent.com/34801996/196276841-c2748a1c-e33c-4e65-af60-a972ae0ab964.gif)![ninja-fortnite](https://user-images.githubusercontent.com/34801996/196276841-c2748a1c-e33c-4e65-af60-a972ae0ab964.gif)![ninja-fortnite](https://user-images.githubusercontent.com/34801996/196276841-c2748a1c-e33c-4e65-af60-a972ae0ab964.gif)

### Suspected cause

![ninja-fortnite](https://user-images.githubusercontent.com/34801996/196276841-c2748a1c-e33c-4e65-af60-a972ae0ab964.gif)![ninja-fortnite](https://user-images.githubusercontent.com/34801996/196276841-c2748a1c-e33c-4e65-af60-a972ae0ab964.gif)![ninja-fortnite](https://user-images.githubusercontent.com/34801996/196276841-c2748a1c-e33c-4e65-af60-a972ae0ab964.gif)![ninja-fortnite](https://user-images.githubusercontent.com/34801996/196276841-c2748a1c-e33c-4e65-af60-a972ae0ab964.gif)![ninja-fortnite](https://user-images.githubusercontent.com/34801996/196276841-c2748a1c-e33c-4e65-af60-a972ae0ab964.gif)![ninja-fortnite](https://user-images.githubusercontent.com/34801996/196276841-c2748a1c-e33c-4e65-af60-a972ae0ab964.gif)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by lxhom** [comment]
OH HI NICK LOL

**Comment by junekept** [comment]
please merge fix

**Comment by mythitorium** [comment]
bump because serious issue
