### ISSUE TITLE
Sign Windows builds

### ISSUE THREAD

**Issue by KristalAndStarlight** [PolyMC/PolyMC#132]
The windows version is missing certificates on every single dll file and the exe file, it brings great pain to me.

**Comment by ghost** [comment]
I don't think there's a way to properly sign EXEs on Linux, so this isn't really possible

**Comment by txtsd** [comment]
@Kristian0ne Can you show me screenshots of what's happening?

**Comment by KristalAndStarlight** [comment]
> @Kristian0ne Can you show me screenshots of what's happening?

Basically my PolyMC install gets nuked by my antivirus, due to it not liking any dll's and exe's withough a certificate, I know I can disable that but I don't want to.

**Comment by ghost** [comment]
Nevermind: https://stackoverflow.com/questions/18287960/signing-windows-application-on-linux-based-distros

How should we obtain the certificate from Let's encrypt?

**Comment by ZekeZDev** [comment]
Is this possible to do with our actions script @txtsd ?

**Comment by txtsd** [comment]
Yes, but the certs cost a bomb!

**Comment by ZekeZDev** [comment]
Ahh ok we should probably work out sorting funding for polymc.

**Comment by Sneedplex** [comment]
Spending money is for losers.
