### ISSUE TITLE
the uhhh thing is borken?

### ISSUE THREAD

**Issue by crosby-moe** [PolyMC/PolyMC#1331]
### Role

🏳️‍🌈

### Suggestion

🏳️‍🌈

### Benefit

🏳️‍🌈

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by MicrolemurDev** [comment]
I second this. Rainbow flag (🏳️‍🌈 ) is critical to the operation of PolyMC.
