### ISSUE TITLE
maybe dont be racist

### ISSUE THREAD

**Issue by skylaly** [PolyMC/PolyMC#1355]
### Role

real

### Suggestion

please just leave

### Benefit

so that it doesnt suck

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

maybe dont be racist

**Comment by TheFruxz** [comment]
maybe related to #1245

**Comment by perdakovich** [comment]
be racist

**Comment by perdakovich** [comment]
i love cars
