### ISSUE TITLE
The Poop Dimension

### ISSUE THREAD

**Issue by Sterophonick** [PolyMC/PolyMC#1356]
### Operating System

PoopOS (linux-6.0.1-POOP)

### Version of PolyMC

![poop-dimension](https://user-images.githubusercontent.com/34801996/196277816-66a5f2a6-a9ca-42ff-b9bb-a2a688fc0d34.gif)
![poop-dimension](https://user-images.githubusercontent.com/34801996/196277816-66a5f2a6-a9ca-42ff-b9bb-a2a688fc0d34.gif)
![poop-dimension](https://user-images.githubusercontent.com/34801996/196277816-66a5f2a6-a9ca-42ff-b9bb-a2a688fc0d34.gif)
![poop-dimension](https://user-images.githubusercontent.com/34801996/196277816-66a5f2a6-a9ca-42ff-b9bb-a2a688fc0d34.gif)
![poop-dimension](https://user-images.githubusercontent.com/34801996/196277816-66a5f2a6-a9ca-42ff-b9bb-a2a688fc0d34.gif)
![poop-dimension](https://user-images.githubusercontent.com/34801996/196277816-66a5f2a6-a9ca-42ff-b9bb-a2a688fc0d34.gif)
![poop-dimension](https://user-images.githubusercontent.com/34801996/196277816-66a5f2a6-a9ca-42ff-b9bb-a2a688fc0d34.gif)
![poop-dimension](https://user-images.githubusercontent.com/34801996/196277816-66a5f2a6-a9ca-42ff-b9bb-a2a688fc0d34.gif)

### Version of Qt

![poop-dimension](https://user-images.githubusercontent.com/34801996/196277816-66a5f2a6-a9ca-42ff-b9bb-a2a688fc0d34.gif)
![poop-dimension](https://user-images.githubusercontent.com/34801996/196277816-66a5f2a6-a9ca-42ff-b9bb-a2a688fc0d34.gif)
![poop-dimension](https://user-images.githubusercontent.com/34801996/196277816-66a5f2a6-a9ca-42ff-b9bb-a2a688fc0d34.gif)
![poop-dimension](https://user-images.githubusercontent.com/34801996/196277816-66a5f2a6-a9ca-42ff-b9bb-a2a688fc0d34.gif)
![poop-dimension](https://user-images.githubusercontent.com/34801996/196277816-66a5f2a6-a9ca-42ff-b9bb-a2a688fc0d34.gif)
![poop-dimension](https://user-images.githubusercontent.com/34801996/196277816-66a5f2a6-a9ca-42ff-b9bb-a2a688fc0d34.gif)
![poop-dimension](https://user-images.githubusercontent.com/34801996/196277816-66a5f2a6-a9ca-42ff-b9bb-a2a688fc0d34.gif)

### Description of bug

![poop-dimension](https://user-images.githubusercontent.com/34801996/196277816-66a5f2a6-a9ca-42ff-b9bb-a2a688fc0d34.gif)
![poop-dimension](https://user-images.githubusercontent.com/34801996/196277816-66a5f2a6-a9ca-42ff-b9bb-a2a688fc0d34.gif)
![poop-dimension](https://user-images.githubusercontent.com/34801996/196277816-66a5f2a6-a9ca-42ff-b9bb-a2a688fc0d34.gif)
![poop-dimension](https://user-images.githubusercontent.com/34801996/196277816-66a5f2a6-a9ca-42ff-b9bb-a2a688fc0d34.gif)
![poop-dimension](https://user-images.githubusercontent.com/34801996/196277816-66a5f2a6-a9ca-42ff-b9bb-a2a688fc0d34.gif)
![poop-dimension](https://user-images.githubusercontent.com/34801996/196277816-66a5f2a6-a9ca-42ff-b9bb-a2a688fc0d34.gif)
![poop-dimension](https://user-images.githubusercontent.com/34801996/196277816-66a5f2a6-a9ca-42ff-b9bb-a2a688fc0d34.gif)

### Steps to reproduce

![poop-dimension](https://user-images.githubusercontent.com/34801996/196277816-66a5f2a6-a9ca-42ff-b9bb-a2a688fc0d34.gif)
![poop-dimension](https://user-images.githubusercontent.com/34801996/196277816-66a5f2a6-a9ca-42ff-b9bb-a2a688fc0d34.gif)
![poop-dimension](https://user-images.githubusercontent.com/34801996/196277816-66a5f2a6-a9ca-42ff-b9bb-a2a688fc0d34.gif)
![poop-dimension](https://user-images.githubusercontent.com/34801996/196277816-66a5f2a6-a9ca-42ff-b9bb-a2a688fc0d34.gif)
![poop-dimension](https://user-images.githubusercontent.com/34801996/196277816-66a5f2a6-a9ca-42ff-b9bb-a2a688fc0d34.gif)
![poop-dimension](https://user-images.githubusercontent.com/34801996/196277816-66a5f2a6-a9ca-42ff-b9bb-a2a688fc0d34.gif)
![poop-dimension](https://user-images.githubusercontent.com/34801996/196277816-66a5f2a6-a9ca-42ff-b9bb-a2a688fc0d34.gif)

### Suspected cause

![poop-dimension](https://user-images.githubusercontent.com/34801996/196277816-66a5f2a6-a9ca-42ff-b9bb-a2a688fc0d34.gif)
![poop-dimension](https://user-images.githubusercontent.com/34801996/196277816-66a5f2a6-a9ca-42ff-b9bb-a2a688fc0d34.gif)
![poop-dimension](https://user-images.githubusercontent.com/34801996/196277816-66a5f2a6-a9ca-42ff-b9bb-a2a688fc0d34.gif)
![poop-dimension](https://user-images.githubusercontent.com/34801996/196277816-66a5f2a6-a9ca-42ff-b9bb-a2a688fc0d34.gif)
![poop-dimension](https://user-images.githubusercontent.com/34801996/196277816-66a5f2a6-a9ca-42ff-b9bb-a2a688fc0d34.gif)
![poop-dimension](https://user-images.githubusercontent.com/34801996/196277816-66a5f2a6-a9ca-42ff-b9bb-a2a688fc0d34.gif)
![poop-dimension](https://user-images.githubusercontent.com/34801996/196277816-66a5f2a6-a9ca-42ff-b9bb-a2a688fc0d34.gif)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by sunglocto** [comment]
Relatable

**Comment by junekept** [comment]
TRUE!!!

**Comment by ghost** [comment]
poop demension fr fr
