### ISSUE TITLE
No Code of Conduct

### ISSUE THREAD

**Issue by billyboybob** [PolyMC/PolyMC#1357]
### Role

I play modded Minecraft

### Suggestion

I want a Code of Conduct

### Benefit

Code of Conduct reasons.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Hello,
As a person who likes looking at projects from time to time, I noticed that your Code of Conduct was recently deleted from the repository with the reason "reclaim polymc from the leftoids". As a person with a normally functioning brain, I'm not aware as to what these words mean. However, not having a Code of Conduct in your repository can lead to problems involving people who want to hurt others joining a community, and could seriously affect the reputation of the project.

:)
![spacechimps](https://user-images.githubusercontent.com/61484364/196278472-38ddf91c-d9a3-4aa0-89fa-12adb1d6b185.gif)

**Comment by billyboybob** [comment]
Can you also add the DOOM source code? SNES version specifically.

**Comment by TheFruxz** [comment]
related to #1240

**Comment by billyboybob** [comment]
> related to #1240

Ah shit, didn't see that one! However, not having the DOOM source code is a major sin.

**Comment by irisfalke** [comment]
i think this issue should be fixed still waiting for a nice COC to get added

**Comment by billyboybob** [comment]
> i think this issue should be fixed still waiting for a nice COC to get added

i love clash of clans
