### ISSUE TITLE
Remove PrefersNonDefaultGPU from Desktop file

### ISSUE THREAD

**Issue by Jan200101** [PolyMC/PolyMC#136]
`PrefersNonDefaultGPU` is a newly added part of the desktop entry spec that allow Desktop Environments to choose to use a GPU that is not the default.

This is useful in cases like Laptops with dedicated GPUs that are not the default.

But it is not very explicit in what the program wants and will fail in cases of Desktop machines where the iGPU is available but not used as default.

A more explicit solution has been discussed on [this issue](https://gitlab.freedesktop.org/xdg/xdg-specs/-/issues/59) but has since gone stale

**Comment by txtsd** [comment]
This is keeping us from building AppImages on GHA because AppImageKit's included version of `desktop-file-validate` is too old.
I filed [an issue](https://github.com/AppImage/AppImageKit/issues/1171), however, there's a [much older issue](https://github.com/AppImage/AppImageKit/issues/871) that suggests it's not a priority for them.

**Comment by Jan200101** [comment]
To follow up on this because people on the Discord discusses how `PrefersNonDefaultGPU` is expected to behave.

to quote the summary

```

              If true, the application prefers to be run on a more powerful discrete GPU if available,
              which we describe as “a GPU other than the default one” in this spec to avoid the need
              to define what a discrete GPU is and in which cases it might be considered more powerful
              than the default GPU.
              This key is only a hint and support might not be present depending on the implementation.

```

but as you can see it itself says it doesn't specifiy a definition for a discrete or dedicated GPU other than `“a GPU other than the default one”`

The spec is rather vague in what it aims to achieve and the implementation a across the board shows this

https://github.com/ValveSoftware/steam-for-linux/issues/7089#issuecomment-903155719

**Comment by d-513** [comment]
on the other hand, when you  dont include it, by default it would run on the iGPU on some systems.
There's no good solution, but maybe we could include it as an option in the launcher, which would edit the desktop file to change it to true/false

**Comment by Jan200101** [comment]
> on the other hand, when you dont include it, by default it would run on the iGPU on some systems. There's no good solution, but maybe we could include it as an option in the launcher, which would edit the desktop file to change it to true/false

that would add another dependency on something that correctly parses .desktop files or require us to implement our own (I suggest looking at eduke32 if you are going to)

This is a cat and mouse game and its probably best to take the same way MultiMC does, use whatever the system provides by default and allow people to use wrapper commands like optirun
