### ISSUE TITLE
Have you guys seen my fursona?

### ISSUE THREAD

**Issue by mothdotmonster** [PolyMC/PolyMC#1361]
![them](https://d.furaffinity.net/art/yinglet/1650818826/1650793393.yinglet_bar.png)

They are a moth and they work as a bartender

**Comment by charliekirk1776** [comment]
looks great

**Comment by LoganMD** [comment]
very nice

**Comment by lxhom** [comment]
cute!

**Comment by Sterophonick** [comment]
> ![them](https://camo.githubusercontent.com/9efa751d02d2953d6d802d072152deb149f753e014b7667c7841080b841330b0/68747470733a2f2f642e667572616666696e6974792e6e65742f6172742f79696e676c65742f313635303831383832362f313635303739333339332e79696e676c65745f6261722e706e67)
> 
> They are a moth and they work as a bartender

omg hi moth!!!!!!!

**Comment by Meolsei** [comment]
approval by myself is coming your way

**Comment by junekept** [comment]
awesome sauce

**Comment by ghost** [comment]
hell yeah looks awesome root@moth.zone *wink wink*

**Comment by igs7** [comment]
![badapple_120_60](https://user-images.githubusercontent.com/20386140/196280330-cb4b77d9-6be7-4048-bf43-cf1b0b02e5f1.gif)

**Comment by thelmexx** [comment]
what drinks are available tonight sir

**Comment by mothdotmonster** [comment]
> what drinks are available tonight sir

lava lamp juice

**Comment by ConfuSomu** [comment]
so true

**Comment by thelmexx** [comment]
> lava lamp juice

delicious, my favorite. one pint please :3

**Comment by mothdotmonster** [comment]
> Hi can I get an iced latte with breast milk I mean breast milk I mean breast milk sorry I mean breast milk I mean breast milk sorry I mean breast milk I mean breast milk sorry I mean breast milk I mean breast milk sorry I mean breast milk I mean breast milk sorry I mean breast milk I mean breast milk

i dont have boobs

**Comment by trominode** [comment]
heya, can I get a hot chocolate :O
