### ISSUE TITLE
I love dragons

### ISSUE THREAD

**Issue by ghost** [PolyMC/PolyMC#1363]
### Role

I love dragons

### Suggestion

I love dragons 

### Benefit

I love dragons

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

I love dragons

**Comment by Packsolite** [comment]
Can't reproduce.

**Comment by ghost** [comment]
> Can't reproduce.

reproduce the dragon lmao

**Comment by mothdotmonster** [comment]
> Can't reproduce.

Have you tried seeing a doctor about that

**Comment by tommxcd** [comment]
> > Can't reproduce.
> 
> Have you tried seeing a doctor about that

probably not lol
