### ISSUE TITLE
Images of @LennyMcLegginton's face leaked.

### ISSUE THREAD

**Issue by LennyMcDeathSentence** [PolyMC/PolyMC#1366]
@LennyMcLennington Hi! Look! You!
![8815767a73a34470b5e13d380e2b82e4d361a4a4r1-802-962v2_hq](https://user-images.githubusercontent.com/116036297/196280460-b847f045-8aba-433f-b7a9-c59f70a0b772.jpg)

**Comment by BabBimmaBome** [comment]
your kind doesnt want to be hated but does everything possible to be hated

**Comment by Joshument** [comment]
"your kind" lmfao

**Comment by rabywastaken** [comment]
> your kind doesnt want to be hated but does everything possible to be hated

I don't know exactly what you mean by your kind, but you gotta agree that this isn't even trying to be funny, it's just deplorable and fucked up

**Comment by BabBimmaBome** [comment]
how dare he dislike someone

**Comment by BabBimmaBome** [comment]
i bet if he disliked trump no one would care but no he dislikes groomers and gets non stop harrassment from the people that want everyone to be equal makes sense
