### ISSUE TITLE
Leaked nudes of Lenny

### ISSUE THREAD

**Issue by Sunconure11** [PolyMC/PolyMC#1367]
### Role

I found his nudes

### Suggestion

I want them distributed on 4chan

### Benefit

Amusement

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

https://www.youtube.com/watch?v=dQw4w9WgXcQ

**Comment by ata-star** [comment]
[Oof its true](https://kekma.net/)
