### ISSUE TITLE
Trans rights are human rights

### ISSUE THREAD

**Issue by tuxcrafting** [PolyMC/PolyMC#1368]
But it may be time for trans wrongs

**Comment by tommxcd** [comment]
trans up and trans downs?

**Comment by Sunconure11** [comment]
Transphobes get the bullet

**Comment by a-weeb-programmer** [comment]
trans norths

**Comment by a-weeb-programmer** [comment]
trans rights my beloved <3

**Comment by BabBimmaBome** [comment]
if you want everyone to have rights why doesnt he get rights? lgbt logic

**Comment by tommxcd** [comment]
i don't care what direction it's in, just give me trans <3

**Comment by Extravi** [comment]
uwu

**Comment by ConfuSomu** [comment]
real

**Comment by a-weeb-programmer** [comment]
owo

**Comment by AwesomePerson2** [comment]
hello!

**Comment by Extravi** [comment]
i am a femboy

**Comment by Nekurone** [comment]
based and trans-rights pilled

**Comment by a-weeb-programmer** [comment]
i am a trans girl :3

**Comment by AwesomePerson2** [comment]
im also a trans girl

**Comment by Extravi** [comment]
github is spamming my email

**Comment by tuxcrafting** [comment]
> github is spamming my email

same this is great

**Comment by Alcosmos** [comment]
Nerds

**Comment by Extravi** [comment]
lmao

**Comment by tuxcrafting** [comment]
> if you want everyone to have rights why doesnt he get rights? lgbt logic

i had sex with your mom last night

**Comment by AwesomePerson2** [comment]
sounds sus

**Comment by Alcosmos** [comment]
> if you want everyone to have rights why doesnt he get rights? lgbt logic

I had gender with your mom

**Comment by a-weeb-programmer** [comment]
> im also a trans girl

nice uwu

**Comment by a-weeb-programmer** [comment]
:transgender_flag::rainbow_flag::transgender_flag::rainbow_flag::transgender_flag::rainbow_flag::transgender_flag::rainbow_flag::transgender_flag::rainbow_flag:

**Comment by Alcosmos** [comment]
🏳️‍⚧️🏳️‍⚧️🏳️‍⚧️🏳️‍⚧️🏳️‍⚧️🏳️‍⚧️🏳️‍⚧️🏳️‍⚧️🏳️‍⚧️🏳️‍⚧️🏳️‍⚧️🏳️‍⚧️🏳️‍⚧️🏳️‍⚧️🏳️‍⚧️🏳️‍⚧️🏳️‍⚧️🏳️‍⚧️🏳️‍⚧️🏳️‍⚧️🏳️‍⚧️🏳️‍⚧️🏳️‍⚧️🏳️‍⚧️

**Comment by AwesomePerson2** [comment]
> > im also a trans girl
> 
> nice uwu

already taken

**Comment by Extravi** [comment]
what happening

**Comment by Alcosmos** [comment]
idk

**Comment by Extravi** [comment]
why this being talking about on a mc client

**Comment by Extravi** [comment]
someone just linked me this github lol

**Comment by AwesomePerson2** [comment]
polymc owner is transphobic

**Comment by Alcosmos** [comment]
who did i just call a virgin btw

**Comment by AwesomePerson2** [comment]
no clue

**Comment by tommxcd** [comment]
me lol

> who did i just call a virgin btw

**Comment by AwesomePerson2** [comment]
if you all wanna email me agentdeath253@gmail.com

(dont tell my gf)

**Comment by Alcosmos** [comment]
feels extremely weird to use github for shitposting

**Comment by ConfuSomu** [comment]
> feels extremely weird to use github for shitposting

yeah, it does lol

this repo has exploded

**Comment by tommxcd** [comment]
it's so wrong, but it feels so good

> feels extremely weird to use github for shitposting

**Comment by AwesomePerson2** [comment]
i have 5 github accounts so im good

**Comment by Alcosmos** [comment]
> me lol
> 
> > who did i just call a virgin btw

are u a transphobe, else why are u saying he got head 💀

**Comment by tuxcrafting** [comment]
the only reason i use this gh account is shitposting at this point, codeberg 4ever

**Comment by AwesomePerson2** [comment]
um

**Comment by Extravi** [comment]
> polymc owner is transphobic

oh okay

**Comment by Alcosmos** [comment]
is this shit public, im from my main 💀

**Comment by Extravi** [comment]
> is this shit public, im from my main skull

same

**Comment by Extravi** [comment]
i hope github does not nuke my account

**Comment by AwesomePerson2** [comment]
this is public

**Comment by Extravi** [comment]
yeah

**Comment by Alcosmos** [comment]
your main got thigh highs as pfp 💀

**Comment by AwesomePerson2** [comment]
github will prob drop the bomb

**Comment by Alcosmos** [comment]
removin jsut in case idk

**Comment by Extravi** [comment]
yeah

**Comment by AwesomePerson2** [comment]
> your main got thigh highs as pfp 💀

ill do it

**Comment by tommxcd** [comment]
> > me lol
> > > who did i just call a virgin btw
> 
> are u a transphobe, else why are u saying he got head skull

no i was that the defender was getting more head. im literally bi why would i be a transphobe lol

**Comment by Extravi** [comment]
what if i am a femboy

**Comment by Extravi** [comment]
they know my github account

**Comment by tommxcd** [comment]
femboys tbh

**Comment by Extravi** [comment]
i am in grade 12 atm

**Comment by tommxcd** [comment]
I am in the 10th grade

**Comment by AwesomePerson2** [comment]
im in 11th

**Comment by Extravi** [comment]
but we ain't even coding in computer science

**Comment by AwesomePerson2** [comment]
ouch

**Comment by Alcosmos** [comment]
> > > me lol
> > > > who did i just call a virgin btw
> > 
> > 
> > are u a transphobe, else why are u saying he got head skull
> 
> no i was saying that the defender was getting more head. im literally bi why would i be a transphobe lol

oof sry i got excited with the insults 💀

**Comment by Extravi** [comment]
they teaching about mass surveillance

**Comment by Extravi** [comment]
if my teachers ever see my github account :skull:

**Comment by Alcosmos** [comment]
omg yall babies im 21
