### ISSUE TITLE
my balls itch

### ISSUE THREAD

**Issue by 5space** [PolyMC/PolyMC#1376]
### Version of PolyMC

at least 3

### Version of Qt

1

### Description of bug

please Help    me

### Steps to reproduce

there are bugs under my skin

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by mothdotmonster** [comment]
i am the bug, can confirm i am under his skin

**Comment by tuxcrafting** [comment]
peel off your skin
