### ISSUE TITLE
Make modpack version available to the user after installation

### ISSUE THREAD

**Issue by Lyle-Tafoya** [PolyMC/PolyMC#138]
### Role

I play modded Minecraft and sometimes install different versions of the same modpack

### Suggestion

I want a way to easily tell the version number of a given modpack instance without having to manually rename them to include the version number

### Benefit

So there is never confusion about which instance is which, regardless of whether the user has remembered to rename the instance

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

For whatever reason, the modpack version is only ever shown to the user when they are selecting which version to install (via "Add Instance"). After that, the user is completely on their own to identify the version number of the modpack. If the version number is not displayed at the main menu after launching the game, there is no easy way to tell what version it is. I think the easiest way to handle this would be to include the version number in the name of the instance folder. The path to the instance folder is displayed on-hover in PolyMC already, and so this would make the information easily available by default, without the player needing to perform any extra steps. Including the version number in the name of the instance by default is also not a terrible idea. Another possible candidate for somewhere to put this information is the "version" tab from the "Edit Instance" menu.

**Comment by HalJordan** [comment]
This has always been an annoyance of mine with this and that which shall not be named.

The only way around this is to edit the Instance name when you first set it up.

Either default to putting it in the name, or maybe add something to the instance.cfg or mmc-pack.json.

It's probably time to rename mmc-pack.json to further distance this project from that which shall not be named.

**Comment by Scrumplex** [comment]
This has been implemented for Technic modpacks already in #384

**Comment by DioEgizio** [comment]
> This has been implemented for Technic modpacks already in #384

actually, we already have that on FTB and ATLauncher modpacks too.
Just not Curse and FTB Legacy

**Comment by HalJordan** [comment]
Is there any reason not to be consistent in that?

**Comment by Scrumplex** [comment]
> Is there any reason not to be consistent in that?

mostly just implementation details. The modpack services were added slowly over time by different people, which is why it's not consistent currently.

**Comment by DioEgizio** [comment]
After investigating a bit, this is impossible to implement on CurseForge since it doesn't have a versioning system like other modpack platforms.

**Comment by Scrumplex** [comment]
So the only modpack platform left should be FTB

**Comment by DioEgizio** [comment]
*FTB Legacy, FTB already has that
