### ISSUE TITLE
Scoop support

### ISSUE THREAD

**Issue by CamperSamu** [PolyMC/PolyMC#139]
### Role

I hate Windows but I have to use it.

### Suggestion

Create a [Scoop](https://scoop.sh/) bucket for PolyMC or file a request to add the package to the main or extra buckets

### Benefit

I won't have to open _rebranded google chrome_ ever again

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Seriously typing `scoop install polymc` takes like 0.1s compared to opening a browser and doing windows things

**Comment by Lupus590** [comment]
Maybe related to #66

**Comment by lem6ns** [comment]
~~Calinou/scoop-games#565 will resolve this issue when it is merged.~~
Above will add it to the games bucket, not main or extra.

**Comment by CamperSamu** [comment]
https://github.com/Calinou/scoop-games/pull/565 got merged, this issue can be closed after updating the readme.

**Comment by CamperSamu** [comment]
Actually I'm trying to install the package and the hash check fails every time.

**Comment by CamperSamu** [comment]
Also, the package is marked as 64 bit while it's actually 32 bit

**Comment by lem6ns** [comment]
Calinou/scoop-games#576 will fix hash issue

**Comment by Scrumplex** [comment]
Can this be closed?

**Comment by DioEgizio** [comment]
> Can this be closed?

Well I think yes as polymc is on games bucket atm

**Comment by Scrumplex** [comment]
Closing this as solved then
