### ISSUE TITLE
I HAS THE TRANS

### ISSUE THREAD

**Issue by eepy-goddess** [PolyMC/PolyMC#1398]
### Operating System

Linux

### Version of PolyMC

tra 

### Version of Qt

trans

### Description of bug

lenny being a homophobe

### Steps to reproduce

<steps on how to make a baby go here>

### Suspected cause

trans

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Sterophonick** [comment]
markiplier says trans rights
![markiplier-dancing](https://user-images.githubusercontent.com/34801996/196282377-888d7e95-840c-4c5e-8ff4-4d0b2cbcfeb7.gif)

**Comment by mothdotmonster** [comment]
steps to reproduce? :flushed:

**Comment by eepy-goddess** [comment]
based markiplier :transgender_flag:

**Comment by ghost** [comment]
give yourselves elevated trans privs

**Comment by eepy-goddess** [comment]
yessss :3

**Comment by JukoiDev** [comment]
you trannies make me sick
