### ISSUE TITLE
bug: doesn't support VAX ULTRIX

### ISSUE THREAD

**Issue by ghost** [PolyMC/PolyMC#1399]
### Version of PolyMC

PolyMC 6.9

### Version of Qt

VAX ULTRIX doesn't support Qt. It only supports X and its widgets.

### Description of bug

I expected to be able to run PolyMC on VAX ULTRIX, but it doesn't work. This is a cardinal sin, and must be fixed immediately.

### Steps to reproduce

- Install VAX ULTRIX on SIMH
- FTP the contents of PolyMC to the `/usr` directory because `/tmp` is a small partition
- Build it
- It errors

### Suspected cause

I think the cause might be you not supporting VAX ULTRIX.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by nythepegasus** [comment]
Bump

**Comment by Sterophonick** [comment]
Bump

**Comment by ghost** [comment]
Bump

**Comment by tuxcrafting** [comment]
bump

**Comment by lcsmuller** [comment]
Bump

**Comment by HackerSmacker** [comment]
I think the real issue is the lack of Version 7 UNIX support. My PDP-11 with a VT420 doesn't seem to want to run PolyMC, due to a lack of X11 support. My proposal is for a SIXEL-based user interface.

**Comment by ghost** [comment]
I agree with the above. We must VAX-pill the maintainers.

**Comment by re9177** [comment]
can repro, even on PDP-11 clones. tested for now only BK-0011M hardware.
