### ISSUE TITLE
🇷🇺🇷🇺🇷🇺🇷🇺🇷🇺🇷🇺🇷🇺🇷🇺🇷🇺🇷🇺🇷🇺🇷🇺🇷🇺🇷🇺🇷🇺🇷🇺🇷🇺🇷🇺🇷🇺🇷🇺🇷🇺🇷🇺🇷🇺🇷🇺🇷🇺🇷🇺🇷🇺🇷🇺🇷🇺🇷🇺🇷🇺🇷🇺🇷🇺🇷🇺🇷🇺🇷🇺🇷🇺🇸🇾

### ISSUE THREAD

**Issue by zprix** [PolyMC/PolyMC#1400]
### Role

🇸🇾🇸🇾

### Suggestion

🇸🇾🇸🇾

### Benefit

🇸🇾🇸🇾

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Слава России
عاشت سوريا

🇷🇺🇸🇾

**Comment by Extravi** [comment]
wowa

**Comment by tuxcrafting** [comment]
i love fascist regimes omg bestie

**Comment by eepy-goddess** [comment]
amogus
