### ISSUE TITLE
OptiFine installation

### ISSUE THREAD

**Issue by d-513** [PolyMC/PolyMC#141]
### Role

using the optifine mod to optimize the game

### Suggestion

We should have a button to install OptiFine just like we have install fabric and install forge.

### Benefit

To make it easier for users

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by Scrumplex** [comment]
I don't know if we can automatically pull OptiFine. The creator clearly wants users to use adfocus or their website in general for ad revenue.
Provided the user downloads OptiFine manually, we could offer an option to install that release.

**Comment by txtsd** [comment]
> I don't know if we can automatically pull OptiFine. The creator clearly wants users to use adfocus or their website in general for ad revenue. Provided the user downloads OptiFine manually, we could offer an option to install that release.

This sounds alright. Hitting an 'Install Optifine' button can bring up a filechooser to pick the OptiFine installer.

**Comment by DioEgizio** [comment]
That feature would be nice but we can't redistribute optifine without sp permission and no meta exists

Also in modern Minecraft optifine isn't the best way to do things

**Comment by DioEgizio** [comment]
> I don't know if we can automatically pull OptiFine. The creator clearly wants users to use adfocus or their website in general for ad revenue. Provided the user downloads OptiFine manually, we could offer an option to install that release.

That's basically how things work now. You install forge, and then you install optifine as a mod

**Comment by d-513** [comment]
yes, but many users don't need the overhead of forge just to run vanilla + optifine. This would be a nice feature, and yes fabolously optimized is better but obviously thats only for fabric supported versions

**Comment by DioEgizio** [comment]
yeah that, I never understood why installing optifine without modloader is so painful in multimc

**Comment by TheKodeToad** [comment]
You can extract OptiFine, select Replace in JAR... and select the extracted version.

There's only a single step that can be removed (unless you're prepared to scrape off OptiFine's website), and it may not be worth the effort. Although it would be nice if that method was documented. I found that out from my friend.

**Comment by DioEgizio** [comment]
https://github.com/MultiMC/MultiMC5/wiki/MultiMC-and-OptiFine

It is?

**Comment by Scrumplex** [comment]
Maybe we should just keep this as is. I feel like we should primarily strive to promote free alternatives like Sodium.

**Comment by DioEgizio** [comment]
I agree
