### ISSUE TITLE
Move distro specific files to their own folder

### ISSUE THREAD

**Issue by txtsd** [PolyMC/PolyMC#142]
There are currently 3 NixOS files in the top level directory of the repo.
Let's move them into packages/nix.

**Comment by Scrumplex** [comment]
afaik, you can't move them away, as they won't work otherwise.

**Comment by txtsd** [comment]
Could you point me to documentation about it?

**Comment by bbjubjub2494** [comment]
Per the [nix manual](https://nixos.org/manual/nix/stable/command-ref/new-cli/nix3-flake.html#description)

> A flake is a filesystem tree (typically fetched from a Git repository or a tarball) that contains a file named flake.nix in the root directory.

Hence `flake.nix` must be at the root. `flake.lock` ensure reproducibility.

Per the [nix manual](https://nixos.org/manual/nix/stable/command-ref/nix-channel.html#channel-format)
> That directory must contain a file default.nix that serves as the channel’s “entry point”.

`default.nix` provides compatibility with old-style nix channels and channel-like usage. It is conceivable that when Flakes are widely adopted, we could get rid of it.

**Comment by txtsd** [comment]
Ah so there's nothing we can do about it.
