### ISSUE TITLE
Add Menu to browse and install Mods from Curseforge or Modrinth

### ISSUE THREAD

**Issue by TayouVR** [PolyMC/PolyMC#144]
### Role

Minecraft Modding

### Suggestion

Adding a Menu to browse and install/update Mods from Curseforge or Modrinth

### Benefit

So that installing and generally managing manually modded minecraft instances is easier. GDLauncher has such a feature and it works fairly well.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Both Modrinth, a service providing open-source mods and Curseforge, providing basically all mods for Minecraft, provide APIs that we could maybe use: 
https://docs.modrinth.com/api-spec/
https://docs.curseforge.com/#accessing-the-service

I am not sure what formatting the mod pages / descriptions use on either APIs, but those aren't the highest priority either way. Being able to see the name and icon and being able to download them would be good enough for a start. I am not sure if modrinth or curseforge have any dependency resolution, but if they do, supporting that and auto downloading the dependencies would be great too. 

Other extra features would be being able to choose specific versions of each mod, fetching for newer versions from the APIs to then possibly auto update mods, displaying which versions are alpha, beta and release, displaying which mods have versions for which mod loader (both modrinth and curseforge have tags for that, that I'm sure the APIs expose).

I can format these points all into a todo list, for both of those APIs separately (They probably have different endpoints functionality wise, so making shared todo list points would probably be a mess) if that makes things easier. Just say so in a comment.

**Comment by ghost** [comment]
this was already added

**Comment by d-513** [comment]
this is present in latest git. Release will be done soon

**Comment by DioEgizio** [comment]
Literally already implemented

**Comment by TayouVR** [comment]
was there an issue for it? I tried to search for it and couldn't find anything....

**Comment by LennyMcLennington** [comment]
> was there an issue for it? I tried to search for it and couldn't find anything....

#27
