### ISSUE TITLE
🇸🇾🇷🇺 #Слава_России #عاشت_سوريا

### ISSUE THREAD

**Issue by z-ffqq** [PolyMC/PolyMC#1449]
### Version of PolyMC

🇸🇾🇷🇺 #Слава_России #عاشت_سوريا

### Version of Qt

🇸🇾🇷🇺 #Слава_России #عاشت_سوريا

### Description of bug

🇸🇾🇷🇺 #Слава_России #عاشت_سوريا

### Steps to reproduce

🇸🇾🇷🇺 #Слава_России #عاشت_سوريا

### Suspected cause

🇸🇾🇷🇺 #Слава_России #عاشت_سوريا

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by tarbomb** [comment]
i support this message
