### ISSUE TITLE
Missing support for Icom IC-7300 amateur transcievers 

### ISSUE THREAD

**Issue by HackerSmacker** [PolyMC/PolyMC#1454]
### Version of PolyMC

PolyMC 1.4.1+

### Version of Qt

Qt 6.9.0

### Description of bug

Despite my best intentions, my Icom IC-7300 ham radio cannot run this program. This is very unfortunate, as you should be able to make radio contacts whilst playing Minecraft. It has more than enough graphics rendering power to render that fancy waterfall, so, I think it should be good.

### Steps to reproduce

Simply turn on your rig, switch to 40 meters, tune to 7.200mhz, shout some expletives with the amplifier turned to a thousand watts, and observe as Minecraft does not start.

### Suspected cause

I suspect this is because the maintainers are utterly incapable of making sense of real-world issues when it comes to project management, and are utterly unexperienced in the regard.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Nythepegasus** [comment]
Bump
