### ISSUE TITLE
Add PolyMC to list of groups using makedeb

### ISSUE THREAD

**Issue by hwittenborn** [PolyMC/PolyMC#147]
### Role

Developer for packaging tools

### Suggestion

Add PolyMC to list of users who are currently using makedeb for packaging

### Benefit

It would benefit both projects, as it makes makedeb look better, and gives PolyMC recognition on another website

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.
At the moment I'm wondering if you guys would be fine with it, and if you like what I currently have it set up as (the image below is just a local preview, the public homepage for makedeb can be at [makedeb.org](https://www.makedeb.org/).):

![image](https://user-images.githubusercontent.com/74838472/153309125-e9ca1b95-da8d-4ee9-b719-30839b8636fd.png)

**Comment by hwittenborn** [comment]
Another thing: should I link to this GitHub page or the PolyMC homepage if we go through with this?

**Comment by ghost** [comment]
We're still in the process of transferring polymc.org to a more permanent solution, so link the Github for now.

**Comment by ghost** [comment]
additionally, I'm on board with this, and if @LennyMcLennington is too then you can go ahead

**Comment by d-513** [comment]
I agree with this.

**Comment by LennyMcLennington** [comment]
okay

**Comment by timoreo22** [comment]
i agree too

**Comment by hwittenborn** [comment]
Does that mean I'm good to add PolyMC to the list of users then?

**Comment by d-513** [comment]
> Does that mean I'm good to add PolyMC to the list of users then?

Yes.

**Comment by LennyMcLennington** [comment]
Have it link to https://polymc.github.io for now because we don't have the new site at polymc.org yet.

**Comment by hwittenborn** [comment]
Fantastic, sounds great! I'll have everything deployed shortly.

> Have it link to https://polymc.github.io/ for now because we don't have the new site at polymc.org yet.

Sounds good, I'll do that.

Let me know if you have anything else :)
