### ISSUE TITLE
open a new issue not owned by me

### ISSUE THREAD

**Issue by Chrono-byte** [PolyMC/PolyMC#1475]

**Comment by Kaydax** [comment]
This was already done by #549, however for some reason it decides to use the system trash instead of managing its own trash. It would be 10x better to just manage trashed instances in the client itself without relying on the system trash

**Comment by ghost** [comment]
🏳️‍⚧️

**Comment by BowDown097** [comment]
No.

**Comment by basdxz** [comment]
> 🏳️‍⚧️

trans rights

**Comment by RedNicStone** [comment]
> This was already done by #549, however for some reason it decides to use the system trash instead of managing its own trash. It would be 10x better to just manage trashed instances in the client itself without relying on the system trash

This could be implemented using the tag system that is already in place. Potentially add a `deleted` tag to deleted instances and hide those instead of moving them to a specific folder.

**Comment by Kaydax** [comment]
> > This was already done by #549, however for some reason it decides to use the system trash instead of managing its own trash. It would be 10x better to just manage trashed instances in the client itself without relying on the system trash
> 
> This could be implemented using the tag system that is already in place. Potentially add a `deleted` tag to deleted instances and hide those instead of moving them to a specific folder.

Yah that's what I was planning on doing, and its also better to keep the deleted modpack folders in its own little containment folder for easier clean up for users via file managers instead of using the launcher only

**Comment by RedNicStone** [comment]
Great! I was thinking about implementing it eariler today but I ended up wasting my time on some gradle stuff.
One problem I see is that this would not work with worlds, resources packs and the sort like mentioned in #1197.
