### ISSUE TITLE
The Flathub link is dead

### ISSUE THREAD

**Issue by Rillian-Grant** [PolyMC/PolyMC#1485]
### Operating System

Linux

### Version of PolyMC

n/a

### Version of Qt

n/a

### Description of bug

The flathub link on the website is broken

### Steps to reproduce

Go to this page: https://polymc.org/download/steam-deck/
And click the flathub link: https://flathub.org/apps/details/org.polymc.PolyMC

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by HeyaGlitz** [comment]
It was marked EOL, however it still is available on https://beta.flathub.org/apps/details/org.polymc.PolyMC
We're working to get a new release out soon, so stay tuned

**Comment by LennyMcLennington** [comment]
We are preparing for a new release to come out today or tomorrow, with it we will include a Flatpak that you can download and install by using the `flatpak install` command. We will include full instructions on the website.

Hopefully this will only need to be a temporary measure and Flathub will add PolyMC back to their repo soon.

**Comment by ata-star** [comment]
I Hope not LUL

@Rillian-Grant https://www.gamingonlinux.com/2022/10/if-you-use-polymc-for-minecraft-you-should-switch-away-now/

**Comment by MathiasDevelopes** [comment]
Yes it is dead, and you should **not** use this project anymore. Rather use https://prismlauncher.org/ or MultiMC

**Comment by Quantenzitrone** [comment]
Use [PrismLauncher](https://github.com/prismlauncher/prismlauncher) instead

its a fork without Lenny who kicked the entire other dev team

**Comment by PedroVNasc** [comment]
It seems to be working again, I just updated PolyMC with flatpak update

**Comment by HeyaGlitz** [comment]
> It seems to be working again, I just updated PolyMC with flatpak update

We got it added back recently

**Comment by LennyMcLennington** [comment]
It's back on flathub now.
