### ISSUE TITLE
Add 🏳️‍⚧️

### ISSUE THREAD

**Issue by ghost** [PolyMC/PolyMC#1488]
### Role

I am 🏳️‍⚧️

### Suggestion

🏳️‍⚧️

### Benefit

🏳️‍⚧️

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

🏳️‍⚧️🏳️‍⚧️🏳️‍⚧️🏳️‍⚧️🏳️‍⚧️🏳️‍⚧️🏳️‍⚧️🏳️‍⚧️🏳️‍⚧️🏳️‍⚧️🏳️‍⚧️🏳️‍⚧️🏳️‍⚧️🏳️‍⚧️🏳️‍⚧️🏳️‍⚧️🏳️‍⚧️🏳️‍⚧️🏳️‍⚧️🏳️‍⚧️🏳️‍⚧️🏳️‍⚧️🏳️‍⚧️🏳️‍⚧️🏳️‍⚧️

**Comment by basdxz** [comment]
🏳️‍⚧️🏳️‍⚧️
