### ISSUE TITLE
Remove all of my contributions from PolyMC

### ISSUE THREAD

**Issue by TheOPtimal** [PolyMC/PolyMC#1491]
### Role

I've previously contributed to PolyMC, namely in the Nix department

### Suggestion

I want all of my contributions to PolyMC to be removed from the project due to the new management.

### Benefit

I no longer want to be associated with the project.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

I own the copyright to all of my code, therefore I have the right to request its removal.

**Comment by RedNicStone** [comment]
This is not how OSS works, by contributing ~you agree to transfer ownership of your work to the project under the project's licence.~
Sorry my bad here, under this projects licencing you still retain copyright to your contributions. 
However since your contribution must be licenced under the same license as the project (GPL-3.0-by), the owner is free to ignore your request.

**Comment by HeyaGlitz** [comment]
You didn't explicitly copyright the code you made, therefore it's under our copyright. Please research how copyright works before making an issue in the future.

**Comment by furtabs** [comment]
Y

**Comment by HeyaGlitz** [comment]
We aren't required to comply unless you appended your own copyright to the file. (Aka you transferred ownership to us)

**Comment by strkeeper** [comment]
it's fundamentally not possible to selectively remove contributions history (and thus, association) from github repositories. if you want to hide your github activity you can do it in your profile settings.

**Comment by RedNicStone** [comment]
Also, while your contributions are surely appreciated, I doubt PolyMC _needed_ some windows script kiddie to add support for some obscure package manager.

**Comment by Midou36O** [comment]
Based on the CLA you signed:

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) **is
    maintained indefinitely** and **may be redistributed** consistent with
   **this project** or the open source license(s) involved.
    
 So your contribution removal request is technically rejected in this case.

**Comment by Midou36O** [comment]
Another point: If by chance you actually got your contributions removed from PolyMC, PrismMC is required to also remove your contributions by that rule. (Assuming the CLA did not exist and you owned the copyright).

**Comment by 62832** [comment]
> I own the *copyright* to all of my code,

You mean the code that was submitted under a copy*left* license?

**Comment by JamesQuinley** [comment]
Unfortunately we can’t fulfill your request, we may revisit this in the future.
Have a good day.

**Comment by TheOPtimal** [comment]
> Based on the CLA you signed:
> 
> (d) I understand and agree that this project and the contribution are public and that a record of the contribution (including all personal information I submit with it, including my sign-off) **is maintained indefinitely** and **may be redistributed** consistent with **this project** or the open source license(s) involved.
> 
> So your contribution removal request is technically rejected in this case.

The project was under much different management when I signed that CLA. I know that doesn't hold up legally, but this isn't really a legal request either, it's just formal.

**Comment by TheOPtimal** [comment]
> > I own the _copyright_ to all of my code,
> 
> You mean the code that was submitted under a copy_left_ license?

You misunderstand how licenses work. At any time, I can decide to change what license my code is using, and the project doesn't have authority over that. Unless of course there is a CLA, in which case there is one that I didn't know about.

**Comment by TheOPtimal** [comment]
Either way, this isn't really a legal request, you don't see a lawyer in here anywhere. I'm just politely, informally asking you to remove my code. I just don't want to be associated with the project anymore, is that too much to ask?

**Comment by Kaydax** [comment]
> > > I own the _copyright_ to all of my code,
> > 
> > 
> > You mean the code that was submitted under a copy_left_ license?
> 
> You misunderstand how licenses work. At any time, I can decide to change what license my code is using, and the project doesn't have authority over that. Unless of course there is a CLA, in which case there is one that I didn't know about.
 
You also misunderstand how licenses work. You willingly contributed to a GPLv3 project meaning your code now falls under the license the project follows. If you really care that much about your contributions being part of the project you're more than welcome to submit a PR that removes all of them. We can't just magically remove everything you did, that's not how this works. Your contributions will forever remain documented in the git history

**Comment by BowDown097** [comment]
> Either way, this isn't really a legal request, you don't see a lawyer in here anywhere. I'm just politely, informally asking you to remove my code. I just don't want to be associated with the project anymore, is that too much to ask?

And we have denied this request. That is all. I don't think any further discussion is needed.

**Comment by DigiBeck** [comment]
Lmao not yall being toxic as fuck calling them a script kiddie. For starters, they have the right to change the licensing at any point as the original author of said code. For two you are all lucky your entire accounts havent been struck and barred from github as a whole for the abhorrent and disgusting behavior demonstrated. Good luck. Youre gonna need it.

**Comment by DigiBeck** [comment]
Also, if you *had* checked their contribs you'd realize that they *literally dont use windows* lmao

**Comment by JamesQuinley** [comment]
Hi, this drama has been over for a long time, don't try and bring it back lol.
