### ISSUE TITLE
Ugly interface on Manjaro KDE

### ISSUE THREAD

**Issue by Foresteam** [PolyMC/PolyMC#1496]
### Operating System

Linux

### Version of PolyMC

PolyMC v1.4+

### Version of Qt

1.4.3 - 6.4.0; 1.3.2 - 5.15.6

### Description of bug

On version 1.4+ the interface of the launcher has gone Win-7-something style. It certainly was better before.

And some colors bugged as well.
## 1.3.2
![1 3 2](https://user-images.githubusercontent.com/28836012/200199789-cec07763-4c95-404d-8451-e0e135694100.png)
![1 3 2](https://user-images.githubusercontent.com/28836012/200199790-dd539c0d-ff1d-41be-a660-22ae737340e0.png)
## 1.4.3
![1 4 3](https://user-images.githubusercontent.com/28836012/200199792-6d515462-9ee6-4e91-8255-1f007dd1080e.png)
![1 4 3](https://user-images.githubusercontent.com/28836012/200199794-2a44c26b-a54f-4821-b973-8a2486e8c811.png)
## An example of a normal system-themed app
![2022-11-07_02-01](https://user-images.githubusercontent.com/28836012/200200070-47913ab3-e30b-4c94-882f-929b6242040f.png)

### Steps to reproduce

* Kvantum Manager 1.0.4
* Kernel: 6.0.6-1-MANJARO
* KDE, plasmashell 5.26.2
* Sweet theme both for GTK and KDE, the same in Kvantum ([Sweet, transparent toolbar](https://store.kde.org/p/1294013/))
* Choose system theme in launcher settings

### Suspected cause

The switch to Qt6?

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by LennyMcLennington** [comment]
The "version of Qt" thing is not asking for your installation of Qt. Is asking which version of Qt PolyMC is using. You can find out in Help > About > About Qt.

**Comment by Foresteam** [comment]
My bad. Updated.

I also noticed that if i set the theme in the app to Dark, then back to System, and back to Dark again, i get this:
### System
![System](https://user-images.githubusercontent.com/28836012/200216302-14805104-77c9-4bdc-85e1-aae2cf0c1fd9.png)
### Dark
![Dark](https://user-images.githubusercontent.com/28836012/200216341-05846160-a782-4bc4-ac05-92fded7cd4be.png)

Furthermore, after changing the System theme it is practically replaced with Light, until restart. Then, if it was selected, it goes normal, and remains white otherwise.

**Comment by LennyMcLennington** [comment]
This seems like a problem with your desktop environment or theme's support for Qt6. Try using a Qt5 build instead. They're available in the AUR as polymc-qt5-bin, polymc-qt5, and polymc-qt5-git
