### ISSUE TITLE
Development is going awfully slowly

### ISSUE THREAD

**Issue by fucksophie** [PolyMC/PolyMC#1502]
### Role

I think it's being developed way too slowly, PR's aren't being accepted that much anymore and something is clearly wrong.

### Suggestion

I think hiring more devs or somehow encouraging the community to conribute.

### Benefit

I thtink this would pretty heavily postively impact PolyMC development, and allow it to flourish pre-lefism.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by HeyaGlitz** [comment]
The community doesn't want to contribute

**Comment by jdpatdiscord** [comment]
it's pretty clear the focus will be fixing bugs, keeping up with what modpack platforms are doing and whatnot given the lack of developers and that's just fine. if you want to help find bugs go ahead and they will be addressed.

**Comment by LennyMcLennington** [comment]
Sorry, the contributors are volunteers and all have lives outside of computer. Stuff is being worked on by people who have already offered to contribute, and more people will contribute if they want to contribute. It's not really under our control.

**Comment by RedsonBr140** [comment]
> all have lives outside of computer. 

Are u sure? 💀

**Comment by KaspianDev** [comment]
What's there to add tho?

**Comment by HeyaGlitz** [comment]
> What's there to add tho?

Currently nothing other than bugfixes

**Comment by MESYETI** [comment]
hello everybody
