### ISSUE TITLE
Instance auto-crash in polymc

### ISSUE THREAD

**Issue by sentientbeingg** [PolyMC/PolyMC#1514]
https://mclo.gs/vjelijE link to the log. any help is appreciated and the polymc support room was very unhelpful

**Comment by HeyaGlitz** [comment]
On the Forge forum someone said installing JDK 15 worked for them, try either JDK 15 or JRE 15

**Comment by sentientbeingg** [comment]
> On the Forge forum someone said installing JDK 15 worked for them, try either JDK 15 or JRE 15

I will try that, thank you so much <3
