### ISSUE TITLE
the maintainer sucks

### ISSUE THREAD

**Issue by electron271** [PolyMC/PolyMC#1520]
### Operating System

Windows, macOS, Linux, Other

### Version of PolyMC

all versions

### Version of Qt

i dunno any

### Description of bug

the maintainer sucks

### Steps to reproduce

1. look at commit history
2. just google `polymc controversy`
3. realize that we need an actual good maintainer

### Suspected cause

a bad maintainer

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by ghost** [comment]
it is quite amusing that he just kinda swept it under the rug and was like "oh yeah, it was just a team restructuring, lmao, previous team was making such a big fuss over nothing" when like, everybody else definitely is like "yeah it was kind of, oh, i dunno.. forcibly stripped away from us by someone who had a little bit too much power", then proceeds to make a commit with the update **"reclaim polymc from the leftoids"**. yeah, i sense nothing foul here at all, just gonna ignore that rancid corpse we kicked downstream.

**Comment by HeyaGlitz** [comment]
Lenny was and always will be the owner of PolyMC, he is more than capable of maintaining this project but currently has no incentive to do so.

**Comment by HeyaGlitz** [comment]
> it is quite amusing that he just kinda swept it under the rug and was like "oh yeah, it was just a team restructuring, lmao, previous team was making such a big fuss over nothing" when like, everybody else definitely is like "yeah it was kind of, oh, i dunno.. forcibly stripped away from us by someone who had a little bit too much power", then proceeds to make a commit with the update **"reclaim polymc from the leftoids"**. yeah, i sense nothing foul here at all, just gonna ignore that rancid corpse we kicked downstream.

It was his project, and he has the right to do whatever he wants with it. Inserting politics into a launcher (libleft ideologies or any other for that matter) is against his views, as a FOSS project should not be governed with a CoC rather the community should act upon the platform rules and basic decency. Being "inclusive" to them just means giving the "socially oppressed" more privilege so that they don't accidentally get triggered by someone. A bubble has no place here, and free speech and right of a different opinion is prioritized. As you said, sweeping it under the rug, no not really, he didn't do that rather he didn't fuel the controversies as you ofc wanted him to do just to have more dirt on him.

**Comment by electron271** [comment]
> it is quite amusing that he just kinda swept it under the rug and was like "oh yeah, it was just a team restructuring, lmao, previous team was making such a big fuss over nothing" when like, everybody else definitely is like "yeah it was kind of, oh, i dunno.. forcibly stripped away from us by someone who had a little bit too much power", then proceeds to make a commit with the update **"reclaim polymc from the leftoids"**. yeah, i sense nothing foul here at all, just gonna ignore that rancid corpse we kicked downstream.

yep, agreed

**Comment by HeyaGlitz** [comment]
> yep, agreed

don't get me started on Prism maintainers, they don't have the best history themselves but I'm not allowed to say more

**Comment by electron271** [comment]
i hope that you did not think i agreed to your last post

**Comment by HeyaGlitz** [comment]
I know you didn't

**Comment by BowDown097** [comment]
dilate

**Comment by electron271** [comment]
i think you should close as not completed, we still have the bad maintainer

**Comment by KaspianDev** [comment]
1984

**Comment by KaspianDev** [comment]
> i think you should close as not completed, we still have the bad maintainer

:billed_cap:

**Comment by ghost** [comment]
we will not let your child grooming ring infiltrate our project, and good god why doesn't github let me use 🤡 or 🥱 as a reaction

**Comment by electron271** [comment]
> we will not let your child grooming ring infiltrate our project, and good god why doesn't github let me use clown_face or yawning_face as a reaction

LMFAO i can see why you are being banned from github

**Comment by refrogerator** [comment]
> we will not let your child grooming ring infiltrate our project, and good god why doesn't github let me use clown_face or yawning_face as a reaction

i literally wanna react to the original issue with the nerd emoji but cant, sad!

**Comment by refrogerator** [comment]
> i think you should close as not completed, we still have the bad maintainer

no the maintainer is based dw

**Comment by samiscool51** [comment]
> LMFAO i can see why you are being banned from github

unless you send the source of this claim then it has no-more substance then water.

**Comment by electron271** [comment]
you are all the most brain-dead kindergarten-failing biggest dummies i have ever seen on github, shut up and go learn basic science

**Comment by electron271** [comment]
it is not worth arguing with idiots, now shut up, im not going to be replying any more.

**Comment by electron271** [comment]
and dont complain about my "unacceptable behavior", there is no CoC

**Comment by slendidev** [comment]
> you are all the most brain-dead kindergarten-failing biggest dummies i have ever seen on github, shut up and go learn basic science

Science says there are only 2 genders. The rest are malformations and gender
dysphoria. Insults don't help you here, and stop trying to put politics into
FOSS projects, especially when it doesn't make any sense. You can complain and
stay mad all you want, the maintainer ain't changing, and this is for the
better. Man up.

**Comment by electron271** [comment]
> > you are all the most brain-dead kindergarten-failing biggest dummies i have ever seen on github, shut up and go learn basic science
> 
> Science says there are only 2 genders. The rest are malformations and gender dysphoria. Insults don't help you here, and stop trying to put politics into FOSS projects, especially when it doesn't make any sense. You can complain and stay mad all you want, the maintainer ain't changing, and this is for the better. Man up.

first of all, intersex people
second of all, this has been proven by science
third of all, thank you for saying that gender dysphoria is real
fourth of all, yes i know insults dont help, but with brain-dead idiots like you nothing helps
fifth of all, it was lenny who put politics in foss projects by saying "reclaim polymc from the leftoids"
and finally, man up, lmao im not a man shut up

**Comment by electron271** [comment]
i could argue all day, but its not worth it, honestly the best way to solve this is to just ignore people like you, i will be ignoring any further comments

**Comment by githubsucksfuckingass2** [comment]
> i could argue all day, but its not worth it, honestly the best way to solve this is to just ignore people like you, i will be ignoring any further comments

>walk into a place
>insult the maintainers
>wonder why everyone is arguing with me
>leave, angry, seething and wondering why nobody here likes me
every time

**Comment by githubsucksfuckingass2** [comment]
> > > you are all the most brain-dead kindergarten-failing biggest dummies i have ever seen on github, shut up and go learn basic science
> > 
> > 
> > Science says there are only 2 genders. The rest are malformations and gender dysphoria. Insults don't help you here, and stop trying to put politics into FOSS projects, especially when it doesn't make any sense. You can complain and stay mad all you want, the maintainer ain't changing, and this is for the better. Man up.
> 
> first of all, intersex people
As I said before, malformations at birth cause such issues, those being typically put under the umbrella of "intersex".
 
> second of all, this has been proven by science
Where? Show me. I can tell you this for sure, using 5th grade biology. Males have 1 X chromosome and 1 Y chromosome, compared to females which have 2 X chromosomes. Is this not enough for you? Alright then, let's look at the bone formation. The hip is usually wider in shape compared to the female counterpart. I can state some more differences. What about you?
 
> third of all, thank you for saying that gender dysphoria is real
You're welcome, thank you for acknowledging this mental illness.
 
> fourth of all, yes i know insults dont help, but with brain-dead idiots like you nothing helps 
You did it again...
 
> fifth of all, it was lenny who put politics in foss projects by saying "reclaim polymc from the leftoids"
Nope, he removed the politics from the project. The "leftoids", like you were the ones which tried to add all of this SJW stuff into the project. Lenny simply got tired of all of this politically-correct nonsense entering *his* project, and thus decided to remove the problem directly from the source.
 
> and finally, man up, lmao im not a man shut up
Sorry I've hurt your little "women" soul! I should've said "people up"!

Sent from my iPhone (slendi)
