### ISSUE TITLE
Crashing when launching new instance of FTB Revelations

### ISSUE THREAD

**Issue by Immortalin** [PolyMC/PolyMC#1522]
### Operating System

Windows

### Version of PolyMC

1.4.2

### Version of Qt

QT 6.3.1

### Description of bug

Crashing when downloading new instance of FTB Revelations

### Steps to reproduce

1) Add Instance -> Search for FTB Revelations under FTB tab
2) Crashes after a few seconds of loading mods 

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by slendidev** [comment]
What's the crash log?

**Comment by Immortalin** [comment]
Fixed after updating to 1.4.3. It wasn't updating automatically with scoop.
