### ISSUE TITLE
with poly mc if u try to run an older mc version it says i have to switch back to java 8 but i can play older versions on the normal launcher

### ISSUE THREAD

**Issue by idksalem** [PolyMC/PolyMC#1524]
### Version of PolyMC

newest

### Version of Qt

newest

### Description of bug

with poly mc if u try to run an older mc version it says i have to switch back to java 8 but i can play older versions on the normal launcher

### Steps to reproduce

Press the cat button

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by 0n** [comment]
Change the java version used by the instance like in this screenshot 
![image](https://user-images.githubusercontent.com/45835056/206926209-96e0c73f-3b54-47ec-9fe2-cdfd9aafec93.png)

**Comment by glowiak** [comment]
Sir, PolyMC does not come with bundled Java. This allows you to like have freedom at cost of choice (and mod downloader support)

**Comment by slendidev** [comment]
Go to Edit Instance -> Settings -> Tick "Java Instalation" -> Auto-detect... -> Choose Java 8. If you don't see an option for Java 8, you do not have it installed.
