### ISSUE TITLE
Can't emerge polymc on gentoo

### ISSUE THREAD

**Issue by sarpedondev** [PolyMC/PolyMC#1529]
### Version of PolyMC

PolyMC 1.4.3

### Version of Qt

n/a

### Description of bug

I can't emerge polymc on gentoo. Log:
`Calculating dependencies... done!
[ebuild  N     ] games-action/polymc-1.4.3  USE="-debug" 

Would you like to merge these packages? [Yes/No] 

>>> Verifying ebuild manifests

>>> Emerging (1 of 1) games-action/polymc-1.4.3::polymc
 * polymc-1.4.3.tar.gz BLAKE2B SHA512 size ;-) ...                                                                                                                                                          [ ok ]
 * Using: openjdk-17
>>> Unpacking source...
>>> Unpacking polymc-1.4.3.tar.gz to /var/tmp/portage/games-action/polymc-1.4.3/work
>>> Source unpacked in /var/tmp/portage/games-action/polymc-1.4.3/work
>>> Preparing source in /var/tmp/portage/games-action/polymc-1.4.3/work/PolyMC-1.4.3 ...
 * Source directory (CMAKE_USE_DIR): "/var/tmp/portage/games-action/polymc-1.4.3/work/PolyMC-1.4.3"
 * Build directory  (BUILD_DIR):     "/var/tmp/portage/games-action/polymc-1.4.3/work/PolyMC-1.4.3_build"
 * Hardcoded definition(s) removed in libraries/quazip/CMakeLists.txt:
 *  	set(CMAKE_BUILD_TYPE RELEASE)
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/games-action/polymc-1.4.3/work/PolyMC-1.4.3 ...
 * Source directory (CMAKE_USE_DIR): "/var/tmp/portage/games-action/polymc-1.4.3/work/PolyMC-1.4.3"
 * Build directory  (BUILD_DIR):     "/var/tmp/portage/games-action/polymc-1.4.3/work/PolyMC-1.4.3_build"
cmake -C /var/tmp/portage/games-action/polymc-1.4.3/work/PolyMC-1.4.3_build/gentoo_common_config.cmake -G Ninja -DCMAKE_INSTALL_PREFIX=/usr -DLauncher_PORTABLE=0 -DCMAKE_INSTALL_PREFIX=/usr -DLauncher_APP_BINARY_NAME=polymc -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=/var/tmp/portage/games-action/polymc-1.4.3/work/PolyMC-1.4.3_build/gentoo_toolchain.cmake /var/tmp/portage/games-action/polymc-1.4.3/work/PolyMC-1.4.3
loading initial cache file /var/tmp/portage/games-action/polymc-1.4.3/work/PolyMC-1.4.3_build/gentoo_common_config.cmake
-- The C compiler identification is GNU 11.3.1
-- The CXX compiler identification is GNU 11.3.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/x86_64-pc-linux-gnu-gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/x86_64-pc-linux-gnu-g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:66 (find_package):
  Could not find a package configuration file provided by "ECM" with any of
  the following names:

    ECMConfig.cmake
    ecm-config.cmake

  Add the installation prefix of "ECM" to CMAKE_PREFIX_PATH or set "ECM_DIR"
  to a directory containing one of the above files.  If "ECM" provides a
  separate development package or SDK, be sure it has been installed.

-- Configuring incomplete, errors occurred!
See also "/var/tmp/portage/games-action/polymc-1.4.3/work/PolyMC-1.4.3_build/CMakeFiles/CMakeOutput.log".
 * ERROR: games-action/polymc-1.4.3::polymc failed (configure phase):
 *   cmake failed
 * 
 * Call stack:
 *     ebuild.sh, line  136:  Called src_configure
 *   environment, line 3824:  Called cmake_src_configure
 *   environment, line 1072:  Called die
 * The specific snippet of code:
 *       "${CMAKE_BINARY}" "${cmakeargs[@]}" "${CMAKE_USE_DIR}" || die "cmake failed";
 * 
 * If you need support, post the output of `emerge --info '=games-action/polymc-1.4.3::polymc'`,
 * the complete build log and the output of `emerge -pqv '=games-action/polymc-1.4.3::polymc'`.
!!! When you file a bug report, please include the following information:
GENTOO_VM=openjdk-17  CLASSPATH="" JAVA_HOME="/usr/lib64/openjdk-17"
JAVACFLAGS="-source 1.8 -target 1.8" COMPILER=""
and of course, the output of emerge --info =polymc-1.4.3
 * The complete build log is located at '/var/tmp/portage/games-action/polymc-1.4.3/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/games-action/polymc-1.4.3/temp/environment'.
 * Working directory: '/var/tmp/portage/games-action/polymc-1.4.3/work/PolyMC-1.4.3_build'
 * S: '/var/tmp/portage/games-action/polymc-1.4.3/work/PolyMC-1.4.3'

>>> Failed to emerge games-action/polymc-1.4.3, Log file:

>>>  '/var/tmp/portage/games-action/polymc-1.4.3/temp/build.log'

 * Messages for package games-action/polymc-1.4.3:

 * ERROR: games-action/polymc-1.4.3::polymc failed (configure phase):
 *   cmake failed
 * 
 * Call stack:
 *     ebuild.sh, line  136:  Called src_configure
 *   environment, line 3824:  Called cmake_src_configure
 *   environment, line 1072:  Called die
 * The specific snippet of code:
 *       "${CMAKE_BINARY}" "${cmakeargs[@]}" "${CMAKE_USE_DIR}" || die "cmake failed";
 * 
 * If you need support, post the output of `emerge --info '=games-action/polymc-1.4.3::polymc'`,
 * the complete build log and the output of `emerge -pqv '=games-action/polymc-1.4.3::polymc'`.
 * The complete build log is located at '/var/tmp/portage/games-action/polymc-1.4.3/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/games-action/polymc-1.4.3/temp/environment'.
 * Working directory: '/var/tmp/portage/games-action/polymc-1.4.3/work/PolyMC-1.4.3_build'
 * S: '/var/tmp/portage/games-action/polymc-1.4.3/work/PolyMC-1.4.3'
`

### Steps to reproduce

Follow the instructions on the Website to adding the PolyMC repository and do `emerge --ask polymc`

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by slendidev** [comment]
@binex-dsk Check overlay PRs, and do your job as a maintainer.

**Comment by ghost** [comment]
> @binex-dsk Check overlay PRs, and do your job as a maintainer.

I have a life outside of the internet, be patient.

**Comment by ghost** [comment]
@TomJuri Open this issue on https://git.swurl.xyz/PolyMC/overlay and I'll take a look when I'm free.

I think this is a missing extra-cmake-modules dependency.

**Comment by ikcikoR** [comment]
+1 had the same issue emerging extra-cmake-modules fixed it, should be added as dependency for sure
