### ISSUE TITLE
Can't retrieve API key

### ISSUE THREAD

**Issue by josesilveiraa** [PolyMC/PolyMC#1536]
### Version of PolyMC

PolyMC 1.4.3

### Version of Qt

6.4.0

### Description of bug

Connection times out when I try to get latest cf api keys.

### Steps to reproduce

Just fetch API keys.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by EfficiencyVI** [comment]
Everything related to Curseforge stopped working. You can't download  api keys, modpacks or mods.

**Comment by KaspianDev** [comment]
I believe this should be fixed now.

**Comment by josesilveiraa** [comment]
> I believe this should be fixed now.

why?

**Comment by KaspianDev** [comment]
> > I believe this should be fixed now.
> 
> why?

because it works for me

**Comment by LennyMcLennington** [comment]
This was a temporary issue

**Comment by Nik-mmzd** [comment]
Seems like API is down again:
![image](https://user-images.githubusercontent.com/19509291/226123640-5de81e2e-a0a4-4da5-b0b3-6ff28bc5bf00.png)
