### ISSUE TITLE
Use GHA for meta repositories, keep meta up to date

### ISSUE THREAD

**Issue by d-513** [PolyMC/PolyMC#154]
### Role

Relying less on self-hosted services

### Suggestion

Setup a cronjob using github actions to update the meta repository automatically

### Benefit

Because the current setup doesn't update the repo and we use GHA for builds anyway

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

This would allow us to also make another repo with M1-specific metadata for #153

**Comment by ghost** [comment]
The scripts can have one small change to fix this, I can set that up later.

**Comment by ghost** [comment]
This change has been made to the meta repositories on the meta server. Haven't been pushed yet though. You can see in meta-{upstream,polymc} that it pushes updates automatically now.
