### ISSUE TITLE
Launching PolyMC 5.0 fails on archlinux

### ISSUE THREAD

**Issue by Sightem** [PolyMC/PolyMC#1542]
### Operating System

Linux

### Version of PolyMC

PolyMC 5.0

### Version of Qt

Qt 6.3.0

### Description of bug

polymc: error while loading shared libraries: libQt6Charts.so.6: cannot open shared object file: No such file or directory

### Steps to reproduce

Download PolyMc from the AUR, running it

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Sightem** [comment]
the Appimage doesn't seem to have this problem

**Comment by Sightem** [comment]
Compiling from source also fixes the issue

**Comment by rinnarii** [comment]
Which AUR package are you using exactly?
I have the same problem on polymc-qt5-bin. Looks like the package qt5-charts (or qt6-charts on polymc-qt6) is a missing dependency which I installed and fixed it. The dependency is also present on the base and git aur package which I tested and works.

**Comment by Sightem** [comment]
> Which AUR package are you using exactly?
> I have the same problem on polymc-qt5-bin. Looks like the package qt5-charts (or qt6-charts on polymc-qt6) is a missing dependency which I installed and fixed it. The dependency is also present on the base and git aur package which I tested and works.
> 

oh should have specified that its polymc-bin https://aur.archlinux.org/packages/polymc-bin
also yea when i compiled from source i noticed that package too, looks like a maintainer issue

**Comment by 62832** [comment]
Can confirm that installing `qt6-charts` fixes this on 5.0. Can also confirm that the package maintainer is currently getting this fixed as we speak.

**Comment by LennyMcLennington** [comment]
This should be fixed now, in the future please report packaging issues to the package maintainer via the AUR's comment section or via the contact method listed in the PKGBUILD if there is one.

**Comment by Kaydax** [comment]
Fixed the aur package, should be good now
