### ISSUE TITLE
Add buttons "Check all", "Uncheck all" on Mod selection window when updating mods

### ISSUE THREAD

**Issue by lospejos** [PolyMC/PolyMC#1554]
### Role

I play modded Minecraft

### Suggestion

Allow to check / uncheck all mods on Mod selection window when updating mods versions

### Benefit

Users will be able quickly check / uncheck mods when there are plenty of mods installed

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Please see image below, it may help to get what I mean:

![image](https://user-images.githubusercontent.com/4608475/219407676-0f6b91f8-b984-407e-a02d-9aae3c87deb8.png)

**Comment by AintSoSunny** [comment]
Just use Ctrl+A
