### ISSUE TITLE
Cannot launch multiple instances of minecraft under the same account

### ISSUE THREAD

**Issue by ghost** [PolyMC/PolyMC#1561]
### Operating System

Windows

### Version of PolyMC

PolyMC 5.1

### Version of Qt

6.4.2

### Description of bug

I can launch 1 instance fine, but if I try to launch another the program stops responding for 20 seconds then does nothing.

### Steps to reproduce

Launch an instance twice

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by glowiak** [comment]
Well technically launching multiple instances of MC would allow cheating, so this is not so a bug, rather a feature.

**Comment by slendidev** [comment]
Launching multiple instances under the same account can cause data corruption. For example, let's say you have a single player world, you start it up and everything is normal, now, you start up another Minecraft instance on the same world. What you will find is that the player is out of sync same with the whole world and player data. This is where data corruption happens. Depending on each game's state, they try to write data to the disk that may cause issues.

**Comment by ghost** [comment]
> Well technically launching multiple instances of MC would allow cheating, so this is not so a bug, rather a feature.

We don't care about whatever "anti cheat" or "anti piracy" DRM mojang wants us to have. Running two instances of an account just straight up won't work

**Comment by Sneedplex** [comment]
This is a feature. Running two instances of minecraft under the same account is a recipe for data corruption.
