### ISSUE TITLE
change default java version in CMakeLists.txt files

### ISSUE THREAD

**Issue by zxq5-dev** [PolyMC/PolyMC#1580]
### Role

trying to manually build and install on linux

### Suggestion

change the java version flags from 7 to 8 by default

### Benefit

the project will compile without modification

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

installing PolyMC on Archlinux is currently a bit of a hassle to say the least. with the version on the releases page the default java version is version 7 which simply wont compile as it is outdated.
pretty much my suggestion is to change the flags in 
libraries/javacheck/CMakeLists.txt and
libraries/launcher/CMakeLists.txt from compiling with java 7 to java 8 as that is the minimum version that is recent enough to compile.

(also providing written instructions on how to change these settings for users who are having issues with which java version is supported would be helpful as i had to search through the code for ages until i found what flags to change)

I believe these to be the most appropriate flag since anything earlier refuses to compile and compiling with newer versions of java seems to break support for versions of the game that use earlier versions of java than the one used to compile it (specifically minecraft 1.7 and 1.8 both use java 8 and these are the earliest versions of the game that are still relevant)

![image](https://github.com/PolyMC/PolyMC/assets/80643031/9fe64199-f682-43dc-a41d-4a864a9dde61) in the current release these numbers are 7 but i found that changing them to 8 was the only way that I wouldn't get an error telling me to use a newer java version.

if this isn't intentional, the easiest fix i guess would be to change them to 8 like i did but otherwise, having a note in the wiki pages about how to change what version is used when compiling from source would be really useful (it would have saved me about an hour of hassle and 4 different attempts trying to install it on my system XD)

**Comment by Zipdox2** [comment]
Java 7 has been obsolete for years now, why is it the default?

**Comment by HeyaGlitz** [comment]
That is a valid issue, and I don't know why we still compile to Java 7. It's really not about being "backwards compatible" since newer JVMs can run anything compiled with Java 6 and newer (because JSR and RET instructions got removed in that version, they're non-existent nowadays).
