### ISSUE TITLE
Add support for lwjgl3 version 3.3.2

### ISSUE THREAD

**Issue by lospejos** [PolyMC/PolyMC#1584]
### Role

I play modded Minecraft using PolyMC

### Suggestion

In "Change LWJGL version" dialog windows make able to select a 3.3.2 version

### Benefit

Possibility to use most recent LWJGL version

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

This may be bound with some technical issues (I'm not an expert in Graphics Drivers etc), f.e. some incompatibility brought with a new version, which involve huge amount of refactoring to support the new version.
I hope that minor version changes (3.3.1 -> 3.3.2) doesn't have breaking changes.

**Comment by lospejos** [comment]
After creating this issue I realized that it probably should be created not in this project but rather in [meta-polymc](https://github.com/PolyMC/meta-polymc)...

**Comment by ghost** [comment]
Issues aren't available for that repo. @LennyMcLennington enable issues there so we can track this so I don't forget

**Comment by LennyMcLennington** [comment]
> Issues aren't available for that repo. @LennyMcLennington enable issues there so we can track this so I don't forget

@binex-dsk Issues aren't supposed to be enabled on that repo, it's automated. Meta related issues should be posted on https://github.com/PolyMC/meta-scripts

**Comment by ghost** [comment]
moved to https://github.com/PolyMC/meta-scripts/issues/19
