### ISSUE TITLE
Needed configuration option to enable PolyMC only for whitelisted mods

### ISSUE THREAD

**Issue by vadim-a-yegorov** [PolyMC/PolyMC#1590]
# Description

Needed configuration field to enable PolyMC only for specified list of mods.

# Details

```
"enabledMods": {
    "Lootr"
}
```

**Comment by slendidev** [comment]
What does this mean?

**Comment by vadim-a-yegorov** [comment]
> What does this mean?

That mean that I need to specify list of mods that PolyMC should work with, and ignore all other mods. Purpose – I want Lootr mod to work serverside-only; other mods should not be involved as they are already presented on the client side which leads to compatibility issues.

**Comment by vadim-a-yegorov** [comment]
> What does this mean?

Este posibil să faci o listă specifică de moduri de ignorat, lista neagră sau lista albă? Există o setare în fișierul de configurare pentru asta?

**Comment by vadim-a-yegorov** [comment]
Îmi pare rău, am confundat PolyMC https://github.com/TheEpicBlock/PolyMc
