### ISSUE TITLE
Login to Microsoft requires two goes. It shouldn't.

### ISSUE THREAD

**Issue by roke-julian-lockhart** [PolyMC/PolyMC#1599]
### Role

I have a slow internet connection.

### Suggestion

Don't require login to Microsoft twice; it shouldn't fail and then work. It should just work.

### Benefit

So that I can authenticate quickly.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Loading the login page on a slow broadband connection is incredibly slow. Having to do it twice is seriously annoying, especially when trying to convince others to use this.

**Comment by roke-julian-lockhart** [comment]
> https://github.com/PolyMC/PolyMC/issues/1599#issue-1877937767

I don't have this issue with https://prismlauncher.org/download/steam-deck/.

**Comment by jdpatdiscord** [comment]
Couldn't reproduce

**Comment by ghost** [comment]
Works just fine for me... what system are you on?

**Comment by Sneedplex** [comment]
works fine for me on a slow connection

**Comment by roke-julian-lockhart** [comment]
> https://github.com/PolyMC/PolyMC/issues/1599#issuecomment-1825981217

@Ghost, apologies for the wait. Missed your message. I was probably using the Fedora 40 KDE Spin.

> https://github.com/PolyMC/PolyMC/issues/1599#event-15255348697

@Sneedplex and @jdpatdiscord, I'll re-test it again at some point. Thanks for sharin’ your experiences.

**Comment by Sneedplex** [comment]
Based on the information there is a potential edge case where OAuth communication is interrupted by the process taking far too long, which wouldn't be unheard of but is a Microsoft-end issue and thus effectively unfixable.

**Comment by roke-julian-lockhart** [comment]
> https://github.com/PolyMC/PolyMC/issues/1599#issuecomment-2469345658

@Sneedplex, I just retried, and it didn't reproduce for me either.
