### ISSUE TITLE
Icon broken in some resolutions on KDE

### ISSUE THREAD

**Issue by pizzadude** [PolyMC/PolyMC#16]
### Operating System

Linux

### Description of bug

The icon is broken in some resolutions on KDE.
Here is what the icon looks in the KDE launcher:
![image](https://user-images.githubusercontent.com/1454420/147980699-e98e9161-7c46-4561-9ef7-85df2f7e75c5.png)

### Steps to reproduce

Step 1. Add PolyMC flatpak to KDE launcher favorites
Step 2. Look at how broken it is.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by ghost** [comment]
Known.

We attempted to fix this but still, it's broken:

![image](https://user-images.githubusercontent.com/65276418/147983728-9910c0a3-e340-4cd6-82ba-dc1f1080e44f.png)

Qt is absolutely horrendous at rendering SVGs properly and we're working on fixing this right now
