### ISSUE TITLE
Provide an `.MSIX` installation package.

### ISSUE THREAD

**Issue by roke-julian-lockhart** [PolyMC/PolyMC#1601]
### Role

Some versions of Windows don't support anything except `.MSIX` and `.APPX`.

### Suggestion

Provide an `.MSIX` package.

### Benefit

So that I can install on every version of Windows, and manage my installation easily.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

1.  `.MSIX` supersedes `.APPX`.
1.  Would make (unattended) installation via https://github.com/microsoft/winget-pkgs/issues/118715#issue-1877854394 better.

**Comment by ghost** [comment]
> Some versions of Windows don't support anything except .MSIX and .APPX.

fr? Which versions?

**Comment by roke-julian-lockhart** [comment]
> https://github.com/PolyMC/PolyMC/issues/1601#issuecomment-1825980656

@binex-dsk, https://support.microsoft.com/en-us/windows/windows-10-and-windows-11-in-s-mode-faq-851057d6-1ee9-b9e5-c30b-93baebeebc85#:~:text=if%20you%20switch%20out%20of%20s%20mode%2C%20you%20can%20install%20x86%20windows%20apps%20that%20aren%E2%80%99t%20available%20in%20microsoft%20store%20in%20windows (although technically Windows IoT also counts XD)

**Comment by ghost** [comment]
S mode is probably not an area of concern, I don't know anybody who uses it and I have plenty of Windows-using frens.

I'll leave this open but very unlikely to add

**Comment by roke-julian-lockhart** [comment]
> https://github.com/PolyMC/PolyMC/issues/1601#issuecomment-1876396205

S Mode isn't the primary reason to use MSIX. It's also the most modern installation technology (meaning it has significant management advantages) and is the sole one able to target Windows 7 to 11 with Microsoft's blessing.

**Comment by ghost** [comment]
Doesn't MSI support all those as well?

**Comment by roke-julian-lockhart** [comment]
> https://github.com/PolyMC/PolyMC/issues/1601#issuecomment-1877356034

@binex-dsk, it doesn't provide the capabilities that MSIX does. MSIX is MSI's successor, though (although technically APPX's successor, which was in turn MSI's successor, which succeeded *comprehensive* EXE installers) so they shall have similarities. MSIX provides things like proper integration with WinGet and Settings, uses the new installation GUI (https://upload.wikimedia.org/wikipedia/commons/3/3b/App_Installer_Screenshot.png) and is compatible with first-party PowerShell management tools.

**Comment by HeyaGlitz** [comment]
We can't make a valid msix package because we don't have a code signing certificate. This usually wouldn't be a problem since we do have an [OpenCollective page](https://opencollective.com/polymc), however due to Prism mass reporting our page, the funds are locked indefinitely.

**Comment by roke-julian-lockhart** [comment]
> https://github.com/PolyMC/PolyMC/issues/1601#issuecomment-1900423792

Don't worry – you can just self-sign. As long as the package has *a* certificate, it will install using the native PackageInstaller. The worst that might occur is it might notify the user, but that's standard practice for self-signed certificates on MSIs too.

Regardless, why does that affect your access to the signing (private) key?

**Comment by HeyaGlitz** [comment]
I can't install the self-signed MSIX package because I don't have the cert installed in `Trusted Root Certification Authorities` or `Trusted Packaged App Installation Authorities` stores. It works fine when I install the certificate, otherwise the installation fails with error code 0x800B0109. I'm not too familiar with all of this and if you know of a better way to fix it, a link to a guide or similar would be much appreciated.

**Comment by roke-julian-lockhart** [comment]
> https://github.com/PolyMC/PolyMC/issues/1601#issuecomment-1900498951

@HeyaGlitz, you may well be correct, unfortunately. I do recall needing to install a root certificate now that you mention it.

I think the only good solution to this is to use the correct key. One must be used for GitHub code integration (because surely your provided packages aren't unsigned, right) so this seems a little confusing ultimately. Why can't you use a proper key?

*If* acquiring the correct key is impossible, I'm sure you're aware that installing a preformatted key file is a trivial matter – the user just clicks it and chooses the credential store. However, that's obviously far from ideal UX, so unless there's a sizable technical userbase, it would render the MSIX package rather useless for most.

**Comment by HeyaGlitz** [comment]
We do not sign our packages because we don't have the funds to do so. (Windows and MacOS)

**Comment by roke-julian-lockhart** [comment]
> https://github.com/PolyMC/PolyMC/issues/1601#issuecomment-1900521919

@HeyaGlitz, have you tried enabling Developer Mode in settings? It's a trivial thing to do, and should allow unsigned (not even merely self-signed) MSIX package installation, so it's actually suitable for distribution in my eyes (considering that the toggle itself doesn't modify any preferences, just provides capabilities).

I apologize for not being able to do any testing – I just don't have Windows on any of my machines currently (openSUSE). Do note that issues like https://github.com/PolyMC/PolyMC/issues/1568#issue-1656792589 demonstrate that there is additional need for a signing key, although I understand that need won't cause money to appear.

**Comment by HeyaGlitz** [comment]
Doesn't seem to work even with Developer Mode turned on :/

**Comment by ghost** [comment]
Self signed certs are not an option. I forgot that was a necessity :/

An MSI package might be viable though

**Comment by roke-julian-lockhart** [comment]
> https://github.com/PolyMC/PolyMC/issues/1601#issuecomment-1900619414

@binex-dsk, perhaps, but MSI is still quite old. It's a million times better than mere `.exe` because it at least standardizes installation and subsequent registry registration, but it can't as easily be managed. Any improvement is an improvement though, so do note I filed https://github.com/PolyMC/PolyMC/issues/1600#issue-1877941206 for this eventuality. :<

**Comment by ghost** [comment]
Making an MSI is also easier because of CPack's WIX plugin. Matter of fact, one of the projects I'm doing right now has an MSI package in the works... when I can iron out a few issues I'll do it here too.

**Comment by ghost** [comment]
Closing because this is a no-go. Windows 11 S-mode is useless, we don't want to pay $85 for a certificate, and MSI is more than good enough for unattended installation.

**Comment by roke-julian-lockhart** [comment]
> https://github.com/microsoft/msix-packaging/issues/332#issuecomment-1901078419

@binex-dsk, might be worth following https://github.com/microsoft/msix-packaging/issues/332#issuecomment-650809083, then.

**Comment by ghost** [comment]
> > https://github.com/microsoft/msix-packaging/issues/332#issuecomment-1901078419
> 
> @binex-dsk, might be worth following https://github.com/microsoft/msix-packaging/issues/332#issuecomment-650809083, then.

Good on you for pushing that, will do. This would greatly benefit several of my projects as well.
