### ISSUE TITLE
Add support for NeoForged (ex Forgecord) mod loader

### ISSUE THREAD

**Issue by steelshot** [PolyMC/PolyMC#1603]
### Role

Modded Minecraft

### Suggestion

Support installing NeoForged (ex Forgecord) the same way it is done with forge

### Benefit

More choice for the end user

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Add support for installing NeoForged (ex Forgecord) mod loader.

> NeoForged is a fork of MinecraftForge. Almost all of the original team has joined the new team, with one obvious exception, LexManos (hereby referred to as Lex). [Source](https://neoforged.net/news/theproject/) [Alternative](https://github.com/neoforged/NeoForge)

This should not replace the current forge loader support, but be a separate option or have it under a generic "Install Forge" and have the end user pick a "flavour" type menu. Currently as a workaround the net.minecraftforge.json file can be edited and modified to download neoforge files instead.

I am keeping details to minimum as to not _hopefully_ include PolyMC into any drama/backlashes.

**Comment by Kaydax** [comment]
Currently there is no point to support it until Neoforge breaks off completely from forge causing full incompatibility with mods, on top of the fact there is currently no "Neoforge only" mods. This may change in the future, but for now its way to early to instantly support a hard fork without it being different enough to support

**Comment by KaspianDev** [comment]
Yaay another software created by drama bringing nothing new!

**Comment by glowiak** [comment]
@KaspianDev heh it's becoming a trend now

**Comment by ghost** [comment]
I see no reason to support more drama-induced mod loaders that are identical to the others. this is another Prism and Quilt situation where they just want to force politics down people's throats and intentionally make other loaders incompatible. Linux as a whole is fragmented enough, we don't need to support fragmentation of... Minecraft mods.

Not closing yet but this is likely a hard no unless NeoForged legitimately adds a lot of useful features. Spoiler: it won't, the only real Forge developer didn't move over. The ones who did have no clue how to code stuff.

**Comment by stasalcatraz** [comment]
Some mods, like Immersive Engineering, support NeoForge only on curseforge.com, so it's impossible to find mode updates, disregard it's Forge compatible.

**Comment by bhechinger** [comment]
Just tried to install SecurityCraft for 1.20.4 and ran into the same issue. SecurityCraft only supports "old" forge for 1.12.2.

**Comment by ghost** [comment]
Awesome, useless mod loader with no changes forcing people to use it.

**Comment by ghost** [comment]
Chances are, we're gonna have to end up supporting this john or at the very least implementing a workaround to spoofing the NeoForged identifier for mods that require it.

**Comment by bhechinger** [comment]
It's the entire forge team that's split off. Like it or not I doubt it's ever going to not be a thing.

**Comment by bhechinger** [comment]
It's the entire forge team that's split off. Like it or not I doubt it's ever going to not be a thing.

**Comment by ghost** [comment]
> It's the entire forge team that's split off. Like it or not I doubt it's ever going to not be a thing.

They said the same thing about Quilt and now it's just a worse version of Fabric with a bunch of politics inserted. Either way, we have to support it to ensure universal modpack support.

**Comment by bhechinger** [comment]
> > It's the entire forge team that's split off. Like it or not I doubt it's ever going to not be a thing.
> 
> They said the same thing about Quilt and now it's just a worse version of Fabric with a bunch of politics inserted. Either way, we have to support it to ensure universal modpack support.

Yeah, that was my point. Doesn't matter how we feel about it. We're stuck with it either way.

**Comment by csdivad** [comment]
It is not just drama. This split (or something like this) should've happened like 10 years ago. If it had been like that, then we probably would have less mod loaders now, but it is what it is.
I don't know who do you mean by "only real Forge developer" (I hope not _that_ guy) but the ones that matter did move over (actually the majority of devs).
If fact some of you are being more dramatic here than than the original story 😄 .

_Also, isn't PolyMC a fork of some other MC launcher? Something something "...disagreements between a portion of the community, and MultiMC’s lead maintainer..."_

Edit: In the meantime I found out that this MultiMC fork has quite a dramatic history as well. I think I'll just switch to that other fork that is hopefully less so, plus it already supports NeoForged. Cheers.

**Comment by ghost** [comment]
> It is not just drama. This split (or something like this) should've happened like 10 years ago. If it had been like that, then we probably would have less mod loaders now, but it is what it is.
> I don't know who do you mean by "only real Forge developer" (I hope not _that_ guy) but the ones that matter did move over (actually the majority of devs).
> If fact some of you are being more dramatic here than than the original story 😄 .
> 
> _Also, isn't PolyMC a fork of some other MC launcher? Something something "...disagreements between a portion of the community, and MultiMC’s lead maintainer..."_
> 
> Edit: In the meantime I found out that this MultiMC fork has quite a dramatic history as well. I think I'll just switch to that other fork that is hopefully less so, plus it already supports NeoForged. Cheers.

That's wonderful. I don't care.

**Comment by Sneedplex** [comment]
> It is not just drama. This split (or something like this) should've happened like 10 years ago. If it had been like that, then we probably would have less mod loaders now, but it is what it is. I don't know who do you mean by "only real Forge developer" (I hope not _that_ guy) but the ones that matter did move over (actually the majority of devs). If fact some of you are being more dramatic here than than the original story 😄 .
> 
> _Also, isn't PolyMC a fork of some other MC launcher? Something something "...disagreements between a portion of the community, and MultiMC’s lead maintainer..."_
> 
> Edit: In the meantime I found out that this MultiMC fork has quite a dramatic history as well. I think I'll just switch to that other fork that is hopefully less so, plus it already supports NeoForged. Cheers.

Sneethe about it groomer

**Comment by Geo25rey** [comment]
> Either way, we have to support it to ensure universal modpack support.

@ghosty141 So does this mean NeoForge is a planned feature now? I can't play the "All the Mods 10" modpack using PolyMC without NeoForge.

**Comment by Geo25rey** [comment]
Wait NeoForge support was added 3 months ago? Why is this still opened? 5e56b8cc307211598e0771bd0875036797051ff7

**Comment by AdminPacman** [comment]
@Geo25rey 

I don't see the support option for NeoForge install in PolyMC v6.1. Was trying to play NeoForge pack from FTB. Downloaded from both CurseForge and FTB. Neither instance will load the mods. Installing normal Forge doesn't work. 

![image](https://github.com/user-attachments/assets/5dbac4ef-4e77-4d2a-96cc-415b1220105c)

**Comment by Geo25rey** [comment]
@AdminPacman It is not in the latest release, yet. For now, you need to compile from source. Hopefully, the PolyMC maintainers make a new release soon so it is more accessible to the general public.
