### ISSUE TITLE
Can't input curseforge api key, only remove the official one

### ISSUE THREAD

**Issue by TheK0tYaRa** [PolyMC/PolyMC#1613]
### Operating System

Linux

### Version of PolyMC

PolyMC 5.1

### Version of Qt

Qt 5.15.11

### Description of bug

The field should accept text inputs, but it only allows for deletion of text.

### Steps to reproduce

1. Fetch official api keys.
2. Try deleting text from that field.
3. try writing or pasting text into that field.

### Suspected cause

I think someone mis-configured the field in qt-quick.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by HeyaGlitz** [comment]
That field is checked for a regex pattern every time you input something, so that's why you can't write anything you want. The first 4 characters **must** be `$2a$`, after that you can write anything you want, but unless you have your own valid key, Curseforge features won't work properly with an invalid key.

**Comment by LennyMcLennington** [comment]
The field rejects invalid keys. You can't just type any random thing there.

**Comment by TheK0tYaRa** [comment]
Before you ask - no i did not check out the current git package from aur

**Comment by TheK0tYaRa** [comment]
> The field rejects invalid keys. 

Well it rejected the one from the api page in my profile too so idk. Literally couldn't paste it in.

**Comment by TheK0tYaRa** [comment]
>  The first 4 characters **must** be `$2a$`

Welp, the api key i got starts with nothing like that so... Maybe add a button that opens the page where own api key can be obtained?

**Comment by ghost** [comment]
Where did you fetch it from? https://cf.polymc.org/api returns a key that starts with `$2a$`.

**Comment by TheK0tYaRa** [comment]
https://legacy.curseforge.com/account/api-tokens

**Comment by TheK0tYaRa** [comment]
I suppose it's a misunderstanding on my part about what api key is needed. But i still wish to know where can i obtain an api key linked to my account. If that's possible at least.

**Comment by HeyaGlitz** [comment]
You should apply for a key [here](https://forms.monday.com/forms/dce5ccb7afda9a1c21dab1a1aa1d84eb?r=use1).
[More info](https://support.curseforge.com/en/support/solutions/articles/9000208346-about-the-curseforge-api-and-how-to-apply-for-a-key).

**Comment by ghost** [comment]
FWIW using your own API key has strict limitations, only the official one is really any good. If you don't want to use the official one then stick to Modrinth and FTB.
