### ISSUE TITLE
[RFC] Formatting Conventions

### ISSUE THREAD

**Issue by ghost** [PolyMC/PolyMC#1618]
### Goal

Based on #1509

Now that PolyMC has diverged from Prism and MultiMC, there is no longer a need to keep backwards compatibility with either codebase. PolyMC needs to establish conventions for how we format our code.

### Motivation

The PolyMC code is generally well put together, but many different developers have different standards for how they format stuff. In order to keep parity within code, we need to keep everything formatted identically.

### Specification

Provide a strict set of standards for all things formatting. How we handle references and pointers, newline spacing, and more.

### Drawbacks

It's impossible to force everyone to always go by the same standards. A random document on GitHub won't suffice.

### Unresolved Questions

Should we adopt clang-format as our standard formatter?

How should we ensure every contributor sets up clang-format the same way?

### Alternatives Considered

Simply running clang-format and having everyone follow whatever it does. See #1509.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by slendidev** [comment]
idk just throw the default clang format config in lol

**Comment by ghost** [comment]
No
