### ISSUE TITLE
make PolyMC support Java 21

### ISSUE THREAD

**Issue by evan0greenup** [PolyMC/PolyMC#1619]
### Role

Just want to launch PolyMC in linux system with OpenJDK 21

### Suggestion

modify `java` launch parameter `-source` and `-target`

### Benefit

I just want single JDK to fit all my purpose both Java application development and running Java app like Minecraft

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

MultiMC can be launched in Java 21 environment. As a fork of MultiMC, I believe PolyMC can also capable to do that.

**Comment by ghost** [comment]
Are you not able to use Java 21 with PolyMC?

**Comment by HeyaGlitz** [comment]
`-source` and `-target` are javac arguments, I made a PR that should fix it. https://github.com/PolyMC/PolyMC/pull/1581

Java 21 should work without an issue, any Java version should.
