### ISSUE TITLE
Change default icons to "Flat" style

### ISSUE THREAD

**Issue by QazCetelic** [PolyMC/PolyMC#162]
### Suggestion

I want the default icon to be the "flat" style.

### Benefit

So it looks more modern compared to the outdated looking current icon theme.

**Comment by Scrumplex** [comment]
Flat doesn't work well when your system has a dark theme

![Flat with dark system theme](https://scrumplex.rocks/img/1644764576.png)

I personnally like Simple (Colored Icons)

![Simple (Colored Icons) with dark system theme](https://scrumplex.rocks/img/1644764600.png)

**Comment by ghost** [comment]
colored based, flat gringo

**Comment by QazCetelic** [comment]
> Flat doesn't work well when your system has a dark theme
> 
> ![Flat with dark system theme](https://camo.githubusercontent.com/bb221938cd9374f8928d475cbb9b5ae3c02eed04a0be6ea03070a8d39925a39d/68747470733a2f2f736372756d706c65782e726f636b732f696d672f313634343736343537362e706e67)
> 
> I personnally like Simple (Colored Icons)
> 
> ![Simple (Colored Icons) with dark system theme](https://camo.githubusercontent.com/15a517eb0497e60fd776b84d91a186e7e9613c8ce30f9f8a2179955ddc4c508d/68747470733a2f2f736372756d706c65782e726f636b732f696d672f313634343736343630302e706e67)

_Simple_ is fine too, almost anything is better looking than the current default imo.

**Comment by ghost** [comment]
"modern":

- flat and ugly
- no color
- no buble

colored:

-color
- bubble
-cool
-beautiful
-based

**Comment by d-513** [comment]
Default is colored.
Not ugly, and I think its the best to be as default. "Flat" looks too material design

**Comment by ZekeZDev** [comment]
Should we create another icon theme for polymc? I would be down to spend some time making a new one I might need some help but it might be an idea.

**Comment by txtsd** [comment]
I like the colored default. It suits the app well.
Themes are provided so users can switch to them if they choose to. There's no need to change the default to suit other theme styles imo.

**Comment by Scrumplex** [comment]
I think we can close this issue either way. There was a bug (still present in 1.0.6) where icon loading was borked.

See https://github.com/PolyMC/PolyMC/pull/107

**Comment by ghost** [comment]
> Should we create another icon theme for polymc? I would be down to spend some time making a new one I might need some help but it might be an idea.

make bubble icon theme
