### ISSUE TITLE
Instance Storage Tab uses hard to read font color on dark theme

### ISSUE THREAD

**Issue by treacherousfiend** [PolyMC/PolyMC#1623]
### Operating System

Windows

### Version of PolyMC

PolyMC 5.1

### Version of Qt

QT 6.4.2

### Description of bug

The storage tab on instances uses a very dark gray color for the storage percentages on the "Dark" theme
![image](https://github.com/PolyMC/PolyMC/assets/46549454/e8462ab2-ce28-40c3-b5ac-d8ff545b9db1)

Only seems noticeable on the "Dark" theme

### Steps to reproduce

- Set PolyMC theme to "Dark"
- Open Instance menu and go to the "Storage" tab
- Strain your eyes to read percentages

### Suspected cause

Something I noticed is that on the "Bright" theme, the non-bugged text on this tab seems to use a font color that's around hex 111111
![image](https://github.com/PolyMC/PolyMC/assets/46549454/3f606bae-c7fc-4c96-97d0-674d0f9cf77e)

the bugged text uses hex 404044
![image](https://github.com/PolyMC/PolyMC/assets/46549454/1394d387-a536-446d-bb2d-645dba2a08b9)
and it seems to keep the exact same color no matter what theme you use
![image](https://github.com/PolyMC/PolyMC/assets/46549454/f5d153d7-ba27-4609-897e-b9ed34f2a6d9)

I assume the intent was to use a slightly more subdued color than the rest of the text, but it unfortunately doesn't seem to take into account the theme. I also don't see that color defined anywhere in the code, so I wouldn't be surprised if its unintentional and just default QT behavior.
I'm not super familiar with QT, but i noticed that the m_chart member in [launcher/ui/pages/instance/StoragePage.cpp](https://github.com/PolyMC/PolyMC/blob/develop/launcher/ui/pages/instance/StoragePage.cpp) never sets the theme that the chart should use? Maybe thats the issue?

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by slendidev** [comment]
my bad bro will fix when i can, its qt default behavior
