### ISSUE TITLE
[Question] Does the flatpak package also gets updated?

### ISSUE THREAD

**Issue by lxwulf** [PolyMC/PolyMC#1624]
I want to congratulate at first for the new milestone release of `6.0`! :tada: 

I want to celebrate this too with the installation of the new update but sadly,
the flatpak repo did not get updated yet. Is this already in the making or is the
flatpak package EOL, which would be really sad…

[Flatpak Link](https://flathub.org/apps/org.polymc.PolyMC)

Greets LxWulf

**Comment by slendidev** [comment]
Should update on flatpak in a few hours

**Comment by LennyMcLennington** [comment]
Hi, the update has been pushed to flathub, but it takes time to actually show up on Flathub, so it's out of my control at this point, just need to wait a few hours for the update to get onto flathub.

**Comment by lxwulf** [comment]
Yes, it is there! Just want to say thank you for your help and answers, really appreciate this!

I wish you both merry Christmas and a happy new year!

:snowman_with_snow:  :christmas_tree: :gift:
