### ISSUE TITLE
Importing BetterThanWolves causes hang only on PolyMC 6.0

### ISSUE THREAD

**Issue by stvev1337** [PolyMC/PolyMC#1632]
### Operating System

Windows

### Version of PolyMC

PolyMC 6.0

### Version of Qt

Qt 6.6.1

### Description of bug

Expect to happen: Importing Better than Wolves from .zip at link,
 https://github.com/BTW-Community/cursed-fabric-loader/releases/tag/1.1.0-btw ,
should succeed without crashing.

What happens: on PolyMC 6.0 (and not 5.1), importing this pack causes the PolyMC launcher to Stop Responding and hang.

### Steps to reproduce

Download .zip from above link, and import into PolyMC 6.0. PolyMC will hang. (Discovered today, for two different users. Workaround is to use PolyMC 5.1).

### Suspected cause

Works in 5.1 but not 6.0.

_Sorry if duplicate issue, but I couldn't find anything._

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by stvev1337** [comment]
End of PolyMC-0.log, anything after 1000.000 would be after i try closing the application.


    7.859 D RefreshSchedule: Background account refresh succeeded
   31.187 D [HttpMetaCache] Saving metacache with 20 entries
 1137.410 W Removing cache entry because of old age!
 1137.410 D Task "NetJob(Download of meta file net.minecraft/index.json)" starting for the first time
 1137.457 D Task "Net::Download(0x24d3c453eb0)" starting for the first time
 1137.458 D Downloading  "https://meta.polymc.org/v1/net.minecraft/index.json"
 1138.087 D Download succeeded: "https://meta.polymc.org/v1/net.minecraft/index.json"
 1138.087 D Task "NetJob(Download of meta file net.minecraft/index.json)" succeeded
 1139.252 D Task "InstanceStaging(0x24d3c4f2510)" starting for the first time
 1139.252 D Task "InstanceImportTask(0x24d3c74c4f0)" starting for the first time
 1139.254 D Attempting to create instance from "C:/Users/Stvev/Desktop/Cursed-Fabric-BTW-MultiMC.zip"

**Comment by stvev1337** [comment]
sorry for formatting

**Comment by HeyaGlitz** [comment]
Confirmed, https://github.com/PolyMC/PolyMC/pull/1616 breaks importing BTW 
@LennyMcLennington
