### ISSUE TITLE
polymc aur, make build in parallel

### ISSUE THREAD

**Issue by evan0greenup** [PolyMC/PolyMC#1637]
### Role

Build polymc via `makepkg`

### Suggestion

build polymc in parallel

### Benefit

build take shorter time

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

In https://aur.archlinux.org/packages/polymc

The maintainer is @LennyMcLennington , So I put this issue here. Currently, it build PolyMC in single thread.

It would be nice to utilize all the CPU core to build the package.

The original PKGBUILD `build()` is 
```
build() {
  cmake -B build -S PolyMC-$pkgver \
      -DLauncher_BUILD_PLATFORM='archlinux' \
      -DLauncher_QT_VERSION_MAJOR='6' \
      -DCMAKE_BUILD_TYPE='None' \
      -DCMAKE_INSTALL_PREFIX='/usr' \
      -Wno-dev
  cmake --build build
}
```

It would be nice to change it to

```
build() {
  cmake -B build -S PolyMC-$pkgver \
      -DLauncher_BUILD_PLATFORM='archlinux' \
      -DLauncher_QT_VERSION_MAJOR='6' \
      -DCMAKE_BUILD_TYPE='None' \
      -DCMAKE_INSTALL_PREFIX='/usr' \
      -Wno-dev
  cmake --build build -- -j $(nproc)
}
```

This would make building process a lot faster.

**Comment by ghost** [comment]
This should instead be changed in `/etc/makepkg.conf` by setting MAKEFLAGS to include `-j$(nproc)`.
