### ISSUE TITLE
Cannot add "authlib-injector" account

### ISSUE THREAD

**Issue by FryFritters** [PolyMC/PolyMC#1643]
### Version of PolyMC

PollyMC 8.0

### Version of Qt

Qt 6.6.0

### Description of bug

Attempted to connect my Ely.by acc with the launcher, and gave me "Mojang user authentication ended with a network error." Tried using Blessedskin and gave me "Mojang user authentication failed." 

### Steps to reproduce

- Open PollyMC 8.0
- Select the accounts button at top right
- Select Manage Accounts
- Select "add authlib-injector"
- Enter in account details
- Press OK
- [Insert error here]

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Kaydax** [comment]
This is the repo for PolyMC, not for Po***ll**yMC. I recommend switching to PolyMC and seeing if the same issue happens, if it does then please make a new ticket regarding polymc instead of pollymc.

**Comment by FryFritters** [comment]
Can I bring everything over from PollyMC?

**Comment by FryFritters** [comment]
@Kaydax

**Comment by FryFritters** [comment]
Nothing will overwrite with polly I assume, yes?

**Comment by Kaydax** [comment]
> Can I bring everything over from PollyMC?

Idk, prob just move your instances folder from Polly to PolyMC and it should just work
