### ISSUE TITLE
Problems with the game (1.7.10)

### ISSUE THREAD

**Issue by VadimFlex** [PolyMC/PolyMC#1644]
### Operating System

Windows

### Version of PolyMC

PolyMC 8.0

### Version of Qt

Qt 6.6.0

### Description of bug

The image on the screen is displayed normally only periodically. It's basically a monochrome screen that changes color when you move the cursor.

![изображение](https://github.com/PolyMC/PolyMC/assets/132595752/f0efb730-8192-4a61-b749-323600d5903d)
![изображение](https://github.com/PolyMC/PolyMC/assets/132595752/b2242723-dd49-4a73-8b8e-59825ec26b95)
![изображение](https://github.com/PolyMC/PolyMC/assets/132595752/94cc8e2f-74fd-45a9-9635-bc5fc2c29983)
![2024-02-22_16 34 21](https://github.com/PolyMC/PolyMC/assets/132595752/9b249e3b-3c98-4b2e-9c28-d9c844cd2659)

### Steps to reproduce

I chose version 1.7.10, then I chose the latest version of forge. Launched, created the world.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by VadimFlex** [comment]
[latest.log](https://github.com/PolyMC/PolyMC/files/14374524/latest.log)

**Comment by HeyaGlitz** [comment]
PolyMC doesn't have an 8.0 version, therefore I guess you're using PollyMC for which we do not provide support.
Please refer to https://github.com/fn2006/PollyMC?tab=readme-ov-file#having-a-problem-with-the-launcher
