### ISSUE TITLE
Chocolatey support

### ISSUE THREAD

**Issue by kleinermob** [PolyMC/PolyMC#165]
### Role

i install most software via chocolatey on windows

### Suggestion

add polymc to chocolatey https://chocolatey.org/

### Benefit

people can install polymc via chocolatey

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by ZekeZDev** [comment]
this is out of our control can we remove this from the milestone?

**Comment by txtsd** [comment]
PolyMC is on chocolatey

https://community.chocolatey.org/packages/polymc
