### ISSUE TITLE
Void Linux Packages?

### ISSUE THREAD

**Issue by Uiyx** [PolyMC/PolyMC#166]
### Role

Availability

### Suggestion

I would like to see a void-packages template for polymc, it isn't too different from an AUR pacakges script.

### Benefit

I would like a native Void Linux package instead of the Appimage or flatpak.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by d-513** [comment]
Would def be welcome. I have no experience with Void, but if someone does, feel free to submit it

**Comment by d-513** [comment]
https://github.com/void-linux/void-packages/pull/34979

**Comment by oynqr** [comment]
That's pretty funny, I originally stumbled upon PolyMC through a package request on the void-packages issue tracker.

**Comment by sh9r** [comment]
I'm familiar with packaging, it might take a few days but I can whip a package for void
edit: seems like @oynqr already is in the process of making one, i'll let that one be!

**Comment by Scrumplex** [comment]
removed the milestone, as this is not in our control

**Comment by ZekeZDev** [comment]
should we remove this from milestone since it is out of our control.

**Comment by DioEgizio** [comment]
this issue can definitely be closed, PolyMC has been in void official repos for a while now
