### ISSUE TITLE
Add microsoft account fails

### ISSUE THREAD

**Issue by theoparis** [PolyMC/PolyMC#1662]
### Operating System

Linux

### Version of PolyMC

6.0-develop

### Version of Qt

Qt 6.7.2

### Description of bug

```
Failed to get authorization for Xbox services: Host unreachable
```

### Steps to reproduce

Add microsoft account and wait until it gets to the xbox services step.

### Suspected cause

Not sure what could be causing this :(

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by theoparis** [comment]
Update: Using the Prismlauncher client id seems to fix it 🤔 (https://github.com/PrismLauncher/PrismLauncher/blob/fc445078cd635119bb8a2090c33c728ce62f6a85/CMakeLists.txt#L243)

**Comment by HeyaGlitz** [comment]
Xbox Live is currently having issues with account authentication, it has nothing to do with the launcher.

**Comment by HeyaGlitz** [comment]
You can always check the status here: https://support.xbox.com/en-US/xbox-live-status

**Comment by theoparis** [comment]
Oh. Alright thanks.
