### ISSUE TITLE
1.12.2 Forge mod turns into "Example mod" when added to PolyMC

### ISSUE THREAD

**Issue by Zane2b2t** [PolyMC/PolyMC#1663]
### Operating System

Windows

### Version of PolyMC

PolyMC 6.1.0.0

### Version of Qt

What's that?

### Description of bug

When i add a mod to PolyMC it becomes ExampleMod and doesn't load. this only happens for 1 mod and it works as intended outside of PolyMC.

### Steps to reproduce

can't send the mod to re-produce. github doesn't support it
it can be found here: https://github.com/Zane2b2t/Grassware.win-rewrite
add it to forge 1.12.2 instance and watch as it becomes ExampleMod
![image](https://github.com/PolyMC/PolyMC/assets/88916121/7347d13e-b3b3-4dfa-a7eb-15fa30937429)

### Suspected cause

i don't know

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by HeyaGlitz** [comment]
PolyMC actually loads mod info from META-INF/mods.toml, so you'll have to edit that for your mod. It'd be logical for it to read from mcmod.info, but it does not.

**Comment by HeyaGlitz** [comment]
![image](https://github.com/PolyMC/PolyMC/assets/30732772/7ad921d2-3b0f-4ff0-9b3b-6a687b7b29ce)
Editing that file works as intended.

**Comment by Zane2b2t** [comment]
> PolyMC actually loads mod info from META-INF/mods.toml, so you'll have to edit that for your mod. It'd be logical for it to read from mcmod.info, but it does not.

thank you!
