### ISSUE TITLE
Gentoo mirror 404s and is no longer functional

### ISSUE THREAD

**Issue by equitist** [PolyMC/PolyMC#1666]
### Operating System

Linux

### Version of PolyMC

N/A

### Version of Qt

N/A

### Description of bug

The gentoo mirror/ebuild repo, https://git.swurl.xyz/PolyMC/overlay.git, is no longer functional and returns a 404.

### Steps to reproduce

- Attempt to sync PolyMC repo on gentoo.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by HeyaGlitz** [comment]
It seems that Swurl has deleted his Gitea which also deleted the overlay, contacted him about it already so it's just a matter of time until he resolves it. Sorry about that.

**Comment by Sneedplex** [comment]
Fixed.

**Comment by Sneedplex** [comment]
nvm

**Comment by Sneedplex** [comment]
Fixed for real
