### ISSUE TITLE
Cant connect to LAN server

### ISSUE THREAD

**Issue by Fruktas2137** [PolyMC/PolyMC#1667]
### Operating System

Windows

### Version of PolyMC

PolyMC 6.1

### Version of Qt

?

### Description of bug

Cant connect to LAN server with hamachi. It worked fine in other MC launchers but not this. Tried mc versions: 1.20 , 1.20.1 , 1.18

### Steps to reproduce

Try to connect through hamachi to Lan server

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by hustlerone** [comment]
The launcher has nothing to do with this. Have you tried checking your firewall?

**Comment by Sneedplex** [comment]
This is a known issue relating to how Java interacts with the system firewall. Try a different JRE like Azul.
