### ISSUE TITLE
[RFC] libpolymc Rust backend

### ISSUE THREAD

**Issue by kloenk** [PolyMC/PolyMC#167]
# Summary
[summary]: #summary

A rust-based library as shared object to handle minecraft downloading and starting.

# Motivation
[motivation]: #motivation

A shared library would create the posibility to add frontends in other languages, for platforms where Qt5 does not look native, or has some bugs.

# Detailed design
[design]: #detailed-design

A shared library written in rust to parse meta files, issue download requests and start an minecraft instance.
Currently the draft of this library is named [`libpolymc`](https://github.com/korewaChino/libpolymc).

# Examples and Interactions
[examples-and-interactions]: #examples-and-interactions
The caller of `libpolymc` creates a `MetaManager`, issues a request for a Minecraft version, based on uid and version. Then the `MetaManager` is called to search for this version, and every `DownloadRequest` issues by the `MetaManager` is downloaded by the caller, and than passed back to the `MetaManager`. When the `MetaManager` succeds and has all files to start a Minecraft instance, the MetaManager result can be turned into an Minecraft `Instance`, which then can be started with a Auth and a Java argument.

# Drawbacks
[drawbacks]: #drawbacks

This will reorder code, and move stuff out of the reach from Qt.
Comitters working on the backend would have to learn rust to some degree.
This also would mean a dependency on rustc for building, which makes a total of 3 compilers required to build the project.

# Alternatives
[alternatives]: #alternatives

Stay on the Qt5 backend for `PolyMC`, rename `libpolymc` to a different name, and write frontends like a `SwiftUI` one under different names, without connections to PolyMC.

# Unresolved questions
[unresolved]: #unresolved-questions

How are the performance implication on rust ffi libraries? Will this be much slower than the current Qt backend?

# Future work
[future]: #future-work

- Writing a `SwiftUI` frontend, for better integration into macOS, as Qt5 has some graphic bugs on macOS. 
- Writing a libadwaita/GTK frontend, as some may favour it over the Qt5 look.

CC: @korewaChino

**Comment by DioEgizio** [comment]
Sounds cool

**Comment by LennyMcLennington** [comment]
Another drawback is that it introduces a dependency on Rust, so then we need a Rust compiler, Java compiler, and C++ compiler.

**Comment by kloenk** [comment]
@LennyMcLennington updated the RFC text, to add that drawback

**Comment by DioEgizio** [comment]
> Another drawback is that it introduces a dependency on Rust, so then we need a Rust compiler, Java compiler, and C++ compiler.

At this point I think we should make javacheck not require a jdk, it's useless to keep a Java jdk as a requirement for a thingy that shows the currently installed jres

**Comment by Scrumplex** [comment]
How does this handle Forge / Fabric? Currently LWJGL, Minecraft, Fabric, Forge and LiteLoader are all handled the same way. So if meta parsing is handled by the Rust backend, we need mod loader support there as well.

**Comment by Scrumplex** [comment]
This also needs to be able to handle custom (local) metadata. For example if someone uses the `Add to Minecraft.jar` feature or the `Add Empty` feature.

**Comment by kloenk** [comment]
We plan to implement all that, so it should be able to handle it eventually.

**Comment by Scrumplex** [comment]
> How are the performance implication on rust ffi libraries? Will this be much slower than the current Qt backend?

This question can probably be dismissed. We aren't dealing with large amounts of data here. As far as I understood this should be a fire and forget situation (apart from downloading meta) for the launcher.

**Comment by kloenk** [comment]
> This question can probably be dismissed. We aren't dealing with large amounts of data here. As far as I understood this should be a fire and forget situation (apart from downloading meta) for the launcher.

Yes, can probably neglect, but still important to mention. 

The downloading itself is supposed to be handled by the caller, to easier set the UA, and also for integration into system ca and everything. The MetaManager just tells you what to download.

**Comment by ghost** [comment]
Don't implement meme languages into this please. Use libplaymc instead, Rust-C++ interop is terrible

**Comment by LennyMcLennington** [comment]
> Don't implement meme languages into this please. Use libplaymc instead, Rust-C++ interop is terrible

Since the library is being made anyway I'd wait and see how difficult or easy it is to integrate with PolyMC instead of just dismissing it, although I'd also prefer C++ because then there's one less compiler dependency.

If they can make a decent C++ wrapper to abstract away the annoying interop stuff it could be OK in terms of working with the library from C++.

Plus, this will be replacing a component written in Java if it's successful so it's not like it's worse.

**Comment by kloenk** [comment]
> Don't implement meme languages into this please. Use libplaymc instead, Rust-C++ interop is terrible

I decided for rust, as it has a C ABI (optional). C++ <-> Swift interrupt is also terrible, but most thinks (C++/Swift) have decent C interopt, and as Rust creates a C ABI its usable for everyone.

**Comment by LennyMcLennington** [comment]
> > Don't implement meme languages into this please. Use libplaymc instead, Rust-C++ interop is terrible
> 
> I decided for rust, as it has a C ABI (optional). C++ <-> Swift interrupt is also terrible, but most thinks (C++/Swift) have decent C interopt, and as Rust creates a C ABI its usable for everyone.

`extern "C"` exists on C++ though so it could've been made in C++ with C bindings to use with swift and stuff

**Comment by kloenk** [comment]
I'm not really able to write good C++ code. As I'm doing rust for my day job (including C ffi) I decided for rust. But yes if somebody wants to do it in C++ I might not able to help that much, but could use it as well (given I can bridge it to swift).

**Comment by LennyMcLennington** [comment]
Okay

**Comment by ghost** [comment]
I don't have much say in this but given libplaymc exists and most of our current developers are better at C++ it'd probably be better to do that

Also I'd rather we not force another compiler. Ideally we make this pure C++, if we can somehow port JavaCheck that would be very nice

**Comment by d-513** [comment]
best would be if we could remove java build dependency

**Comment by kloenk** [comment]
I think removing all java could be somewhat hard, without loosing features, as I understand the current org.multimc.laucher package also handles features like setting the dock icon for macOS. So we probably always have to keep some sort of minecraft mod written in java/kotlin to keep features like those.

**Comment by korewaChino** [comment]
> Also I'd rather we not force another compiler. Ideally we make this pure C++, if we can somehow port JavaCheck that would be very nice

I actually stopped work on libplaymc due to difficulties with debugging C++ code.  libpolymc (Rust) also currently has way more features than the C++ implementation, due to issues with JSON parsing and the fact that we are simply better at Rust.

I plan to make libpolymc replace all the Java dependent code if possible to remove Java as a build dependency altogether.

As for libplaymc, if anyone would like to write yet another metadata parser in C++, then go ahead.

**Comment by Scrumplex** [comment]
> best would be if we could remove java build dependency

I don't see this as an issue. The best way to integrate into a Java application is... Java. Same with the `JavaCheck.jar`. Easiest way to get info about the Java runtime is to run... Java code.

**Comment by ghost** [comment]
If we can't remove Java then I'm not on board with forcing users into 3 different compilers just to build it.

and @korewaChino why is it hard to debug? use a graphical GDB client

**Comment by yavko** [comment]
> > Don't implement meme languages into this please. Use libplaymc instead, Rust-C++ interop is terrible
> 
> I decided for rust, as it has a C ABI (optional). C++ <-> Swift interrupt is also terrible, but most thinks (C++/Swift) have decent C interopt, and as Rust creates a C ABI its usable for everyone.

Chad D is best

**Comment by glowiak** [comment]
rust is bloat.
Assembly rocks

**Comment by d-513** [comment]
what's the state of this? I think we mostly don't want 3 compilers

**Comment by korewaChino** [comment]
> what's the state of this? I think we mostly don't want 3 compilers

Still currently in progress. Currently, I am working on authentication and instance configuration. Also refactoring code.

P.S. Help needed as I'm currently the only one working on this.

**Comment by wyatt-herkamp** [comment]
So I was just sent this by a friend

I have implemented Microsoft Authentication and asset downloading in https://github.com/wyatt-herkamp/minecraft.rs

The project is still a bit of a work in process. 

I do plan to stabilize the library in the coming weeks

**Comment by LennyMcLennington** [comment]
I don't see it happening in PolyMC because it would complicate building and maintaining the project just to do the "rewrite in rust" meme, that's if it's even viable at all and gets finished in the first place. I'm closing it until something happens that's actually worthy of reopening the issue. It would probably fit in better in a launcher that's built from the ground up to be used with rust.
