### ISSUE TITLE
Cant start minecraft

### ISSUE THREAD

**Issue by Adrianiasan** [PolyMC/PolyMC#1671]
### Version of PolyMC

6.1

### Version of Qt

idk?

### Description of bug

PolyMC version: 6.1

Launched instance in online mode

authserver.mojang.com resolves to:
    [N/A]

session.minecraft.net resolves to:
    [13.107.246.44]

textures.minecraft.net resolves to:
    [13.107.246.44]

api.mojang.com resolves to:
    [13.107.246.44]

Minecraft folder is:
C:/Users/Adrian/AppData/Roaming/PolyMC/instances/1.21/.minecraft

The java binary "" couldn't be found. Please fix the java path override in the instance's settings or disable it.

### Steps to reproduce

what

### Suspected cause

i dont know what to do and what to fix, me and my friend tryed playing together in a lan world, and he couldnt connect to me by an error (Internal Exception: io.nettuhander codec Decoder Exception: Failed to decode packet 'clientbound/sinecraftourton payload) and i though i need to install the same launcher as him, so i did, and first error was incopatible java version, but after that *The java binary "" couldn't be found. Please fix the java path override in the instance's settings or disable it.* please help me

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Sneedplex** [comment]
Install Java from Azul. https://www.azul.com/downloads/?package=jdk#zulu

Install Java 21 or above, and go to Settings -> Java -> Auto-Detect. Select the JDK21 and try again.
