### ISSUE TITLE
Flatpak: Check for Java binaries under /run/host/

### ISSUE THREAD

**Issue by RalphORama** [PolyMC/PolyMC#1674]
### Role

I use PolyMC with Flatpak on Linux

### Suggestion

Check for Java binaries under /run/host/

### Benefit

Allows usage of Java versions installed on the host machine

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

When playing Minecraft, I prefer to use the Azul Zulu JRE. I recently started using PolyMC on Linux via the Flatpak and found I was unable to auto-detect versions of Java installed on the host machine. I think checking for Java installations under `/run/host/` would be beneficial because it would allow users of the Flatpak to easily auto-detect their own Java versions for whatever their needs may be.

I specifically cite `/run/host/` because it would allow users to run

```bash
sudo flatpak override --filesystem=host-os:ro org.polymc.PolyMC
```

Which then mounts `/usr`, `/bin`, `/sbin`, `/lib{32, 64}`, `/etc/ld.so.cache`, and `/etc/alternatives` under `/run/host` in the Flatpak image with read-only access (see [the Flatpak docs](https://docs.flatpak.org/en/latest/sandbox-permissions.html#filesystem-access)). 

This override currently works, but the Java path must be manually specified as `/run/host/usr/lib/jvm/<jvm name>/bin/java` in PolyMC rather than being able to pick it with the file picker.

Making this experience more streamlined would be very beneficial for Flatpak users.

**Comment by Sneedplex** [comment]
The intended pathway is to use the existing Java JRE extensions provided by Flatpak. Running the PolyMC Flatpak with these extensions places the JDK in /app/jdk, which is already scanned by the auto-detect feature.

Adding the additional hassle of scanning the entirety of /run/host is unlikely to be added.
