### ISSUE TITLE
I just lost hundreds of hour of work because of using the wrong keyboard to log in.

### ISSUE THREAD

**Issue by poxy100** [PolyMC/PolyMC#1676]
### Role

I don't understand the question.

### Suggestion

MOVE TO TRASH

### Benefit

I have lost hundreds of hours of work because of just a button press. 

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

there are Zero safeguards to prevent or recover from accidental deletion. I just tried logging into my computer only to discover its the wrong keyboard and EVERYTHING IS GONE from poly MC. I lost HUNDREDS OF HOURS of progress. this has happened multiple times, and I honestly don't understand what is hard about just moving something to the trash, if I want to actually delete it I'll do it on purpose myself because I already have to empty the trash out to clear space for other files.

**Comment by Sneedplex** [comment]
There's an option to undo the last instance deletion.

Failing that, the instance is moved to your system trashbin, be it the Recycle Bin on Windows, Trash-1000 on Linux, or the Trash Can on macOS. You can go into your trash and restore your instances from there.

**Comment by poxy100** [comment]
at this current moment the option to undo is not available and the trash
folder you mentioned is empty.

unless there is a security technicality with how steam deck views files,
they are otherwise gone.

having an undo for the last possible instance would not help in the case of
multiple instances, which I had several times before given how easy it is
to lose all of it.

is there an option to disable or reconfigure keybindings? because there
should be.

I'm sure you have better things to do & I won't have to accost you about
this if i can just kill the root of the problem by disabling the
keybindings.

there are multiple roots to prevent this that do not appear to exist, it
should not be this easy to permanently delete files, it doesn't even have a
confirmation check, pressing the backspace button just starts
deleting things,

**Comment by Sneedplex** [comment]
By default, if the system can find a suitable trashbin, it will place the deleted instances into that trashbin. If it's configured incorrectly or emptied by accident at some point, then there's not really much you can do past that point. Undoing an instance deletion is only able to be done immediately after deletion in the same launch.

Adding a confirmation dialog isn't too hard, I can probably do that.

**Comment by Sneedplex** [comment]
turns out, there was a confirmation dialog only for deletion. Why we would go all that way just to not do it for trashing as well is beyond me, probably a Peterix moment.
