### ISSUE TITLE
download shaderpacks from curseforge

### ISSUE THREAD

**Issue by DioEgizio** [PolyMC/PolyMC#170]
### Role

I play modded Minecraft with complementary shaders.

### Suggestion

i would like to install shaderpack with less clicks, with a feature similar to #64

### Benefit

Less clicks and more ease of use

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

But there's one thing that I think can create issues: the curseforge api. It's known for having issues and I don't know if you can download shaderpacks with it

**Comment by forkiesassds** [comment]
Unfortunately CurseForge doen't have any dedicated shader category, which causes a ton of problems.

**Comment by timoreo22** [comment]
Yeah i can agree with that problem, only solution is see is a potential filter based on description/name but that  can't be perfect. On the other hand there is a resource pack category.....

**Comment by Scrumplex** [comment]
This seems to be hard to implement. Maybe we can revisit this if Modrinth were to implement support for shaderpacks or if a new database emerges.

**Comment by ryanccn** [comment]
This is more feasible with the new CurseForge Core API with the introduction of the **class** system.

Most shader packs are under the "Customization" section, although I'm not sure if that's made for shaders

**Comment by DioEgizio** [comment]
It still applies because customisation is not only shaders
