### ISSUE TITLE
Segfault when closing Mod downloader while it's fetching data

### ISSUE THREAD

**Issue by Scrumplex** [PolyMC/PolyMC#182]
### Operating System

Linux

### Description of bug

Mod downloader causes a segfault when closing the window while it's fetching stuff.

### Steps to reproduce

- Click `Install mods`
- Click on any mod in the list and close the window very quickly (before it finishes loading)

### Suspected cause

```
#0  0x00007ffff6c91734 in QByteArray::append(QByteArray const&) () from /usr/lib/libQt5Core.so.5
No symbol table info available.
#1  0x000055555580423e in Net::ByteArraySink::write (data=..., this=0x555556930d90) at /media/DATA/Projects/PolyMC/launcher/net/ByteArraySink.h:34
No locals.
#2  Net::Download::downloadReadyRead (this=0x55555692c560) at /media/DATA/Projects/PolyMC/launcher/net/Download.cpp:279
        data = {d = 0x55555690d330}
        __PRETTY_FUNCTION__ = "virtual void Net::Download::downloadReadyRead()"
```

Probably tries to change stuff in the window, but as it was closed it segfaults. Big F

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Scrumplex** [comment]
CC @timoreo22

**Comment by DioEgizio** [comment]
so i'm not the only that had that issue
