### ISSUE TITLE
remove imgur

### ISSUE THREAD

**Issue by ghost** [PolyMC/PolyMC#187]
### Role

Relying less on MultiMC API keys, and proprietary services.

### Suggestion

Use a dead-simple FOSS service. Something as simple as https://file.swurl.xyz.

### Benefit

a

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

A separate instance of [trance](https://git.swurl.xyz/swirl/trance) can be hosted on https://img.polymc.org (or similar), by someone other than me.

This can be implemented in a similar way to paste.ee removal: have a default list and allow users to use their own

**Comment by ghost** [comment]
Note that trance just uses the POST body directly and doesn't yet support multipart or anything.

Should we use multipart?

**Comment by DioEgizio** [comment]
I don't think we should remove Imgur, it's fine at the end

**Comment by Scrumplex** [comment]
Let's revisit this in the future.
