### ISSUE TITLE
Icons toggle visibility when closing/opening settings

### ISSUE THREAD

**Issue by embeddedt** [PolyMC/PolyMC#189]
### Operating System

Linux

### Description of bug

Icons seem to toggle between being visible and completely invisible every time I exit the settings window. Please refer to the following GIF.

![Peek 2022-02-21 08-43](https://user-images.githubusercontent.com/42941056/154966906-a19e440d-8de4-4941-b826-08b4736e04fa.gif)

### Steps to reproduce

1. Open PolyMC.
2. Open and close Settings.
3. Icons disappear.
4. Open and close Settings.
5. Icons reappear.

### Suspected cause

I suspect this might be related to the same general codepath as https://github.com/PolyMC/PolyMC/pull/107.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by DioEgizio** [comment]
can you reproduce on latest development build?

**Comment by embeddedt** [comment]
Yes; I'm using https://github.com/PolyMC/PolyMC/commit/613b351f according to my AUR helper:

```
polymc-git 1.0.6.r284.g613b351f-1
```

**Comment by Scrumplex** [comment]
This should be finally fixed with #230

**Comment by embeddedt** [comment]
I can confirm this is fixed with the latest `polymc-git` AUR package.
