### ISSUE TITLE
add curseforge api warning

### ISSUE THREAD

**Issue by DioEgizio** [PolyMC/PolyMC#190]
### Role

add curseforge api warning

### Suggestion

the cf api is famous for having issue. Alert about it like gdlauncher/atlauncher

### Benefit

curseforge moment

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

<img width="1036" alt="Schermata 2022-02-21 alle 17 11 44" src="https://user-images.githubusercontent.com/83089242/154991752-33d3908b-e328-45d9-a093-927b3e466fd3.png">

**Comment by ghost** [comment]
where should this be present, and is there a general "status" endpoint for CF's api?

**Comment by DioEgizio** [comment]
> where should this be present, and is there a general "status" endpoint for CF's api?

No there isn't. I think just a general alert when installing curseforge modpacks/mods that issues could occur

**Comment by ghost** [comment]
Does this show at all times? Or is it user-reported? Not familiar with GD.

**Comment by DioEgizio** [comment]
> Does this show at all times? Or is it user-reported? Not familiar with GD.

I don't think we should do it exactly like gd, but just alerting users that curseforge can have issues

**Comment by d-513** [comment]
and that they should push for modrinth which is a more developer friendly platform

**Comment by DioEgizio** [comment]
yeah that too

**Comment by Scrumplex** [comment]
bump. I want this now

**Comment by Madis0** [comment]
I do not think the alert should be this generic and this visible, users will learn to ignore repetitive warnings.

Rather just show the warning at the end of the search saying that "some mods might've opted out" or instead of the search if no mods have been found that "the API might be having issues".
