### ISSUE TITLE
CurseForge mod downloader is unable to find several mods

### ISSUE THREAD

**Issue by txtsd** [PolyMC/PolyMC#196]
### Operating System

Linux

### Description of bug

I tried to download several CurseForge mods from the mod downloader, but they refused to show in the search results even though they exist on the website.

For example:
- [Engineer's Decor](https://www.curseforge.com/minecraft/mc-mods/engineers-decor)
- [Immersive Engineering](https://www.curseforge.com/minecraft/mc-mods/immersive-engineering)
- [JEI](https://www.curseforge.com/minecraft/mc-mods/jei)
- [Valhesia Core](https://www.curseforge.com/minecraft/mc-mods/valhelsia-core)
- [Valhesia Structures](https://www.curseforge.com/minecraft/mc-mods/valhelsia-structures)

MC version is 1.18.1 in case that matters.

### Steps to reproduce

Search for the mods listed above in the mod downloader. They will not show in the results.
Even just searching for `Core` does not return `Valhesia Core`.

### Suspected cause

¯\\\_(ツ)\_/¯

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by DioEgizio** [comment]
I can't reproduce. Are you sure you were using forge?

**Comment by DioEgizio** [comment]
![immagine](https://user-images.githubusercontent.com/83089242/155470014-ab74948f-2124-4f14-94ff-49866bf09d83.png)
![immagine](https://user-images.githubusercontent.com/83089242/155470070-61145408-0fab-484b-bba3-7c7d912c3b95.png)
![immagine](https://user-images.githubusercontent.com/83089242/155470107-6dc4e1ab-80c9-43b1-885a-605b063de4e7.png)
![immagine](https://user-images.githubusercontent.com/83089242/155470164-fcb94aae-ac02-43e4-bf3b-4cfd43102ad4.png)
![immagine](https://user-images.githubusercontent.com/83089242/155470201-33d5566a-d6c6-49b8-949f-ca6ee82183e3.png)
(on forge 1.18.1)

**Comment by DioEgizio** [comment]
Note: if you were using fabric that's expected :P

**Comment by txtsd** [comment]
You're right. I had fabric installed but disabled. It needed to be removed before I could get the search results.
