### ISSUE TITLE
should remove reference to multimc discord

### ISSUE THREAD

**Issue by oldherl** [PolyMC/PolyMC#2]
### Description of bug

"If you want to contribute, talk to us on Discord first."
it links to multimc discord

### Steps to reproduce

see readme and issue template

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by LennyMcLennington** [comment]
Thanks for mentioning this, I think we need to discuss what we should replace this with. I've removed it for now until we settle on something suitable to replace it with.

**Comment by oldherl** [comment]
Here are the issue templates: https://github.com/PolyMC/PolyMC/tree/develop/.github/ISSUE_TEMPLATE
Need to remove those MultiMC references as well.

**Comment by ghost** [comment]
We could replace this with a PolyMC Discord server, but I don't actually use Discord myself. I might have to grab an old account and make it with that.

Also, I just fixed the issue templates, thanks for mentioning that.

**Comment by Realswitzer** [comment]
replace it with matrix server and make everyone use matrix to get any response

**Comment by clydebottoms** [comment]
I know you guys might want to use matrix for privacy reasons or in the interest of open source but also consider that most people (especially people unable to fix issues themselves) are on discord. A bridge is a good compromise I'd say if you guys choose not to use Discord.

another alternative: https://revolt.chat

**Comment by ghost** [comment]
I believe @LennyMcLennington still uses Discord so he can probably set that up, I can get the Matrix room all set up and have a bridge hosted on my homeserver. I'll probably have to set up a bridged room for news, updates, announcements, etc. but I'm not 100% sure how to do that without letting random people post in there. I'll figure this out when I've got the time.

**Comment by logan2611** [comment]
> but I'm not 100% sure how to do that without letting random people post in there.

You can set permissions so that send messages requires Moderator or above or some other power level. You could also set the default role to a power level less than 0.

**Comment by ghost** [comment]
> > but I'm not 100% sure how to do that without letting random people post in there.
> 
> 
> 
> You can set permissions so that send messages requires Moderator or above or some other power level. You could also set the default role to a power level less than 0.
> 
> 
> 
> 
> 
> 
> 
> 


Right, but the problem is that we still want to have the Discord bridge puppets be able to post. I might have to modify the bridge's source code, I'll see.
