### ISSUE TITLE
AppImage cannot access system's Java installation

### ISSUE THREAD

**Issue by ghost** [PolyMC/PolyMC#20]
### Operating System

Linux

### Description of bug

Hi, I tried running AppImage package and found out that it cannot auto-detect system's Java installation
![image](https://user-images.githubusercontent.com/90791307/148433401-c6589624-4112-4eee-a947-9e39cb8da877.png)

After manually pointing it to /bin/java it gave me this weird error
![image](https://user-images.githubusercontent.com/90791307/148433646-75ac548f-33bd-44a1-b089-f36d8bb12732.png)

Tested on OpenSUSE Tumbleweed.

### Steps to reproduce

1. Download and launch AppImage package
2. Try to auto-detect
3. Fail
4. Try pointing it to Java manually
5. Still fail

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by ghost** [comment]
okay, I'll probably need to find a way to bundle JDK. Might need a plugin for the Jenkins script

**Comment by d-513** [comment]
yeah, i think it needs bundling. Flatpak works because i've bundled all the MC jdks in it

**Comment by ghost** [comment]
This could also be fixed via #7

**Comment by ghost** [comment]
@sunfiwtn Try it now with the latest version. Don't have this issue on Gentoo.

**Comment by ghost** [comment]
yup, latest version works just fine, thank you

**Comment by Hund** [comment]
I have this issue with Fedora and version 1.0.6 of PolyMC.

**Comment by ghost** [comment]
> I have this issue with Fedora and version 1.0.6 of PolyMC.

The official AppImage bundles java 8 and 17. Do you have a system java installed?

**Comment by Hund** [comment]
> > I have this issue with Fedora and version 1.0.6 of PolyMC.
> 
> The official AppImage bundles java 8 and 17. Do you have a system java installed?

I do.

**Edit:**  This will be a non-issue for me later this week. While Fedora is nice, it's not something for me. I'll be switching back to what I'm usedd to. Hopefully this will not be an issue for me then. :)

**Comment by Hund** [comment]
This is an issue in Gentoo as well. I wish you would provide an archive that you can simply just run directly like MultiMC. Then we don't have to mess with this.

**Comment by ghost** [comment]
> This is an issue in Gentoo as well. I wish you would provide an archive that you can simply just run directly like MultiMC. Then we don't have to mess with this.

I don't have this issue. what USE flags does `app-emulation/fuse` have for you?

**Comment by Hund** [comment]
> > This is an issue in Gentoo as well. I wish you would provide an archive that you can simply just run directly like MultiMC. Then we don't have to mess with this.
> 
> I don't have this issue. what USE flags does `app-emulation/fuse` have for you?

I have these enabled for `app-emulation/fuse`:

* alsa
* backend-gtk3
* png
* xml
* zlib
