### ISSUE TITLE
[RFC] Create a new shorter and democratic Code of Conduct in the spirit of Free Software

### ISSUE THREAD

**Issue by Vaanessaa** [PolyMC/PolyMC#202]
### Goal

Give the majority control over major project decisions along with what to do with abusive community members.

### Motivation

The current Code of Conduct is needlessly verbose, undemocratic, and in my opinion, not in the spirit of free software; therefore, we should make our own license that is easier to read and gives the majority control over decisions.

### Specification

A basic example of a shorter and democratic Code of Conduct (rough draft)
```
# This project uses the PolyMC Code of Conduct
## To keep it simple and to avoid unnecessary complexity, we have made this Code of Conduct as short as possible, while still creating rules to adequately prevent abusive behavior from community members.

### The Pledge
As a contributor to the PolyMC project, you should uphold a high standard of respect for other contributors and users of the project. For example, you should try to avoid flame wars if possible and instead solve things constructively.

### Enforcement
Abusive behavior will be handled on a case by case basis, democratically through votes done by the PolyMC community. Obviously, people who spam or have no intention of contributing to the PolyMC project will be banned without warning.
```
### Drawbacks

There would be a possibility for vote manipulation if voting was done by the entire PolyMC community, voting should probably be done by the main contributors of the project.

### Unresolved Questions

The actual Code of Conduct has to be written and sorted out

### Alternatives Considered

We could just have no Code of Conduct, but this is not ideal.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by Scrumplex** [comment]
I disagree.
The Code of Conduct is just for moderation. If someone acts in bad faith and does so repeatedly, we will take action immediately. By having a democratic vote, where quite frankly most participants won't even know what it's about, the bad actor can continue to break rules while the vote is running.

Free software has nothing to do with a CoC. The spirit of free software is allowing users to do whatever they please with software. I don't see any connection here, as the Code of Conduct only applies in our chat rooms and on GitHub

**Comment by LennyMcLennington** [comment]
It does say

> Obviously, people who spam or have no intention of contributing to the PolyMC project will be banned without warning.

tbf

**Comment by binex-dsk** [comment]
> I disagree.
> The Code of Conduct is just for moderation. If someone acts in bad faith and does so repeatedly, we will take action immediately. By having a democratic vote, where quite frankly most participants won't even know what it's about, the bad actor can continue to break rules while the vote is running.
> 
> Free software has nothing to do with a CoC. The spirit of free software is allowing users to do whatever they please with software. I don't see any connection here, as the Code of Conduct only applies in our chat rooms and on GitHub

"i don't want this because it doesn't give me the power to do what I want when I want"

1984 in the real

**Comment by Scrumplex** [comment]
There is no reason to change the CoC now. There was no case where the decision of a moderator was wrong.
Apart from this, I don't see a reason why we shouldn't just use the Contributor Covenant like so many other FOSS projects.

**Comment by Med1cinal** [comment]
At least 4 people here (and probably many more on the matrix server) agree the CoC should be changed, can this be reconsidered?

**Comment by Summertime** [comment]
Democratic vote pre-action (e.g. voting then administering a ban) should only be done for situations that are more complicated than what simple rules can cover, and only for contributors. Elsewise it'll just lead to endless bikeshedding of every slightly heated discussion in the community

**Comment by Scrumplex** [comment]
Discussion seems to have died down here. Feel free to reopen if I am wrong here.

**Comment by LennyMcLennington** [comment]
im just re-closing this as "not planned" because that's probably more correct type of close to use
