### ISSUE TITLE
Old versions of Forge fail to launch due to dependencies hosted on MMC servers.

### ISSUE THREAD

**Issue by forkiesassds** [PolyMC/PolyMC#208]
### Operating System

Windows

### Description of bug

If you set up an instance of Minecraft on version 1.4.7 for example and install Forge the game refuses to launch due to dependencies that have to be downloaded from MMC servers.

### Steps to reproduce

1. Create new instance for 1.4.7
2. Click "Edit Instance"
3. Click "Install Forge"
4. Select latest version
5. Click "Launch"
6. Wait for files to download or fail downloading
7. Downloading of file fails.

### Suspected cause

This might be due to the PolyMC user agent being banned.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by LennyMcLennington** [comment]
Thanks for reminding me to fix this.

**Comment by Scrumplex** [comment]
https://github.com/PolyMC/PolyMC/blob/84e9ce71b06f7f123eb0a600ccd9fa0700bae647/buildconfig/BuildConfig.h#L100

We can use our existing https://github.com/PolyMC/files repo for this

**Comment by Scrumplex** [comment]
These are all hardcoded libraries: https://github.com/PolyMC/PolyMC/blob/develop/launcher/minecraft/VersionFilterData.cpp

**Comment by LennyMcLennington** [comment]
> These are all hardcoded libraries: https://github.com/PolyMC/PolyMC/blob/develop/launcher/minecraft/VersionFilterData.cpp

I already fixed it in PolyMC/files when I made that previous comment I just needed to push the url change to this repo
