### ISSUE TITLE
PolyMC fails emerging

### ISSUE THREAD

**Issue by Uiyx** [PolyMC/PolyMC#213]
### Operating System

Linux

### Description of bug

`emerge polymc` fails on the configuration phase and spits out the following:

```
CMake Error at CMakeLists.txt:107 (find_package):
  By not providing "FindQt5Concurrent.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "Qt5Concurrent", but CMake did not find one.

  Could not find a package configuration file provided by "Qt5Concurrent"
  with any of the following names:

    Qt5ConcurrentConfig.cmake
    qt5concurrent-config.cmake

  Add the installation prefix of "Qt5Concurrent" to CMAKE_PREFIX_PATH or set
  "Qt5Concurrent_DIR" to a directory containing one of the above files.  If
  "Qt5Concurrent" provides a separate development package or SDK, be sure it
  has been installed.


-- Configuring incomplete, errors occurred!
See also "/var/tmp/portage/games-action/polymc-1.0.6/work/polymc-1.0.6_build/CMakeFiles/CMakeOutput.log".
 * ERROR: games-action/polymc-1.0.6::swirl failed (configure phase):
 *   cmake failed
 *
 * Call stack:
 *     ebuild.sh, line  127:  Called src_configure
 *   environment, line 2986:  Called cmake_src_configure
 *   environment, line 1162:  Called die
 * The specific snippet of code:
 *       "${CMAKE_BINARY}" "${cmakeargs[@]}" "${CMAKE_USE_DIR}" || die "cmake failed";
 *
 * If you need support, post the output of `emerge --info '=games-action/polymc-1.0.6::swirl'`,
 * the complete build log and the output of `emerge -pqv '=games-action/polymc-1.0.6::swirl'`.
 * The complete build log is located at '/var/tmp/portage/games-action/polymc-1.0.6/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/games-action/polymc-1.0.6/temp/environment'.
 * Working directory: '/var/tmp/portage/games-action/polymc-1.0.6/work/polymc-1.0.6_build'
 * S: '/var/tmp/portage/games-action/polymc-1.0.6/work/polymc-1.0.6'
```

### Steps to reproduce

`emerge polymc`

### Suspected cause

Missing "Qt5Concurrent" or unset variables.

This could very well be user error but even it is I think something mentioning it should be added to the README or other documentation.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by flowln** [comment]
hmm I didn't have this problem, though I'm using the polymc-9999 one... Can you try to emerge this one to see if it works?

**Comment by Uiyx** [comment]
The same thing happens, no difference.

Could a missing dependency be the cause of this?

**Comment by flowln** [comment]
It is very possible, try emerging `dev-qt/qtconcurrent`. This ebuild probably needs to be updated to account for this dependency...

**Comment by Uiyx** [comment]
`dev-qt/qtconcurrent` wasn't the only missing dependency. I also needed to emerge `dev-qt/qttest`.
After emerging both of these polymc now emerges fine.

**Comment by Uiyx** [comment]
I shouldn't have sent that while it was still emerging, now I get this error message:

 ```
* polymc.svg is not a valid file/directory!
 * ERROR: games-action/polymc-9999::swirl failed (install phase):
 *   (no error message)
 *
 * Call stack:
 *     ebuild.sh, line  127:  Called src_install
 *   environment, line 2997:  Called doicon 'polymc.svg'
 *   environment, line 1276:  Called _iconins 'doicon' 'polymc.svg'
 *   environment, line  694:  Called die
 * The specific snippet of code:
 *       fi ) || die
 *
 * If you need support, post the output of `emerge --info '=games-action/polymc-9999::swirl'`,
 * the complete build log and the output of `emerge -pqv '=games-action/polymc-9999::swirl'`.
 * The complete build log is located at '/var/tmp/portage/games-action/polymc-9999/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/games-action/polymc-9999/temp/environment'.
 * Working directory: '/var/tmp/portage/games-action/polymc-9999/work/polymc-9999/program_info'
 * S: '/var/tmp/portage/games-action/polymc-9999/work/polymc-9999'
```

**Comment by flowln** [comment]
Oh yeah, I had the same problem... The way I fixed it was to update the ebuild by changing the `doicon polymc.svg` line to `doicon org.polymc.PolyMC.svg` and updating the Manifest. I uploaded my ebuilds in a personal repo trying to fix all these problems you had, so if anyone from the main team wants to update the official ebuilds, feel free to use mine as a base: https://gitlab.com/flowln/flowln-overlay (It's my first time making ebuilds so please don't expect much :P)

**Comment by Hund** [comment]
> Oh yeah, I had the same problem... The way I fixed it was to update the ebuild by changing the `doicon polymc.svg` line to `doicon org.polymc.PolyMC.svg` and updating the Manifest. I uploaded my ebuilds in a personal repo trying to fix all these problems you had, so if anyone from the main team wants to update the official ebuilds, feel free to use mine as a base: https://gitlab.com/flowln/flowln-overlay (It's my first time making ebuilds so please don't expect much :P)

Thank you! I'm finally able to use PolyMC. :)

**Comment by d-513** [comment]
we should probably move the ebuilds to another overlay anyway, as the current one is owned by an a previous maintainer

**Comment by flowln** [comment]
The wiki was updated, and the ebuilds were updated to address the problems brought up here. If there's any more problems with the ebuilds, please tell me! :)

**Comment by ZekeZDev** [comment]
Close this issue?

**Comment by Hund** [comment]
You should really consider submitting the ebuilds to the official repositories. I know they'll be more than glad for it! :)

**Comment by flowln** [comment]
I think this would be nice, but I'll give it some time for potential problems, related either to the ebuilds themselves or with changes to the launcher itself (e.g. [changing from GPL-3+ to just GPL-3](https://github.com/PolyMC/PolyMC/pull/278) on the ebuilds), to show up, since it's easier to make changes to them on our overlay. 

Definitively a cool idea though ^-^

**Comment by Scrumplex** [comment]
Can I mark this issue as resolved?

**Comment by flowln** [comment]
Yes! :)
