### ISSUE TITLE
Seperate the core parts into a library

### ISSUE THREAD

**Issue by sharpenedblade** [PolyMC/PolyMC#219]
### Goal

Separate the GUI from the things needed to actually manage instances. The code for the core functionality should be seperated into a library, with the GUI calling the library. The library should have everything in it needed to make a new GUI with ever polymc feature in it.

### Motivation

I think the main part of the code can be seperated into a library without to much effort. This can make it possible to make alternate GUIs, like writing one in GTK/LibAdwaita. This also means that bindings to other languages can be made, so app devs are not limited to c++.

### Specification

I am not use exactly what has to be done, but I think it is possible. First the "core" code should stop having qt as a dependency. Then the gui should be removed from the core code. Finally the core code shou;d be moved into a library.

### Drawbacks

It could take a lot of effort/time. QT types might be used in the core code.

### Unresolved Questions

Is it possible?

### Alternatives Considered

Porting it directly. This is a huge amount of effort, which is not practical.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.
#167 is not braod enough, also there is no need to rewrite in rust, it is completely a fad from people who haven't rewriten anything themselves.

**Comment by txtsd** [comment]
Even if we separate the logic from the GUI, the core will still depend on Qt. The event loop and everything is Qt, not raw C++.

That said, it's a good way to be able to build alternate GUIs, even TUIs!

**Comment by sharpenedblade** [comment]
Even if the logic is seperated but still depends on qt, then it will become easier to move the logic into functions that are toolkit agnostic. I am thinking of something similar to `libvirt`'s approach for this, since this is very similar.

**Comment by korewaChino** [comment]
Isn't this exactly the point of libpolymc? Moving all the logic into a library that will do all the work to manage Minecraft instances.

**Comment by sharpenedblade** [comment]
Whats libpolymc, I havnet heard of it anywhere

**Comment by obj-obj** [comment]
> Whats libpolymc, I havnet heard of it anywhere

https://github.com/PolyMC/PolyMC/issues/167

**Comment by LennyMcLennington** [comment]
Not really useful for PolyMC itself, I don't think anyone working on PolyMC plans to implement this, but if someone manages to accomplish this and makes a PR then we can *consider* accepting it if it's very high quality and doesn't have any significant downsides.
