### ISSUE TITLE
Have "Support PolyMC" button not link to MultiMC Patreon

### ISSUE THREAD

**Issue by stephen-smith** [PolyMC/PolyMC#22]
### Role

Player

### Suggestion

Not direct users to fund MultiMC

### Benefit

Hopefully encourage user funding on PolyMC

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by ghost** [comment]
We currently don't need any funding and I don't believe we will ever. If we do, it'll likely just be personal funding to me since I host all the servers and stuff. I think it best to completely remove all traces of the Patreon stuff.

**Comment by stephen-smith** [comment]
WFM, though I'd be glad to pitch in some USD on a monthly basis.  I did so for the MultiMC team for years (and stopped because of their resistance to AUR / Flatpak distribution).

Doesn't have to be Patreon, either.  I also support Free Software through LIberaPay already and might be convinced to support PolyMC elsewhere.

**Comment by ghost** [comment]
I don't know how I'll get money to me without a credit card, unless they support XMR or BTC. But that could work and I can set that up later

**Comment by stephen-smith** [comment]
Just not directing to MultiMC (remove the button, even) would work.

But if you want some funding, let us know your address(es) so we can fund you that way. :)

I hodl ADA, but I have a Coinbase account so I should be able to send BTC, though right now the network fee would swamp any monthly contribution I might want to make.

**Comment by ghost** [comment]
BTC and XMR are available on my [website](https://swurl.xyz#Donate)
