### ISSUE TITLE
Weird errors on Windows 

### ISSUE THREAD

**Issue by DioEgizio** [PolyMC/PolyMC#222]
### Operating System

Windows

### Description of bug

completely random (some people can reproduce, other don't) TLS errors, maybe for OpenSSL
With the   ` 8.219 W QSslSocket::connectToHostEncrypted: TLS initialization failed` error in logs

Also I get random "MSVCR100.dll is missing" on the windows VM even if Microsoft C++ redistributable 2010 was installed I could reproduce this error 

### Steps to reproduce

- use polymc on windows I guess 

### Suspected cause

Building on windows is pain

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by DioEgizio** [comment]
I investigated and the resolution seems like it's installing https://download.microsoft.com/download/C/6/D/C6D0FD4E-9E53-4897-9B91-836EBA2AACD3/vcredist_x86.exe

**Comment by DioEgizio** [comment]
Opz, misclick

**Comment by txtsd** [comment]
> I investigated and the resolution seems like it's installing https://download.microsoft.com/download/C/6/D/C6D0FD4E-9E53-4897-9B91-836EBA2AACD3/vcredist_x86.exe

Very descriptive lol. What VC version is that?

**Comment by DioEgizio** [comment]
2010 x86

**Comment by txtsd** [comment]
Thanks!

**Comment by txtsd** [comment]
This is addressed in the Chocolatey package. It installs VC 2010 as a dependency.

**Comment by DioEgizio** [comment]
Great

**Comment by DioEgizio** [comment]
I would still keep this issue up for people having issues and don't understanding what they need to do

**Comment by txtsd** [comment]
Yea, it's not ready to be closed yet. Until we figure out how to rid ourselves of this dependency, we need to tell users to install VC 2010 (x86) explicitly.

We also need to find out what scenarios this happens in, because PolyMC runs fine on my bare Win10 VM.

**Comment by txtsd** [comment]
Here's the relevant log from GHA:
https://github.com/PolyMC/PolyMC/runs/5522472395?check_suite_focus=true#step:17:38

Looks like we'll need to add [`InstallRequiredSystemLibraries`](https://cmake.org/cmake/help/latest/module/InstallRequiredSystemLibraries.html) in `CMakeLists.txt`
