### ISSUE TITLE
Hide PolyMC when lauching

### ISSUE THREAD

**Issue by LiamDawe** [PolyMC/PolyMC#226]
### Role

Steam Deck

### Suggestion

Hide the UI

### Benefit

It would work properly

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

On the Steam Deck when in main gaming mode, only one window is supported at a time. It gets confused between which one to pick and flashes between the launcher and the game and could easily cause someone to have an fit. Oh, it's also unplayable due to that of course.

Please add an option for it.

For now, it seems forcing full-screen and manually setting the Deck resolution can get around it but a quick tickbox to just hide the UI when the game launches would be smoother.

**Comment by DioEgizio** [comment]
wdym? closing polymc after mc opens? that's already implemented on devbuilds since a long time

**Comment by LiamDawe** [comment]
Yes that exactly. Is that feature in the Flatpak version on Flathub that I've missed?

**Comment by DioEgizio** [comment]
<img width="923" alt="Schermata 2022-03-05 alle 16 21 58" src="https://user-images.githubusercontent.com/83089242/156889598-1e6e79ee-5bb6-4ce8-a8b2-c08d8955cd39.png">
it's available on devbuilds, 1.1.0 stable coming soon
if you want to run devbuilds on flatpak, use flathub beta

**Comment by Scrumplex** [comment]
@LiamDawe get the Flathub Beta! It has that feature already and it works perfectly well on my Steam Deck

**Comment by LiamDawe** [comment]
Perfect, that'll do thanks everyone :)

**Comment by Scrumplex** [comment]
See #70, fixed in #79
