### ISSUE TITLE
Minecraft <= 1.12.2 not launching (LWJGL errors)

### ISSUE THREAD

**Issue by AnErrupTion** [PolyMC/PolyMC#227]
### Operating System

Linux

### Description of bug

Any Minecraft version <= 1.12.2 doesn't launch, and the cause seems to be some LWJGL 2 libraries missing.

With Java 17 and Java 11, the missing file is:
```
Caused by: java.lang.UnsatisfiedLinkError: Can't load library: /usr/lib/jvm/java-17-openjdk-17.0.2.0.8-2.rolling.fc35.x86_64/lib/libawt_xawt.so
```

I'm suspecting the Java 17 error is due to something else, but I'm including it here just in case.

With Java 8, the missing files are:
```
Caused by: java.lang.UnsatisfiedLinkError: /home/anerruption/.local/share/polymc/instances/1.8.9/natives/liblwjgl64.so: libjawt.so: cannot open shared object file: No such file or directory
```

Everything works with the official Minecraft launcher. I'm using Fedora 35.

### Steps to reproduce

Create a new Minecraft <= 1.12.2 instance, then select either Java 11-17 or Java 8 to get the indicated errors.

### Suspected cause

I think it's because of missing LWJGL 2 libraries.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by DioEgizio** [comment]
which openjdk build are you using?

**Comment by AnErrupTion** [comment]
For Java 8 it's ``1.8.0.322.b06-2``, and for Java 17 it's ``17.0.2.0.8-2.rolling``.

**Comment by DioEgizio** [comment]
weird, can you send the full log?

**Comment by AnErrupTion** [comment]
Java 8 ``https://paste.ee/p/YN7NX``
Java 17 ``https://paste.ee/p/4tLmf``

**Comment by DioEgizio** [comment]
It's a bit weird, looks like some missing openjdk parts. Can you try using Azul/adoptium java 8 and see if it happens?

**Comment by AnErrupTion** [comment]
Well, now the error is different (https://paste.ee/p/LHYdQ)

**Comment by DioEgizio** [comment]
Have you xrandr installed?

**Comment by AnErrupTion** [comment]
Oh, I don't. Is that a problem? (It wasn't a dependency when I installed it from the COPR repo)

**Comment by DioEgizio** [comment]
From what I remember old Minecraft versions don't work without it because lwjgl2

**Comment by AnErrupTion** [comment]
Well, now it works, thanks!

**Comment by DioEgizio** [comment]
np

**Comment by d-513** [comment]
Should be added as a dependency in the next release
