### ISSUE TITLE
Restore pre-0.6.14 log file location.

### ISSUE THREAD

**Issue by starcraft66** [PolyMC/PolyMC#23]
Since upstream included [this](https://github.com/MultiMC/Launcher/issues/4328) critical regression in 0.6.14 and refused to fix it, I think that issue would be a good candidate to fix in this fork. Logging used to log to the right folders but that broke somewhere between 0.6.13 and 0.6.14 as indicated in the upstream issue.

**Comment by LennyMcLennington** [comment]
This should work on read only filesystems with cmake -DLauncher_LAYOUT=lin-system. Is that different to what you're asking for, or does it not work when with that defined?

**Comment by starcraft66** [comment]
The issue is that when you run the launcher, it tried to write its logs into the directory where the executable is located. In a lot of cases, the user might not have permission to write into that folder or whatever (or polymc could be located on a read-only filesystem). The correct approach is to dump the logs into a folder where the user running the app has write permission to (such as `$XDG_CACHE_HOME`). This used to be the case until 0.6.14 changed something that made the app write its logs into the location of the executable.

**Comment by LennyMcLennington** [comment]
Configuring cmake with `-DLauncher_LAYOUT=lin-system` is what you should use if you're installing it to a read only file system. It will build as a portable app, thus requiring it to be on a writable filesystem, otherwise.

**Comment by starcraft66** [comment]
Okay, I will try that.

**Comment by starcraft66** [comment]
Thanks that seems to work.
