### ISSUE TITLE
Can not launch minecraft 1.12.2 or lower

### ISSUE THREAD

**Issue by blt-r** [PolyMC/PolyMC#233]
### Description of bug

When I'm trying to launch minecraft on version 1.12.2 or lower it crushes with this error:
```
...
[03:40:36] [Client thread/INFO]: Setting user: blt_r
[03:40:36] [Client thread/INFO]: (Session ID is token:<ACCESS TOKEN>:<PROFILE ID>)
[03:40:36] [Client thread/INFO]: LWJGL Version: 2.9.4
Inconsistency detected by ld.so: dl-lookup.c: 106: check_match: Assertion `version->filename == NULL || ! _dl_name_match_p (version->filename, map)' failed!
Process exited with code 127.
```

### Steps to reproduce

Try to launch instance with version 1.12.2 or less. I'm using arch btw, and I installed PolyMC from `polymc-bin` aur package. 

### Suspected cause

At first I thought it has something to do with #227, but the error message is different and I have `xrandr` installed.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Scrumplex** [comment]
You need to use an older Java version here. Try Java 8

**Comment by Scrumplex** [comment]
You can override the Java environment on a per-instance level if you switch between newer and older Minecraft versions often

**Comment by blt-r** [comment]
Thank you, that was the problem
