### ISSUE TITLE
Restore PrefersNonDefaultGPU for Linux Desktop file

### ISSUE THREAD

**Issue by Eonfge** [PolyMC/PolyMC#238]
### Description of bug

See history:
https://github.com/PolyMC/PolyMC/commits/develop/program_info/org.polymc.PolyMC.desktop.in

In January the property `PrefersNonDefaultGPU=true` was added to the file but in February it was removed again. This is odd since no reason is given and PrefersNonDefaultGPU is part of the official specs.

### Comment when I added the parameter
> With the Property 'PrefersNonDefaultGPU', you can signal to dekstop environments like GNOME that you want to run the application using the more powerful secondary graphics card, if such a card is available. Specification: https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s06.html
>
> With this change, you won't have to include a special prime-run script.

### Steps to reproduce

Let's revert that single commit

### Suspected cause

Likely just some administrative confusion

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Eonfge** [comment]
@txtsd Can you help us? What was your reasoning for removing the FeeDesktop Specification entry from the .desktop file?

**Comment by Scrumplex** [comment]
IIRC there were issues with desktop users with an iGPU and dGPU. The spec doesn't really define a behavior for this scenario.

**Comment by txtsd** [comment]
That, and the AppImage tool fails when validating the desktop file because it ships with an ancient desktop-file-validate.

**Comment by Jan200101** [comment]
https://github.com/PolyMC/PolyMC/issues/136

**Comment by txtsd** [comment]
This doesn't look likely. I'm closing it as wontfix.
