### ISSUE TITLE
Include proper license file

### ISSUE THREAD

**Issue by tydog98** [PolyMC/PolyMC#24]
### Role

Minecraft player

### Suggestion

Include a license file

### Benefit

To make it's terms of use and distrobution clear

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

The project should include a proper license file that includes all the terms of the GPL. Most other FOSS projects have this included.

**Comment by Okxa** [comment]
The project has COPYING.md which is what [GNU project recommends as a name](https://www.gnu.org/licenses/gpl-howto.en.html). However it does not have the full licence in it, which is recommended, instead includes the short header and other licence notices. Also the GPL licence should be in plaintext.

As for the other licence notices, they can be included somewhere if necessary, but the full GNU general public licence for this project should probably be included.

**Comment by tydog98** [comment]
I have personally never seen a COPYING file, which caused some confusion trying to find out how this project is actually licensed. LICENSE is much more widespread and understood.
