### ISSUE TITLE
Language change does not apply to settings dialog immediately

### ISSUE THREAD

**Issue by flowln** [PolyMC/PolyMC#245]
### Operating System

Linux

### Description of bug

I would expect that, when you change the language on the Settings dialog, the text inside the other tabs in the same dialog would also change, as happens in the rest of the application. That does not occur.

### Steps to reproduce

1. Go to Settings -> Language and change to a different language
2. Switch to a different tab in the settings dialog
3. The text is still in the old language

### Suspected cause

Seems like all the tabs are created when you open the dialog, but do not get updated when the language is changed. We could rebuild those pages when a new language is selected, or at the very least set a `should_update` flag on them or something, that is checked when we enter that page, and if set, rebuilds it with the new language.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by DioEgizio** [comment]
Upstream issue

**Comment by Scrumplex** [comment]
Not really high prio. Let's move this to a different milestone
