### ISSUE TITLE
Add development builds to copr repo

### ISSUE THREAD

**Issue by yavko** [PolyMC/PolyMC#246]
### Role

I want to use the development builds but there isnt a package in the copr repo

### Suggestion

Add development builds to copr

### Benefit

I can use development builds

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

This is actually for a friend but i also have a fedora machine and would like to use the development builds there as well.

**Comment by DioEgizio** [comment]
You can use flathub beta

**Comment by DioEgizio** [comment]
Also I don't think copr supports per-commit builds

**Comment by Jan200101** [comment]
nightly copr builds will be added once 1.1.0 releases

**Comment by Jan200101** [comment]
it took a bit longer, but the copr now has nightly builds that are made every 24 hours
