### ISSUE TITLE
gui changes

### ISSUE THREAD

**Issue by SomaSatoBLM** [PolyMC/PolyMC#252]
### Role

i play minecraft 

### Suggestion

changes to make polymc look like its own package

### Benefit

helps distinguish it from multimc

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

I think it would be to polymc benifit if it was to try to make its gui not look like a rip off of mulitmc.

**Comment by HalJordan** [comment]
NGL - I don't disagree, but right now(IMO) the priority should be features that distinguish(i.e. mod downloads and a wide range of platforms) instead of just a new skin.

Just be careful how you stir the pot with this.

**Comment by LennyMcLennington** [comment]
Changing it for the sake of changing it isn't useful. If you have a specific suggestion of how you want to see the GUI changed feel free to suggest it.
