### ISSUE TITLE
Toggleable options for MangoHud, PRIME and/or GameMode

### ISSUE THREAD

**Issue by SomaSatoBLM** [PolyMC/PolyMC#253]
### Role

i play minecraft

### Suggestion

prime/mangohud toggle

### Benefit

easier to get running for new users

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

it would be cool if polymc could detect an optimus enviroment and have a toggle to enable runing with prime/ if in windows running with nvidia/amd gpu over intel intergrated
also a toggle for enable mangohud would be cool as well

**Comment by d-513** [comment]
I mean, for prime at least, PrefersNonDefaultGPU did that, we should probably discuss that option further as I haven't seen the bug reproduced

**Comment by txtsd** [comment]
@Jan200101 can pitch in about his experience

**Comment by SomaSatoBLM** [comment]
> I mean, for prime at least, PrefersNonDefaultGPU did that, we should probably discuss that option further as I haven't seen the bug reproduced

i cant find an option for this and it does not use nvidia gpu without nvidia-prime wrap command 

issue #238 PrefersNonDefaultGPU=true was removed in commit 92a5b12

**Comment by Jan200101** [comment]
> I mean, for prime at least, PrefersNonDefaultGPU did that

yes and no

`PrefersNonDefaultGPU` is a flawed option that was never properly specified.

To sum it up (and not go on another rant):
`PrefersNonDefaultGPU` was intended to use your dedicated GPU if available
almost all implementations do what its name implies, use whatever GPU is not the default

Multiple examples of this happening and arguments for and against it have been thrown around in https://github.com/PolyMC/PolyMC/issues/136

**Comment by Continous** [comment]
I think, if `PreferNonDefaultGPU` is to be used, it should be provided un-obfuscated, with an explanation of what it is expected to do. This way people don't tick it on accident when they really shouldn't. Also, it could theoretically be beneficial or detrimental to those with multi-GPU setups. I, for example, have a 3090 and a 1080 in my system. The 1080 is used exclusively for compute applications (mostly AI processing and rendering) while the 3090 is able to run games and the like. The 1080 is also not connected to a display. `PreferNonDefaultGPU` could potential cause problems in my configuration, so implementing it as a simple "this solves optimus problems" solution is haphazard in my opinion. I'm also not sure how much of this is a problem PolyMC should be solving.

**Comment by SomaSatoBLM** [comment]
I think it would be better to give a toggle option for the wrapper prime-run if it is toggles Java is given prime-run. There isn’t really any point in polymc using dedicated graphics card itself

**Comment by Continous** [comment]
I agree with @stephenseiber, I think it would be better to have PolyMC utilize third party programs that simply do these things better.
