### ISSUE TITLE
Modify mods while instance is running

### ISSUE THREAD

**Issue by Rafii2198** [PolyMC/PolyMC#255]
### Role

"Knowledgeable" Player

### Suggestion

An option to allow for modification of mods while an instance is running

### Benefit

Easier management for other "Knowledgeable" players

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

I know that modifying with files while Minecraft is running is not a good idea, so an option to allow that behavior with special attention that it may break stuff and even turning it on will show additional "Are you sure?" window would be good. The thing is if someone was to turn it on, they would probably know what they are doing anyway. Especially with your great feature of downloading mods, when Minecraft is running you can't even browse them at all. Personally, I keep downloading mods and if I could do that in the launcher itself, it would be great. 
And also, I sometimes go through the mod list in Minecraft and disable/delete the less wanted mods, again, can't do that in the launcher.

And also also I know I was talking only about Mods but I can't see why instance's Settings are also unchangeable, I think all of them are launch parameters so if Minecraft is running, changing them would do nothing. (unless I don't understand something)

**Comment by ZekeZDev** [comment]
This should also extend the shaders and resourcepacks its annoying to close the instance to add them.

**Comment by DioEgizio** [comment]
For mods you could have issues removing mods when the game is open and it won't launch added mods while game is open 



> This should also extend the shaders and resourcepacks its annoying to close the instance to add them.

For shaders and resourcepacks it would make sense to dehardcode the block for adding since you can add *while* game is open

**Comment by Sneedplex** [comment]
Not possible without caveats or breakage.
