### ISSUE TITLE
Cannot run binary polymc because of missing but not missing libPolyMC_rainbow

### ISSUE THREAD

**Issue by K0-RR** [PolyMC/PolyMC#258]
### Operating System

Linux

### Description of the bug

```
k0rr@mageia ~/D/PolyMC> ./bin/polymc
./bin/polymc: error while loading shared libraries: libPolyMC_rainbow.so: cannot open shared object file: No such file or directory
k0rr@mageia ~/D/PolyMC [127]> ls ./lib
libPolyMC_rainbow.so
```
Is this some quantum computing?

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Scrumplex** [comment]
You are trying to launch the application directly from the tarball. It won't work like that, as PolyMC will be looking for it's stuff in `/usr`.
You can work around this specific issue by adding the `lib` folder to your `LD_LIBRARY_PATH`, but I am sure that it won't work anyway as it will not be able to find the JAR files it needs.

**Comment by K0-RR** [comment]
>You are trying to launch the application directly from the tarball. It won't work like that, as PolyMC will be looking for it's stuff in /usr

It worked in MultiMC? How to use this binary?

**Comment by Scrumplex** [comment]
This one is not a portable build like the one from MultiMC. You can use the AppImage (which also bundles Java)

**Comment by K0-RR** [comment]
Appimage doesn't currently detect any java https://github.com/PolyMC/PolyMC/issues/117#issuecomment-1065987593.

>This one is not a portable build like the one from MultiMC

So what can I do with binary polymc? Use `install`?

**Comment by Scrumplex** [comment]
You could install PolyMC, yes. Otherwise, you could use the Flatpak.

**Comment by txtsd** [comment]
I think we should rename this build artifact. It's meant to be used by -bin type packages, not for running manually. The latter type should also be built and included, and it should come with a handy run script in the top level directory.

**Comment by glowiak** [comment]
A 'cp ./lib/* ./bin/' will fix this.

**Comment by glowiak** [comment]
FSR the portable build searches for libs in it's $CWD instead of ../lib

**Comment by Scrumplex** [comment]
This can't happen anymore as of #322
