### ISSUE TITLE
Flatpak: use the java extension from the runtime instead of bundling it.

### ISSUE THREAD

**Issue by Mek101** [PolyMC/PolyMC#26]
### Role

I play modded minecraft

### Suggestion

Use less space for the flatpak installation

### Benefit

Shorter build times for flathub, better manteinability

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

See:
- Java 11 https://github.com/flathub/org.freedesktop.Sdk.Extension.openjdk11
- Java 17 https://github.com/flathub/org.freedesktop.Sdk.Extension.openjdk17
- Latest openjdk https://github.com/flathub/org.freedesktop.Sdk.Extension.openjdk

**Comment by ZekeZDev** [comment]
I agree. Java 8 is also available from the looks of things so there should be no issue.

**Comment by d-513** [comment]
Ok, here's the result of a conversation in the chat room:
- By default only Java 17 will be included via SDK extensions
- other Java versions will be published as runtime extensions for the flatpak. Most will use runtime extensions if possible

**Comment by Mek101** [comment]
There would need to be a way to signal on PolyMC that to install the other JDKs you need to install the extensions (and possibly a gui to install them?)

**Comment by Mek101** [comment]
@ZekeSmith where have you seen the JDK8?

**Comment by d-513** [comment]
GUI is already there, Discover and Gnome Software should show the extensions on the app page

**Comment by d-513** [comment]
Maybe we could detect ~/.flatpak-info and display a message about it in Java detect gui

**Comment by ZekeZDev** [comment]
> @ZekeSmith where have you seen the JDK8?

https://github.com/flathub/org.freedesktop.Sdk.Extension.openjdk8

**Comment by d-513** [comment]
Does that work for kde platform sdk btw?

**Comment by ZekeZDev** [comment]
If your talking to me I have no idea

**Comment by Mek101** [comment]
@dada513 "That" being? If you mean the extensions, those are part of the freedesktop runtime

**Comment by d-513** [comment]
> @dada513 "That" being? If you mean the extensions, those are part of the freedesktop runtime

Yes I mean the sdk extensions. If they don't work with kde sdk we need to bundle. We aren't using free desktop sdk because it's a qt app

**Comment by ZekeZDev** [comment]
Are you sure freedesktop doesnt work with kde?

**Comment by d-513** [comment]
I'm not sure if the extensions work, I know I need kde for qt. I'll have to research this further once I'm back home

**Comment by ZekeZDev** [comment]
Freedesktop

The Freedesktop runtime is the standard runtime that can be used for any application and contains a set of essential libraries and services, including D-Bus, GLib, Gtk3, PulseAudio, X11 and Wayland.

**Comment by d-513** [comment]
Yeah doesn't look like it has qt5

**Comment by d-513** [comment]
We could bundle qt to freedesktop, but that would make another issue about bundling lol. I think I'll try the freedesktop extensions if they don't work the addons will have to bundle their jre

**Comment by ZekeZDev** [comment]
Huh?

**Comment by ZekeZDev** [comment]
It can be used with any application and the runtime includes wayland, dbus etc.

**Comment by d-513** [comment]
There's a reason kde runtime exists. Freedesktop has gtk, kde has qt

**Comment by ZekeZDev** [comment]
Yes but cant you use both?

**Comment by d-513** [comment]
More info:

https://docs.flatpak.org/en/latest/available-runtimes.html

I will experiment with it later once I'm home

**Comment by ZekeZDev** [comment]
Ok sounds good. I am pretty sure I have seen qt apps with freedesktop extensions. I think one of the latex editors does.

**Comment by ghost** [comment]
I don't really know anything about flatpak so @dada513 if you could work on this and let me know if help is needed that would be great.

**Comment by bilelmoussaoui** [comment]
The KDE and gnome SDK are based on the freedesktop one( it is their parent from a parent child perspective) so an SDK extension targets freedesktop SDK so it can work with either freedesktop, KDE or GNOME

**Comment by d-513** [comment]
Implemented in [23fd3c383bc18b9b99d3c3e6e7d3c6d0e0f92ce4](https://github.com/flathub/org.polymc.PolyMC/commit/23fd3c383bc18b9b99d3c3e6e7d3c6d0e0f92ce4). Users will need to manually change their java in the settings of PolyMC.

I removed java 16 and 11 because they are unneccesary, 8 and 17 cover all MC versions

**Comment by ghost** [comment]
You need 16 for 1.17 right?

**Comment by d-513** [comment]
> You need 16 for 1.17 right?

no mojang seems to have fixed it now works with 17

**Comment by d-513** [comment]
@binex-dsk can you close this please
