### ISSUE TITLE
Feral's Gamemode toggle for Linux

### ISSUE THREAD

**Issue by RondoRevolution** [PolyMC/PolyMC#260]
### Role

I play Minecraft on Linux.

### Suggestion

Add a toggle for enabling Feral's Gamemode on Linux if installed.

### Benefit

Any Linux user with Gamemode installed can benefit from better performance.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by Scrumplex** [comment]
Let's track this in #253
