### ISSUE TITLE
Corp repository is out-of-date

### ISSUE THREAD

**Issue by K0-RR** [PolyMC/PolyMC#264]
### Operating System

Linux

### Description of the bug

Last Build: 15 days ago

### Steps to reproduce

https://download.copr.fedorainfracloud.org/results/polymc/polymc/opensuse-leap-15.3-x86_64/

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Jan200101** [comment]
the copr was maintained by someone that was formerly involved with PolyMC.

work is being done to get a new one off the ground

**Comment by K0-RR** [comment]
Just wanted to say that the opensuse package from https://copr.fedorainfracloud.org/coprs/sentry/polymc/ (https://download.copr.fedorainfracloud.org/results/sentry/polymc/opensuse-leap-15.3-x86_64/) is working just fine on Mageia 8 and OpenMandriva 4.3. (This may be useful for the users of these distributions if they use the search before opening an issue)

**Comment by K0-RR** [comment]
Corp packages (I used the opensuse one) have broken version number
![Screenshot from 2022-03-14 14-02-49](https://user-images.githubusercontent.com/43277609/158178598-7558d828-507d-4415-95f8-ad5986b0af7d.png)
![Screenshot from 2022-03-14 14-02-18](https://user-images.githubusercontent.com/43277609/158178646-445090e6-37f3-47f3-9048-69fba143a13f.png)

Also, in the title bar the PolyMC name is duplicated

**Comment by Scrumplex** [comment]
@Jan200101 if possible either rename the branch which is used to build to "stable" or checkout a commit (detach from HEAD) and build. The former will remove the `-<branch>` suffix completely, while the latter will add the current commit instead (`-<commit-sha>`)

**Comment by Jan200101** [comment]
> @Jan200101 if possible either rename the branch which is used to build to "stable" or checkout a commit (detach from HEAD) and build. The former will remove the `-<branch>` suffix completely, while the latter will add the current commit instead (`-<commit-sha>`)

the copr does not use git at all.
For the latest released (1.1.0) it uses https://github.com/PolyMC/PolyMC/archive/1.1.0/polymc-1.1.0.tar.gz

Looking one further, the version string is suppose to include `GITDIR-NOTFOUND` but it gets cut off
https://github.com/PolyMC/PolyMC/blob/6cd4375aff98554c56a0138208d869aca0587656/cmake/GetGitRevisionDescription.cmake#L50

This can be verified by these two lines found in the COPR build logs
```
-- Git commit: GITDIR-NOTFOUND
-- Git refspec: GITDIR-NOTFOUND
```

**Comment by Scrumplex** [comment]
Hmm interesting. Might need to fix that.

**Comment by Jan200101** [comment]
Will be fixed in the next release of the copr package
![image](https://user-images.githubusercontent.com/15076013/158688514-38705368-205d-4093-a624-5520cd4b73eb.png)
