### ISSUE TITLE
Add PolyMC to Pacstall

### ISSUE THREAD

**Issue by K0-RR** [PolyMC/PolyMC#266]
### Role

I play Minecraft on pop os and mint

### Suggestion

https://github.com/pacstall/pacstall

### Benefit

Easly install PolyMC on Debian-based distributions without opening the PolyMC website/repository

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by Scrumplex** [comment]
There already is [MPR](https://polymc.org/wiki/installing/linux/ubuntu/) for this.

**Comment by K0-RR** [comment]
There is **both** choco and scoop package on windows too

**Comment by Scrumplex** [comment]
Not sure if anyone from our team wants to maintain this package. We generally only maintain packages ourselves that we use personally as well. Of course someone else can just go ahead and maintain a pacstall package.

**Comment by glowiak** [comment]
It's a good idea, I'd do it, but I don't have any ubuntu machine/vm, and today I'm busy updating *BSD and Slack packages to 1.1.0

**Comment by glowiak** [comment]
Okay, updated everything, but still ubuntu is very slooow on vms

**Comment by txtsd** [comment]
I don't think we might do this. The community is welcome to though.
