### ISSUE TITLE
[Feature Request] Download mods from modrinth and curseforge directly in the launcher 

### ISSUE THREAD

**Issue by DioEgizio** [PolyMC/PolyMC#27]
### Suggestion

it would be nice to have the ability to download mods from modrinth and curseforge directly through the launcher and auto updating them.

Peterix always said that this feature is useless because "you can do that on your browser"

### Benefit

It would make everything better and simpler. also it would make simpler to transition for people that previously used gdlauncher or curseforge

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by ZekeZDev** [comment]
You can download modpacks through the launcher but I am guessing your reffering to indivdual mods is that correct?

**Comment by DioEgizio** [comment]
yes

**Comment by ZekeZDev** [comment]
Yeah that would be epic Ill try and see if I can get more people interested in this idea because I have personally used gd and its an amazing feature.

**Comment by ZroNoh** [comment]
This was the feature MultiMC needed most but Peterix was always very opposed to this. https://github.com/MultiMC/Launcher/issues/3591#issuecomment-782694412 Hoping the get this one in PolyMC cause it's the only reason I still have GDLauncher installed.

**Comment by ghost** [comment]
since this seems to be a very highly requested issue I'll shift this to high priority.

Unfortunately, with FIRST Robotics season starting, I will have very little free time to work on this. Anyone willing to get some stuff started in a PR feel free to do so.

**Comment by timoreo22** [comment]
I already had a look around on the api side
modrinth has a good api for this, allowing for browsing mods, and downloading them directly without any api key
curseforge on the other hand, officially you should "apply for an api key" for using the official api, but there is still a valid api endpoints at https://addons-ecs.forgesvc.net/api/v2/ that don't require any key
i can try implementing that in tho i have no experience with polymc's code base

**Comment by ghost** [comment]
@timoreo22 If you're willing, you could easily make a simple script to demonstrate most usage of the API. Then when I have the time I will go ahead and work on adding it.

**Comment by timoreo22** [comment]
Hi ! i'll try to make it myself, i've created a draft pull request for this issue.

**Comment by jdpage** [comment]
One thing to look at regarding prior art might be https://github.com/packwiz/packwiz, which is what I'm currently using to manage my mods. It integrates fairly nicely with PolyMC as-is (using the "run a command before launching minecraft" feature), but it would be neat if PolyMC could read packwiz files directly, since they can also specify the game and Forge version.

Basically it provides a tree of TOML files which reference the appropriate files on Curseforge and Modrinth. The TOML files can be served up over HTTP, and the tool linked above provides a command-line interface for managing the modlist.

**Comment by DioEgizio** [comment]
> One thing to look at regarding prior art might be https://github.com/packwiz/packwiz, which is what I'm currently using to manage my mods. It integrates fairly nicely with PolyMC as-is (using the "run a command before launching minecraft" feature), but it would be neat if PolyMC could read packwiz files directly, since they can also specify the game and Forge version.
> 
> Basically it provides a tree of TOML files which reference the appropriate files on Curseforge and Modrinth. The TOML files can be served up over HTTP, and the tool linked above provides a command-line interface for managing the modlist.

Packwiz is more for modpacks

**Comment by theofficialgman** [comment]
incase it helps anyone here trying to implement this
I currently use https://github.com/Senth/minecraft-mod-manager to handle installation/updating of mods from curseforge/modrinth. A custom pre-launch script is used to read the minecraft version from `mmc-pack.json`, update mods to this version, install mods with that version, etc https://gist.githubusercontent.com/theofficialgman/e5de0a715edfee96f2445a790df1f597/raw/9df72200d6cbe8e9c9329ff7d80599b4410cf0bd/pre-launch.sh

clearly you wouldn't use this, but I figured it might help to reference the github repo from Senth incase any of the api documentation there for curseforge is of any help

**Comment by DioEgizio** [comment]
pog

**Comment by ZekeZDev** [comment]
Epic
