### ISSUE TITLE
mod updater

### ISSUE THREAD

**Issue by stradus64** [PolyMC/PolyMC#274]
### Role

playing latest minecraft with a lot of small QoL and performance enhancing mods that don't alter vanilla content

### Suggestion

add a button that checks installed mods for updates and automatically installs them after confirmation

### Benefit

convenient updates for small vanilla-enhancing fabric mods without having to manually go through each mod one by one and installing latest verison 

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

https://github.com/ATLauncher/ATLauncher implements such feature

![image](https://user-images.githubusercontent.com/10760147/158077703-a6cab036-13d5-4969-a357-e785cbf2f3ea.png)

![image](https://user-images.githubusercontent.com/10760147/158077725-bb10fd9f-cbc6-46c9-b7b8-21f20805b0d0.png)

**Comment by obj-obj** [comment]
GDLauncher also implements this

**Comment by Un1q32** [comment]
I cannot describe in words how awesome this would be

**Comment by DioEgizio** [comment]
i agree this would be cool

**Comment by luximus-hunter** [comment]
I think this feature is really important and time saving for a lot of people

**Comment by RaptaG** [comment]
But to upgrade a modpack's mods separately from other mods

**Comment by wertercatt** [comment]
I'd also love if it could notify you when all your mods now support a new Minecraft version, so you can update to the new version.

**Comment by UnlimitedCookies** [comment]
https://github.com/PolyMC/PolyMC/issues/378#issuecomment-1148536896

> Maybe you should be able to define something similar to a Cargo.toml or package.json and then you would have a Lockfile that always keeps the same version. Then when you decide to update the Lockfile would be updated according to the constraints defined in the "Cargo.toml". This would make downloading mod updates less of a hassle and you could easily share a manifest file with your friend, which then would get the identical mc instance with the same mods. Obviously hindering this would be mod authors like the author of optifine, who don't like it when other people automatically download mods from their site or redistribute it.

**Comment by DioEgizio** [comment]
> [#378 (comment)](https://github.com/PolyMC/PolyMC/issues/378#issuecomment-1148536896)
> 
> > Maybe you should be able to define something similar to a Cargo.toml or package.json and then you would have a Lockfile that always keeps the same version. Then when you decide to update the Lockfile would be updated according to the constraints defined in the "Cargo.toml". This would make downloading mod updates less of a hassle and you could easily share a manifest file with your friend, which then would get the identical mc instance with the same mods. Obviously hindering this would be mod authors like the author of optifine, who don't like it when other people automatically download mods from their site or redistribute it.

This already exists (#426)

**Comment by dhouck** [comment]
An important feature for a mod updater is to be able to choose which version, even among CurseForge’s alphas and betas.  Some launchers hide those and it probably shouldn’t be the *default* for most mods, but it should be supported.
