### ISSUE TITLE
PolyMC force closed

### ISSUE THREAD

**Issue by 0uros** [PolyMC/PolyMC#276]
### Operating System

Windows

### Description of bug

You only see a white window, the language selection window, and it closes suddenly.

### Steps to reproduce

Just run polymc.exe, either normally, such as with administrator permissions or by cmd

### Suspected cause

[log.txt](https://github.com/PolyMC/PolyMC/files/8241826/log.txt)

```
E:\descargas\PolyMC-Windows-1.1.0>java --version
openjdk 17.0.2 2022-01-18
OpenJDK Runtime Environment Temurin-17.0.2+8 (build 17.0.2+8)
OpenJDK 64-Bit Server VM Temurin-17.0.2+8 (build 17.0.2+8, mixed mode, sharing)

E:\descargas\PolyMC-Windows-1.1.0>
```

I think is a Java issue, but I'm not sure, I was trying to start the program in Windows 10 LTSC 21h2.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by txtsd** [comment]
Additionally, MultiMC works fine for OP.

**Comment by txtsd** [comment]
@0uros Can you try the build from [here](https://github.com/PolyMC/PolyMC/actions/runs/1980037532)?

**Comment by txtsd** [comment]
Also can you try a debug build so we can get a stacktrace?

**Comment by 0uros** [comment]
> Also can you try a debug build so we can get a stacktrace?

I downloaded the debug version, started it using cmd and got the following log, if you need any other information let me know

[log.txt](https://github.com/PolyMC/PolyMC/files/8246037/log.txt)

**Comment by txtsd** [comment]
That's it? There was no additional crash information after the log stuff?

**Comment by 0uros** [comment]
No, copy everything that appeared in cmd, if there is another way to have a log I would gladly try it to get more information in detail.

**Comment by Scrumplex** [comment]
Can you try one of the Windows builds from here: https://github.com/PolyMC/PolyMC/actions/runs/2002938513

**Comment by 0uros** [comment]
Now it works, for a moment in the log it seemed that it was repeating the error, but the configuration of the version of java to use appeared.

In case you find it useful, I leave you the log, but now the error is solved thanks a lot ^^
[log.txt](https://github.com/PolyMC/PolyMC/files/8308097/log.txt)

**Comment by Scrumplex** [comment]
Cool, thanks for your feedback!
