### ISSUE TITLE
mod version matching is too strict

### ISSUE THREAD

**Issue by stradus64** [PolyMC/PolyMC#279]
### Operating System

Linux

### Description of bug

mod installer won't show mods that match major version but not minor, some mods are marked as 1.18 but work on 1.18, 1.18.1, 1.18.2 etc

examples
https://modrinth.com/mod/ebe
https://www.curseforge.com/minecraft/mc-mods/carpet

![image](https://user-images.githubusercontent.com/10760147/158248613-6942c359-296a-4d76-9c44-b9f34a656472.png)

### Steps to reproduce

search for mod for minecraft 1.18 in mod installer  in an instance of minecraft 1.18.1 or 1.18.2

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by DioEgizio** [comment]
We can't do anything about it if the authors don't mark the version correctly

**Comment by DioEgizio** [comment]
Also we can't know if it actually works or not, like 1.18.2 broke a lot of mods

**Comment by DioEgizio** [comment]
Also ebe is broken on 1.18.2

**Comment by glowiak** [comment]
Well, fabric is not Forge. In Forge only the major version matters (I played 1.8 mod on 1.8.9), while fabric checks the full version number in-game. So, this would be a good idea to disable minor-version checking when Forge is used, but not when fabric

**Comment by DioEgizio** [comment]
> Well, fabric is not Forge. In Forge only the major version matters (I played 1.8 mod on 1.8.9), while fabric checks the full version number in-game. So, this would be a good idea to disable minor-version checking when Forge is used, but not when fabric

This is not true at all

**Comment by DioEgizio** [comment]
For example 1.18.2 broke a lot of mods in forge too

**Comment by DioEgizio** [comment]
If you use ancient MC versions then it might be the case, but it's definitely not

**Comment by obj-obj** [comment]
For me, all the 1.18/1.18.1 mods I've tried work fine on 1.18.2
Mod authors might just not upload a new version if they notice the current on works fine on the newest version
Don't prevent people from installing those mods, just display a warning

**Comment by Scrumplex** [comment]
We could implement a feature that allows the user to select from a few options to adjust the filter. I would propose these options:
- Exact version (1.18.2)
- Same release (1.18.x)
- Any version

**Comment by DioEgizio** [comment]
Yeah but a disclaimer should be there like:
"If you really know what you're doing"

**Comment by txtsd** [comment]
> Yeah but a disclaimer should be there like:
> "If you really know what you're doing"

Why would you need a disclaimer for a filter?
