### ISSUE TITLE
Icons on windows build are currently broken

### ISSUE THREAD

**Issue by DioEgizio** [PolyMC/PolyMC#28]
### Operating System

Windows

### Description of bug

Icons on windows build are currently broken

![IMG_20220108_125203_188](https://user-images.githubusercontent.com/83089242/148645885-5d4b24aa-1a91-44d9-8263-8b845aa07fc3.jpg)

### Steps to reproduce

- Open PolyMC on windows
- see

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by ghost** [comment]
Are these your MultiMC instances?

If so, you need to point the icons to MultiMC as well.

**Comment by DioEgizio** [comment]
> If so, you need to point the icons to MultiMC as well.

Yes, and on multimc I did

**Comment by ghost** [comment]
Last I remember, I didn't have this issue on Windows. I will check later.

**Comment by Cynosphere** [comment]
Can replicate, both instances and interface icons are missing. *Some*, but not all of my instance icons do load though.
![example of some instance icons loading](https://i.imgur.com/Q9UNPfU.png)

**Comment by ghost** [comment]
That's weird. Can you test on the latest 1.0.5 build?

**Comment by DioEgizio** [comment]
> That's weird. Can you test on the latest 1.0.5 build?

I tried, same issue 
![immagine](https://user-images.githubusercontent.com/83089242/149204344-a6bac744-c5d3-4325-9330-73fcb2dfa4ee.png)

**Comment by ghost** [comment]
I don't see any instances at all there. Did you set the folder correctly?

**Comment by DioEgizio** [comment]
i took the photo without instances, but as you can see, the icons of the app are broken

**Comment by ghost** [comment]
Okay, I'm assuming that this is an issue with the Jenkins build. If not then I have no clue what's going on. I will test this later.

@LennyMcLennington I have no idea how the windows build works so if you could check it on Jenkins that would be cool + good

**Comment by helpimnotdrowning** [comment]
Looks to me only GIF icons work. pngs and jpgs don't, for some reason.
![image](https://user-images.githubusercontent.com/35247379/149603860-4f5a5896-d19e-46b5-b530-cae9178fd96d.png)

**Comment by ghost** [comment]
amogus

**Comment by ghost** [comment]
Might be a MinGW moment or an old build causing issues.

I started a Jenkins build from scratch, let's see if this fixes it

**Comment by ghost** [comment]
Nope.

I have literally no clue what causes this

**Comment by ZekeZDev** [comment]
Yeah I was able to replicate this bug too. I think we should probably increase the severity of this issue and probably pin it since it basically ruins the whole launcher for windows users which is a pretty big market of users.

**Comment by PanoptesDreams** [comment]
![image](https://user-images.githubusercontent.com/55162814/149925243-50973537-5e1e-40db-9e39-72f3cd336a17.png)
+1 my first launch experience has no icons

**Comment by ZekeZDev** [comment]
Yep as to be expected. We really need to sort this issue out asap its a rather big issue, ik that @binex-dsk is currently busy so it might be difficult to get this patch soon.

**Comment by timoreo22** [comment]
This reminds me of another bug i had during making the mod download part.
Icon in the .webp format wouldn't work
Until i installed a qt plugin package on my linux distro.
I'm feeling this has to do with some kind of qt plugin not getting packaged correctly

I will try to reproduce it on a dev build, it will probably take me some time to setup for windows build

**Comment by ghost** [comment]
You can check our current Jenkins config in [polymc-misc](https://github.com/PolyMC/polymc-misc). If you figure out the missing library you can PR it.

**Comment by Sightem** [comment]
screenshots seem to be broken as well
![PolyMC_iXGpUL2Ss2](https://user-images.githubusercontent.com/67830794/150074877-016622c3-ee22-4109-beba-ce4425bbbdd0.png)

**Comment by ZekeZDev** [comment]
Hmm if its screenshots too @timoreo22 might be on to something.

**Comment by Sightem** [comment]
also another thing i just noticed, if you select an instance, click on edit instance, then click on the screenshots tab, then try to close it whether using the bottom right close button or using X, the main window stops responding for a bit, then fixes itself.

edit: on my machine takes around 20 seconds before it comes back to life, not sure if this is related to anything regarding the issue

**Comment by ghost** [comment]
Probably the missing platform plugin then.

**Comment by txtsd** [comment]
We should triage this. What was the last version that worked correctly?

**Comment by ghost** [comment]
I don't think any version worked.

I believe I've figured out the problem, however. Here are the currently installed MinGW Qt 5 packages on the server:
```
$ pacman -Qs mingw qt   
local/mingw-w64-qt5-base 5.15.2+kde+r222-2 (mingw-w64-qt5)
    A cross-platform application and UI framework, native OpenGL backend (mingw-w64)
local/mingw-w64-qt5-base-static 5.15.2+kde+r222-1 (mingw-w64-qt5)
    A cross-platform application and UI framework, native OpenGL backend (mingw-w64)
local/mingw-w64-qt5-declarative 5.15.2+kde+r42-1 (mingw-w64-qt5)
    Classes for QML and JavaScript languages (mingw-w64)
local/mingw-w64-qt5-svg 5.15.2+kde+r7-1 (mingw-w64-qt5)
    Classes for displaying the contents of SVG files (mingw-w64)
```

**It's missing qt5-multimedia**.

This would explain the complete lack of any media being displayed. The server is currently in the process of compiling `mingw-w64-qt5-multimedia-static` and I will update Jenkins build scripts to accomodate for this (by adding the QtMultimedia.dll to the directory)

**Comment by ghost** [comment]
Failed to compile due to a version mismatch. It's now recompiling literally all of MinGW Qt5.

**Comment by LennyMcLennington** [comment]
The -static packages aren't used in the Jenkins build.

30 Jan 2022 16:30:53 swirl ***@***.***>:

**Comment by txtsd** [comment]
@binex-dsk Are we sticking with Jenkins permanently? Is GitHub Actions not good?

**Comment by ghost** [comment]
We are going to have GH actions for per-commit builds, and it will also likely build releases too. However, Jenkins will also build releases, automatically publish to AUR/MPR, and will put prebuilt generic packages onto packages.polymc.org.

Thanks to the configurability of Jenkins (especially being on a real machine hosted by me), it is much more versatile for the purposes of publishing packages and package updates.

**Comment by ghost** [comment]
THIS ISSUE HAS BEEN FIXED ON THE LATEST BUILD

@system69-e can you test screenshots? Zip available [here](https://jenkins.polymc.org/job/PolyMC/ws/win32-1.0.6.zip)

**Comment by Sightem** [comment]
> THIS ISSUE HAS BEEN FIXED ON THE LATEST BUILD
> 
> @system69-e can you test screenshots? Zip available [here](https://jenkins.polymc.org/job/PolyMC/ws/win32-1.0.6.zip)

![PolyMC_mEqtFNVGI4](https://user-images.githubusercontent.com/67830794/151813282-69196677-cb17-4885-b579-725525e89474.png)
can indeed confirm, it is fixed!

**Comment by Sightem** [comment]
> also another thing i just noticed, if you select an instance, click on edit instance, then click on the screenshots tab, then try to close it whether using the bottom right close button or using X, the main window stops responding for a bit, then fixes itself.
> 
> edit: on my machine takes around 20 seconds before it comes back to life, not sure if this is related to anything regarding the issue

this issue seems to be resolved as well, gj!

**Comment by DioEgizio** [comment]
> > THIS ISSUE HAS BEEN FIXED ON THE LATEST BUILD
> > @system69-e can you test screenshots? Zip available [here](https://jenkins.polymc.org/job/PolyMC/ws/win32-1.0.6.zip)
> 
> ![PolyMC_mEqtFNVGI4](https://user-images.githubusercontent.com/67830794/151813282-69196677-cb17-4885-b579-725525e89474.png) can indeed confirm, it is fixed!

Cool, closing issue

**Comment by ghost** [comment]
I'm an absolute genius

**Comment by Cynosphere** [comment]
Ironically JPEG icons, which are the ones that only worked before this, are not working now
