### ISSUE TITLE
[Linux?] Modpack icons are not automatically downloaded when the icons path is changed

### ISSUE THREAD

**Issue by Alkaline-Dreams** [PolyMC/PolyMC#287]
### Operating System

Linux

### Description of bug

I store all my PolyMC instances on an HDD, and after changing the icons directory from the default to a new directory, new modpacks that get downloaded no longer automatically fetch their icon. Changing the icon directory back to the default and then redownloading the pack works as expected.

I'd also note that the icon doesn't get downloaded into the default folder when this happens either, it just silently fails.

### Steps to reproduce

- Go into settings and change the icon directory to any other place
- Download a modpack

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by HalJordan** [comment]
I've noticed this myself, it's down to the pack authors themselves and what's included with the pack. Seems it's something they're leaving out, or not including in the right way. It might be more relevant on one platform(thinking CurseForge) vs another.

**Comment by Scrumplex** [comment]
Can you make sure that the required Qt packages are installed?

On Arch they would be `qt5-imageformats qt5-svg`

**Comment by HalJordan** [comment]
I already had those on my end, if it helps.

```
hal_j@home ~ % yay -Qs qt5-imageformats
local/qt5-imageformats 5.15.3+kde+r0-1 (qt qt5)
    Plugins for additional image formats: TIFF, MNG, TGA, WBMP
hal_j@home ~ % yay -Qs qt5-svg         
local/qt5-svg 5.15.3+kde+r12-1 (qt qt5)
    Classes for displaying the contents of SVG files

```

**Comment by Scrumplex** [comment]
Okay. Can you tell me about one of the modpacks where the icon doesn't work?

**Comment by HalJordan** [comment]
FTB(New) The DW20 1.16 pack. It has an icon in the new instance list, but not when you actually add it. I'm on 1.2.1-5adcc261 and just tested. It's setting an iconKey value in instance.cfg, but not pulling the actual icon. So it really looks like it's down to each pack individually.
