### ISSUE TITLE
Minecraft Folder; Config Folder; Instance Folder buttons don't work

### ISSUE THREAD

**Issue by K0-RR** [PolyMC/PolyMC#289]
### Operating System

Linux

### Description of bug

```
  697.615 D Opening directory "/home/naciacia/.var/app/org.polymc.PolyMC/data/polymc/instances/1.18.1"
Failed to call portal: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.portal.Desktop was not provided by any .service files
  698.279 D Opening directory "/home/naciacia/.var/app/org.polymc.PolyMC/data/polymc/instances/1.18.1/.minecraft/config"
Failed to call portal: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.portal.Desktop was not provided by any .service files
```

### Steps to reproduce

Click one of these buttons

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Scrumplex** [comment]
All of them work on my end. This is probably an issue with your environment. Do you have the necessary XDG Desktop Portals installed and configured correctly? If you are on a window manager make sure to have at least `xdg-desktop-portal-gtk`, which provides most interfaces needed for most Flatpaks

**Comment by K0-RR** [comment]
The only ones that are available in my repos are `xdg-desktop-portal` and `xdg-desktop-portal-kde`... time to report to distro maintainers
