### ISSUE TITLE
Allow loading of .so as a mod.

### ISSUE THREAD

**Issue by Bitwolfies** [PolyMC/PolyMC#290]
### Role

I play modded minecraft

### Suggestion

Allow mods to use .so files if needed

### Benefit

Becasue the only client that can do this so far is the offical one.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Minecraft mod Retro64 depends on the usage of an .so file to get it to work properly, the native library folder does nothing, and even if it did the mod requires the so to be in the mods folder. Launching with the so in the folder crashes the game, so allowing us to use them like the normal client would be great.

**Comment by Scrumplex** [comment]
Can you provide the Minecraft log when you tried to start the game with the `.so` in your mods folder

**Comment by Bitwolfies** [comment]
https://0x0.st/oNb3.txt

**Comment by Scrumplex** [comment]
It seems like this is an issue with your sm64.so specifically.

The Minecraft mod can't load sm64.so because of the following error:
```
 ne.mi.ev.EventBus/EVENTBUS]: Exception caught during firing event: Unable to load library '/home/bitwolf/.var/app/org.polymc.PolyMC/data/PolyMC/instances/1.18.21/.minecraft/mods/sm64.so':
/usr/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /home/bitwolf/.var/app/org.polymc.PolyMC/data/PolyMC/instances/1.18.21/.minecraft/mods/sm64.so)
```

This might just be a mismatch between glibc in the Flatpak and glibc which was used to compile sm64.so

**Comment by Bitwolfies** [comment]
> It seems like this is an issue with your sm64.so specifically.
> 
> The Minecraft mod can't load sm64.so because of the following error:
> 
> ```
>  ne.mi.ev.EventBus/EVENTBUS]: Exception caught during firing event: Unable to load library '/home/bitwolf/.var/app/org.polymc.PolyMC/data/PolyMC/instances/1.18.21/.minecraft/mods/sm64.so':
> /usr/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /home/bitwolf/.var/app/org.polymc.PolyMC/data/PolyMC/instances/1.18.21/.minecraft/mods/sm64.so)
> ```
> 
> This might just be a mismatch between glibc in the Flatpak and glibc which was used to compile sm64.so

Thing is, I also used non flatpak Polymc, same issue.

**Comment by oynqr** [comment]
Do you have glibc 2.34 on your system? If not, then yes, same issue.

Also, could you provide a log from a non-flatpak PolyMC install and some general info about your system?

**Comment by Scrumplex** [comment]
PolyMC doesn't handle anything related to mod loading. PolyMC only gives you an interface to manage your installed mods, but it doesn't affect actual mod loading. You should try to compile that library yourself and see if it works.

**Comment by Bitwolfies** [comment]
> PolyMC doesn't handle anything related to mod loading. PolyMC only gives you an interface to manage your installed mods, but it doesn't affect actual mod loading. You should try to compile that library yourself and see if it works.

I did, it’s only available if you compile by hand.

**Comment by oynqr** [comment]
I mean, there is the chance that something weird happens because of LD_PRELOAD... Could you enable the checkboxes for using the system native versions of GLFW/OpenAL?

**Comment by Bitwolfies** [comment]
> I mean, there is the chance that something weird happens because of LD_PRELOAD... Could you enable the checkboxes for using the system native versions of GLFW/OpenAL?

Makes it crash faster, somehow. Still using flatpak for these tests, I gave the app every permission in flatseal.
