### ISSUE TITLE
authlib-injector

### ISSUE THREAD

**Issue by vanja-san** [PolyMC/PolyMC#293]
### Role

I play modded Minecraft

### Suggestion

I want to be able to authorize through LittleSkin and other authlib-injector services

### Benefit

To use capabilities of skins without manual loading

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

If such an opportunity arises, I'm sure many will appreciate it.

**Comment by Scrumplex** [comment]
This can be achieved once #175 is merged. I don't think we would add support for authlib-injector specifically.

**Comment by DioEgizio** [comment]
authlib-injector is used manly for piracy...

**Comment by vanja-san** [comment]
@DioEgizio So the offline game isn't being used for piracy?

**Comment by DioEgizio** [comment]
wdym

**Comment by vanja-san** [comment]
@DioEgizio sorry, i noob
If this is indeed the case, then we can close this issue!

**Comment by DioEgizio** [comment]
wdym

**Comment by vanja-san** [comment]
@DioEgizio I'm sorry, I'm not good at English.

**Comment by Scrumplex** [comment]
The feature needed for this to work is in #175. I will close this as we won't provide support for authlib-injector specifically.
