### ISSUE TITLE
Steam can't inject into PolyMC

### ISSUE THREAD

**Issue by ZroNoh** [PolyMC/PolyMC#302]
### Operating System

Linux

### Description of bug

When adding PolyMC as a non-steam game, the Steam overlay and controller configurations do not work. Using the "-l" launch command does not change anything. This works works fine in MultiMC.

### Steps to reproduce

1. Add PolyMC to steam.
2. Launch PolyMC with or without the "-l" command.
2a. If you didn't use "-l" then launch an instance manually.
4. Steam overlay fails to work as well as controller configuration.

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by kthchew** [comment]
> 1. Add PolyMC to steam.

@ZroNoh How did you install PolyMC, and which executable did you add to Steam?

If you used the .tar.gz, there's a bash script called `PolyMC` that should be added to Steam (or at least, add some shortcut that runs that script). You should not add the `bin/polymc` executable directly, because the bash script seems to do some stuff with the environment variables that (are supposed to) allow the Steam overlay to work. I'm not very familiar with the other install options on Linux, but I'd assume it's the same there.

**Comment by ZroNoh** [comment]
I used una to install it as well as Flatpak.

**Comment by kthchew** [comment]
If you make a script with the below contents (edit the bottom section to open PolyMC as needed):

```bash
#!/bin/bash

export GAME_LIBRARY_PATH=${GAME_LIBRARY_PATH-${LD_LIBRARY_PATH}}
export GAME_PRELOAD=${GAME_PRELOAD-${LD_PRELOAD}}

polymc # if una
flatpak run org.polymc.PolyMC # if flatpak
# or if neither of these run polymc, just do whatever you'd do to run it from bash
```

And add that script to Steam as your game, does that work?

**Comment by ghost** [comment]
> If you make a script with the below contents (edit the bottom section to open PolyMC as needed):
> 
> And add that script to Steam as your game, does that work?

I was having the same issue and this fixed it, I only added `"$@"` after polymc so arguments can still be passed through Steam.
Both the overlay and the controller configurations work properly, thank you :)

**Comment by kthchew** [comment]
Thanks for testing! I made an educated guess and tried a change at https://github.com/kthchew/PolyMC/actions/runs/2538851494 that may fix the issue without the need for a script. Could you go to that link and use one of the Linux artifacts at the bottom, and see if the Steam overlay works with those, please? If it does then I'll open a PR and see if the fix can be added to the main PolyMC build.

To test the change, you should add the `bin/polymc` (not the `PolyMC` script, which already has the workaround I gave above in it but doesn't seem to be present when installed with `una` etc.) to Steam and see if everything works correctly. I don't have a VM prepared to test the changes easily myself, unfortunately.

**Comment by ghost** [comment]
I tried with the appimage and yes, overlay and controller configs work fine without any tweaking, do you want me to try the other installation methods?

**Comment by kthchew** [comment]
> I tried with the appimage and yes, overlay and controller configs work fine without any tweaking, do you want me to try the other installation methods?

If AppImage worked fine and didn’t work before, then that should be fine. Thank you very much!
