### ISSUE TITLE
GUI is too big with Windows display scaling

### ISSUE THREAD

**Issue by Nesewebel** [PolyMC/PolyMC#307]
### Operating System

Windows

### Description of bug

When using display scaling on Windows the GUI is too big on certain scaling values

I've noticed this problem at 4k with 150% scaling, but it is the same for other resolutions and only depends on the scaling value.

> *Side by side comparison between MultiMC (left) and PolyMC (right) at 4k 150%*
> ![Side by side comparison](https://cdn.discordapp.com/attachments/923671344921600201/954908820574973993/unknown.png)

Another user on the discord did the same comparison on Arch Linux (also at 4k 150%) and there it was the correct size

At first a guess was that fractional scaling doesn't work at all, but 1.25x works fine
> *100% (okay)* ✔️
> ![100%](https://cdn.discordapp.com/attachments/923671344921600201/954916438005661706/unknown.png)

> *125% (okay)* ✔️
> ![125%](https://cdn.discordapp.com/attachments/923671344921600201/954916438202806302/unknown.png)

> *150% (too big)* ❌
> ![150%](https://cdn.discordapp.com/attachments/923671344921600201/954916438399922247/unknown.png)

> *175% (too big)* ❌
> ![175%](https://cdn.discordapp.com/attachments/923671344921600201/954916438576095282/unknown.png)

> *200% (okay)* ✔️
> ![200%](https://cdn.discordapp.com/attachments/923671344921600201/954916438810984479/unknown.png)

### Steps to reproduce

* Use Windows
* Set scaling to 150% or 175%
* Start PolyMC

### Suspected cause

Another user suggested it could be caused by a different qt version to MultiMC

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by txtsd** [comment]
Can you try a build [from here](https://github.com/txtsd/PolyMC/actions/runs/2010938385) and see if the 150% and 175% fractional scaling is fixed?

**Comment by Nesewebel** [comment]
> Can you try a build [from here](https://github.com/txtsd/PolyMC/actions/runs/2010938385) and see if the 150% and 175% fractional scaling is fixed?

Looks good!

*new build (left) vs release (right)*
![after vs before](https://cdn.discordapp.com/attachments/345689507133259777/954990315775885312/unknown.png)

**Comment by txtsd** [comment]
Okay good. I'll make a PR with the change.
