### ISSUE TITLE
Change text scaling behavior for High DPI displays

### ISSUE THREAD

**Issue by Nesewebel** [PolyMC/PolyMC#308]
### Role

To replace the default launcher.

### Suggestion

Change the font size to be more dynamic

### Benefit

So that users with High DPI screens have the same experience as FullHD users, just crisper

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

As stated in the Bug Report #307 there is a different scaling behavior between MultiMC and PolyMC that makes the GUI too big when using display scaling in Windows.

But MultiMC doesn't work perfect either, because there the text size doesn't change at all, only the icon sizes and spaces between UI elements. (Not sure if Windows only yet)

Ideally the text size of the GUI would have the same ratio to the rest of the OS (like the window title bar) at any scaling value

> *100%*
> ![100%](https://cdn.discordapp.com/attachments/923671344921600201/954916438005661706/unknown.png)

> *300%*
> ![300%](https://cdn.discordapp.com/attachments/345689507133259777/954968652225069107/unknown.png)

> *100% screenshot inside 300% screenshot* 
> ![test](https://cdn.discordapp.com/attachments/345689507133259777/954975058391093258/unknown.png)

**Comment by DioEgizio** [comment]
This should work fine nowadays, can you try again?
