### ISSUE TITLE
[Modrinth] the mod downloader shows mods even if they are server only

### ISSUE THREAD

**Issue by DioEgizio** [PolyMC/PolyMC#309]
### Operating System

Windows, macOS, Linux, Other

### Description of bug

self-explinatory, you can find server only mods

![immagine](https://user-images.githubusercontent.com/83089242/159161036-a6be35f9-5cda-4ec1-a71b-0f06e780db10.png)

### Steps to reproduce

- go to modrinth mod downloader
- youl'll find server side mods

### Suspected cause

missing check

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Rafii2198** [comment]
I mean you can use Server side mods on client, they would still work. Like Server Hats, it allows you put certain (or all depending on config) blocks on your head, you can use it on single to put these blocks on your head.

Basically `Server side` means only the host needs it and it will work for other people if they don't have it. So there is nothing wrong from showing them.

You could even benefit from ServerCore on Single. And you can open your world to LAN and basically be a server.

**Comment by luni3359** [comment]
Rather than outright removing them it would be better if there was a way to mark them with a tag so that it's immediately noticeable if not already obvious in its name, but I don't think there's really a need to change anything.

**Comment by Scrumplex** [comment]
Is this still the case?

**Comment by DioEgizio** [comment]
Yes!

**Comment by DioEgizio** [comment]
Closing this in favour of https://github.com/PolyMC/PolyMC/issues/210
