### ISSUE TITLE
Change the font to make the UI more nice

### ISSUE THREAD

**Issue by DioEgizio** [PolyMC/PolyMC#310]
### Role

i use polymc

### Suggestion

I would like a better and a more nice UI font since the current one is incredibly ugly

### Benefit

better UI/UX

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by txtsd** [comment]
Doesn't it just use your default system font? Are you implying your default system font is ugly? :trollface:

**Comment by DioEgizio** [comment]
yes :trollface:

**Comment by Scrumplex** [comment]
Not sure if we want to touch this. This should be handled by your Qt platform theme.
