### ISSUE TITLE
Can't log into microsoft account

### ISSUE THREAD

**Issue by randomskoolkid** [PolyMC/PolyMC#318]
### Description of bug

When you click on add Microsoft account, the login page gets stuck loading
![Screenshot (4](https://user-images.githubusercontent.com/62577311/159176473-f94354a3-e423-4809-8cab-57cd51be005f.png)
.

### Steps to reproduce

1. Launch PolyMC
2. Go to settings
3. Go to accounts and click on add Microsoft

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Scrumplex** [comment]
This is probably an issue with OpenSSL. You can see [this wiki page](https://polymc.org/wiki/getting-started/installing-polymc/#i'm-getting-random-openssl-errors-on-windows.-what-can-i-do) ("I'm getting random OpenSSL errors on Windows. What can I do?") to see the solution to this. This will be fixed for good with the next version

**Comment by Tellegar** [comment]
got the same issue on linux
log:
```
    5.577 D Task "MSAInteractive(0x55c81d5d8df0)" starting for the first time
    5.577 D AuthFlow: "Logging in with Microsoft account."
    5.577 D DeviceFlow::link
    5.577 D DeviceFlow::setLinked: false
    5.666 D DeviceFlow::onDeviceAuthReplyFinished
   12.859 W QCoreApplication::postEvent: Unexpected null receiver
```

the same method works on multimc client but not on polymc
