### ISSUE TITLE
Logos and branding are non-free

### ISSUE THREAD

**Issue by ghost** [PolyMC/PolyMC#319]
Files in /program_info directory are licensed under Creative Commons BY-NC-SA 4.0. These files (and hopefully nothing else) are non-free and makes PolyMC only semi-free or proprietary.
Choosing CC-BY-SA 4.0 for example would make PolyMC as a whole complaint with something like the Debian Free Software Guidelines I guess. (Just ignoring the fact that MC itself is proprietary) it would still be nice to have the possibility to get a fully free software game launcher for MC into the Debian/Ubuntu repositories.

**Comment by Scrumplex** [comment]
@ZekeSmith holds the copyright here. Maybe he can relicense it under CC-BY-SA 4.0. That would make it easier for people to monetize content about the launcher as well. (like using the logo in thumbnails on video platforms)

**Comment by ZekeZDev** [comment]
Yep I should have time to do this tommorow.

**Comment by ZekeZDev** [comment]
#383
