### ISSUE TITLE
Make PolyMC Less Dependant on Qt

### ISSUE THREAD

**Issue by Zenith222** [PolyMC/PolyMC#320]
### Goal

Modifying PolyMC so it's less dependent on QT framework would open the door to using different application toolkits in the future. This could be important as the project gains independence, and focuses on UI/UX improvements. 

### Motivation

I do not believe the current UI/UX is as good as it can be and there may be better suited application toolkits out there. Independence from specific frameworks should be a goal to future-proof the project even if there is not an immediate need to rework the user interface. 

In particular, as I will submit in a separate discussion, the use of the GTK toolkit. This toolkit would be well optimized for Gnome-based distributions, as well as providing a truly Libre toolkit solution for cross-platform versions of PolyMC. (In the spirit of the GPL 3.0 license this project uses.) This would simplify and clarify the user interface, as well as the project, and provide an opportunity to redesign the user interface. 

### Specification

Begin to separate components of the Qt framework from the functional code. Qt can still be used, but the project should become less dependent on it. 

### Drawbacks

Immediate drawbacks are not obvious to me as I'm unable to directly contribute to the code. Whichever drawbacks present themselves and are solved immediately will likely be well appreciated in the future in the event another toolkit is used. 

### Unresolved Questions

How do maintainers feel about the complexity of this task? 

### Alternatives Considered

If Qt must be used, perhaps consult interested UI/UX parties to enhance the current user interface. 

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by Scrumplex** [comment]
Not sure if this is possible in a meaningful way. Qt doesn't just provide UI, it also handles most of the backend. Even if we could get rid of the UI, most of the codebase will rely on Qt.

**Comment by K0-RR** [comment]
#219

**Comment by Zenith222** [comment]
#167

**Comment by LennyMcLennington** [comment]
Closing for similar reason to https://github.com/PolyMC/PolyMC/issues/219#issuecomment-1161137325
