### ISSUE TITLE
Use GTK Instead of Qt 

### ISSUE THREAD

**Issue by Zenith222** [PolyMC/PolyMC#321]
### Goal

Switch the application from the QT framework to the GTK.

### Motivation

GTK is well suited to Gnome-based distributions, and looks native. It's also cross-platform compatible. It also seems simpler and more streamlined being a UI toolkit instead of an entire framework, which could help with contributions in the future. (As well as making the app more optimized.) New GTK apps have a consistent, simplified, and beautiful UI/UX. This is well suited to a relatively simple yet capable app such as PolyMC.

I also believe as this project further diverges from the MultiMC project, developing a distinct UI/UX should be a key differentiator and an area of improvement. 

Here are some examples of apps from Gnome, which properly implement GTK principles. They're streamlined and simplified. 

![image](https://user-images.githubusercontent.com/26575338/159179194-0301b7c9-7b50-4093-9046-6c4f6ddd9f79.png)

![image](https://user-images.githubusercontent.com/26575338/159179261-2622a112-2473-444e-9d2d-f8afc1a12f91.png)

![image](https://user-images.githubusercontent.com/26575338/159179280-2169fb62-b93e-43ed-9e91-913d2e372ff4.png)

### Specification

Separate PolyMC from the Qt framework and then implement GTK to create the UI.

### Drawbacks

The complexity of the task could make it untenable. See my other discussion about first separating PolyMC from the Qt framework to allow for more changes in the future. 

### Unresolved Questions

How do maintainers feel about the complexity of this task? 

### Alternatives Considered

There are other toolkits to consider, but I feel GTK fits the open source spirit of this project. 

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

The applications Glade, Cambalache, and Builder (all on Flathub) would be a good place to begin experimenting with UI changes.

**Comment by obj-obj** [comment]
I'm not a PolyMC dev but ...what? Pretty sure no one wants to rewrite their entire UI in a different toolkit

**Comment by Zenith222** [comment]
To be fair, this UI was forked from MultiMC. Look 1-2 years down the line. I hope this project continues to evolve. However, we've got to consider enhancements that would make PolyMC unique. It's either going to be a stagnant worse version of MultiMC or the better version. With UI changes, it can be the better version.

**Comment by Scrumplex** [comment]
Apart from having to reimplement the UI, which is a huge task by itself, we would also need to rewrite most of the codebase. We heavily rely on Qt data structures which are not compatible with GLib and by extension GTK. 

Apart from these technical issues, GTK is not a good cross-platform toolkit. It works well on GNOME and other GTK based DEs, but it doesn't work well on Windows nor macOS. I am also not sure if GTK's minimal approach is the right way for PolyMC.

We will probably move more to KDE technologies (KDE Frameworks), which integrate very well with vanilla Qt.

**Comment by Zenith222** [comment]
I was aware the complexity was going to be a major consideration for this sort of suggestion. Thanks for bringing more clarity to the situation. 

Again, it's all a bit radical and progressive at this point in time. I don't really expect anything of this magnitude to get done with urgency, but it's at least something to consider.

**Comment by txtsd** [comment]
> going to be a stagnant worse version of MultiMC

Unlikely >_>

**Comment by Zenith222** [comment]
> > going to be a stagnant worse version of MultiMC
> 
> Unlikely >_>

Great to hear. I believe it has so much more potential.

**Comment by TheKodeToad** [comment]
This is a good suggestion in my opinion. Sort of. Only if it was additionally maintained.

I'm not a developer of this project, but that doesn't sound like it could happen. It wouldn't make sense on Windows and Mac or even the KDE desktop either, so there would still need to be a version that used QT. I have seen projects that have multiple versions with different UI toolkits, but I'm not sure if it's really plausible for this project.

**Comment by luni3359** [comment]
The aesthetic of gtk looks too barebones.

**Comment by ZekeZDev** [comment]
I am going to close this issue for now. its something we are aware of but I don't think its something we are going to consider till quite far down the line.
