### ISSUE TITLE
[Feature request] Allow mod downloads from a file.

### ISSUE THREAD

**Issue by Crec0** [PolyMC/PolyMC#325]
### Role

I play lightly modded minecraft (40-50 mods) and setting up new instances, it's kind off tedious by doing mods one by one. If someone asks for the modlist, its either same amount of pain for them or the user has to share their entire mods directory which could become very large very soon. Therefore, having a simple text file to share and allowing them to download the mods with ease is an amazing QOL feature.

### Suggestion

I want PolyMC to take file with mod names as input and then download them all based on instance version and mod loader.  

### Benefit

This will make downloading mods pretty straightforward if you already have a set list defined. List can also be easily shared instead of sharing the whole zipped mods directory.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### File format
Simple text files with mod names should be enough.
```
mod1
mod2
...
```
If possible, can also add version restrictions on them in case of known incompatibilities or known issues.  
Possibly similar to [requirements.txt format from python](https://peps.python.org/pep-0508/) Because its much more beginner friendly and easier to read.
```
mod1
mod2==2.0.3
mod3>=2.0.*; source="modrinth"
...
```

**Comment by HeyaGlitz** [comment]
:eye: :eye:
