### ISSUE TITLE
bring back non-portable windows builds

### ISSUE THREAD

**Issue by DioEgizio** [PolyMC/PolyMC#327]
### Role

i play with polymc and sometimes I use Windows 

### Suggestion

bring back non-portable windows builds. While it was on 1.1.0 for mistake, it would be cool since it makes updating easier on Windows.

### Benefit

i prefer non-portable stuff 

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by Scrumplex** [comment]
Yes. I was also thinking about this. Every user since 1.1.0 would suddenly *lose* their instances which would be very confusing probably.

**Comment by DioEgizio** [comment]
Yeah also I prefer having non-portable builds because it makes updating easier since we don't have an updater *yet*

**Comment by LennyMcLennington** [comment]
> Yes. I was also thinking about this. Every user since 1.1.0 would suddenly _loose_ their instances which would be very confusing probably.

Loose is the opposite of tight but I agree we should have both options available for Windows so people won't just lose their configuration due to that bug.

**Comment by ZekeZDev** [comment]
yeah having both is a better idea, I will put both downloads on the download page
