### ISSUE TITLE
Minecraft 4K doesn't download on PolyMC because it tries to download from multimc servers

### ISSUE THREAD

**Issue by DioEgizio** [PolyMC/PolyMC#328]
### Operating System

Windows, macOS, Linux, Other

### Description of bug

Minecraft 4K doesn't download on PolyMC because it tries to download from multimc servers
I was testing stuff and I found this 

### Steps to reproduce

Self-explanatory

### Suspected cause

missing change of link

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Scrumplex** [comment]
We might want to drop that version. We are not really allowed to distribute that JAR, nor should MultiMC be.

**Comment by DioEgizio** [comment]
Yeah but it's also true that that version is not distributed anymore by Mojang. Maybe we can just remove it

**Comment by DioEgizio** [comment]
I just noticed [it's on archive.org](https://archive.org/details/Minecraft4K)

**Comment by Heath123** [comment]
> I just noticed [it's on archive.org](https://archive.org/details/Minecraft4K)

They don't make it very clear but that's a modded version: 
> Minecraft 4k Portable is a game by Markus "Notch" Persson, and moded by Microapps Team. Attribution 4.0 International License is used to licensed on our team's work. If you are posting this moded version, please add this: Minecraft 4k Portable is licensed under the Attribution 4.0 International.

**Comment by Scrumplex** [comment]
:crab: :crab: :crab: [4k is gone](https://github.com/PolyMC/meta-polymc/commit/60bf58d42e32f5f0a7ed08d5d829ca0d03eea25b) :crab: :crab: :crab:
