### ISSUE TITLE
weird scaling on windows on latest devbuilds

### ISSUE THREAD

**Issue by DioEgizio** [PolyMC/PolyMC#331]
### Operating System

Windows

### Description of bug

weird scaling

### Steps to reproduce

open polymc and see

![immagine](https://user-images.githubusercontent.com/83089242/159495759-91d0d794-f6cb-439f-be70-0eaca9514e30.png)

this is how it looked like before: 
![immagine](https://user-images.githubusercontent.com/83089242/159495914-a6641969-823f-4ac5-8a08-1f23d846aadd.png)

### Suspected cause

#315 

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Scrumplex** [comment]
I don't see a scaling issue? The second screenshot just looks like it has a lower scale factor and smaller window

**Comment by DioEgizio** [comment]
Yeah maybe I used the wrong words but see icons and scale factor

**Comment by DioEgizio** [comment]
![IMG_20220322_144938](https://user-images.githubusercontent.com/83089242/159496622-ac7e34e9-3e0a-4433-ba80-0deda32b6c82.jpg)
Like this

**Comment by Scrumplex** [comment]
oooh

**Comment by DioEgizio** [comment]
This is kinda annoying, icons are too big and everything looks too weird

**Comment by txtsd** [comment]
It fixed #307 though. Maybe we need to use SVGs, or higher quality PNGs for those icons?

What's your scale ratio? If it was fractional before, it would've been getting rounded up to the next whole number. Which it doesn't do anymore since it respects the ratio now.

**Comment by DioEgizio** [comment]
> It fixed #307 though. Maybe we need to use SVGs, or higher quality PNGs for those icons?
> 
> What's your scale ratio? If it was fractional before, it would've been getting rounded up to the next whole number. Which it doesn't do anymore since it respects the ratio now.

125% (the default)
except the icon resolution, it looks so weird

**Comment by DioEgizio** [comment]
10p background cat lol

![immagine](https://user-images.githubusercontent.com/83089242/159643129-3cbfcd42-b49c-4eaa-8d4e-1dde2402144e.png)

**Comment by Scrumplex** [comment]
> Maybe we need to use SVGs, or higher quality PNGs for those icons?

All the icons are SVG

**Comment by txtsd** [comment]
Huh. Not sure why it's upscaling so ugly-ly then.

**Comment by DioEgizio** [comment]
https://github.com/PolyMC/PolyMC/blob/92f3154e8f7c1421541a00ae7cf57f188cfe46a5/launcher/resources/backgrounds/catbgrnd2.png the background cat is actually png

**Comment by txtsd** [comment]
https://bugreports.qt.io/browse/QTBUG-52444
https://bugreports.qt.io/browse/QTBUG-50785
https://bugs.kde.org/show_bug.cgi?id=400422

These are the same bug, I believe, but they're reported to be fixed.

@DioEgizio Can you reproduce this with the msys2 builds that use the latest Qt5?

**Comment by DioEgizio** [comment]
Yeah I think they're that bug except the kde one.
The KDE one was a plasma bug while the first two are closed as "cannot reproduce".
So probably yeah, Qt bug

**Comment by DioEgizio** [comment]
But actually, it only happens with simple colored icons

**Comment by DioEgizio** [comment]
*on every icon theme except legacy

**Comment by txtsd** [comment]
[Qt docs about High DPI Displays](https://doc.qt.io/qt-5/highdpi.html) says
> Always use the qreal versions of the [QPainter](https://doc.qt.io/qt-5/qpainter.html) drawing API.

Is this something we need to modify, with regards to the cat at least?

**Comment by DioEgizio** [comment]
idk but note that the cat is png

**Comment by txtsd** [comment]
@DioEgizio Can you try

```
set QT_SCALE_FACTOR=0
set QT_AUTO_SCREEN_SCALE_FACTOR=0

start "" "PolyMC.exe"
```

**Comment by DioEgizio** [comment]
> set QT_SCALE_FACTOR=0
> set QT_AUTO_SCREEN_SCALE_FACTOR=0
> 
> start "" "PolyMC.exe"

yes that fixes

**Comment by DioEgizio** [comment]
![immagine](https://user-images.githubusercontent.com/83089242/168414411-fadbd96d-fccf-4105-bd3a-b44ad79c05dd.png)
 with that


![immagine](https://user-images.githubusercontent.com/83089242/168414423-7f5335e9-71a8-453c-b466-f0a8c9558274.png)
without that

**Comment by txtsd** [comment]
Is it just disabling fractional scaling? Is this how it looked before the fractional scaling PR?

**Comment by DioEgizio** [comment]
yeah

**Comment by txtsd** [comment]
Oh derp. It's not really a solution then. I'm not sure how to proceed.

**Comment by pyanmcbride** [comment]
I have this same problem. Any updates on this?

**Comment by txtsd** [comment]
> ```
> set QT_SCALE_FACTOR=0
> set QT_AUTO_SCREEN_SCALE_FACTOR=0
> 
> start "" "PolyMC.exe"
> ```

@pyanmcbride You could try this until Qt6 builds are ready.
