### ISSUE TITLE
Title bar has duplicated name.  

### ISSUE THREAD

**Issue by Zenith222** [PolyMC/PolyMC#335]
### Operating System

Linux

### Description of bug

The title bar is inconsistent. It shows PolyMC twice. It also uses - and — within the same line of text, which is inconsistent. The version number is extremely long and seems unnecessary because it could be moved to a menu instead. 

![DFF41764-2729-407B-8DE4-C2126E823CB5](https://user-images.githubusercontent.com/26575338/159692044-d7c514fb-b5f3-4ced-9746-5a96ea21666f.png)

### Steps to reproduce

Install PolyMC. Use PolyMC. 

### Suspected cause

This seems to have been carried over from MultiMC. 

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by K0-RR** [comment]
Previously mentioned in https://github.com/PolyMC/PolyMC/issues/264#issuecomment-1066769634.

**Comment by Scrumplex** [comment]
This is a relic from MultiMC. Not sure why it's there tbh.

**Comment by obj-obj** [comment]
> This is a relic from MultiMC. Not sure why it's there tbh.

It's because the desktop environment usually shows the application name after the title, which is causing the second "PolyMC"

**Comment by flowln** [comment]
Seems to me that fixing this is just a matter of changing this line, so if anyone want to contribute go ahead :^) https://github.com/PolyMC/PolyMC/blob/fd7745cbebf55f5bcfccc16500fff0e67a789169/launcher/ui/MainWindow.cpp#L833

**Comment by forkiesassds** [comment]
This seems to be caused by the app name which is used when the window has no name, as seen here.

Top: App name
Bottom: Window name
![image](https://user-images.githubusercontent.com/54495659/168392911-b30271ed-b543-4ce2-b80f-5e4fb46d2620.png)
EDIT: Turns out it's using the main window's title bar, but the desktop environment has no clue it has the programs name, so it cluelessly adds the programs name, to a title that already has the program's name in it. This issue may be solved if the version was removed from the title bar.

EDIT 2: Ok, I'm a bit wrong. It turns out desktops like Gnome do actually use the programs name, but I'm not so sure why in the world its happening like this.
![image](https://user-images.githubusercontent.com/54495659/173424519-f687a95d-e1f0-47b8-a394-5f79cab86958.png)
EDIT 3: It turns out it uses the display name and appends to every window name.

**Comment by forkiesassds** [comment]
Turns out this is caused by this line, removing it fixes the issue.
https://github.com/PolyMC/PolyMC/blob/349fc4143d4c83c50aa6340bbe7dc537a6fbf949/launcher/Application.cpp#L229

**Comment by jn64** [comment]
Qt is the one appending the applicationDisplayName to the window title. Not the DE.

Simple test, compare other Qt and non-Qt apps on your DE. Or set the window title yourself and see:

```shell
$ polymc -qwindowtitle "Real fake window title"
```

So when setting the window title, don't include the application name.

Qt behaviour might differ by platform though.

**Comment by forkiesassds** [comment]
> Qt behaviour might differ by platform though.

It is! Especially comparing other Linux desktops, and the behaviour of the display name changed around QT 5, which means this could be a leftover from when MultiMC used QT4.

**Comment by Scrumplex** [comment]
Now the important question would be: What do we change the main window title to?

`<program name> <version>` seemed practical. Maybe we should just change it to `Instances` and Qt will add ` - PolyMC` at the end. We might put the version into the statusbar or something like that

**Comment by jn64** [comment]
Does version number have to be visible on the main window? I think it's better in the Help > About (but it should be text selectable there, it currently isn't)

**Comment by Scrumplex** [comment]
> Does version number have to be visible on the main window? 

It is pretty helpful for support, as most people will just send screenshots and which means you can quickly see what version they are on

**Comment by jn64** [comment]
In that case how about set applicationDisplayName to `PolyMC <version>`, so every window has the version number. Since some screenshots will be of other windows than the main window.

Can shorten it to `v1.3.2` rather than `Version 1.3.2`, or even just `1.3.2`

**Comment by Zenith222** [comment]
How about the version number is removed from the title bar completely? It seems pretty unnecessary for such a stable piece of software. No other software does this. It's clutter and it should go. In my opinion the "but sometimes people will share screenshots with the version number" argument is extremely weak. The version number should be moved elsewhere.
