### ISSUE TITLE
mod categories/folders

### ISSUE THREAD

**Issue by sybenx** [PolyMC/PolyMC#338]
### Role

sorting and keeping track of mods

### Suggestion

folders or sections in the mods list

### Benefit

keep track of which incompatible mods i'm using (e.g. which sound physics mods i'm using/have installed)

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

i have sound physics remastered and simple voice chat installed and want to try "resounding" mod. To try it i must disable sound physics remastered and simple voice chat as they are incompatible with resounding.

I already have a large list of mods, some disabled. To keep track of which mods are incompatible with Resounding, some kind of folder or category system would allow me to associate these three mods.

**Comment by Scrumplex** [comment]
I think we already have this request in #120.

**Comment by txtsd** [comment]
@Syberiyxx Does the linked issue describe what you want? If so, this can be closed as duplicate.

**Comment by sybenx** [comment]
Ya
