### ISSUE TITLE
[Feature] [Pastebin Service] Support mclo.gs as a pastebin service

### ISSUE THREAD

**Issue by Merith-TK** [PolyMC/PolyMC#342]
### Role

Play and Maintain Modpacks

### Suggestion

use mclo.gs as an pastebin service for logs

### Benefit

easier way for people to read logs

### This suggestion is unique

- [x] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

https://mclo.gs/

Legit, makes uploading and reading logs easier as they automatically censor information such as IP addresses and Computer Usernames, 

here is an example from my vanilla+ modpack
https://mclo.gs/sShksYb

I am mainly suggesting this as people are hesitant to send me, and other admins their logs due to the fact that the logs, more often than not, contain private information such as their name, and using mclo.gs as an option allows people to feel safe sending me and other server admins/modpack maintainers their logs

**Comment by oynqr** [comment]
The correct way to implement this is to make PolyMC exclude possibly identifying information from logs itself, not trusting a random company to do it for you.

**Comment by Merith-TK** [comment]
They are [[Github Repo] fully open source](https://github.com/aternosorg/mclogs), so you are fully capable of running your own instance of `mclo.gs` on polymc.org

**Comment by DioEgizio** [comment]
I think this should be considered, mslo.gs is open source too but it's a lot better for Minecraft logs

**Comment by kthchew** [comment]
Is there any case where your public IP address is outputted in the logs? From the example you give, the only censored IPs that I found were:

```
authserver.mojang.com resolves to:
    [**.**.**.**, **.**.**.**, **.**.**.**, **.**.**.**]

session.minecraft.net resolves to:
    [**.**.**.**, **.**.**.**, **.**.**.**]

textures.minecraft.net resolves to:
    [**.**.**.**, **.**.**.**, **.**.**.**, **.**.**.**]

api.mojang.com resolves to:
    [**.**.**.**, **.**.**.**, **.**.**.**, **.**.**.**]
```

...which is not personal information (they're Mojang's IPs) and may just make troubleshooting harder, and this:

```
[12:03:16] [main/WARN]: Mod `xaerominimapfair` (**.**.**.**) uses more dot-separated version components than SemVer allows; support for this is currently not guaranteed.
[12:03:16] [main/WARN]: Mod `xaeroworldmap` (**.**.**.**) uses more dot-separated version components than SemVer allows; support for this is currently not guaranteed.
```

...which is a false positive, and again, may make troubleshooting harder in some cases.

Hiding the username makes sense though. But I agree that it should be done client-side, before the log is sent off-device.

**Comment by Merith-TK** [comment]
the main reason is that mclo.gs *actually colors the logs* to make it readable and easily able to spot warnings and errors rather than scrolling for five minutes, looking at monochrome text. 

It makes it easier for people to actually *read* the damned logs
