### ISSUE TITLE
[Feature] [Release Platform] portableapps.com release

### ISSUE THREAD

**Issue by Merith-TK** [PolyMC/PolyMC#343]
### Role

I play minecraft on the go

### Suggestion

have an official release for portableapps

### Benefit

minecraft portable, but better

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

https://portableapps.com/

literally just provide an portableapps platform release,

**Comment by RuinTD** [comment]
I got a PortableApps.com version of PolyMC working but getting it fully portable relies on either #7 or #284. I'm able to automatically handle the global Java path setting, but not the overridden setting for individual instances. #357 is also needed for MultiMC to detect jPortable or any other Java versions installed via PortableApps, which is needed to make it truly portable.

**Comment by Merith-TK** [comment]
well, all it would need to check for, for a portableapps java, is `<DRIVE_ROOT>:/PortableApps/CommonFiles/Java64/<rest of java path I dont remember>`

and then it would have java 8, since java 17 isnt on portableapps yet

**Comment by RuinTD** [comment]
> well, all it would need to check for, for a portableapps java, is `<DRIVE_ROOT>:/PortableApps/CommonFiles/Java64/<rest of java path I dont remember>`

I don't have control over the PolyMC code. The most I can do is provide possible Java locations to the `POLYMC_JAVA_PATHS` environment variable, but it's bugged on Windows; hence #357.

```ini
[Environment]
POLYMC_JAVA_PATHS=%JAVA_HOME%\bin\javaw.exe;%PAL:PortableAppsDir%\CommonFiles\Java\bin\javaw.exe;%PAL:PortableAppsDir%\CommonFiles\Java64\bin\javaw.exe;%PAL:PortableAppsDir%\CommonFiles\JDK\bin\javaw.exe;%PAL:PortableAppsDir%\CommonFiles\JDK64\bin\javaw.exe;%PAL:PortableAppsDir%\CommonFiles\OpenJDK\bin\javaw.exe;%PAL:PortableAppsDir%\CommonFiles\OpenJDK64\bin\javaw.exe;%PAL:PortableAppsDir%\CommonFiles\OpenJDKJRE\bin\javaw.exe;%PAL:PortableAppsDir%\CommonFiles\OpenJDKJRE64\bin\javaw.exe
```

EDIT: Also, PortableApps can automatically provide apps with the path to jPortable using %JAVA_HOME%

> and then it would have java 8, since java 17 isnt on portableapps yet

Yes it is. It's under [OpenJDK](https://portableapps.com/apps/utilities/OpenJDK).

![](https://files.catbox.moe/869p4s.png)

**Comment by Merith-TK** [comment]
oohh... they should really rename those better

**Comment by RuinTD** [comment]
A community maintained PortableApps.com release can now be downloaded here:

https://faynealdan.github.io/PolyMCPortable/

**Comment by txtsd** [comment]
Can this be closed now?

**Comment by Merith-TK** [comment]
ye
