### ISSUE TITLE
libqt5xml5 should be a dependency of the MPR version

### ISSUE THREAD

**Issue by Un1q32** [PolyMC/PolyMC#350]
### Operating System

Pop_OS! 21.10

### Description of bug

When installing PolyMC from the MPR, it didn't automaticly install `libqt5xml5`, even though PolyMC cannot launch without it.

### Steps to reproduce

Install PolyMC from the MPR without having `libqt5xml5` installed.
Attempt to launch PolyMC.
Get error `polymc: error while loading shared libraries: libQt5Xml.so.5: cannot open shared object file: No such file or directory`

### Suspected cause

You forgot to add `libqt5xml5` as a dependency.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by d-513** [comment]
I don't know how this happened, I test these on a clean Debian VM.

Anyways I'll push an update quickly

**Comment by d-513** [comment]
Updated all packages.

**Comment by Un1q32** [comment]
> I don't know how this happened, I test these on a clean Debian VM.

I'm on Pop OS so maybe debian has libqt5xml5 by default but Pop OS doesn't.
