### ISSUE TITLE
Troubles with running Forge on MC 1.1

### ISSUE THREAD

**Issue by Rafii2198** [PolyMC/PolyMC#362]
### Operating System

Windows, Linux

### Description of bug

I don't know if this is a problem with Poly or what but whenever I try to create or join a world on Minecraft 1.1 with Forge, it just crashes. Here is the log https://0x0.st/oqjy.txt

Again these are very old times, I don't know if I am doing something wrong or it is something with Poly.

### Steps to reproduce

* Create new 1.1 instance
* Add any Forge version
* Launch and Create/Join a world
* Crash

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by timoreo22** [comment]
I think you need to add ModLoader

**Comment by forkiesassds** [comment]
Using the Install Forge feature works perfectly fine, or you could simply install ModLoader.

**Comment by glowiak** [comment]
Install ModLoader: https://mcarchive.net/mods/modloader

**Comment by Rafii2198** [comment]
Adding ModLoader worked, thanks! I had no idea about it. (literally, I didn't even have computer when this version released, yet alone knowing about Minecraft)
