### ISSUE TITLE
Linux, Minecraft 1.8.9, mouse doesn't lock to game after alt+tab on multi-monitor setups.

### ISSUE THREAD

**Issue by Regular-Baf** [PolyMC/PolyMC#369]
### Operating System

Linux

### Description of bug

This issue doesn't seem to be present in newer versions, so I'm not even sure if it's launcher issue but I thought it was worth reporting anyway just in case it can be fixed.

### Steps to reproduce

On the plasma desktop, pretty sure this happens on both x11 and wayland. Alt+tab from Minecraft 1.8 and then Alt+tab back and the cursor fails to lock to the window on multi-monitor setups.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Scrumplex** [comment]
This is most certainly an issue with the game not the launcher

**Comment by Regular-Baf** [comment]
is it an issue the launcher could fix though? it is rather annoying.

**Comment by dajix350** [comment]
This has nothing to do with the launcher, it happened to me on the default launcher and GDL. There are probably mods to properly fix this, but I generally just turn off full screen before alt tabbing, and turn it back on when I go back to the game window.

**Comment by ZekeZDev** [comment]
@Regular-Baf this happens even with official launcher the only way to fix it is "borderless fullscreen" or "windowed fullscreen" mods. As this issue is out of the hands of PolyMC I am going to close it.
