### ISSUE TITLE
Most 1.16.5 forge verisons dont launch

### ISSUE THREAD

**Issue by binturongx10** [PolyMC/PolyMC#372]
### Operating System

Windows

### Description of bug

Forge versions for 1.16.5 prior to 36.2.26 fail to start when installed through the launcher When useing java version above 8 312
[debug.log](https://github.com/PolyMC/PolyMC/files/8383265/debug.log) 
[latest.log](https://github.com/PolyMC/PolyMC/files/8383266/latest.log)

### Steps to reproduce

create a 1.16.5 instance
set java to version above 8 312
install a forge version prior to 36.2.26
launch instance

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by DioEgizio** [comment]
> create a 1.16.5 instance
install a forge version prior to 36.2.26
launch instance

use java 8u312 or inferior there

**Comment by binturongx10** [comment]
Upon closer inspection this appears to be a forge issue rather than a polymc issue as it also happens under gdlauncher

**Comment by DioEgizio** [comment]
It's not a polymc issue, it's a forge moment

**Comment by DioEgizio** [comment]
We can't do anything about it
