### ISSUE TITLE
Modrinth does not have a usable URL in the mod downloader

### ISSUE THREAD

**Issue by HarryPeach** [PolyMC/PolyMC#374]
### Operating System

Linux

### Description of bug

There is no way to navigate to a mods page when installing mods from Modrinth.

### Steps to reproduce

1. Select an instance
2. Select "View Mods"
3. Select "Download mods"
4. Select a mod from the Modrinth page, the title of the mod does not link to the mods page

### Suspected cause

When setting the ```websiteUrl``` field of a ```IndexedPack``` object, it seems to be set to the field "page_url" which doesn't seem to exist in the [Modrinth API](https://docs.modrinth.com/api-spec/#operation/getProject).

https://github.com/PolyMC/PolyMC/blob/e22d54abd35560213377bb41f2bc902f67c8de64/launcher/modplatform/modrinth/ModrinthPackIndex.cpp#L15

The URL could instead by created using the ```slug``` field and appending it to "https://modrinth.com/mod/{slug}"

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by DioEgizio** [comment]
> When setting the websiteUrl field of a IndexedPack object, it seems to be set to the field "page_url" which doesn't seem to exist in the Modrinth API.

It was actually a relic that wasn't fixed with the API V2 migration
