### ISSUE TITLE
[Bug] all world size give the saves size

### ISSUE THREAD

**Issue by kylianpl** [PolyMC/PolyMC#386]
### Operating System

Linux

### Description of bug

The world size should be per world but all world has the size of the saves folder
![image](https://user-images.githubusercontent.com/66625058/161375801-67b1e5d5-ed01-4af2-ab4a-3350e29396ed.png)

### Steps to reproduce

1. open polymc
2. create multiple worlds
3. click manage worlds

### Suspected cause

Linux ?

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by DioEgizio** [comment]
@Scrumplex ⚠️

**Comment by Scrumplex** [comment]
I might have done an oopsie.
