### ISSUE TITLE
The F3 Debug screen still says "MultiMC5" in the top left corner

### ISSUE THREAD

**Issue by Firlaev-Hans** [PolyMC/PolyMC#39]
![PolyMC_Debug_MultiMC5](https://user-images.githubusercontent.com/61254500/148697307-5188bcf1-74ee-4345-8988-c8b1061692bf.jpg)
Just something I noticed, this should probably say PolyMC instead

**Comment by ghost** [comment]
known and will be fixed in more "rebranding"
