### ISSUE TITLE
add support for modrinth modpacks

### ISSUE THREAD

**Issue by DioEgizio** [PolyMC/PolyMC#393]
### Role

I use polymc and I like modrinth 

### Suggestion

Support for modrinth modpacks. Note that mr modpacks are not complete yet, so a search filter can't be really implemented at the time of writing, but there are modpacks but unlisted, see https://modrinth.com/modpack/fabulously-optimized for example

### Benefit

better 

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

(this was a feature request for a long time but i wanted to make an issue to track it).

**Comment by ranger10700** [comment]
@Scrumplex Should this stay open until released? Or do you prefer to stop tracking issues at time of code? Just curious, excited to take a look at Modrinth modpacks in PolyMC :D

**Comment by txtsd** [comment]
> Should this stay open until released? Or do you prefer to stop tracking issues at time of code? Just curious, excited to take a look at Modrinth modpacks in PolyMC :D

We close issues automatically when we merge related code.

**Comment by Scrumplex** [comment]
@ranger10700 we generally just auto-close issues once the corresponding pull request is merged. I guess you can just subscribe to new Releases on GitHub to get notified once a new version releases.
