### ISSUE TITLE
Toggleable Options for upgrading mods seperated from modpacks

### ISSUE THREAD

**Issue by RaptaG** [PolyMC/PolyMC#394]
### Role

I'd like being able to easily upgrade my mods

### Suggestion

Have an upgrade button for mod (I'm not talking for modpacks, meaning not a duplicate of #324, but for mods seperated from modpacks)

### Benefit

Easier upgrading mods

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

This is a feature of CurseForge Launcher & GDLauncher, which would be very useful for PolyMC. The mods can be detected by the instance's mod list.

**Comment by DioEgizio** [comment]
duplicate of #274

**Comment by RaptaG** [comment]
oops
