### ISSUE TITLE
Steam Deck: Importing instance from zip is broken in Gaming Mode

### ISSUE THREAD

**Issue by zack-emmert** [PolyMC/PolyMC#396]
### Operating System

Linux

### Description of bug

When running PolyMC in Gaming Mode on the Steam Deck, I cannot import modpacks via zip files because the file chooser never appears. I click on New Instance > Import from zip > Browse, and the file chooser never appears and I can no longer interact with the launcher until I restart PolyMC.

### Steps to reproduce

1. Install & configure PolyMC on a Steam Deck
2. Launch PolyMC from Gaming Mode
3. Click on New Instance > Import from zip > Browse

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Scrumplex** [comment]
I don't think there is much we can do here. Steam OS's gaming mode does not provide any xdg-desktop-portal interfaces AFAICT. Inside Flatpak those are a necessity.

**Comment by sonicer105** [comment]
I actually have this issue in desktop mode as well. Got my steam-deck today and the dialog will not open for zip import

**Comment by txtsd** [comment]
Does it crash? If it does it's probably the same as #248. It's the same behavior for me.

**Comment by sonicer105** [comment]
So the strangest thing just happened. I went to try and reproduce #248 and found that not only did that work fine (no crash), now all the other file dialogues are also working (import zip, instance folder browse). I can no longer reproduce my issue.

**Comment by zack-emmert** [comment]
I've discovered that adding `--env=QT_QPA_PLATFORMTHEME=kde --env=XDG_CURRENT_DESKTOP=KDE` as launch parameters in the Steam game options will make the KDE file selection window show up in gaming mode as an adequate work around. These env variables will also make PolyMC use the breeze dark theme.

**Comment by d-513** [comment]
Wish valve released SteamOS so I could debug it. Would setting the env vars using the flatpak's wrapper script if steam deck is detected be good? Would also make it less ugly and look like in desktop mode

**Comment by Scrumplex** [comment]
> Wish valve released SteamOS so I could debug it. Would setting the env vars using the flatpak's wrapper script if steam deck is detected be good? Would also make it less ugly and look like in desktop mode

that's an ugly hack IMO. This should be fixed by Valve

**Comment by d-513** [comment]
> > Wish valve released SteamOS so I could debug it. Would setting the env vars using the flatpak's wrapper script if steam deck is detected be good? Would also make it less ugly and look like in desktop mode
> 
> that's an ugly hack IMO. This should be fixed by Valve

then get valve to fix it /:

**Comment by Scrumplex** [comment]
Closing this, as this is not something we can fix.
