### ISSUE TITLE
Instances cannot be renamed by pressing enter/return on the keyboard

### ISSUE THREAD

**Issue by kthchew** [PolyMC/PolyMC#399]
### Operating System

macOS (Edit: tested on Linux, and enter just opens the instance instead. This seems to be a macOS specific bug. Which makes sense, cause enter to rename seems to be a platform-specific thing.)

### Description of bug

When pressing enter while an instance is selected, you enter rename mode (so you can type to rename an instance), but when you let go of enter, rename mode immediately exits. The effect is that if you tap enter, the name of the instance just flashes and you can't really rename it.

Expected behavior:
Pressing enter allows you to type to rename the instance and then press enter again to confirm your change

Actual behavior:
"Rename mode" is active while enter is being held down, but is exited once you let go of the enter key, so you can't actually rename the instance unless you hold down enter while you type the new name.

### Steps to reproduce

1. Open PolyMC.
2. Select an instance. (Or, create an instance if no instances exist.)
3. Press enter on the keyboard.

### Suspected cause

https://github.com/PolyMC/PolyMC/blob/8bc6cdf55c143313616aefe12a3c8bf7f0b67557/launcher/ui/instanceview/InstanceDelegate.cpp#L360-L376

When enter is first depressed, it enters rename mode, and when it is released, it seems to register again and exit rename mode.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by txtsd** [comment]
@kthchew Can you try the [build from here](https://github.com/txtsd/PolyMC/actions/runs/2188960766)?

It should only trigger rename on KeyDown, not KeyUp.
