### ISSUE TITLE
Implement the menu bar

### ISSUE THREAD

**Issue by kthchew** [PolyMC/PolyMC#401]
### Role

I use PolyMC on macOS

### Suggestion

I'd like actions to be present on the menu bar

### Benefit

Pretty much all other apps on macOS have actions on the menu bar, so this enhancement means PolyMC no longer would be the odd one out, and it would feel like it integrates a little better with the OS. In addition, the OS allows me to set custom keyboard shortcuts for actions in the menu bar (see below for example).

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

For reference, this is what the menu bar looks like now on macOS (pretty much empty, only includes default stuff):
<img width="587" alt="old" src="https://user-images.githubusercontent.com/79120643/161902882-41a57e52-6e93-44f5-92f6-fd3d83c0a99e.png">

I've made a mock-up to demonstrate what I'm talking about (the keyboard shortcuts were chosen arbitrarily for this mock-up, as Qt lets you choose keyboard shortcuts for `QAction`s, which show up nicely in the menu bar):

https://user-images.githubusercontent.com/79120643/161902922-b103554a-6816-491b-a77e-7d2c0124050f.mov

As for the second benefit I mentioned above (custom keyboard shortcuts), an example of this would be that I could go into macOS settings and say that I want to use "Ctrl + G" for the "Open Config Folder" action, since it's in the menu bar, without requiring any other intervention from PolyMC other than providing the option in the menu bar.

I don't have much functionality implemented in my mock-up yet, but I could work more on it and open a PR for this if this request is approved.

----

On systems without a native menu bar (e.g. Windows and most Linux DE's), the menu bar would be on the top of the window. Since there's already a tool bar up there, it probably wouldn't make sense to show them both next to each other most of the time. For these systems, I propose that the menu bar be hidden by default, but a user can press the 'alt' key on their keyboard to show or hide it. Many other apps do this (if you want an example, try opening a Firefox window and pressing 'alt'). If keyboard shortcuts are added with this change, then users could do this so they could get a hint of what the shortcuts are.

The menu bar itself can also be navigated more easily than the tool bar with just the keyboard on Windows and Linux, so this change can benefit users on those OS's as well who like to use the keyboard even without shortcuts:

https://user-images.githubusercontent.com/79120643/161908624-a42d58be-0cc0-4b2f-be96-b76d97c911d4.mov

**Comment by ZekeZDev** [comment]
I dont personally use mac os but I do like the idea of shortcuts and hiding the menu I think as we start to follow a more user friendly design it would be beneficial and having shortcuts for power users is a great idea.

**Comment by glowiak** [comment]
On menubar systems it would be good, but on those that don't have a top menubar, it just looks bad

**Comment by kthchew** [comment]
> On menubar systems it would be good, but on those that don't have a top menubar, it just looks bad

Yeah agreed. That’s why I suggested hiding it by default (so the UI looks the same as it does now) but only showing it once someone presses the “alt” key. Since some other apps follow this convention, I think someone who wants a menu bar (e.g. for easier keyboard navigation) would be able to find it, but for most regular users who mostly use the mouse, they won’t see it.
