### ISSUE TITLE
make the polymc logo an instance icon

### ISSUE THREAD

**Issue by DioEgizio** [PolyMC/PolyMC#402]
### Role

i use PolyMC

### Suggestion

Probably many of you know, but MultiMC had an icon called Infinity which was default and that was basically the multimc logo, but got removed with debranding. What I'm asking here is that but with the PolyMC logo

### Benefit

more cool

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by ZekeZDev** [comment]
Hmm I dont see this as a major change its up to the others

**Comment by HalJordan** [comment]
While I feel the icons are needed, it really pisses me off that none of the packs I try to install include a logo, or they don't do it in the right way, so I have to go in and manually set them every time.
