### ISSUE TITLE
Quilt support

### ISSUE THREAD

**Issue by clarfonthey** [PolyMC/PolyMC#406]
### Role

Some mods are planning to switch to Quilt over Fabric.

### Suggestion

PolyMC should support Quilt in addition to Forge and Fabric

### Benefit

Because it's required for these mods.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

[Quilt is going into beta soon](https://quiltmc.org/blog/2022/03/22/quilt-enters-beta/) and [Modrinth has pledged to support them on release day](https://twitter.com/modrinth/status/1502436206616842243?s=20&t=PxE0BMJawqa0iTjejrratg), so, it makes sense for PolyMC to consider supporting Quilt at some point in the future. Some mods are already considering switching to Quilt exclusively (not guaranteeing Fabric support), and it would be good to support Quilt and its community.

**Comment by DioEgizio** [comment]
#185

**Comment by DioEgizio** [comment]
It's basically already supported, waiting for beta release

**Comment by clarfonthey** [comment]
This is what I get for only searching issues and not PRs. -___-
