### ISSUE TITLE
Java arguments in instance settings have hard-to-read colors

### ISSUE THREAD

**Issue by kthchew** [PolyMC/PolyMC#410]
### Operating System

macOS

### Description of bug

In instance settings, the java arguments text box has gray text on a black background in dark mode, making it hard to read.
<img width="812" alt="Screen Shot 2022-04-07 at 6 28 20 PM" src="https://user-images.githubusercontent.com/79120643/162329954-e0e113eb-4afd-470f-9fe0-49988f69357b.png">

The system dark mode is enabled, PolyMC colors are set to "system"

Edit: not dark mode specific, the text is light gray in light mode
<img width="812" alt="Screen Shot 2022-04-07 at 6 37 17 PM" src="https://user-images.githubusercontent.com/79120643/162330813-14a283e0-cdc9-446a-a6d3-47e95df78a47.png">

### Steps to reproduce

1. Select an instance
2. Select "Edit Instance"
3. Select the Settings tab
4. Check the "Java arguments" box and type in some arguments

### Suspected cause

Qt? I can't reproduce the issue when building with Qt 5.15, but PolyMC 1.1.1-bd60c549 from the website does have the issue. Not sure which Qt version exactly fixes this, though.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by DioEgizio** [comment]
> Qt? I can't reproduce the issue when building with Qt 5.15, but PolyMC 1.1.1-bd60c549 from the website does have the issue. Not sure which Qt version exactly fixes this, though.

PolyMC CI currently uses Qt 5.12.12 on macos to keep macos sierra compat, since i didn't find major issues with it personally, and i didn't find anything actually valuable for updating (tho i have a branch with qt 5.15.3 on my fork).
I didn't notice that was fixed with newer Qt. Actually, I didn't notice it was a bug at all lol
