### ISSUE TITLE
Icons cut off

### ISSUE THREAD

**Issue by techyporcupine** [PolyMC/PolyMC#416]
### Operating System

Linux

### Description of bug

Parts of application are cut off. It used to work.
[Image of issue](https://i.cb-tech.me/ZyXZZ1bQGTf7ERuWr4b.png)

### Steps to reproduce

* Install PolyMC
* Open PolyMC

### Suspected cause

No Idea

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Scrumplex** [comment]
This could be an issue with your Qt platform theme (QGnomePlatform?)

**Comment by techyporcupine** [comment]
How would I tell if that is the issue?

**Comment by Scrumplex** [comment]
Maybe you can try changing the theme/style in the settings to something other than `System` and see if it changes things.

**Comment by techyporcupine** [comment]
I'll see if I can navigate to settings.

**Comment by techyporcupine** [comment]
After changing the theme between dark, custom and bright, nothing changes.

**Comment by txtsd** [comment]
Is this still happening? Do you use qt5ct or qvantum?

**Comment by Model11MKE** [comment]
I had the same problem as yours, turns out the problem is caused by the [Scaling Factor](https://i.imgur.com/N8C0PKN.png)  you'd find inside of "Gnome Tweaks", you ought to leave it at default (1.00 Scale) for PolyMC to look normal again. :)

**Comment by techyporcupine** [comment]
Thank you so much @Model11MKE, that fixed it!
