### ISSUE TITLE
Discord Rich Presence Support

### ISSUE THREAD

**Issue by waddon1** [PolyMC/PolyMC#421]
### Role

Modpack Developer

### Suggestion

Implement flatpak permissions to allow discord rich presence to function

### Benefit

It can help people discover modpacks and see when other people are playing on a server

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

I'm not the most technical person, so I don't know how achievable this is, but there are instructions here: https://github.com/flathub/com.discordapp.Discord/wiki/Rich-Precense-(discord-rpc) A lot of modpacks implement discord rich presence with mods and I think it would be good if this worked when using flatpaks particularly for devices like the Steam Deck

**Comment by luni3359** [comment]
I think you accidentally closed the issue

**Comment by waddon1** [comment]
> 

There was already one open on the PolyMC flathub repo
