### ISSUE TITLE
Minecraft Java profile acquisition failed.

### ISSUE THREAD

**Issue by ghost** [PolyMC/PolyMC#422]
### Operating System

Linux/Flatpak

### Description of bug

Logging into an original unmigrated account results in the message "Minecraft Java profile acquisition failed."

### Steps to reproduce

- Go to the accounts page and click "Add Mojang", logging in with the username and password of the account.

### Suspected cause

A similar issue in MultiMC resulted in some discussion where folks reported that logging in with other launchers still worked, and that this was a MultiMC specific issue.

I have successfully used this account before many times in both MultiMC and PolyMC without issue, it was only today I received the message for the first time.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by forkiesassds** [comment]
Perhaps M$ has forced you to migrate to a M$ account, since I'm having the same issue.

Edit: Seems to be the case.
```   19.447 D AuthFlow: "Fetching the Minecraft profile."
   19.713 W AuthRequest::onRequestError: Error 201
   19.713 W AuthRequest::onRequestError: Error string:  "Error transferring https://api.minecraftservices.com/minecraft/profile - server replied: Forbidden"
   19.713 W AuthRequest::onRequestError: HTTP status 403 "Forbidden"
   19.713 D ""
   19.713 W Error getting profile:
   19.713 W  HTTP Status:         403
   19.713 W  Internal error no.:  QNetworkReply::ContentAccessDenied
   19.713 W  Error string:        "Error transferring https://api.minecraftservices.com/minecraft/profile - server replied: Forbidden"
   19.713 W  Response:
   19.714 W ""
   19.714 C Task "MojangLogin(0x1f344ec5ca0)" failed:  "Minecraft Java profile acquisition failed."```

**Comment by DioEgizio** [comment]
> ### Operating System
> 
> Linux/Flatpak
> ### Description of bug
> 
> Logging into an original unmigrated account results in the message "Minecraft Java profile acquisition failed."
> ### Steps to reproduce
> 
>     * Go to the accounts page and click "Add Mojang", logging in with the username and password of the account.
> 
> 
> ### Suspected cause
> 
> A similar issue in MultiMC resulted in some discussion where folks reported that logging in with other launchers still worked, and that this was a MultiMC specific issue.
> 
> I have successfully used this account before many times in both MultiMC and PolyMC without issue, it was only today I received the message for the first time.
> ### This issue is unique
> 
>     * [x]  I have searched the issue tracker and did not find an issue describing my bug.

I'd say Mojang just removed Mojang Auth from your account and you need to migrate

**Comment by forkiesassds** [comment]
> I'd say Mojang just removed Mojang Auth from your account and you need to migrate

I can't migrate because I do not have access to the email, don't know the security questions and I don't have the transaction ID.

**Comment by DioEgizio** [comment]
We can't do much about it, it doesn't depend on us but mojang

**Comment by forkiesassds** [comment]
> We can't do much about it, it doesn't depend on us but mojang

Account isn't even mine.

**Comment by DioEgizio** [comment]
Again, not something that can be fixed by PolyMC

**Comment by ZekeZDev** [comment]
Im closing this issue as its unrelated to PolyMC discussion can be continued in #427.
