### ISSUE TITLE
openSUSE Tumbleweed package in Copr has broken dependency.

### ISSUE THREAD

**Issue by DWW256** [PolyMC/PolyMC#423]
### Description of bug

Attempting to update PolyMC to 1.1.1-2 on openSUSE Tumbleweed using the Copr repo/package results in the following error:
`Problem: nothing provides 'qt5-qtimageformats' needed by the to be installed polymc-1.1.1-2.suse.tw.x86_64`

### Steps to reproduce

1. Download openSUSE Tumbleweed
2. Add Copr repo with priority <99
3. Manually add the GPG key because Copr/Zypper interoperability is lame I guess
4. Try to install the package
5. Get the same message I just did, probably :(((

### Suspected cause

I think that someone accidentally added a dependency from Fedora that either isn't in openSUSE or has a different name.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Jan200101** [comment]
I'm the one to blame here.
Fedora and openSUSE have different naming schemes for packages and thus this kind of issue slips in.

In this case it should have been `libqt5-qtimageformats`.

There will be a fixed build somewhere along the day

**Comment by DWW256** [comment]
New broken dependency: `libqt5-qtsvg`

**Comment by Jan200101** [comment]
Hmm that is weird since openSUSE reports that to be a valid package https://software.opensuse.org/package/libqt5-qtsvg

**Comment by Jan200101** [comment]
issue has been fixed
openSUSE only provides a `libqt5-qtsvg-devel` with the real library package being `libQt5Svg5`
strange choice

**Comment by DWW256** [comment]
Always strange how openSUSE uses capitals in packages sometimes.  After poking around on r/opensuse, I determined that this can be checked by enabling the source repos in an openSUSE install and then looking up package info for the build-only package.  Feel free to @ me or whatever if you need my help with this in the future (although I guess I might be the first one to notice!)
