### ISSUE TITLE
Offline Mode Support

### ISSUE THREAD

**Issue by bexnoss** [PolyMC/PolyMC#43]
### Role

I play vanilla and modded Minecraft.

### Suggestion

Add offline mode support.

### Benefit

Makes it possible to play with unavailable username, for example just "firstname" instead of "Xx_firstname420_xX".

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

## Preamble

I own many Minecraft accounts. Some are from the time they were ten bucks during alpha, some were bought in a physical store where you buy a piece of plastic with a code on it. I am not interested in playing "cracked" Minecraft for free. I am only interested in the officially supported and blessed offline mode.

## Offline Mode

The vanilla Minecraft server includes an offline mode. If this mode is selected the server does not authenticate connecting players through the Mojang account system and allows any compatible client to connect. The existence of this mode proves that offline mode servers and the accompanying offline mode clients are a officially supported use-case.

## (Dis)Advantages of Offline Mode

The big advantage of offline mode is that players may choose any name they desire. For example just "firstname" instead of "Xx_firstname420_xX". But offline mode is not suitable for public servers - it makes administrating them impossible because kicks and bans cannot be enforced.

Private servers don't have this problem though. If you just want to run a small server with people that all know and trust each other the advantage of choosing any name far outweighs the non-relevant disadvantage of not being able to kick and ban players.

## Possible Risks

Some may argue that supporting offline mode is the same as supporting "cracked" or "pirated" Minecraft. Since Mojang themselves explicitly support offline mode it is clear that this is not the case.

But Mojang, which is now part of Microsoft (aka M$), may at any point decide to drop support for offline mode and treat any launcher that supports it as a tool for piracy. If that should happen they have three options:
- Politely ask to remove offline mode support (in my opinion the most likely outcome, as they have shown to support the community even while being part of Microsoft, for example by releasing the obfuscation maps)
- Revoke the PolyMC API key (which could be reinstated after implementing the requested changes, it is also easy to create a new key for a new version without offline mode support)
- Take down the PolyMC repository (GitHub is also part of Microsoft, they can do whatever they want - yet projects such as AfoninZ's fork of MultiMC which are explicitly intended for piracy are left untouched...)

So, **if** Mojang decides to drop support for offline mode and then **if** they decide to go after launchers that support offline mode and then **if** they choose to be dicks about it PolyMC **might** have a problem for a bit. A problem that can be resolved amicably to the satisfaction of all sides (except of course players that enjoy offline mode on private servers).

My conclusion is that offline mode should be supported. Many non-pirate players such as myself have legitimate use for it.

**Comment by ghost** [comment]
98/100 A+

Well-formed introduction, body paragraphs, and conclusion. Proof and explanations are provided cleanly.

In all seriousness, I doubt offline mode will ever be removed, so it's perfectly fine to implement it for now. If AfoninZ's repo gets taken down we would have to be more careful, though.

**Comment by DioEgizio** [comment]
Isn't offline mode supported by MultiMC itself?

**Comment by d-513** [comment]
It is supported though. You have to add a legitimate account first, then offline mode appears. It's not piracy or anything as you need to login to a legit one first 

Also I doubt mojang cares tbh, they keep the game downloads accessible without auth

**Comment by bexnoss** [comment]
> Isn't offline mode supported by MultiMC itself?

> It is supported though. You have to add a legitimate account first, then offline mode appears. It's not piracy or anything as you need to login to a legit one first

Yes, it is sort of supported. It's bolted onto online mode account support, though. This results in terrible UX - instead of selecting your desired username through the account switcher on the top right you have to first jump through hoops to launch in offline mode (by either right clicking the instance and then selecting "Launch Offline" or opening the instance console and then clicking the "Launch Offline" button) and then you have to enter your offline mode username every single time. I should have clarified that I am talking about offline mode **account** support, enabling the desired UX of the **account switcher** being the central place that handles usernames.


> Also I doubt mojang cares tbh, they keep the game downloads accessible without auth

I think so, too. I think anything that might cause people to end up paying for subscriptions (Realms) or micro-transactions (Bedrock) is OK with Mojang.

**Comment by bexnoss** [comment]
I have submitted a draft PR that demonstrates the desired UX by implementing the UI at https://github.com/PolyMC/PolyMC/pull/50.
