### ISSUE TITLE
Switch away from paste.ee

### ISSUE THREAD

**Issue by ghost** [PolyMC/PolyMC#44]
### Role

We don't want to rely on MultiMC's related services, nor their API keys.

### Suggestion

Switch to a service such as paste.swurl.xyz, a tiny pastebin I made, because it's easier to use and doesn't require an API key.

### Benefit

MultiMC could revoke the API key to spite us.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by A-UNDERSCORE-D** [comment]
I'd suggest preferring a more globally used pastebin for privacy concerns, termbin and https://0x0.st/ come to mind.

**Comment by ghost** [comment]
wdym privacy?

My end goal is to have a dedicated Pastebin service for PolyMC, I can host pacebin on it if necessary.

**Comment by A-UNDERSCORE-D** [comment]
> wdym privacy?

I'd rather not have any single service have a list of *only those who use PolyMC* or similar. Rather use a public paste service thats used by others, helping PolyMC users be lost in the noise.

**Comment by ghost** [comment]
Consensus:

- Default to something like paste.polymc.org (mirror of my instance), or 0x0.st
- Allow for any FOSS pastebin service that uses basic POST with no auth or headers, returning a plaintext URL response
- Allow users to choose, potentially in the setup wizard.

**Comment by LennyMcLennington** [comment]
> Consensus:
> 
> * Default to something like paste.polymc.org (mirror of my instance), or 0x0.st
> * Allow for any FOSS pastebin service that uses basic POST with no auth or headers, returning a plaintext URL response
> * Allow users to choose, potentially in the setup wizard.

I don't think there was any consensus about defaulting to paste.polymc.org, it looks like people are more comfortable with 0x0.st

**Comment by ghost** [comment]
ok, then we can Default to that and keep paste.polymc.org as an option

**Comment by ghost** [comment]
Actually, if we are going to default to 0x0.st, then we have no need for the setup wizard since everyone should be content with it.

First order of business is getting a short list of potential options to select. They must:

- Use ONLY basic POST with NO AUTHENTICATION OR HEADERS
- Return a PLAINTEXT URL response
- The resulting URL MUST be plaintext

So far I've seen 0x0, paste.polymc.org, and term-bin
