### ISSUE TITLE
switching to older Ubuntu for building on linux

### ISSUE THREAD

**Issue by DioEgizio** [PolyMC/PolyMC#440]
For getting into appimagehub we need to build on Ubuntu 18.04 https://github.com/AppImage/appimage.github.io/pull/2862

The issue is that it'd require adding 2 custom repos and generally relying on older stuff

What'd we do?

**Comment by txtsd** [comment]
@PolyMC/launcher Need everyone's opinions

**Comment by Regular-Baf** [comment]
Seems like a fair amount of work for something that really won't matter too much.

**Comment by d-513** [comment]
Seems cringe to use old versions of everything, we shouldn't support 18.04 honestly

**Comment by DioEgizio** [comment]
at this point why isn't #127 merged?

**Comment by txtsd** [comment]
> at this point why isn't #127 merged?

That's [2.0.0](https://github.com/PolyMC/PolyMC/milestone/3)

**Comment by DioEgizio** [comment]
> > at this point why isn't #127 merged?
> 
> That's [2.0.0](https://github.com/PolyMC/PolyMC/milestone/3)

I know, I mean why not doing that if we don't want to support older systems

**Comment by Scrumplex** [comment]
NACK from me. Seems like too much work, just to get into an aggregator for download links. I am sure that AppImageHub might bump their requirements in the next few months.

**Comment by d-513** [comment]
Same
