### ISSUE TITLE
Cant use Modrinth with Quilt

### ISSUE THREAD

**Issue by ZekeZDev** [PolyMC/PolyMC#446]
### Description of bug

Mod downloader will not show anything under the modrinth section when Quilt is set as the modloader

### Steps to reproduce

create an instance with quilt go to edit instance > mods > download mods 

Modrinth will be blank like this:
![unknown-8](https://user-images.githubusercontent.com/81902668/163748729-cc1a1e19-4e94-4ca9-9f44-df317171a22b.png)

Curseforge works as expected

### Suspected cause

No quilt filter option and not fallbacking to fabric

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by DioEgizio** [comment]
@Scrumplex looks like something in #431

**Comment by DioEgizio** [comment]
@Scrumplex yes it definitely is

**Comment by DioEgizio** [comment]
for now an hacky workaround is adding an empty component named like you want but with the 'net.fabricmc.fabric-loader' uid

**Comment by Scrumplex** [comment]
Oh I see why. Interesting

**Comment by DioEgizio** [comment]
![immagine](https://user-images.githubusercontent.com/83089242/163797820-8f8de407-c5bc-4cfd-9f75-f3d8a41291c2.png)
 this is the reason

**Comment by DioEgizio** [comment]
@Scrumplex  found a fix

it should request the categories separetely, like:

https://api.modrinth.com/v2/search?offset=0&limit=25&query=&index=relevance&facets=[[%22categories:fabric%22,%20%22categories:quilt%22],[%22versions:1.18.2%22],[%22project_type:mod%22]]
