### ISSUE TITLE
A question: How is the version marked in launcher/minecraft/MinecraftInstance.cpp

### ISSUE THREAD

**Issue by glowiak** [PolyMC/PolyMC#457]
### Operating System

Other

### Description of bug

Recently someone has made a patch for FreeBSD with native libraries, but it's lwjgl2 only. I am normally using python, and i am not familar with this for PMC is built, so I ask how is the version marked in launcher/minecraft/MinecraftInstance.cpp

### Steps to reproduce

...

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by RuinTD** [comment]
For a question like that, I'd recommend going to the Discord or Matrix space:
https://polymc.org/#get-involved
