### ISSUE TITLE
Major wrongly defined

### ISSUE THREAD

**Issue by glowiak** [PolyMC/PolyMC#458]
### Operating System

Other

### Description of bug

Look at suspected cause

it happens only in 1.2.0

### Steps to reproduce

build portable on freebsd

### Suspected cause

```
[ 21%] Building CXX object launcher/CMakeFiles/Launcher_logic.dir/minecraft/launch/VerifyJavaInstall.cpp.o                            
/home/glowiak/gits/appbsd-builds/PolyMC/launcher/minecraft/launch/VerifyJavaInstall.cpp:53:77: error: no member named '__major' in 'JavaVersion'; did you mean 'major'?
    if (compatibleMajors.isEmpty() || compatibleMajors.contains(javaVersion.major()))
                                                                            ^                                                         
/usr/include/sys/types.h:389:18: note: expanded from macro 'major' 
#define major(d)        __major(d)
                        ^
/home/glowiak/gits/appbsd-builds/PolyMC/launcher/java/JavaVersion.h:30:9: note: 'major' declared here
    int major()
        ^
/home/glowiak/gits/appbsd-builds/PolyMC/launcher/minecraft/launch/VerifyJavaInstall.cpp:68:111: error: no member named '__major' in 'JavaVersion'; did you mean 'major'?
                    "Please switch to one of the following Java versions for this instance:").arg(javaVersion.major()),
                                                                                                              ^                       
/usr/include/sys/types.h:389:18: note: expanded from macro 'major' 
#define major(d)        __major(d)
                        ^
/home/glowiak/gits/appbsd-builds/PolyMC/launcher/java/JavaVersion.h:30:9: note: 'major' declared here
    int major()
        ^
2 errors generated.                                                
*** Error code 1

Stop.
make[2]: stopped in /usr/home/glowiak/gits/appbsd-builds/PolyMC/build
*** Error code 1

Stop.
make[1]: stopped in /usr/home/glowiak/gits/appbsd-builds/PolyMC/build
*** Error code 1

Stop.
make: stopped in /usr/home/glowiak/gits/appbsd-builds/PolyMC/build
glowiak@Alderaan:~/gits/appbsd-builds/PolyMC/build % make > build.log
/home/glowiak/gits/appbsd-builds/PolyMC/launcher/minecraft/launch/VerifyJavaInstall.cpp:53:77: error: no member named '__major' in 'JavaVersion'; did you mean 'major'?
    if (compatibleMajors.isEmpty() || compatibleMajors.contains(javaVersion.major()))
                                                                            ^                                                         
/usr/include/sys/types.h:389:18: note: expanded from macro 'major' 
#define major(d)        __major(d)
                        ^
/home/glowiak/gits/appbsd-builds/PolyMC/launcher/java/JavaVersion.h:30:9: note: 'major' declared here
    int major()
        ^
/home/glowiak/gits/appbsd-builds/PolyMC/launcher/minecraft/launch/VerifyJavaInstall.cpp:68:111: error: no member named '__major' in 'JavaVersion'; did you mean 'major'?
                    "Please switch to one of the following Java versions for this instance:").arg(javaVersion.major()),
                                                                                                              ^                       
/usr/include/sys/types.h:389:18: note: expanded from macro 'major' 
#define major(d)        __major(d)
                        ^
/home/glowiak/gits/appbsd-builds/PolyMC/launcher/java/JavaVersion.h:30:9: note: 'major' declared here
    int major()
        ^
2 errors generated.
```

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Scrumplex** [comment]
Can you run a Git bisection to figure out which commit introduced this issue?

**Comment by glowiak** [comment]
git: 'bisection' is not a git command. See 'git --help'

But it's the java checker one as I assume

**Comment by glowiak** [comment]
as i remember, the same bug happened when I tried to build multimc 0.6.14

**Comment by Scrumplex** [comment]
`git bisect start 1.2.0 1.1.1`

For further usage info look at the manpage

**Comment by glowiak** [comment]
HEAD is now at 56ce7f5d Merge pull request #437 from DioEgizio/bump-1.2.0
Bisecting: 136 revisions left to test after this (roughly 7 steps)
[382548e0a7106ce6b97accb320c7901499b00435] Merge pull request #355 from dada513/flatpak_properly

**Comment by glowiak** [comment]
glowiak@Alderaan:~/gits/appbsd-builds/PolyMC/build % make
-- Git commit: 382548e0a7106ce6b97accb320c7901499b00435
-- Git refspec: 
CMake Error at CMakeLists.txt:122 (find_package):
  By not providing "FindQuaZip-Qt5.cmake" in CMAKE_MODULE_PATH this project                                                           
  has asked CMake to find a package configuration file provided by 
  "QuaZip-Qt5", but CMake did not find one.                        
                                                                   
  Could not find a package configuration file provided by "QuaZip-Qt5" with                                                           
  any of the following names:                                      
                                                                   
    QuaZip-Qt5Config.cmake                                         
    quazip-qt5-config.cmake                                        
                                                                   
  Add the installation prefix of "QuaZip-Qt5" to CMAKE_PREFIX_PATH or set                                                             
  "QuaZip-Qt5_DIR" to a directory containing one of the above files.  If                                                              
  "QuaZip-Qt5" provides a separate development package or SDK, be sure it has                                                         
  been installed.                                                  
                                                                   
                                                                   
-- Configuring incomplete, errors occurred!
See also "/home/glowiak/gits/appbsd-builds/PolyMC/build/CMakeFiles/CMakeOutput.log".
*** Error code 1

Stop.
make: stopped in /usr/home/glowiak/gits/appbsd-builds/PolyMC/build

**Comment by glowiak** [comment]
@Scrumplex can you help me with this? I'd like to package new version as fast as it's possible, and your command makes it build 1.1.1

**Comment by glowiak** [comment]
Nevermind I got it to build, but I had to entirely remove the java checker from code
