### ISSUE TITLE
No Old Snapshots available

### ISSUE THREAD

**Issue by jopejoe1** [PolyMC/PolyMC#468]
### Operating System

Linux

### Description of bug

When Filtering for `Old Snapshots` in the Version select screen no version is displayed.

### Steps to reproduce

1. Add Instance
2. Vanilla
3. Filter for Only `Old Snapshots` ~~(Currently also crashes PolyMC)~~
4. Refresh (Optional)

### Suspected cause

There are no `Old Snapshot` versions in the [Mojang version Manifest](https://launchermeta.mojang.com/mc/game/version_manifest_v2.json). JAR files for these version exist but they are not in the Manifest.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by kthchew** [comment]
Seems like the manifest hasn't had them since 2016: https://web.archive.org/web/20160331202147/https://launchermeta.mojang.com/mc/game/version_manifest.json

> JAR files for these version exist but they are not in the Manifest.

Do you know where? If it's not from an official source it might not be possible to fix this.

**Comment by jopejoe1** [comment]
> Do you know where? If it's not from an official source it might not be possible to fix this.

Yes there are version available on the official minecraft site here are some examples the links can be found on the minecraft wiki if you need more examples:

- 13w09b https://assets.minecraft.net/13w09b/minecraft.jar
- 12w30d https://assets.minecraft.net/12w30d/minecraft.jar
- 11w47a https://assets.minecraft.net/11w47a/minecraft.jar

@dada513 could you reopen this issue as only the crashing part of this issue was fixed in #470

**Comment by d-513** [comment]
Sure, it was closed automatically by merged PR

**Comment by kthchew** [comment]
Seems like the JSON files are available at https://archive.org/download/Minecraft-JSONs. They’re all marked as `snapshot` instead of `old_snapshot`, but I think they’re what we’re looking for. Is it possible to just feed this to the meta scripts in their current form?

**Comment by Scrumplex** [comment]
> Seems like the JSON files are available at https://archive.org/download/Minecraft-JSONs. They’re all marked as `snapshot` instead of `old_snapshot`, but I think they’re what we’re looking for. Is it possible to just feed this to the meta scripts in their current form?

They don't have download links to the corresponding jar files
