### ISSUE TITLE
[Feature Request] Add an option to launch with the official launcher

### ISSUE THREAD

**Issue by jexom** [PolyMC/PolyMC#47]
### Role

Modded player

### Suggestion

Have an option to launch Minecraft using an official launcher while using PolyMC as a modpack manager.

### Benefit

I as well as many other people are concerned about giving their credentials to third parties. Using the official launcher gives the confidence that your credentials are only given to Mojang/Microsoft.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

CurseForge uses an official launcher to start the game and never asks for your Minecraft credentials. While it presents itself only as a mod and pack manager it also makes much more sense security-wise. The disatvantage of Curse though is that it is not open source, it is a part of pretty much bloatware, and that you also need an Overwolf account.
Having a togglable option to launch through PolyMC or an official launcher would be a nice touch.

**Comment by ZekeZDev** [comment]
Hmm I dont think its a big security concern there is a lot of documentation on using the microsoft api and etc any new account on polymc is handled through microsoft not polymc. Mabye an issue for old mojang accounts but they will be phased out and all the source is open. There is no benefit in having to launch through the official launcher if everyone is on microsoft accounts.

I am not a programmer of polymc this infomation I have gathered from discussion and looking at the microsoft authentication and third party launchers.

**Comment by ghost** [comment]
It's open source for a reason. No reason to add this in my opinion unless others support  this

**Comment by ZekeZDev** [comment]
Mabye we could auto detect their login from the signed in minecraft launcher but thats another thing entirely thats likely a huge security risk however I have seen propreitary launchers do it before.

**Comment by A-UNDERSCORE-D** [comment]
It would be rather brittle to attempt to swipe tokens from a launcher that may change its format. Not to mention thats pretty silly, and possibly not really nice to the vanilla launcher devs.

Personally I dislike the `Launcher to launch a Launcher` thing, but you can reasonably easily sidestep this with some links and the vanilla launcher anyway, so I dont think adding complexity would be worth the few users that may use it.

**Comment by ZekeZDev** [comment]
I agree

**Comment by ghost** [comment]
Considering these points I am no longer open to adding this feature. You can always make a fork and implement it yourself if you so desire.
