### ISSUE TITLE
Crash on "Download mods" on latest snapshot

### ISSUE THREAD

**Issue by RuinTD** [PolyMC/PolyMC#471]
### Operating System

Windows

### Description of bug

Clicking "Download mods" in 22w15a (Latest snapshot at the time) causes PolyMC to crash.

### Steps to reproduce

* Click Add Instance
* Enable the "Snapshots" filter
* Select the newest snapshot (22w15a at time of report)
* Change the Mod Loader to "Fabric"
* Click OK
* Click View Mods on the instance
* Click Download mods

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by txtsd** [comment]
It segfaults.
