### ISSUE TITLE
If building on FreeBSD, set Launcher_META_URL different

### ISSUE THREAD

**Issue by glowiak** [PolyMC/PolyMC#476]
### Role

I don't want to use custom runtimes

### Suggestion

Put in CMakeLists.txt that if the OS is FreeBSD, then set Launcher_META_URL to http://glowiak.github.io/freebsd-polymc-meta/

### Benefit

So it can run without any problems on FBSD

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

I've actually implemented it in my fork of MMC, [CO2MC](http://codeberg.org/glowiak/CO2MC) and it work without any issues

**Comment by glowiak** [comment]
https://codeberg.org/glowiak/CO2MC/src/commit/f195d47d7aee15263254c7bd0268bd95ed1f78c4/CMakeLists.txt#L76

**Comment by Scrumplex** [comment]
We don't have control over your own neta repo, which is why we probably won't add your meta URL to this codebase. You can just set that URL on build time for your FreeBSD builds using `cmake`

```
cmake ... -DLauncher_META_URL=https://glowiak.github.io/freebsd-polymc-meta/ ...
```

**Comment by glowiak** [comment]
Oh ok
