### ISSUE TITLE
LWJGL 3 version cannot be changed

### ISSUE THREAD

**Issue by kthchew** [PolyMC/PolyMC#483]
### Operating System

macOS, Linux

### Description of bug

For versions of Minecraft that use LWJGL 3, the version of LWJGL 3 used cannot be changed.

Expected behavior: the version can be changed (e.g. to work around certain bugs by using different versions of LWJGL)

Actual behavior: upon clicking another version and confirming, the version changes for a split second before changing back.

A Linux user found this bug in https://github.com/PolyMC/PolyMC/issues/473#issuecomment-1107371377, and I was able to replicate it on macOS.

It is possible to workaround the issue by clicking customize on the LWJGL 3 version and then manually editing the json file.

### Steps to reproduce

1. Create a Minecraft 1.18.2 instance.
2. Edit the instance.
3. Click LWJGL 3, then click change version.
4. Choose a different version, then click OK.

### Suspected cause

```
  385.448 D Change "org.lwjgl3" to "3.3.1"
  385.453 D Task "ComponentUpdateTask(0x6000009a0000)" starting for the first time
  385.453 D Loading components
  385.453 D Index is already loaded
  385.453 D "Minecraft" is already loaded
  385.454 D "LWJGL 3" is already loaded
  385.454 D "Intermediary Mappings" is already loaded
  385.454 D "Fabric Loader" is already loaded
  385.454 D Resolving dependencies
  385.454 D "Req: net.fabricmc.intermediary" Is met.
  385.455 D "Req: net.minecraft == 1.15.2" Is met.
  385.455 D "Req: org.lwjgl3 == 3.2.2" already has different version that can be changed.
  385.455 D Setting version of  "org.lwjgl3" to "3.2.2"
```
A hard version requirement for `org.lwjgl3` should not be set. Note that a hard version requirement is not set for older versions of Minecraft that require lwjgl 2.

Edit:

https://github.com/PolyMC/meta/blob/090f785b49ce13b51164c73bcc27773142f78005/generateMojang.py#L324-L328

Apparently this was done to make sure people who updated MC would have a LWJGL version that actually works, in case the older selected LWJGL version no longer works with the new MC version, so it might require some additional fixes to prevent that.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by glowiak** [comment]
I've noticed that too with my fork of MMC, so this bug is common for all launchers based on it

**Comment by DioEgizio** [comment]
MultiMC relic

**Comment by d-513** [comment]
This was fixed a while ago in meta.
