### ISSUE TITLE
x64 Windows Build Lagging Over Time

### ISSUE THREAD

**Issue by Bopler** [PolyMC/PolyMC#484]
### Operating System

Windows

### Description of bug

I'm having issues where the client massively slows down after a few minutes of use. It only happens when using the x64 build. Issue also gets worse and worse over time, near unusable after ~20 minutes.

Resource usage is completely normal when this happens.

I do not even have to interact with anything for the client to start lagging. It also happens on a completely fresh client, without any instances loaded.

The 32bit build works perfectly fine, with no slowdown at all.

Have tried the very first msys2 build to see if it is a newer issue, but the issue persists. ( PR #294 , `Build #119` )

Below is a video comparing 64bit, 32bit, and MultiMC.

https://user-images.githubusercontent.com/57711260/164946026-2b22954a-aac1-4e76-9c32-c78e898a906c.mp4

### Steps to reproduce

1. Open PolyMC
2. Wait ~3 Minutes
3. Try to drag window, or interact with any button

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by LennyMcLennington** [comment]
Do you know if this happens for anyone else? I haven't seen anyone mention it and have no idea what could cause it. Also which build of PolyMC was this tested with? Where was it downloaded from?

**Comment by Bopler** [comment]
> Do you know if this happens for anyone else? I haven't seen anyone mention it and have no idea what could cause it. Also which build of PolyMC was this tested with? Where was it downloaded from?

I don't know if it happens for anyone else, contributors mentioned also having slowdowns in the discord when I first asked in the support channel, but their issues did not depend on the build used.

I tested with Release 1.2, 1.1.1, `Build #150` (pre-scaling), and `Build #119` (first msys2 build). I have also tested the newest release 1.3 with the new windows installer. The issue still persists for me. All were downloaded from this GH repo.

**Comment by krystofkrticka** [comment]
I also have this slow down issue on 64-bit version of PolyMC, tested on latest release version and also latest development version downloaded from github actions.

**Comment by Scrumplex** [comment]
We don't offer x86_64 builds on Windows anymore. Closing this as solved

**Comment by DioEgizio** [comment]
but this issue still happens when polymc is built with mingw64/ucrt64, so we should keep this open

**Comment by Scrumplex** [comment]
Our build instructions tell you to use MinGW x86. No developer was able to reproduce this issue, so I don't see any reason to keep this open. Just use the x86 builds and it will work fine
