### ISSUE TITLE
Failed to find Minecraft main class

### ISSUE THREAD

**Issue by HalJordan** [PolyMC/PolyMC#485]
### Operating System

Linux

### Description of bug

Log: https://0x0.st/oTL6.txt

This is a fresh install, using the Linux portable of All The Forge 8 from the Atlauncher category(on Arch btw). I tried in Atlauncher proper as a test(but prefer to have all instances in one place) and it starts fine from there. I tested a few other packs and they launch, even from the Atlauncher category.

### Steps to reproduce

Install All The Forge 8 from Atlauncher category.
Click Launch (not Launch offline)
Watch console log.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by glowiak** [comment]
Open the minecraft.jar with xarchiver and check if the net/minecraft/launchwrapper/Launch.class exists

**Comment by glowiak** [comment]
If not then it's not PolyMC bug

**Comment by Scrumplex** [comment]
Something is not right with that instance. Can you remove and re-add Forge in the instance settings?

**Comment by DioEgizio** [comment]
If launchwrapper isn't there there's something really wrong

**Comment by HalJordan** [comment]
Umm, yeah, I'm finally home where I have more control. there's not even a minecraft.jar to open with xarchiver...

I started polymc in shell, and this is everything from when I clicked install on a fresh copy of AllTheForge 8: https://pastebin.com/R5S3NKsc

**Comment by HalJordan** [comment]
It's a different error, but I'm unable to start the DNS Tech Pack from Poly either: https://0x0.st/oTgI.txt

This is on a different minecraft major release(1.16 instead of 1.18). I'm starting to think there's something missing from how the packs are being provided by ATLauncher, or how they're read in. Another difference here is importing it after installing(and confirming it works) in ATLauncher didn't work for this one when exported using the Curseforge format.

**Comment by DioEgizio** [comment]
> It's a different error, but I'm unable to start the DNS Tech Pack from Poly either: https://0x0.st/oTgI.txt
> 
> This is on a different minecraft major release(1.16 instead of 1.18). I'm starting to think there's something missing from how the packs are being provided by ATLauncher, or how they're read in. Another difference here is importing it after installing(and confirming it works) in ATLauncher didn't work for this one when exported using the Curseforge format.

https://polymc.org/wiki/getting-started/installing-java/#forge-1.16.5-and-java-8u321+

**Comment by HalJordan** [comment]
Same forge version, same java in use between poly and atlauncher, how come one works and the other doesn't?

**Comment by DioEgizio** [comment]
I don't think it's the same java, ATL uses its own Java version.

**Comment by Scrumplex** [comment]
> It's a different error, but I'm unable to start the DNS Tech Pack from Poly either: [0x0.st/oTgI.txt](https://0x0.st/oTgI.txt)
> 
> This is on a different minecraft major release(1.16 instead of 1.18). I'm starting to think there's something missing from how the packs are being provided by ATLauncher, or how they're read in. Another difference here is importing it after installing(and confirming it works) in ATLauncher didn't work for this one when exported using the Curseforge format.

This error is unrelated. This is just a bug with Forge and newer Java 8 versions. As DioEgizio already linked using an older release should fix that.

**Comment by Scrumplex** [comment]
For some reason PolyMC adds a fourth entry in the version page for the modpack "All The Forge". That one changes the main class of the game to launchwrapper, which is not right. We use a different main class when Forge is in use. Removing that fourth entry fixes it for now. At the end it should only have LWJGL, Minecraft and Forge. 

We need to look into why it is even created.

**Comment by Scrumplex** [comment]
Fixed by #630
