### ISSUE TITLE
Minecraft don't start

### ISSUE THREAD

**Issue by mirronake** [PolyMC/PolyMC#490]
### Description of bug

Minecraft don't start

### Steps to reproduce

https://0x0.st/oTEi.txt

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by DioEgizio** [comment]
What's your CPU/GPU? OS?

**Comment by glowiak** [comment]
<strike>priwiet russkij tawariszcz</strike> <strike>hello putinland resident</strike>

Remove the Not Enough Crashes mod. It ironically causes the crash.

**Comment by DioEgizio** [comment]
It doesn't cause the crash here, but it obfuscate the real crash.

Anyways, what your CPU/GPU and your OS

**Comment by glowiak** [comment]
The OS is winblow$, the C:\ says it

**Comment by DioEgizio** [comment]
*what* version of windows

**Comment by DioEgizio** [comment]
Also I just noticed you're using too much ram, don't allocate more than 4gb

**Comment by glowiak** [comment]
LWJGL failed to load a library

**Comment by DioEgizio** [comment]
yeah

**Comment by glowiak** [comment]
OP should add the -Dorg.lwjgl.util.Debug=true -Dorg.lwjgl.util.DebugLoader=true and post log then

**Comment by mirronake** [comment]
I had to completely delete the minecraft and polymc files, only after that the game started with the same mods.

**Comment by ryleu** [comment]
so it was a bad download. does poly do checksums on downloaded stuff?

**Comment by ghost** [comment]
I had the same issue with the Linux Flatpak version. I was able to fix this by 
- renaming `~/.var/app/org.polymc.PolyMC/` to `~/.var/app/org.polymc.PolyMC.bak/`
- uninstalling and reinstalling PolyMC
- running PolyMC
- copying `~/.var/app/org.polymc.PolyMC.bak/data/PolyMC/instances/` to `~/.var/app/org.polymc.PolyMC/data/PolyMC/instances/`

Launched fine after that while preserving my instances.

**Comment by txtsd** [comment]
Can this be closed now?

**Comment by ryanccn** [comment]
> Can this be closed now?

probably
