### ISSUE TITLE
Search for mods by project ID

### ISSUE THREAD

**Issue by Un1q32** [PolyMC/PolyMC#494]
### Role

I play modded mc

### Suggestion

I want to be able to put a mods project ID into the search bar of the mod downloader, and get the result

### Benefit

It will be useful for when the mod updater is implemented, if we can't find a way to make it automatically find manually installed mods.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by DioEgizio** [comment]
hmn, https://github.com/PolyMC/PolyMC/issues/726 seems more complete

**Comment by txtsd** [comment]
duplicate of #726
