### ISSUE TITLE
Hovering over the close button in the launcher causes a segfault

### ISSUE THREAD

**Issue by HPlinko** [PolyMC/PolyMC#496]
### Operating System

Linux

### Description of bug

I use GNOME 42 on the Fedora 36 Beta, so i'm not sure if this is a problem with PolyMC or current Fedora. But anyway, in the launcher, when i hover over the close button, the launcher crashes. I ran PolyMC through a terminal and found out that when I hover my cursor over the close button it causes a segmentation fault. I also get a core dump, but i haven't been able to find where it's kept. Dragging the window by clicking and holding on the titlebar doesn't cause this, only hovering over the close button does.

### Steps to reproduce

1. Open PolyMC
2. Move your cursor to the close button

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by txtsd** [comment]
This is the strangest bug so far lol.

Are you comfortable running `gdb` with a debug build?

**Comment by HPlinko** [comment]
@txtsd i don't know what you're talking about, but i'd be more than happy to if it helps!

**Comment by Un1q32** [comment]
I had this bug when I briefly installed fedora 36 beta a few days ago.  This happens with ALL qt apps.

**Comment by HPlinko** [comment]
> I had this bug when I briefly installed fedora 36 beta a few days ago. This happens with ALL qt apps.

Yeah, i switched to KDE and tried running PolyMC and everything was smooth sailing. Did GNOME 42 implement something that messes up qt apps?

**Comment by txtsd** [comment]
Found a reddit thread about it but couldn't find upstream bugs with either Gnome or Qt.

https://www.reddit.com/r/Fedora/comments/uaitq1/qt_apps_crash_when_hovering_over_menu_close/

**Comment by Un1q32** [comment]
> Found a reddit thread about it but couldn't find upstream bugs with either Gnome or Qt.
> 
> https://www.reddit.com/r/Fedora/comments/uaitq1/qt_apps_crash_when_hovering_over_menu_close/

lmao thats my post

**Comment by txtsd** [comment]
> > Found a reddit thread about it but couldn't find upstream bugs with either Gnome or Qt.
> > https://www.reddit.com/r/Fedora/comments/uaitq1/qt_apps_crash_when_hovering_over_menu_close/
> 
> lmao thats my post

lol I didn't even notice the username

**Comment by forkiesassds** [comment]
Cannot reproduce on Arch Linux using Gnome 42.

**Comment by Un1q32** [comment]
@forkiesassds its fixed in Fedora also.  It was a Fedora problem, not a PolyMC problem.

**Comment by txtsd** [comment]
Can this be closed now?

**Comment by Un1q32** [comment]
yes
