### ISSUE TITLE
RPM package

### ISSUE THREAD

**Issue by ghost** [PolyMC/PolyMC#5]
If anyone with experience in RPM packaging would like to volunteer to make one, please feel free to do so. If nobody volunteers I'll do it in a week or so.

**Comment by d-513** [comment]
found this specfile https://download.copr.fedorainfracloud.org/results/elxreno/multimc/fedora-35-x86_64/02841104-multimc/multimc.spec from https://copr.fedorainfracloud.org/coprs/elxreno/multimc/. With minor changes could be used

**Comment by ghost** [comment]
okay, I've got some more free time over the weekend so I could probably do it with that on Saturday

**Comment by ghost** [comment]
I lied because I'm lazy I'll do it later today

**Comment by d-513** [comment]
Looks like MMC had an RPM before too. https://github.com/MultiMC/Launcher/blob/f78152d725c83ddaf8c58b50996eac2e998b2e5c/application/package/rpm/MultiMC5.spec. It seems to have been removed (just likes source for debs) after the debranding

**Comment by ghost** [comment]
I removed it during rebrand and can use it as a base later. I'm not gonna set a deadline anymore because my schedule is funky but I'll get this done sooner or later

**Comment by akdev1l** [comment]
the provided spec file isn't great - I'll take a stab at packaging this

On Fedora this would need some minor patching to use the system `quazip`
