### ISSUE TITLE
CI build caching

### ISSUE THREAD

**Issue by kthchew** [PolyMC/PolyMC#501]
### Role

Contributor

### Suggestion

The CI should cache builds with ccache/sccache/similar

### Benefit

Faster build times from CI

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by DioEgizio** [comment]
Except windows, they're already fast enough from my POV

**Comment by txtsd** [comment]
I'm working on it!
