### ISSUE TITLE
[Suggestion] Add "Don't show again" option on java startup setup

### ISSUE THREAD

**Issue by roworu** [PolyMC/PolyMC#506]
### Role

I play modded minecraft

### Suggestion

Add "Don't show again" option on java startup setup

### Benefit

As all my java binaries written to settings of minecraft versions, I don't  java installed globally. So every time I start polyMC - this window show up.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

![image](https://user-images.githubusercontent.com/36964755/165949497-13d958f0-7079-421e-b8d6-89d07c80795e.png)
![image](https://user-images.githubusercontent.com/36964755/165949580-7134885d-f076-461b-8e6e-4d6a0306c931.png)

**Comment by RuinTD** [comment]
Random question. Why do you have a JRE for each instance???

**Comment by roworu** [comment]
Hey! I use multiple java versions for different minecraft instances.  As older versions of minecraft don't work on newest versions of java and vice versa.
