### ISSUE TITLE
App icon doesn't display under Wayland

### ISSUE THREAD

**Issue by baduhai** [PolyMC/PolyMC#51]
### Operating System

Linux

### Description of bug

The PolyMC icon should display, but the generic Wayland icon is displayed instead.

### Steps to reproduce

Open PolyMC under a Wayland environment.

### Suspected cause

It seems as though notepadqq had the same [problem](https://github.com/notepadqq/notepadqq/issues/515) at one point. Specifically due to this:

> On X11 the applications exported the window icon as pixmap data. This is no longer possible on Wayland. Instead the compositor maps the window icon from the desktop file and the application announces the desktop file for a window. In Qt this is done by using the reverse domain name combined with the binary name. The domain name is set with KAboutData and defaults to “kde.org”. So for example in the case of kate the desktop file should be called “org.kde.kate.desktop”. So please fix the naming of your desktop files. If you want to test please be aware that this requires Qt 5.5 to work properly.

https://blog.martin-graesslin.com/blog/2015/07/porting-qt-applications-to-wayland/

The [fix](https://github.com/notepadqq/notepadqq/pull/661/commits/619ac281a969507602a874850b73d7a67cff1326) seems simple enough, will try to open a pull request when I have some time.

Mumble has a similar issue, but I wasn't able to fix it the same way the notepadqq guys did. I think the way it's packaged might also affect this.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by ghost** [comment]
Where are you talking about?

In settings and about it displays for me properly. However I use sway so I can't see desktop icons.

**Comment by baduhai** [comment]
Sorry, should have clarified that in docks and some parts of the DE the proper icon doesn't get displayed(only under Wayland, works fine on X11).

Here's what I mean. [Example 1](https://i.imgur.com/97D3msq.png). [Example 2](https://i.imgur.com/miiYAo8.png)

**Comment by ghost** [comment]
Interesting. I can add that potential fix to a branch and you can try building/installing from that.

**Comment by baduhai** [comment]
I can give a shot, yeah.

**Comment by ghost** [comment]
OK, I can do this probably between 3 and 5 PM EST.

**Comment by d-513** [comment]
it works for me on wayland under gnome

**Comment by baduhai** [comment]
It seems as though this problem is exclusive to the Flatpak package. It works fine on the rpm(OpenSUSE) and Appimage. If you want I can reopen this issue under flathub/org.polymc.PolyMC .

**Comment by d-513** [comment]
Its probably fine to keep it here, I am using the flatpak too and this isnt happening. Using wayland on fedora 35

**Comment by ghost** [comment]
Keep it here. I'll work on it soon

**Comment by calcastor** [comment]
This is an issue I originally noticed with MultiMC on KDE Wayland. I believe it's related to StartupWMClass within the .desktop file and potentially the .desktop file's name though I'm not entirely sure if it's related to both or just one or the other. In my own case I believe I was able to get the window to use the correct icon by fiddling with both the .desktop file's name and the defined StartupWMClass, setting them to `org.multimc.MultiMC`. This is likely resolvable within the code but if I had to guess it's related to discrepancies with the window class under Wayland and the window class in the .desktop file. I didn't have this issue in KDE X11 or while running MultiMC in XWayland.

I've switched to GNOME and Fedora since I encountered this issue when using MultiMC. With PolyMC installed from Copr, the window "connects" as expected to the .desktop file when I use XWayland. I haven't had the chance to test with launching as Wayland native though.

**Comment by ghost** [comment]
Freedesktop is total spaghetti that I don't feel like dealing with. Is the WM class configurable in Qt and does it need to be set to org.polymc.PolyMC?

**Comment by d-513** [comment]
Seems to be broken on MMC too [MMC-3500](https://github.com/MultiMC/Launcher/issues/3500), but maintainer doesnt seem willing to fix that

**Comment by d-513** [comment]
Though the thing is PolyMC desktop file is correct rDNS, so renaming won't work

**Comment by timoreo22** [comment]
Your fix seems to only work for qt 5.7, i believe PolyMC currently targets qt 5.6

**Comment by ghost** [comment]
@baduhai does #95 fix it?

**Comment by baduhai** [comment]
> @baduhai does #95 fix it?

Unfortunately not.

**Comment by baduhai** [comment]
Was this fix included in 1.0.6? Because neither the flatpak nor the native package for 1.0.6 display the icon properly in Plasma Wayland.

**Comment by d-513** [comment]
> Was this fix included in 1.0.6? Because neither the flatpak nor the native package for 1.0.6 display the icon properly in Plasma Wayland.

No, it wasn't. The fix will be in 1.1.0.
