### ISSUE TITLE
Only force Java 8 if Forge is detected on old versions

### ISSUE THREAD

**Issue by forkiesassds** [PolyMC/PolyMC#513]
### Role

I play old verisons of Minecraft

### Suggestion

Make it so it wouldn't force you to use Java 8 unless Forge is detected on older versions of Minecraft.

### Benefit

So I don't have to set the JRE every time I set up an old version of Minecraft.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Java 17 works fine with many of the older versions of the game, provided if you use a specific build, such as Adoptium or Zulu builds of OpenJDK.

**Comment by Scrumplex** [comment]
Java 16 and newer won't work for any version which uses LWJGL 2 (I think everything before Minecraft 1.13).

**Comment by forkiesassds** [comment]
> Java 16 and newer won't work for any version which uses LWJGL 2 (I think everything before Minecraft 1.13).

??? It clearly does work?

**Comment by kthchew** [comment]
> Java 16 and newer won't work for any version which uses LWJGL 2 (I think everything before Minecraft 1.13).

Not true. It does work if you have a completely vanilla instance (and maybe some limited mods which directly modify the jar, like OptiFine without Forge) and disable the compatibility check.
![2022-05-01_01 14 30](https://user-images.githubusercontent.com/79120643/166133251-9994110e-98d8-4259-88b4-4a9002d584a1.png)

It's definitely not supported, though.

**Comment by DioEgizio** [comment]
It's going to have some serious issues, just use java 8 on these older versions, there's an issue of random CMEs there

**Comment by DioEgizio** [comment]
https://bugs.mojang.com/browse/MC-149777

**Comment by kthchew** [comment]
Yeah, agreed. It's probably not a good idea to use these Java versions on old MC versions, even if the game does run.

Of course, if someone wants to ignore these warnings, the "skip java compatibility checks" checkbox is there for a reason already.

**Comment by DioEgizio** [comment]
Yeah

**Comment by DioEgizio** [comment]
Also I want to note that even on fabric mods like hydrogen break with newer java so it's not an optimal experience

**Comment by d-513** [comment]
It isn't forced, you can disable the check in global settings. It's clearly not supported but there's the toggle
