### ISSUE TITLE
[Suggestion] White Flat Icons

### ISSUE THREAD

**Issue by he3als** [PolyMC/PolyMC#516]
### Role

I use the QT dark mode and a custom QT dark theme on Linux.

### Suggestion

I want there to be a white version of the flat icons.

### Benefit

I would no longer have to manually install my icon theme and it would be nicer to have an actual name for it in the icon theme selector instead of 'Custom'.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

I have made an icon theme that already modifies all of the flat icons to be a nice white colour, which fits in well with the dark colour scheme.

Link: https://cdn.discordapp.com/attachments/694176292995858492/970374862868738098/custom.zip

**Comment by he3als** [comment]
also would fix complaints in https://github.com/PolyMC/PolyMC/issues/162 about the flat theme not being good with a dark theme

**Comment by StaticRocket** [comment]
@he3als, out of curiosity, is there any reason why you haven't submitted a PR for this yet? Seems like you already took care of most of the work.

**Comment by theofficialgman** [comment]
@Scrumplex "fixes" wasn't correctly linked to this issue. so merging the PR didn't auto close it.

This can be closed
