### ISSUE TITLE
Screenshots do not appear in PolyMC's screenshot manager if instances are stored on a exFAT/FAT32 partition

### ISSUE THREAD

**Issue by kthchew** [PolyMC/PolyMC#517]
### Operating System

macOS

### Description of bug

The "Manage Screenshots" screen does not show any screenshots, even though the instance's `screenshots` folder has image files in it.
<img width="697" alt="Screen Shot 2022-05-02 at 2 10 52 AM" src="https://user-images.githubusercontent.com/79120643/166191950-1ea35e7f-eef9-40d3-9c5f-523963242030.png">
That folder is the one opened when clicking "View Folder" in the screenshots manager.

### Steps to reproduce

1. In PolyMC settings, set your `instances` folder to a location stored on an exFAT or FAT32 file system.
2. Select an instance with screenshots. (If you don't already have one, open an instance and take a screenshot.)
3. Click "Manage Screenshots."

### Suspected cause

It has to do with file permissions. If the executable bit on a screenshot is set, then it won't show in the screenshot manager. Unfortunately, exFAT/FAT32 have no concept of Unix permissions, and thus the permissions cannot be fixed if stored on those file systems. In addition, this bug will also appear if the instances folder is moved from a exFAT/FAT32 system to one that does support Unix permissions, because the permissions are not automatically fixed. See https://github.com/PolyMC/PolyMC/issues/517#issuecomment-1115233037 for more details.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by ryanccn** [comment]
Interesting, I can't reproduce this issue 🤔

**Comment by DioEgizio** [comment]
Can't reproduce either

**Comment by kthchew** [comment]
Hmm, I’ll do some extra testing later. I’ll see if temporarily removing my data and starting from scratch still causes the issue.

**Comment by kthchew** [comment]
Okay, it works when I rename my data folder and try my reproduction steps:
<img width="805" alt="Screen Shot 2022-05-02 at 2 01 19 PM" src="https://user-images.githubusercontent.com/79120643/166300285-fa16db79-d470-4c4a-9bc7-0ff4d9864855.png">

I'll have to do some more testing and see what exactly is wrong with my data folder, then. It's quite old and has been moved across different hard drives with different file systems.

**Comment by kthchew** [comment]
Well, I've found the issue.

```
❯ ls -la /Users/kenneth/Library/Application\ Support/PolyMC/instances/1.8.9/minecraft/screenshots
total 80912
drwxrwxrwx  67 kenneth  staff     2144 Aug  9  2021 .
drwxrwxrwx  25 kenneth  staff      800 Apr  8 20:21 ..
-rwxrwxrwx@  1 kenneth  staff     6148 Jun 19  2020 .DS_Store
-rwxrwxrwx   1 kenneth  staff  1004899 Nov 25  2017 2017-11-25_16.59.47.png
-rwxrwxrwx   1 kenneth  staff   556083 Dec 18  2018 2018-12-18_15.45.49.png
...
```
Yikes. How'd that happen?

I'm guessing it happened because at some point, I moved my instances folder to an external drive formatted as exFAT, which has no concept of Unix permissions. As a result, everything appears to have `777` permissions. When I moved it back to my internal drive, which does have Unix permissions, the `777` permissions were retained (yikes), and apparently that's the case for my entire instances folder (although, given that a parent folder is not readable to anyone except my user, I don't think it's as big of an issue as it could be).

When I apply the stick of correction to fix my instances folder (or at the very least, remove the executable bit from the screenshot png files), then everything shows again:
```
❯ find /Users/kenneth/Library/Application\ Support/PolyMC/instances -type f -print0 | xargs -0 chmod 0644
❯ find /Users/kenneth/Library/Application\ Support/PolyMC/instances -type d -print0 | xargs -0 chmod 0755
```

---

Arguably, this is user error. But I'd still say this is a bug, because this means that if the instance folder is stored on a partition formatted as exFAT or FAT32 on macOS (and probably Linux as well, though I haven't tested this), then the screenshot manager won't show any of the screenshots. I did test and confirm this on my system - I'll update the reproduction steps to reflect this.

**Comment by d-513** [comment]
this is so oddly specific lol

**Comment by forkiesassds** [comment]
For me it happens on an NTFS partition 
![image](https://user-images.githubusercontent.com/54495659/167643622-72729323-656a-4209-9bd2-21077a5e78f0.png)

**Comment by Scrumplex** [comment]
> For me it happens on an NTFS partition ![image](https://user-images.githubusercontent.com/54495659/167643622-72729323-656a-4209-9bd2-21077a5e78f0.png)

depending on how it is mounted, the files might have the executable flag
