### ISSUE TITLE
Some things are untranslated after changing languages

### ISSUE THREAD

**Issue by flowln** [PolyMC/PolyMC#527]
### Operating System

Linux

### Description of bug

Some text is not translated when you switch languages. For instance, in this case I started the application in Chinese and switched to English. Some things did not get translated: 
![image](https://user-images.githubusercontent.com/9145768/167274803-ea2b2e4e-2be3-41b6-bbb3-b2424eef9078.png)

I could only find these two places in the UI where it didn't retranslate property.

### Steps to reproduce

- Start PolyMC in language X
- Switch to language Y
- Some things are still in language X

### Suspected cause

Missing `retranslate()` calls / functions. Shouldn't be a problem with the translation percentage, since the same thing happens with English <-> Russian (both at 100% translation at the time of writing)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Scrumplex** [comment]
This is prbably because of the mnemonics we added, that changed the translation strings. Latest Git builds should be working in this regard

**Comment by flowln** [comment]
Oh, sorry for not specifying, but this happens on the latest commit :slightly_smiling_face: 
On 1.2.1, it also happens, though the bottom playtime text gets re translated after closing the translate dialog, and the 'No default account' button on the top don't
