### ISSUE TITLE
Automated Arch Linux builds

### ISSUE THREAD

**Issue by ghost** [PolyMC/PolyMC#53]
Creating a .pkg.tar.zst on Jenkins may be a good idea for Arch users who do not want to compile for themselves.

I first need to figure out how to makepkg it without rebuilding the whole thing again

**Comment by d-513** [comment]
I agree, on my very high-end system it takes a minute to compile, I can imagine what it would take on a low-spec computer

**Comment by ghost** [comment]
Made a custom PKGBUILD in Jenkins and am currently building to test if everything works.
