### ISSUE TITLE
Make Account Switcher on top right button, Scrollable.

### ISSUE THREAD

**Issue by forwind0001** [PolyMC/PolyMC#542]
### Role

I use a lot of accounts on my instances.

### Suggestion

I want the Account Switcher on top right button to be scrollable instead of viewing all the Accounts at once. Right now, clicking the button on top right will view all the accounts logged in in a large window (if you have many accounts). Instead of this, I want the said window to be scrollable, so the accounts wont overflow outside of the screen if there are way too many accounts logged in at once.

### Benefit

There won't be overflow in the Account Switcher UI. If there are too many accounts logged in, the window appeared from the top right button will be overflowed outside of the screen making it unable to click on certain accounts.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by forwind0001** [comment]
This is an example picture (account names erased for privacy of course) of how it looks like when there are many accounts logged in. The Account Switcher UI overflowed until outside of the screen. Imagine more account is being added, some of the overflowed items will not able to be clicked by users to be used from the said UI component.

![mpv-shot0001](https://user-images.githubusercontent.com/105194222/167354890-f7cc37a1-0d0f-4669-9b40-6da94c6a4879.jpg)

**Comment by kthchew** [comment]
...Wow. Honestly this is just impressive.

I tried a fix at #546. Could you try a build at https://github.com/PolyMC/PolyMC/actions/runs/2296552328 under the "artifacts" section (once it completes, which will probably be in ~about half an hour from now~ now) and see if it's fixed for you?

**Comment by forwind0001** [comment]
@kthchew thanks for the commit. Now the Account Switcher UI is in vertical shape and scrollable from top the bottom. All accounts can be accessed and no items are overflowed withot being able to scroll to them now. Now, just hoping the PR can be merged to close this issue.
