### ISSUE TITLE
When downloading InsaneCraft Modpack by SparkUniverse_ it crashes the polymc application.

### ISSUE THREAD

**Issue by ghost** [PolyMC/PolyMC#544]
### Operating System

Windows

### Description of bug

Hi, i found a bug when i tried downloading a modpack called "InsaneCraft Modpack" and in the middle of the installation, it crashes. Idk why but it didnt happen on other modpacks, just "InsaneCraft Modpack"

Edit: it did happen on other modpacks.
![image](https://user-images.githubusercontent.com/102156869/167411860-abfbee44-b164-449a-8ddb-bf680c0a4bde.png)

### Steps to reproduce

idk

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by ghost** [comment]
Nvm its fixed. I just have to wait lol, and im really impatient lol.

**Comment by txtsd** [comment]
Was it `Not Responding` without any prodding?
