### ISSUE TITLE
Trash instances instead of deleting

### ISSUE THREAD

**Issue by ryanccn** [PolyMC/PolyMC#548]
### Role

I use PolyMC :D

### Suggestion

Make the "Delete Instance" button trash the instances instead of straight up deleting it

### Benefit

So that if someone accidentally deletes the instances they can recover it.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by luni3359** [comment]
It would be really nice if there was a new place where deleted instances could stay in to make rolling back easier from within PolyMC.

**Comment by Derpitron** [comment]
the terms "Trash" and "Delete" mean similar things, so it might confuse the user. What about calling it "Archive" instead?

**Comment by ryanccn** [comment]
> the terms "Trash" and "Delete" mean similar things, so it might confuse the user. What about calling it "Archive" instead?

The "delete" wording is being kept, just that on systems with trash it will be moved to trash instead of being outright `rm`ed.

"Archive" would probably imply an archival feature in PolyMC (i.e. `{PolyMC_data_dir}/archive` or sth), which is not the case here.
