### ISSUE TITLE
Launch microsoft login instead of link

### ISSUE THREAD

**Issue by ZekeZDev** [PolyMC/PolyMC#55]
### Role

Microsoft accounts

### Suggestion

when the user adds a microsoft account instead of showing a link with a timer open the microsoft login page similar to other launcher

### Benefit

Ease of use for newer users

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Polymc handles microsoft accounts quite poorly from a ux standpoint compared to most launchers eg. Badlion:
![image](https://user-images.githubusercontent.com/81902668/149257420-bad8fa60-74ae-4590-a32b-ed93aeb28046.png)
Once clicked:
![image](https://user-images.githubusercontent.com/81902668/149257453-45cdd534-2121-48b5-a549-029060f076f1.png)
Having similar functionality when adding a Microsoft account in PolyMC would be very convenient for Microsoft account users compared to the current method.

**Comment by Jan200101** [comment]
Showing the login page within the app would require using some web technology.

Qt does provide QtWebEngine but I feel this is a bit heavier than needed for an application like this

**Comment by ZekeZDev** [comment]
Alternatively use portals to open this page on the users default web browser.

**Comment by clydebottoms** [comment]
please do not add qtwebengine as a dependency

I agree with ZekeSmith's idea

**Comment by ghost** [comment]
I don't use Microsoft accounts so I'm not entirely sure how the system works right now. What exactly needs to be done?

**Comment by clydebottoms** [comment]
Currently you have to open a link and copy paste a code, it would be better if it just opened to the microsoft login site and asked you to sign in like other implementations do it.

**Comment by Jan200101** [comment]
If the URL is intended to be opened automatically [QDesktopServices::openUrl](https://doc.qt.io/qt-5/qdesktopservices.html#openUrl) can be used

**Comment by bbjubjub2494** [comment]
cons:
- Parity: DevLauncher doesn't do this, with the reasoning that there's no way to do it that's officially supported by MS. See [here](https://github.com/MultiMC/Launcher/issues/4101#issuecomment-922370353)
- Burden: we will have to write, support, and maintain it ourselves.
- Lack of flexibility: the manual log-in procedure can e.g. be performed on a different device entirely, which can be convenient. I personally benefit from it because I run Minecraft in a separate user account.

**Comment by Jan200101** [comment]
> * Parity: DevLauncher doesn't do this, with the reasoning that there's no way to do it that's officially supported by MS. See [here](https://github.com/MultiMC/Launcher/issues/4101#issuecomment-922370353)

Agreed.
Not only will this be a pain to maintain in the case Microsoft changes it.

> * Burden: we will have to write, support, and maintain it ourselves.

If Microsoft ever decides to change their API to make the ota stuff easier then DevLauncher might rework that code leaving us with a dead patch that needs to be weeded out.
Considering right now the User just has to press a button I agree that its not worth the effort

> * Lack of flexibility: the manual log-in procedure can e.g. be performed on a different device entirely, which can be convenient. I personally benefit from it because I run Minecraft in a separate user account.

I don't think thats a good argument
I assume you are on Linux, since I am not aware of any way of doing this on Windows or MacOS.
Running your apps as different users within the same X11/Wayland instance has many downsides and problems that might be encountered depending on the setup and I don't think that should be something that should be specifically targeted against.

**Comment by bbjubjub2494** [comment]
> I assume you are on Linux, since I am not aware of any way of doing this on Windows or MacOS.
> Running your apps as different users within the same X11/Wayland instance has many downsides and problems that might be encountered depending on the setup and I don't think that should be something that should be specifically targeted against.

With all due respect,
I was using 2 different computers, hence copying 10 letters by hand is quite handy.
I am aware that X11 has no GUI isolation. I heard Wayland does though.
I think overall this is an acceptable setup, irrespective of OS choice. And it would also work well with VT-x virtual machine graphics if the clipboard isn't shared. Do I think it should be a straight up design goal? Probably not, this is quite niche.

**Comment by ZekeZDev** [comment]
> cons:
> 
>     * Parity: DevLauncher doesn't do this, with the reasoning that there's no way to do it that's officially supported by MS. See [here](https://github.com/MultiMC/Launcher/issues/4101#issuecomment-922370353)
> 
>     * Burden: we will have to write, support, and maintain it ourselves.
> 
>     * Lack of flexibility: the manual log-in procedure can e.g. be performed on a different device entirely, which can be convenient. I personally benefit from it because I run Minecraft in a separate user account.

The parity part makes sense however the way devlauncher approaches this is different to everything else. Lunar, badlion, gdlauncher, curseforge, the official launcher all use a direct link. Having the user have to copy an expiring link is confusing for new users and can cause issues.

**Comment by ZekeZDev** [comment]
Perhaps a solution like this? https://github.com/MultiMC/Launcher/issues/4095 but instead of copy to clipboard its open in browser.

**Comment by Scrumplex** [comment]
We could add a button to the popup, that opens the URL using the system browser and copies the code to clipboard

**Comment by ghost** [comment]
Only problem is me and Lenny do not have M$ accounts and don't plan to migrate any time soon.

Someone else who does have a M$ account should probably make a PR and test; or, I can make the PR on Sunday and others can test.

**Comment by bbjubjub2494** [comment]
I am willing to test

**Comment by Scrumplex** [comment]
I have MSA, and am working on a draft as we speak :D

**Comment by Scrumplex** [comment]
@lourkeur Can you test PR #88? It works on Wayland, so preferably on X11?

**Comment by ZekeZDev** [comment]
@Scrumplex I can test it very soon.
