### ISSUE TITLE
Swap Modrinth and Curseforge in the download mods tab

### ISSUE THREAD

**Issue by Oondanomala** [PolyMC/PolyMC#558]
### Role

I point out tiny errors that don't really matter

### Suggestion

They should be sorted alphabetically

### Benefit

This makes the menu more consistent with the modpack download menu, and saves me a click since most mods are still on Curseforge

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

A project like this should not be biased! :P

**Comment by DioEgizio** [comment]
no

**Comment by LennyMcLennington** [comment]
We're biased towards services which actually care about their users.

**Comment by Oondanomala** [comment]
i understand, but you could have been less rude about it

**Comment by LennyMcLennington** [comment]
> i understand, but you could have been less rude about it

It wasn't my intention to be rude to you, sorry if it came off like that.

**Comment by Oondanomala** [comment]
don't worry its fine
