### ISSUE TITLE
newer minecraft versions default to java 17 or show warning.

### ISSUE THREAD

**Issue by ZekeZDev** [PolyMC/PolyMC#56]
### Role

playing 1.17 and onward

### Suggestion

newer minecraft versions default to java 17 reducing launch issues

### Benefit

currently you have to change your java version manually to launch 1.17. automatically selecting the latest java will help to remedy this.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Currently PolyMC users have to manually change java version for any new version of minecraft this is complicated especially for new users. Having the java version automatically switch to java 16 and warning the user if they dont have it installed will reduce confusion. Hopfully if #7 is completed there will be a way to install java 17 automatically after the warning or already have it installed.

**Comment by ZekeZDev** [comment]
This might be duplicate of #54 but I am not sure if that includes automatic swapping?

**Comment by ghost** [comment]
> This might be duplicate of #54 but I am not sure if that includes automatic swapping?

It doesn't. It simply checks.

We can kill both of these birds with one stone. I can make a branch for this whole subset of features.
