### ISSUE TITLE
Steam Deck: Unable to close Launcher in Game Mode

### ISSUE THREAD

**Issue by Xalcon** [PolyMC/PolyMC#563]
### Operating System

Linux

### Version of PolyMC

PolyMC 1.2.2

### Description of bug

When running PolyMC from Steam Decks Game Mode, the launcher cannot be closed manually as there is no close button. The steam decks "Force Quit" Key Bind `STEAM+B (Long Press)` is ignored as well. The haptic feedback occurs, but the launcher stays uninterrupted.

I've only found two ways to close the launcher:
1. Restart Steam Client via the Power Menu
2. Configure PolyMC to quit when MC quits

Option 2 wont work if the game crashes during startup since the Launcher will then ignore the "quit when mc quits" setting.

### Steps to reproduce

(Only applies to Steam Deck)
* Switch to Desktop Mode
* Add PolyMC to Steam Library
* Switch to Game Mode
* Run PolyMC

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Scrumplex** [comment]
Hmm weird. I can close the launcher through Steam on my Deck without any issues

**Comment by Xalcon** [comment]
Alright, nevermind then. Still learning the OS itself. You are right, using the `Steam Menu -> Exit Game` does indeed work. Force Quit via `STEAM + B (Long Press)` though does not - but i'm fine with Exit Game via Steam Menu.
