### ISSUE TITLE
Adjust ram for modpack

### ISSUE THREAD

**Issue by ZekeZDev** [PolyMC/PolyMC#57]
### Role

I play modded minecraft

### Suggestion

Have downloaded mods ram adjusted for optimal experience

### Benefit

many mods have a lot of issues or flat out wont launch if ram is set incorrectly.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

After using GDlauncher and curseforge for a bit I found it sets the ram for modpacks to fairly reasonable amounts. PolyMC sets and does not automatically adjust from the 1gb default ram. Most modpacks require upwards of 4gb of dedicated ram and having a way for PolyMC to detect that would be highly beneficial.

**Comment by ghost** [comment]
Are you saying that for modpacks we automatically set RAM to 4gb, if the user has enough?

**Comment by clydebottoms** [comment]
there's already a setting to change default ram (although it's set ridiculously low by default) how exactly do you want this implemented?

**Comment by ghost** [comment]
I personally believe it should be set to 4GB as a sensible default, instances where that is too much are the exception and almost every single computer in existence has 8 or more.

**Comment by ghost** [comment]
@ZekeSmith Is commit b19e3156 a suitable solution?

**Comment by ZekeZDev** [comment]
I belive it will work well for now however there might be a way to do it dynamicaly. I belive curseforge and gd do it dynamicaly.

**Comment by ghost** [comment]
It can't be as simple as `if mods are present, increase RAM`. Likely, modpacks in the MultiMC format would have to include the amount of RAM to use

**Comment by ghost** [comment]
> Likely, modpacks in the MultiMC format would have to include the amount of RAM to use

Aren't MMC modpacks just zipped MMC instances? If so, you can set/override memory allocation settings in the Settings tab.

**Comment by ghost** [comment]
In that case this needs no further attention.
