### ISSUE TITLE
suddenly crashing

### ISSUE THREAD

**Issue by vladdeda** [PolyMC/PolyMC#571]
### Operating System

Linux

### Version of PolyMC

polymc 1.2.1-dev

### Description of bug

https://0x0.st/omhf.txt

was working and loaded in just fine, polymc updated and now crashes when loading

### Steps to reproduce

running vault hunters modpack from curseforge

### Suspected cause

recent update

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by DioEgizio** [comment]
Update forge/downgrade java

**Comment by vladdeda** [comment]
I have Java version 8, which is the only version 1.16.5 will let it launch with. And forge is the version the modpack installs with.

**Comment by DioEgizio** [comment]
> I have Java version 8, which is the only version 1.16.5 will let it launch with. And forge is the version the modpack installs with.

https://polymc.org/wiki/getting-started/installing-java/#forge-1.16.5-and-java-8u321+

**Comment by Scrumplex** [comment]
This looks like an issue with your installation outside of PolyMC itself
