### ISSUE TITLE
Malformed zip files are badly handled

### ISSUE THREAD

**Issue by timoreo22** [PolyMC/PolyMC#572]
### Operating System

Linux

### Version of PolyMC

Polymc 1.2.2

### Description of bug

When using malformed zips such as the ones currently exported by packwiz, polymc cannot extract them (see packwiz/packwiz#115 )
Polymc should try to handle the zips, adding folder entries when missing

### Steps to reproduce

- Make a modpack using packwiz (exporting to curseforge, or modrinth)
- Try importing it
- Error extracting

### Suspected cause

This is probably rooted in Quazip's handling of zips, could be mitigated by trying to add theses missing folders to the zip before fully extracting them

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by flowln** [comment]
Should be fixed by https://github.com/PolyMC/PolyMC/pull/565/commits/82760f4b916ef122eabb644e8679f9ae76587e44, as it changes the handling of all zips in PolyMC to handle these cases.
