### ISSUE TITLE
Toolbar disappears if PolyMC exits abnormally after switching from menu bar to toolbar.

### ISSUE THREAD

**Issue by LennyMcLennington** [PolyMC/PolyMC#573]
### Operating System

Linux

### Version of PolyMC

1.2.2

### Description of bug

Toolbar disappears when you re-open PolyMC, after it exits abnormally after switching from menu bar to toolbar.

### Steps to reproduce

- Open PolyMC
- Go to Settings > Launcher > User Interface
- Check "Replace toolbar with menubar"
- Close the settings window
- Close PolyMC normally
- Open PolyMC
- Go to Settings > Launcher > User Interface
- Uncheck "Replace toolbar with menubar"
- Close the settings window
- Run `killall -TERM polymc`
- Open PolyMC
- The toolbar is gone. (🦀)

### Suspected cause

Maybe something to do with the fact that the layout can be moved around and the abnormal exit means it didn't have the opportunity to save the layout with the tool bar.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by LennyMcLennington** [comment]
May be able to fix it by using `APPLICATION->settings()->set("MainWindowState", mainWindow->saveState().toBase64());` after the option is toggled, to make sure that the saved state includes the toolbar when the toolbar is supposed to be there, even in the event of an abnormal exit.

I don't know how the pointer to the main window mainWindow should be found though because I don't know where in the code it needs to be called.

**Comment by kthchew** [comment]
> I don't know how the pointer to the main window mainWindow should be found though because I don't know where in the code it needs to be called.

You can likely do it at the end of this function:

https://github.com/PolyMC/PolyMC/blob/6d78ea5a457f510e95f179c3e33862af2f6c79a4/launcher/ui/MainWindow.cpp#L1859-L1869

**Comment by LennyMcLennington** [comment]
> > I don't know how the pointer to the main window mainWindow should be found though because I don't know where in the code it needs to be called.
> 
> You can likely do it at the end of this function:
> 
> https://github.com/PolyMC/PolyMC/blob/6d78ea5a457f510e95f179c3e33862af2f6c79a4/launcher/ui/MainWindow.cpp#L1859-L1869

cheers
