### ISSUE TITLE
Menu text to small on HiDPI

### ISSUE THREAD

**Issue by jkroepke** [PolyMC/PolyMC#574]
### Operating System

Windows

### Version of PolyMC

1.2.1

### Description of bug

On Windows 10 with a 4k HiDPI Monitor with 150% scaling, the menu text appears very small, close to unreadable.

<img width="1909" alt="2022-05-16 19_48_14-PolyMC - Version 1 2 1-5adcc261 - PolyMC" src="https://user-images.githubusercontent.com/1560587/168652646-290f20a1-aa14-4984-aeeb-e19fbd896ed4.png">

I guess the same issue exists on MultiMC, too. But the font is slightly larger and clear.

### Steps to reproduce

* Open PolyMC on a 4k HiDPI Monitor with 150% scaling

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by DioEgizio** [comment]
Can you try latest develop?

**Comment by Scrumplex** [comment]
Can you try PolyMC 1.4.0 (released today)?

**Comment by jkroepke** [comment]
Looks better, thanks
