### ISSUE TITLE
Github intergration now works

### ISSUE THREAD

**Issue by ZekeZDev** [PolyMC/PolyMC#582]
After many months of hard work we have finally intergrated github into our discord. With this amazing new technology we are able to bring peace to the galaxy.

**Comment by ZekeZDev** [comment]
this issue is very cool

**Comment by LennyMcLennington** [comment]
test

**Comment by LennyMcLennington** [comment]
ok it works properly

**Comment by Explodey-Wolf** [comment]
are you sure It works!

**Comment by LennyMcLennington** [comment]
yeah, but im disabling the comment webhook thing now because it would be really spammy

**Comment by ZekeZDev** [comment]
yeah agreed
