### ISSUE TITLE
CurseMeta will go down permantly soon.

### ISSUE THREAD

**Issue by dries007** [PolyMC/PolyMC#585]
### Role

I maintain CurseMeta.

### Suggestion

I leave that up to you.

### Benefit

I won't get a bunch of traffic or help request anymore :)

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

CurseMeta will go away soon as the underlying API is now officially dead.

Since you're a MultiMC fork, you inherited the code that calls my API.

Fun fact: I get about 2.5 million requests for your user agent monthly.

See also MultiMC/Launcher#4690.

**Comment by DioEgizio** [comment]
We don't use it anymore in PolyMC 1.2.2

**Comment by dries007** [comment]
Oh sorry for the ticket. Now at least you'll know if you get support questions.
