### ISSUE TITLE
CurseForge: "Some mod ID resolving tasks failed"

### ISSUE THREAD

**Issue by ConnorJC3** [PolyMC/PolyMC#593]
### Operating System

Linux

### Version of PolyMC

1.2.2-da25f3b8 (latest `polymc-bin` on Arch Linux)

### Description of bug

Error dialogue pops up during modpack installation: "Unable to resolve mod IDs: Some mod ID resolving tasks failed."
![image](https://user-images.githubusercontent.com/6501170/169153674-d17bb55a-f728-4c47-b87d-4cc5edc82dcd.png)

### Steps to reproduce

1. Attempt to install curseforge modpack
2. Whether or not a modpack triggers the bug is inconsistent, but I am currently able to trigger it 100% of the time with version "RLCraft 1.12.2 - Release v2.9.1c.zip" (i.e. the latest version) of RLCraft

### Suspected cause

Maybe the recent Curse API changes? #585 claims that 1.2.2 doesn't use CurseMeta though, so it could just be a coincidence.

It also could be some intermittent issue with Curse's website, but because they have no status page it's not easy for me to determine this. I skimmed their official communication methods such as twitter and saw no mention of an outage or similar.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Scrumplex** [comment]
CurseForge started to enforce the option for modders to disallow third-party applications like PolyMC and other launchers.

We probably can't fully fix this. If you find out which mod i causing this, tell the modder to toggle that option.

Example comment from @DioEgizio 
![CF Comment](https://cdn.discordapp.com/attachments/923671344921600201/976526761250652260/unknown.jpeg)

**Comment by ConnorJC3** [comment]
Is it possible to differentiate this error from other mod ID errors, to at least improve the error message to something like "mod X doesn't allow third party downloads"?

**Comment by Scrumplex** [comment]
Yes we were planning on handling this error more gracefully. Will probably be coming with the next release

**Comment by mondash** [comment]
> CurseForge started to enforce the option for modders to disallow third-party applications like PolyMC and other launchers.
> 

bruh

**Comment by FederAndInk** [comment]
this is so dumb, well, I think we'll be back to the old days of launchers opening the dl page of the mods that don't allow this...
damn you cursedforge

**Comment by ConnorJC3** [comment]
It'll never be included in PMC proper because of the obvious legal issues, but I assume the way the official launcher works is that it uses a special API key that doesn't have this restriction, so you theoretically could extract that API key and use it with PMC if I'm right about how it works.

**Comment by glektarssza** [comment]
> It'll never be included in PMC proper because of the obvious legal issues, but I assume the way the official launcher works is that it uses a special API key that doesn't have this restriction, so you theoretically could extract that API key and use it with PMC if I'm right about how it works.

This is entirely possible. Their API key is in plaintext in their app code. I haven't done so myself but I would think you could just plug it into PolyMC and it would work unless they're somehow checking what your client is. That wouldn't be hard to get around either, though...

**Comment by ConnorJC3** [comment]
Semi-related link I saw on /r/feedthebeast: https://git.sakamoto.pl/domi/curseme/-/blob/meow/getToken.sh

**Comment by d-513** [comment]
we will not endorse these methods because of obvious reasons, but there will be added a toggle to the APIs page where you can add a custom key.

**Comment by d-513** [comment]
> we will not endorse these methods because of obvious reasons, but there will be added a toggle to the APIs page where you can add a custom key.

https://github.com/PolyMC/PolyMC/pull/607

**Comment by mondash** [comment]
FWIW I tried downloading some packs yesterday evening that were giving me this error the night before and they worked this time. I'm guessing that just means some mod author(s) ticked this switch to allow 3rd party access.

**Comment by d-513** [comment]
> FWIW I tried downloading some packs yesterday evening that were giving me this error the night before and they worked this time. I'm guessing that just means some mod author(s) ticked this switch to allow 3rd party access.

Yes. If you see a mod not allowing, you should ask the author to allow it. The toggle is misleading (maybe on purpose?) so a lot of mod authors disable it without knowing.

**Comment by DioEgizio** [comment]
This (hopefully) shouldn't happen in develop atm

**Comment by brucethemoose** [comment]
> This (hopefully) shouldn't happen in develop atm

Any chance ya'll could post a prerelease in releases, for testing?

**Comment by d-513** [comment]
> > This (hopefully) shouldn't happen in develop atm
> 
> Any chance ya'll could post a prerelease in releases, for testing?

https://nightly.link/PolyMC/PolyMC/actions/runs/2363671111

**Comment by brucethemoose** [comment]
That was fast, couldn't even start downloading the build dependencies in time, thanks!

**Comment by d-513** [comment]
I dont think our release workflow is ready for pre-releases right now, so downloading latest commit from Github actions (or using nightly.link) is best

**Comment by brucethemoose** [comment]
That nightly build does seem to fix the mod downloading issue on a few packs that previously weren't working.

**Comment by Scrumplex** [comment]
We have been contacted by CurseForge, and we might need to remove our workaround. We are still clarifying with them. But I would call this a lost cause

**Comment by brucethemoose** [comment]
> We have been contacted by CurseForge, and we might need to remove our workaround. We are still clarifying with them. But I would call this a lost cause

What about a workaround requiring the presence of a Curse client install on the system? Could that mitigate whatever issue they're bringing up?


...How are other launchers working around this?

**Comment by ConnorJC3** [comment]
This has been "fixed" by #607, no other solutions will work long-term, closing (feel free to continue discussion).

**Comment by Scrumplex** [comment]
> This has been "fixed" by #607, no other solutions will work long-term, closing (feel free to continue discussion).

Actually.. #621

**Comment by Lgmrszd** [comment]
While there's no good workaround for that, how about providing links for mods for manual download, instead of showing just error message? So that user can download remaining mods.

**Comment by ConnorJC3** [comment]
There are improvements that can be made to improve the workflow when this problem is encountered, but the only fix that will work in any long-term capacity is using an API key that has access to the mods you need to download. #607 adds a way to supply your own API key.

Other than that, contact Curseforge and let them know you think this change is bad and hope they change their minds.

**Comment by brucethemoose** [comment]
> While there's no good workaround for that, how about providing links for mods for manual download, instead of showing just error message? So that user can download remaining mods.

I agree with this. Not sure if this is already in the fix, but some notification about what mods can't be downloaded would be extremely helpful. 

In the last release, the downloader would just silently fail.

**Comment by Revemohl** [comment]
Seconding, thirding, or whatevering the idea about showing which mods exactly failed to download instead of throwing a generic error message and failing the entire download/import process, unless that really isn't possible due to quirks regarding how modpacks are installed. Having the whole instance prepared except for a few mods which you need to download manually and stick into the mods folder would be a decent way to solve this issue despite requiring a few manual steps.

**Comment by goodtrailer** [comment]
I like what they did for ATLauncher, which is just automatically opening forgecdn mod download links in the user's default browser, detecting when they've finished downloading into the user's Downloads folder, and then moving the jars into the modpack instance folder. This is pretty nice because it's all automated, so imo this could be a pretty nice option to have.

**Comment by d-513** [comment]
> Seconding, thirding, or whatevering the idea about showing which mods exactly failed to download instead of throwing a generic error message and failing the entire download/import process, unless that really isn't possible due to quirks regarding how modpacks are installed. Having the whole instance prepared except for a few mods which you need to download manually and stick into the mods folder would be a decent way to solve this issue despite requiring a few manual steps.

That’s what we plan on doing.

**Comment by Lgmrszd** [comment]
> I like what they did for ATLauncher, which is just automatically opening forgecdn mod download links in the user's default browser, detecting when they've finished downloading into the user's Downloads folder, and then moving the jars into the modpack instance folder. This is pretty nice because it's all automated, so imo this could be a pretty nice option to have.

What about having built-in web-view, to allow user to log in and store CF session cookies, and then opening said forgecdn links in it to download the mods? Basically the same idea but more integrated.

**Comment by d-513** [comment]
> > I like what they did for ATLauncher, which is just automatically opening forgecdn mod download links in the user's default browser, detecting when they've finished downloading into the user's Downloads folder, and then moving the jars into the modpack instance folder. This is pretty nice because it's all automated, so imo this could be a pretty nice option to have.
> 
> What about having built-in web-view, to allow user to log in and store CF session cookies, and then opening said forgecdn links in it to download the mods? Basically the same idea but more integrated.

included web view would weigh too much

**Comment by Continous** [comment]
> > > I like what they did for ATLauncher, which is just automatically opening forgecdn mod download links in the user's default browser, detecting when they've finished downloading into the user's Downloads folder, and then moving the jars into the modpack instance folder. This is pretty nice because it's all automated, so imo this could be a pretty nice option to have.
> > 
> > 
> > What about having built-in web-view, to allow user to log in and store CF session cookies, and then opening said forgecdn links in it to download the mods? Basically the same idea but more integrated.
> 
> included web view would weigh too much

Could just provide a link to the mod page, and have a place for them to then pick the downloaded file.

**Comment by ImUrX** [comment]
is it possible to implement a way to patch your code or maybe add support for addons?
tbh its a solution that gives the user responsibility on what they want to do

**Comment by glektarssza** [comment]
> is it possible to implement a way to patch your code or maybe add support for addons? tbh its a solution that gives the user responsibility on what they want to do

Letting the user use a custom CurseForge API key basically does that. If you want to go get your own API key (and agree to CurseForge's ToS) then the onus shifts onto you if you decide to do things you're not supposed to with that key. I think the combination of this feature plus supplying some kind of list of "missing" mods for the user to go download manually is a good solution.
