### ISSUE TITLE
Auto-detect feature detects unexpected versions of Java

### ISSUE THREAD

**Issue by sudobeans** [PolyMC/PolyMC#596]
I am using MultiMC on Pop!_OS and it is flatpak version 1.2.2. (This is the latest version as of 18 May 2022.)

Hello, sorry for leaving a message here but I was not able to get the Matrix support chat room to work. I just switched from MultiMC to PolyMC. PolyMC's Java auto-detect button detects different versions of Java than MultiMC.

![Screenshot of MultiMC vs PolyMC](https://user-images.githubusercontent.com/12636657/169206474-afde8a4e-2bad-4133-94ce-3d946a604464.jpg)

I want to know what's up before uninstalling MultiMC. Why are the Java versions in different locations? Where is the /app/ folder on my computer? I can't find it anywhere.

Thanks!

**Comment by d-513** [comment]
Flatpak has its own java, /app is a virtual directory, you can’t use system java in flatpak

**Comment by sudobeans** [comment]
Ah, so it's a Flatpak thing. Good to know. Thanks.
