### ISSUE TITLE
Add a way to login to multiple Mojang accounts from a text file.

### ISSUE THREAD

**Issue by forwind0001** [PolyMC/PolyMC#598]
### Role

I use a lot of accounts.

### Suggestion

I suggest a way to add many accounts just from a credentials in a text file.

### Benefit

Adding more than one account one by one manually would consume too much time. Therefore, if there is a way to add multiple accounts from a single text file, that would cut some time used.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

The text file may be formatted in a way such that:

```
email1:password1
email2:password2
email3:password3
...
emailn:passwordn
```

If any of the account is unable to be logged in, the process should not break and the next account should be logged in instead.

**Comment by Scrumplex** [comment]
Not possible once Mojang logins stop working, as Microsoft Authentication will require interaction from the user

**Comment by forwind0001** [comment]
The issue was opened for Mojang accounts in mind. But thinking again, going forward, Mojang login will stop working completely anyway. Closed.
