### ISSUE TITLE
[Suggestion] Use optimized java arguments by default

### ISSUE THREAD

**Issue by ConnorJC3** [PolyMC/PolyMC#610]
### Role

For users that are new to modded minecraft and want a launcher that "just works"

### Suggestion

Use optimized JVM arguments by default (see below)

### Benefit

so users aren't leaving free performance gains on the table

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

When you recommend a new player to modded minecraft, there's a lot of steps just to get to a baseline playable level of performance, especially on lower end machines: download a launcher, setup JVM args, enable `alwaySetupTerrainOffThread` if on forge, install performance mods, etc. PolyMC unfortunately can't easily help users with most of these steps, but there is one place we can: the JVM arguments.

As of right now, PolyMC defaults to using no performance-related JVM arguments (other than the RAM specified by the user). I would like to propose changing that default to:
```
-XX:+UseG1GC -Dsun.rmi.dgc.server.gcInterval=2147483646 -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
```

These arguments are extracted from [this reddit post](https://old.reddit.com/r/feedthebeast/comments/5jhuk9/modded_mc_and_memory_usage_a_history_with_a/), and are pretty much guaranteed to increase performance compared to the default of nothing. Anecdotal testing shows improvements in literally every situation I've seen them used, from potato-tier laptops to top of the line gaming PCs.

**Potential caveats:**

*G1GC performance is questionable on Java 7 and not implemented in previous versions*

Java 7 has been EOL since 2015, users running it have much more serious problems like all the unpatched security vulnerabilities.

*These arguments are specific to the hotspot JVM*

Hotspot is the de-facto default on all relevant platforms, and users installing an alternative JVM are presumably knowledgeable enough to configure their own JVM arguments.

**Comment by ryanccn** [comment]
I've also seen this:

```
-XX:+UnlockExperimentalVMOptions
-XX:+UseG1GC
-XX:G1NewSizePercent=20
-XX:G1ReservePercent=20
-XX:MaxGCPauseMillis=50
-XX:G1HeapRegionSize=16m
-XX:-UseAdaptiveSizePolicy
-XX:-OmitStackTraceInFastThrow
-XX:-DontCompileHugeMethods
```

That's pretty similar but adds a few more.

**Comment by DioEgizio** [comment]
i think it's better to not mess up with jvm arguments by default but keeping the user to do it

**Comment by Continous** [comment]
Unless people can explain exactly what each of these arguments do and why they should be appended by default, and then no I really dislike the idea of adding them.

Also do we know at all if these differ between Oracle and OpenJDK implementations? Or versions of Java?

**Comment by ConnorJC3** [comment]
@Continous 
> Unless people can explain exactly what each of these arguments do and why they should be appended by default, and then no I really dislike the idea of adding them.

Click the link to the reddit post that is my source, long time forge developer cpw explains it better than I ever could. I'm generally against adding random arguments with no logical reasoning behind, but these all are explained.

> Also do we know at all if these differ between Oracle and OpenJDK implementations?

Not in any meaningful way.

> Or versions of Java?

Not in java 8+

**Comment by DioEgizio** [comment]
Honestly we shouldn't mess up with JVM arguments by default

**Comment by Cynosphere** [comment]
Having these be available behind a troubleshooting dialog would be a better option than a "sensible default" approach in my opinion. Even as someone who's used these arguments for years as a sensible default, the better option is to recommend if needed opposed to force, even if there is no effect in most newer versions or not.

**Comment by luni3359** [comment]
> I'm generally against adding random arguments with no logical reasoning behind, but these all are explained.

The way these were "explained" doesn't really inspire much confidence. I still don't know what `-XX:+UnlockExperimentalVMOptions` does.

**Comment by glowiak** [comment]
Or there should be a checkbox 'Use optimized java arguments'

**Comment by glowiak** [comment]
But IMO, the defaults are pretty good

**Comment by ryanccn** [comment]
> > I'm generally against adding random arguments with no logical reasoning behind, but these all are explained.
> 
> The way these were "explained" doesn't really inspire much confidence. I still don't know what `-XX:+UnlockExperimentalVMOptions` does.

@luni3359 it basically enables all the options starting with `-XX:`, because those are experimental. If you don't specify this flag using the other options will trigger an error in the JVM.

**Comment by ConnorJC3** [comment]
Hiding them behind a (default-off) setting would defeat the purpose of this suggestion, the point is to make it as easy as possible for new players to use PolyMC - they shouldn't have to think about java arguments. As an alternative to adding them as a default, asking about them during the initial setup wizard could probably also work?

As an addendum: it also might be worth adding `-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump` on Windows, as the official vanilla launcher does that and the name implies it somehow helps with performance.

**Comment by ryanccn** [comment]
now initial setup wizard is a good idea

**Comment by ryanccn** [comment]
> Hiding them behind a (default-off) setting would defeat the purpose of this suggestion, the point is to make it as easy as possible for new players to use PolyMC - they shouldn't have to think about java arguments. As an alternative to adding them as a default, asking about them during the initial setup wizard could probably also work?
> 
> As an addendum: it also might be worth adding `-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump` on Windows, as the official vanilla launcher does that and the name implies it somehow helps with performance.

does PolyMC use the `["arguments"]["jvm"]` in the version manifest?

**Comment by txtsd** [comment]
I don't think we should be setting JVM flags for anyone considering the various JVMs that are available and used. Using G1GC explicitly was needed on Java 8. Current Java versions have other GCs like Shenandoah GC and ZGC.

Also that reddit post is over 5 years old. A lot has happened since then.

**Comment by ConnorJC3** [comment]
G1GC outperforms Shenandoah and ZGC for Minecraft (generally, in specific circumstances they may outperform G1GC - these args are a guaranteed improvement over the default however). Nothing much has changed in the last 5 years for GC tuning on Java, the arguments are up to date and useful for modern versions of Minecraft.

For what it's worth, alternative launchers such as CurseForge set their own performance JVM args. By setting none PolyMC is automatically slower by default than these launchers, and users are basically guaranteed to hit GC stutters making the game near-unplayable on medium to large modpacks.

**Comment by TrashboxBobylev** [comment]
> Hiding them behind a (default-off) setting would defeat the purpose of this suggestion, the point is to make it as easy as possible for new players to use PolyMC - they shouldn't have to think about java arguments. As an alternative to adding them as a default, asking about them during the initial setup wizard could probably also work?
> 
> As an addendum: it also might be worth adding `-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump` on Windows, as the official vanilla launcher does that and the name implies it somehow helps with performance.

this argument just makes JVM crashes be saved in minecraft's folder instead of nowhere

**Comment by Continous** [comment]
I think that, generally, we should also avoid using any feature the Java VM would typically prevent people from using. I don't think enabling experimental behavior is worth a potential performance gain. Even if other people do it.

**Comment by ConnorJC3** [comment]
@TrashboxBobylev that's what it literally does, but the side effect is tricking GPU drivers that perform specific optimizations based on the command line arguments into using them. This argument may already be delivered by the metadata as pointed out above though.

@Continous the hotspot JVM hides them behind a scary looking flag, but these features have been in the JVM for upwards of a decade. Bytecode patching is also something you're "not supposed" to do and the JVM makes hard but Minecraft mods/modloaders do it all over the place.

**Comment by kthchew** [comment]
> it basically enables all the options starting with `-XX:`, because those are experimental.

This is not necessarily the case. `-XX:+UseG1GC`, for example, is not experimental (at least in Zulu 1.8.0_332) and will work if you pass that argument alone.

Anyway, I don't think the default arguments, if any, should stray too far (if at all) from whatever the vanilla launcher does. (If I recall correctly, the vanilla arguments are very close to the ones given in the original post, including the experimental arguments, so it should be okay in that regard.) But the vanilla launcher has the benefit of coming bundled with Java that supports those arguments (and if a user changes it, that's on them) – PolyMC does not have the same guarantee.

Maybe there could be a whitelist of JVMs that give new users those arguments, and leave it blank as a fallback?

**Comment by ConnorJC3** [comment]
> Maybe there could be a whitelist of JVMs that give new users those arguments, and leave it blank as a fallback?

I thought about this, but I figured it wasn't a big deal because 99.9% of JVMs out there users are using support these arguments, and users installing an alternative JVM probably are technical enough to figure out java arguments on their own. Also, I don't know what the status on the work for this is, but it's planned for PolyMC to be able to manage its own java versions.

That said, a jank way to check support would be to just run `java ARGS_HERE -version`, which at least on the JVMs I just tested on (hotspot, openj9, zulu) all throw some sort of error if the option isn't supported (and presumably if the JVM doesn't throw an error the option is either supported or at worst does nothing).

**Comment by Continous** [comment]
We seriously need to actually demonstrate that these are even beneficial in the first place as well. In my testing these settings were _detrimental_ to integrated server performance. I seriously think this is a catch 22 and that PolyMC really would gain nothing but trouble by peddling "optimized defaults".

`the hotspot JVM hides them behind a scary looking flag, but these features have been in the JVM for upwards of a decade.`

There's probably a very good reason that these are hidden behind a scary looking flag instead of just a usual flag.

`Bytecode patching is also something you're "not supposed" to do and the JVM makes hard but Minecraft mods/modloaders do it all over the place.`

You'll note that PolyMC is not itself a mod loader, and again to reiterate, just because other people do it does not mean it is the right thing to do. Minecraft mods and mod loaders would likely be more than happy to _not_ utilize bytecode patching, but that is their only choice. We can choose not to do this, so the argument is further moot.

Let's also not forget that people are on drastically different platforms, and that things that may work on Windows or the latest Linux may not work on say Mac OS, or a LTS release of Linux. The fact that JVMs vary only hinders matters further. It'd be neigh on impossible to guarantee that these "optimized defaults" would never, in fact, degrade performance on any given system and as such we should probably just not have them at all.

**Comment by ConnorJC3** [comment]
@Continous can you provide your hardware specs, testing method, and JVM version? I was not kidding in the original suggestion when I said I have never seen these arguments significantly reduce performance (To be clear I'm not accusing you of lying, I'd like to see if you have some vastly different setup to what I know works for sure).

The official Mojang launcher adds these arguments (specifically, they use `-Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M`).

Unfortunately, it's really hard to "prove" any specific arguments increase performance. Unless someone here has reason to believe they know more about tuning java for the game than Mojang/Microsoft I suggest PolyMC adopt the arguments from vanilla (minus the `-Xmx2G`, as PMC has its own system for managing RAM), as there's no reason to stray from the vanilla defaults without reason to do so.

**Comment by Continous** [comment]
> @Continous can you provide your hardware specs, testing method, and JVM version?

I think you're missing the point. If we need this level of debugging to ensure why the arguments are or aren't working, we probably shouldn't be adding them just because.

> I was not kidding in the original suggestion when I said I have never seen these arguments significantly reduce performance (To be clear I'm not accusing you of lying, I'd like to see if you have some vastly different setup to what I know works for sure).

The fact that, simply launching the game with and then without them bore out an improvement in favor of not having them enabled for me, demonstrates enough that they are not worth adding by default. The entire point of an "optimized default" would be to be something that is more optimized.

> The official Mojang launcher adds these arguments

The official Mojang launcher assumes you're using a specific Java version (the one they ship) and we are not Mojang. Without knowing why Mojang chose these specific arguments, it's also simply not important what Mojang uses. For all we know, Mojang appends that on launch because that happens to be the default that the developer liked using during testing, and not as a result of performance testing.

> Unfortunately, it's really hard to "prove" any specific arguments increase performance. Unless someone here has reason to believe they know more about tuning java for the game than Mojang/Microsoft I suggest PolyMC adopt the arguments from vanilla

I suggest that not appending any arguments except those defined by the user is best, unless we can demonstrate that not appending Mojang's typical defaults is somehow detrimental. Otherwise, it should be up to the user to determine what is best for them.

> as there's no reason to stray from the vanilla defaults without reason to do so.

I'd suggest that since PolyMC does not have the benefit of assuming what Java version you're running we shouldn't even do that. Any given Java VM may behave wildly different with a given set of arguments, especially those that attempt to tune the more technical aspects of the JVM, like the garbage collector.

With all of that said, I would be entirely on board with providing some commonly used arguments as toggles similar to how PolyMC does RAM management.

**Comment by ConnorJC3** [comment]
@Continous I think you're looking at this backwards. The JVM used by Mojang is the de-facto default, and most users have setups that are very similar or identical to it. _Not_ including the arguments used by Mojang is detrimental to all those users.

This also leans in to why I asked for your setup - I can't really comment without knowing that. For all I know you're on some obscure platform like BSD. PolyMC should not choose to hurt the performance of the 95% of users running Hotspot on a Mojang-supported OS because the other 5% of users *might* see a detriment, but that is what is happening right now.

> it's also simply not important what Mojang uses. For all we know, Mojang appends that on launch because that happens to be the default that the developer liked using during testing, and not as a result of performance testing.

So you think that Mojang just happened to use the arguments already widely circulated in the community for performance tuning by accident? That something as important as JVM args were just randomly checked into the launcher with no approval or code review?
