### ISSUE TITLE
Help website is broken

### ISSUE THREAD

**Issue by OhaDerErste** [PolyMC/PolyMC#627]
### Operating System

Linux

### Version of PolyMC

PolyMC 1.3.0

### Description of bug

Help page shows a 404 error

### Steps to reproduce

Click on the Help button in the Instance settings
![image](https://user-images.githubusercontent.com/77100649/169841906-2a03d724-0e95-4f4f-a1ca-9f746fedd9a7.png)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by DioEgizio** [comment]
duplicate of #377 

tl;dr we don't have all help pages yet, help'd be good though
