### ISSUE TITLE
Remove MultiMC news feed

### ISSUE THREAD

**Issue by GriffintheFolf** [PolyMC/PolyMC#63]
### Role

N/A

### Suggestion

Remove this news feed, or perhaps replace it with the project's own

### Benefit

To further disassociate the project from MultiMC and its oppressive developer

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

In the main screen of the program (the Instance viewer), the news feed from MultiMC still exists. Clicking the "More news" button will also open the MultiMC site.

Given the attitude of the MMC dev, this feature should either be changed to a new news feed for the project, or be removed altogether.

Here is an example:
![image](https://user-images.githubusercontent.com/26304783/149434898-aa6a7835-6fda-4eca-a617-304920b536a5.png)

**Comment by ghost** [comment]
I've been considering changing this for sometime. Should we copy the MultiMC news feed over or start from scratch? I'm leaning towards the latter, and can use my website's RSS generation scripts for this.

And if I'm going to use the scripts and publish the Jenkins config, I could make a `polymc-misc` or similar repo that contains all this

**Comment by ZekeZDev** [comment]
I can have a look at importing the multimc news feed into the polymc website if you want that. Otherwise making a new news feed should be pretty easy.

**Comment by ZekeZDev** [comment]
Yep I just checked the multimc website code importing the posts should take a few minutes at most.

**Comment by ghost** [comment]
Most of it is irrelevant to us though, and I'd prefer to initialize an RSS using my scripts.

**Comment by ZekeZDev** [comment]
There is rss scripts apart of the website I dont think we need an external one it just pulls from the md files in the website.
