### ISSUE TITLE
Add version number to Windows installer

### ISSUE THREAD

**Issue by RuinTD** [PolyMC/PolyMC#644]
### Role

I handle PolyMC's manifest on WinGet

### Suggestion

The PolyMC version number should be included in the Windows installer

### Benefit

This would allow WinGet to detect PolyMC is outdated and update it

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

![](https://files.catbox.moe/txy749.png)

**Comment by txtsd** [comment]
CC @kthchew

**Comment by kthchew** [comment]
Interesting. The installer is already supposed to write the version to a registry key:

https://github.com/PolyMC/PolyMC/blob/7f73e57c679944d5ee8574476f9cbffc9e344785/program_info/win_install.nsi#L133

Do you know where winget checks the version (another registry key, something else)? I'm not too familiar with it.

**Comment by kthchew** [comment]
Actually, looking again, this might be a GHA thing:

https://github.com/PolyMC/PolyMC/blob/7f73e57c679944d5ee8574476f9cbffc9e344785/.github/workflows/build.yml#L100-L104

https://github.com/PolyMC/PolyMC/blob/7f73e57c679944d5ee8574476f9cbffc9e344785/.github/workflows/build.yml#L206

I'm not able to test right now, but I feel like it probably wrote the commit hash into the registry instead of the actual version number.

**Comment by txtsd** [comment]
Yea that's definitely a short commit hash. You should use this:

https://github.com/PolyMC/PolyMC/blob/7f73e57c679944d5ee8574476f9cbffc9e344785/CMakeLists.txt#L74-L77

**Comment by xIGBClutchIx** [comment]
Probably best would be to pass it somehow along like for Mac: https://github.com/PolyMC/PolyMC/blob/develop/CMakeLists.txt#L195

Launcher_RELEASE_VERSION_NAME seems like it would be best: https://github.com/PolyMC/PolyMC/blob/develop/CMakeLists.txt#L130

Or to manually add them together like done for Mac also.

**Comment by Scrumplex** [comment]
I was working on using configure_file (like in #669) for the nsis file. That would have replaced all PolyMC branding with the CMake values and the version would have been populated by CMake. But Windows stuff is cancer and I gave up after some time

**Comment by Scrumplex** [comment]
Feel free to test if this works correctly using the latest builds from GitHub Actions
