### ISSUE TITLE
when a pack has both a manifest.json and a modrinth.index.json, PolyMC prefers always the manifest.json

### ISSUE THREAD

**Issue by DioEgizio** [PolyMC/PolyMC#647]
### Operating System

Windows, macOS, Linux, Other

### Version of PolyMC

1.3.0 or higher

### Description of bug

when a pack has both a manifest.json and a modrinth.index.json, PolyMC prefers always the manifest.json

it'd be useful to use the modrinth.index.json here, since some packs use it to make people be able to use their packs on third party launchers (see https://twitter.com/VazkiiMods/status/1528923557488730112?cxt=HHwWgIC9zf_36bcqAAAA for example)

### Steps to reproduce

.

### Suspected cause

.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Scrumplex** [comment]
See #639

**Comment by DioEgizio** [comment]
That's another thing, this is modpacks having Both a modrinth index and a curseforge manifest

**Comment by Scrumplex** [comment]
No that's exactly what that fixes as well. Modrinth will be preferred with that PR

**Comment by DioEgizio** [comment]
Oh good then
