### ISSUE TITLE
Truncated text in the settings bar.

### ISSUE THREAD

**Issue by ibll** [PolyMC/PolyMC#648]
### Operating System

macOS

### Version of PolyMC

PolyMC Version 1.3.0

### Description of bug

When running PolyMC from my laptop with the display on my larger monitor, the text and icons in the Settings bar are weird. The icons grow outside their bounding and the text is truncated in the middle.

<img width="1084" alt="image" src="https://user-images.githubusercontent.com/61601241/170601850-79964276-f63b-47c8-a9cc-2e57e3b45d9b.png">

![image](https://user-images.githubusercontent.com/61601241/170602156-08d7f1a6-eb29-42ad-825d-b6c4905fbe15.png)

### Steps to reproduce

- Open PolyMC on my laptop.
- Drag it over to my second display.

### Suspected cause

My secondary screen is larger, but is has a lower pixel density and overall worse resolution, I think somehow the icons aren't scaling properly and causing the text to not fit.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by ibll** [comment]
This does not seem to happen with the 'Legacy' icon set.

**Comment by DioEgizio** [comment]
Probably Qt/HiDPI moment

**Comment by DioEgizio** [comment]
try a build from https://nightly.link/PolyMC/PolyMC/actions/runs/2393188872

**Comment by ibll** [comment]
The MacOS one in that link did fix it.
![SCR-20220608-298](https://user-images.githubusercontent.com/61601241/172548631-8e44d027-459f-4d9f-b2a4-38031c56991c.png)

**Comment by txtsd** [comment]
Should be fixed in latest version with the HiDPI revert.

**Comment by DioEgizio** [comment]
> Should be fixed in latest version with the HiDPI revert.

No it won't, it's a Qt bug and I can reproduce it, the only thing that could fix it is qt6

**Comment by DioEgizio** [comment]
Fixed in develop

**Comment by Scrumplex** [comment]
If you want to test this using our new Qt 6 builds, make sure **not** to download the "Legacy" builds. Those will still be affected. They are inteded for Windows versions before Windows 10
