### ISSUE TITLE
Modpack updating

### ISSUE THREAD

**Issue by DioEgizio** [PolyMC/PolyMC#65]
### Role

I play modded mc

### Suggestion

currently, modpacks don't update. This means if you want to upgrade you need to create a new instance

### Benefit

It would be more user friendly, nicer and better

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by schmensch** [comment]
Modrinth, a service providing open-source mods provides an API that we could maybe use: https://docs.modrinth.com/api-spec/

Curseforge, providing basically all mods for Minecraft, also has an API available: https://docs.curseforge.com/#accessing-the-service

**Comment by HalJordan** [comment]
On the one hand, I get where you're coming from, but I'm not sure any of the launchers do this do they? Typically, you want to keep the current working instance, and copy your world over, in case an update breaks the world, you can just go back to the working instance until there's a fix.

**Comment by DioEgizio** [comment]
> On the one hand, I get where you're coming from, but I'm not sure any of the launchers do this do they? Typically, you want to keep the current working instance, and copy your world over, in case an update breaks the world, you can just go back to the working instance until there's a fix.

I mean, other launchers like gd or curse just provide an option to simply update your modpack, in an easy way, without needing to create another instance and migrate worlds/config to the new one

**Comment by CodeF53** [comment]
Perhaps this could be achieved much easier by integrating packwiz.

https://github.com/packwiz/packwiz

This integration would likely also touch #144

**Comment by DioEgizio** [comment]
packwiz is cool but it's made for **creating** modpacks

**Comment by ZekeZDev** [comment]
@timoreo22 this might be within your expertiese if you can have a look at this I hope to have this done before 1.2.0

**Comment by XandarNull** [comment]
@Scrumplex @ZekeSmith , it's been months and i think this feature would be great, maybe the devs should reconsider adding it in the next update.

**Comment by ryanccn** [comment]
It's a work in progress

**Comment by kylhuk** [comment]
@ryanccn Any updates here?

**Comment by ryanccn** [comment]
> @ryanccn Any updates here?

@kylhuk PolyMC has had modpack updating since 5.0 for Modrinth and CurseForge modpacks!

Simply go through the process of adding a new modpack instance, and if you have an existing instance of that modpack it will ask if you want to update it to the selected version!

**Comment by ReiDaTecnologia** [comment]
> > @ryanccn Any updates here?
> 
> @kylhuk PolyMC has had modpack updating since 5.0 for Modrinth and CurseForge modpacks!
> 
> Simply go through the process of adding a new modpack instance, and if you have an existing instance of that modpack it will ask if you want to update it to the selected version!

I did that and nothing happened it just created the instance as normal

**Comment by TurnrDev** [comment]
> > @ryanccn Any updates here?
> 
> @kylhuk PolyMC has had modpack updating since 5.0 for Modrinth and CurseForge modpacks!
> 
> Simply go through the process of adding a new modpack instance, and if you have an existing instance of that modpack it will ask if you want to update it to the selected version!

I'm running PolyMC 6.1, and when I try this, my instance created from a mod pack doesn't get updated; it just creates a new instance.
