### ISSUE TITLE
Package in snap format on Linux

### ISSUE THREAD

**Issue by evanmohr** [PolyMC/PolyMC#655]
### Role

To play Minecraft

### Suggestion

I want PolyMC to be distributed in another packing format

### Benefit

This would make it easier for Ubuntu users to discover and install PolyMC, and similarly to the flatpak, all java versions can be included inside the snap itself

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

I am wondering if PolyMC would have any interest in maintaining a snap package for PolyMC. I know the Snap format isn't too popular among more hardcore Linux users for a few reasons, like slow startup times. However, this isn't an issue for snaps that follow good practices (like using the faster LZO compression method rather than XZ).

**Comment by txtsd** [comment]
I don't think any of the maintainers use Snap so it's unlikely. However, the community is welcome to do so.

**Comment by ZekeZDev** [comment]
Agree with @txtsd, official packaging is unlikely however like our other third party packages its welcome to be done and will be shown on the website download page distro specific packaging.
