### ISSUE TITLE
webp images don't work in the mod downloader

### ISSUE THREAD

**Issue by Ember-Ember** [PolyMC/PolyMC#663]
### Operating System
Linux mint 20.3

### Version of PolyMC

PolyMC 1.3.0

### Description of bug

The image should show, it doesn't
examples
----
**Iris**
![Screenshot from 2022-05-29 00-42-35](https://user-images.githubusercontent.com/48266942/170830639-5fdb72ba-bd3f-4b94-9625-c047c728c023.png)
 
BetterLeads
![Screenshot from 2022-05-29 00-47-48](https://user-images.githubusercontent.com/48266942/170830704-022e3422-8157-4c6c-af64-d6272702e137.png)

### Steps to reproduce

go to mod downloader, iris will have no image

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by DioEgizio** [comment]
What package are you using?

**Comment by MagentaPuppy** [comment]
.tar.gz

**Comment by DioEgizio** [comment]
What's your distro? You need to install the qt5-imageformats package from your package manager (the name of the package changes based on the distro)

**Comment by MagentaPuppy** [comment]
installing `qt5-image-formats-plugins` fixed it, thanks
Maybe it could be mentioned somewhere that you need that package?

**Comment by DioEgizio** [comment]
Distro packages already depend on it, appimage/MacOS/Windows already bundles it, but I could add something in the wiki for it
