### ISSUE TITLE
Issue with import zip pack

### ISSUE THREAD

**Issue by KorewaLidesu** [PolyMC/PolyMC#670]
### Operating System

Windows

### Version of PolyMC

PolyMC 1.3.0-dca4ea5c

### Description of bug

Import modpack but PolyMC not recognize formats

*Comment: Didn't check on other zip pack*

### Steps to reproduce

Download Nomifactory zip archive from GitHub, import and get the error *(please ignore the version in image as its the same as the above version)*
![image](https://user-images.githubusercontent.com/24401452/170866568-c3bb8f98-72f6-4b2c-bffa-7b6bd2d1d822.png)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Scrumplex** [comment]
Should be fixed in #671
