### ISSUE TITLE
Partial translations, despite them existing upstream

### ISSUE THREAD

**Issue by Madis0** [PolyMC/PolyMC#673]
### Operating System

Windows

### Version of PolyMC

PolyMC 1.3.0-dca4ea5c

### Description of bug

Some phrases are not translated in PolyMC, despite them existing on upstream MultiMC. 
I understand that you are adding features and for those, you have a translation platform, but all identical strings should still be pulled from upstream because they have more translators overall and it would ease the effort of PolyMC translators as well.
![image](https://user-images.githubusercontent.com/8611110/170869443-291d8cd0-9d92-46ff-91da-1b1dfa58dbc8.png)

### Steps to reproduce

1. Get latest MultiMC (dev preferred)
2. Get latest PolyMC
3. Switch to a specific language on both (Estonian on this image)
4. Compare

### Suspected cause

QT trickery that changes the string names so they don't match?

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Scrumplex** [comment]
We have our own translations. We recently changed those strings, so it might need to be retranslated. See https://hosted.weblate.org/projects/polymc/polymc/


The changes were about adding `&` characters to those strings, which are used for keyboard-based navigation

**Comment by Madis0** [comment]
> The changes were about adding & characters to those strings, which are used for keyboard-based navigation

Ahh, having translated strings for Linux programs I can understand what that means :D
I guess that's unfortunate then because a script would not be able to automatically generate those for translated strings.

**Comment by Scrumplex** [comment]
> I guess that's unfortunate then because a script would not be able to automatically generate those for translated strings.

Nope. Sadly not. Though clicking through Weblate should be fairly easy. If you want to fix those, you can probably look at the strings that "need editing" in Weblate.
