### ISSUE TITLE
Unable to detect modpacks, and zip import

### ISSUE THREAD

**Issue by Srdjan-V** [PolyMC/PolyMC#676]
### Operating System

Windows 10

### Version of PolyMC

Tested on dev build 65d23fc-Debug

### Description of bug

Some modpaks are not being recognized, for example E2E Extended.

### Steps to reproduce

The same behavior can be experienced with importing from zip and CF download
![image](https://user-images.githubusercontent.com/78452357/170875009-6ae0078c-e167-4885-a9e1-fc4da71c7955.png)

### Suspected cause

 My guess is that [this](https://github.com/PolyMC/PolyMC/blob/4f0f74d2011f23089f1a9240c6b12ddb3e746da7/launcher/InstanceImportTask.cpp#L165) line is not recognizing character encoding. Since after extracting the zip and re saving the manifest.json and re zipping it again, allowed the pack to be imported.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by DioEgizio** [comment]
that modpack opted out access to third party apps

**Comment by DioEgizio** [comment]
It's not "not getting recognised"

**Comment by Srdjan-V** [comment]
Are you sure, sine on 1.3.0 its working
![image](https://user-images.githubusercontent.com/78452357/170875365-fcdfe0b0-fdae-49be-8ef5-b2cdae11da27.png)

**Comment by DioEgizio** [comment]
Yes I'm *fully* sure, #645

**Comment by Scrumplex** [comment]
If rezipping the file fixes it, then it might be an issue with the modpack itself. We could try to work around this issue, but at least for me motivation for fixing CurseForge issues is very low.

**Comment by DioEgizio** [comment]
Well I checked with an API request and the modpack is opted out, I could try importing it though

**Comment by Srdjan-V** [comment]
>I could try importing it though

That is the problem its not recognizing the manifest.json

**Comment by DioEgizio** [comment]
no that's just false, importing manually now without rezipping worked fine

**Comment by DioEgizio** [comment]
so yeah, it's just that the modpack is opted out so the modpack downloader can't download it and it works completely fine adding it manually

**Comment by Srdjan-V** [comment]
I have no clue why its now working. Can someone tell me if a CF api key is ip based, since i have used it with a different instance of polymc.

**Comment by DioEgizio** [comment]
No it's not ip based

**Comment by Srdjan-V** [comment]
So im unable to reproduce the zip import bug, and you have identified that the author has oped out of third part.
I will be reopening this issue if i find a way to reproduce it.
