### ISSUE TITLE
Utilize Native-style File selection in Windows

### ISSUE THREAD

**Issue by Justfines** [PolyMC/PolyMC#696]
Version: PolyMC Version 1.3.1-d7fad4bd, from the polymc website download page
OS: Windows 10 21h1 19043.1706

**Issue:**
While choosing a file in PolyMC, the file selection prompt utilizes a stylisation that is not as featured than a native-style one like MMC previously has used. In addition it currently doesn't follow the system-wide set "dark mode" setting in Window's Settings/Personalization/Colors menu

This is actually quite a downgrade, as the "look in" drop down (in my case) doesn't allow directory path input, nor has shortcuts to Window's Library shortcuts (like for the Downloads Library).

PolyMC Current:
![WegQ0LTLEx](https://user-images.githubusercontent.com/22578581/171538156-d0f00e62-0c02-4ad0-997f-5071259ef16f.png)

MMC:
![AHRkqe64yZ](https://user-images.githubusercontent.com/22578581/171538257-161509e5-bafd-4d6e-8b27-eb019fbb9553.png)

**Comment by DioEgizio** [comment]
Qt bug

**Comment by Justfines** [comment]
Alright, How would I go about appropriately bug reporting it to Qt?

**Comment by Scrumplex** [comment]
This could be a bug with the Qt distribution we are using (MSYS2). Maybe we should first research before reporting it upstream

**Comment by Justfines** [comment]
What may I do to help research this issue then?

**Comment by Justfines** [comment]
Decided to do some tests; using the builds from the Github Actions Artifacts (#1233) it seems to only not work on the x86_64 version of PolyMC, but acts as desired with the i686/32bit version.

**Comment by Scrumplex** [comment]
We are probably gonna drop 64-bit builds. Not sure if it's a problem with PolyMC, Qt or MSYS2, but it just doesn't work reliably.

**Comment by Justfines** [comment]
I think thats good enough to close the issue. Alright.
