### ISSUE TITLE
Add option to close PolyMC after launching the game [multimc suggestion]

### ISSUE THREAD

**Issue by ZekeZDev** [PolyMC/PolyMC#70]
### Role

playing minecrat

### Suggestion

Add a setting to close MultiMC after launching the game

### Benefit

similar to how the default minecraft launcher works close PolyMC after launching the game. may be benificial to low end computer's or planned arm release.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

From issue [#3406](https://github.com/MultiMC/Launcher/issues/3406) for multimc.

**Comment by clydebottoms** [comment]
![image](https://user-images.githubusercontent.com/94135507/149611186-5890c3d4-2075-4162-bcaf-878c86bc79a0.png)
I have significant doubts that it will be beneficial for low-end computers, not that there's a problem with doing this.

**Comment by ZekeZDev** [comment]
¯\_(ツ)_/¯ yeah I was mostly thinking of a way to justify it but even just having parody with the official launcher isnt bad. Its a small preference I know people who prefer it or will care about the extra 33mb of ram.

**Comment by ghost** [comment]
questions:
- when should we close PolyMC?
- Does Poly/MultiMC actually re-launch in case of a Minecraft crash?

**Comment by ZekeZDev** [comment]
1. After the game launches and there is a visible window. 

2. Yes

**Comment by ghost** [comment]
Okay. I'm not entirely sure how to detect when the window launches. Maybe you have to set up a listener that activates when GLFW messages pop up

**Comment by ghost** [comment]
It seems to launch right after:

`[12:05:38] [Client thread/INFO] [minecraft/Minecraft]: LWJGL Version: 2.9.4`
