### ISSUE TITLE
PolyMC doesn't set InstanceType=OneSix by default

### ISSUE THREAD

**Issue by DioEgizio** [PolyMC/PolyMC#704]
### Operating System

Windows, macOS, Linux, Other

### Version of PolyMC

1.3.1

### Description of bug

Basically, PolyMC doesn't set that by default.
Not an issue for PolyMC users, but a huge issue for backwards compatibility (multimc will think the instance is legacy when it's not)

### Steps to reproduce

.

### Suspected cause

#192 

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Scrumplex** [comment]
I changed this behavior back in #192 

I guess it's time to change this again
