### ISSUE TITLE
Modpack Update Feature

### ISSUE THREAD

**Issue by ghost** [PolyMC/PolyMC#706]
### Role

Modded Minecraft

### Suggestion

Add an option to update our modpack instance and find and delete old builds of the updated mods.

### Benefit

So we don't need to copy our stuff to the new instances.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

It will get the mod list of the selected mod pack and delete them from current instance, it will not touch all of the mods because there might be mods that are installed manually by user. Once this process finished, it will extract the mods and the configs from the modpack.

**Comment by flowln** [comment]
Duplicate of #65?

**Comment by ghost** [comment]
> Duplicate of #65?

Yes it is, I'm closing this issue.
