### ISSUE TITLE
Universal folder [multimc suggestion]

### ISSUE THREAD

**Issue by ZekeZDev** [PolyMC/PolyMC#71]
### Role

I use it to play multiple instances.

### Suggestion

I want there to be a universal folder or folders for worlds and resource packs.

### Benefit

Worlds and texture packs can be universal to be used across instances..

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

From issue [#4357](https://github.com/MultiMC/Launcher/issues/4357) and [#3861](https://github.com/MultiMC/Launcher/issues/3861) for multimc

## Approach
Add a universal option to the Folders menu that has a Resourcepack and Worlds subfolder

Or

Add a universal resource pack and universal worlds folder under the Folders menu.

### Extra
Possibly have a toggle to remove a pack from linking to universal folder(s)

**Comment by ZekeZDev** [comment]
![image](https://user-images.githubusercontent.com/81902668/149613578-980bc664-84ae-4c26-8c86-bd08ce1baa44.png)
or 2 folders
![image](https://user-images.githubusercontent.com/81902668/149613623-fe7a8fe2-81ef-4c49-9fd3-f4651ba7cf09.png)
/
![image](https://user-images.githubusercontent.com/81902668/149613646-5a093ced-9d3a-4fed-af09-a3026d993c56.png)

**Comment by d-513** [comment]
I agree 100%, used to do symlinks but it’s annoying

**Comment by ZekeZDev** [comment]
@dada513 What do you think of #73 I think it would make more sense since this will likely cause incompatibility issues.

**Comment by d-513** [comment]
Yeah that one seems better

**Comment by ZekeZDev** [comment]
alright ill close this issue in favor of #73
