### ISSUE TITLE
[GitHub page] License name can't be seen via the main PolyMC page

### ISSUE THREAD

**Issue by RaptaG** [PolyMC/PolyMC#713]
### Operating System

Linux

### Version of PolyMC

1.3.1

### Description of bug

The license name is shown in the main GitHub page of PolyMC

### Steps to reproduce

- Enter https://github.com/PolyMC/PolyMC/ and look for the license icon
- Instead of `GPL-3.0`, it says "View license"

Screenshot:
![Screenshot](https://user-images.githubusercontent.com/77157639/172001012-c63d3eb9-a9cf-48e5-98b0-841b98b7f756.png)

### Suspected cause

Incorrect license template?

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by DioEgizio** [comment]
It's a gh bug

**Comment by DioEgizio** [comment]
seems fixed now

**Comment by RaptaG** [comment]
> seems fixed now

Indeed!
