### ISSUE TITLE
macOS Shortcuts support

### ISSUE THREAD

**Issue by ryanccn** [PolyMC/PolyMC#717]
### Role

I use *(finally)* and contribute to PolyMC

### Suggestion

Add the ability to launch (or do other stuff) from Shortcuts

### Benefit

More automation capabilities for macOS!

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by kthchew** [comment]
Right now you can use the Run Shell Script action and then use the `polymc` command line options. I presume any shortcuts that would be added would have exactly the same functionality as the command line options.

But yes, of course actual Shortcuts support would be more user friendly.

**Comment by ryanccn** [comment]
I've never seen working Shortcuts support with a Qt app though...

**Comment by kthchew** [comment]
Well, Shortcuts is a macOS-specific feature. I don't think most cross-platform developers really consider that a priority. I mean, most first-class macOS native apps that I've seen don't have Shortcuts support.

Looking right now, I have a single non-Apple app on my Mac that donated any actions to Shortcuts. I didn't even know it supported it, lol

**Comment by kloenk** [comment]
I searched through QT references, and did not found a reasonable way to do it, so probably only via some objcpp.
Also when implementing this, PolyMC should donate the things doable via shortcuts to Siri when the user does it, so it can be discovered, wich also requires some more changes. Not sure how good this changes can be made with c++, I think most things have to be done with objcpp or swift.

**Comment by kloenk** [comment]
And it looks like QT does not expose the AppDelegate, which would probably even mean that we need to patch QT.

https://bugreports.qt.io/browse/QTBUG-38184
