### ISSUE TITLE
Add Dependencies to Mod Downloader

### ISSUE THREAD

**Issue by e-splat** [PolyMC/PolyMC#722]
### Role

Mod Downloader

### Suggestion

Download Dependencies together with Mods

### Benefit

When i download a mod, i need always to search a compatible version of a dependency

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by DioEgizio** [comment]
Duplicate of #211
