### ISSUE TITLE
make windows installer not create desktop shortcut in unattended mode

### ISSUE THREAD

**Issue by Un1q32** [PolyMC/PolyMC#730]
### Role

I use winget to update polymc

### Suggestion

i want the windows installer to not create a desktop shortcut when running in unattended mode

### Benefit

becuase i dont wanna have to always delete the desktop shortcut when i update

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Most people running the installer in unattended mode are updating via winget.  There's no point in recreating the desktop shortcut every time its run.  There can be a flag for creating a desktop shortcut in unattended so if someone really wants it they can still have it.

**Comment by kthchew** [comment]
This functionality should already exist. Use the `/NoShortcuts` flag.

**Comment by Un1q32** [comment]
@kthchew the winget version doesnt use that

**Comment by kthchew** [comment]
I’m not sure about the winget version.

CC @FayneAldan, because I seem to recall that you maintain that. Is it possible to pass additional flags to the installer?

**Comment by kthchew** [comment]
Actually, thinking about it again that’s probably not the best solution since the first install should probably still install the shortcuts.

The installer could probably detect if PolyMC is already installed, realize this is an “update,” then deselect the shortcuts by default (whether unattended or not).

**Comment by RuinTD** [comment]
> I’m not sure about the winget version.
> 
> CC @FayneAldan, because I seem to recall that you maintain that. Is it possible to pass additional flags to the installer?

I won't disable the shortcuts in WinGet for the reason you just mentioned, but you can override it yourself by running:
`winget install PolyMC --override "/S /NoShortcuts"`

I believe the standard for installers, however, is to not add a desktop shortcut by default. Maybe that could be changed on PolyMC's installer?

**Comment by Un1q32** [comment]
@FayneAldan i think @kthchew's solution is likely the best.  I use topgrade to update my packages which just runs `winget upgrade --all`

**Comment by RuinTD** [comment]
> @FayneAldan i think @kthchew's solution is likely the best.  I use topgrade to update my packages which just runs `winget upgrade --all`

The solution I gave was literally the same as @kthchew's? I said to pass `/NoShortcuts` to the installer. However, `winget upgrade --all` won't update PolyMC because of #644

**Comment by kthchew** [comment]
> The solution I gave was literally the same as @kthchew's

I think they meant the solution in my second message where I suggested having the installer not install the shortcuts by default if it detects that the program is already installed, so that you don’t need to pass an additional flag.

**Comment by Un1q32** [comment]
> > The solution I gave was literally the same as @kthchew's
> 
> I think they meant the solution in my second message where I suggested having the installer not install the shortcuts by default if it detects that the program is already installed, so that you don’t need to pass an additional flag.

this
