### ISSUE TITLE
Default to colored icons

### ISSUE THREAD

**Issue by d-513** [PolyMC/PolyMC#74]
### Role

I want icons to look good

### Suggestion

By default polymc uses ugly icons, but can be changed via settings to use colored ones. I would like the colored icons to be default

### Benefit

Users would like the style of the launcher more than the default icons

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by DioEgizio** [comment]
Yeah it would be nice, default icons are bad and colored ones are the best

**Comment by d-513** [comment]
Yeah gotta make a good first impression
