### ISSUE TITLE
abort button is broken on technic packs

### ISSUE THREAD

**Issue by DioEgizio** [PolyMC/PolyMC#768]
### Operating System

Windows, macOS, Linux, Other

### Version of PolyMC

PolyMC 1.3.1

### Description of bug

.

### Steps to reproduce

.

### Suspected cause

https://user-images.githubusercontent.com/83089242/172912398-e43d5895-08a1-4a70-902c-c3380e4e71d4.mp4

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by flowln** [comment]
I think this is fixed in develop. Can't reproduce in the latest commit :^)

**Comment by DioEgizio** [comment]
oh, I was using 1.3.1 stable :ioa:

**Comment by DioEgizio** [comment]
yes, doesn't happen on latest develop.

**Comment by TheKodeToad** [comment]
This is also the case when starting regular instances.
Hopefully this has been fixed too.

**Comment by DioEgizio** [comment]
It's not on latest develop
