### ISSUE TITLE
Win32/NTFS: Duplicate EXE name

### ISSUE THREAD

**Issue by AppleDash** [PolyMC/PolyMC#77]
### Operating System

Windows

### Description of bug

I expected there to be one PolyMC exe in the zip. Instead, there were two, which conflict on Windows. The lowercase one seems to work fine.

### Steps to reproduce

Extract the MultiMC Win32 zip - observe that there is a file named `PolyMC.exe`, and one named `polymc.exe`. These are the same file on Windows/NTFS filesystem. Windows' built in zip extractor seems to pick the lowercase one.

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by ghost** [comment]
This is caused because I forgot to delete the old (lowercase) EXE from testing

**Comment by ghost** [comment]
fixed in latest build

**Comment by AppleDash** [comment]
Thank you!

**Comment by ghost** [comment]
@AppleDash I actually lied, there was a weird problem with CMake that was creating the bad (this case, actually the UPPERCASE) exe. I've implemented a potential fix into Jenkins and it should work now on the latest build, I'll test right now.

**Comment by ghost** [comment]
fixed in latest build (forgor to close). Make sure your browser's download cache is empty.
