### ISSUE TITLE
Cannot install "Rustic Waters II" from CurseForge

### ISSUE THREAD

**Issue by skupr** [PolyMC/PolyMC#789]
### Operating System

Windows

### Version of PolyMC

PolyMC 1.3.2

### Description of bug

Cannot install "Rustic Waters II" from CurseForge.
It appears in the CurseForge search list, but when selected, "OK" button is disabled (and "Version selected" dropbox is disabled too).
![image](https://user-images.githubusercontent.com/783636/173272135-7f5dacae-cd12-4349-a508-6448ece218be.png)

### Steps to reproduce

1. Open PolyMC
2. Click "Add Instance"
3. Choose "CurseForge"
4. In "Search and filter..." input, enter "rustic"
5. Select "Rustic Waters II"

Expected: "OK" button is enabled, "Version selected:" shows latest modpack version
Actual: "OK" button is disabled, "Version selected:" is disabled.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by DioEgizio** [comment]
That modpack opted out access to third party apps, we can't do anything about it

**Comment by skupr** [comment]
Then maybe add some message that explains it? Similar as PolyMC already notifies that some mods cannot be downloaded because authors opted out.

**Comment by DioEgizio** [comment]
#697
