### ISSUE TITLE
"This account does not own Minecraft" when Microsoft authentication is down

### ISSUE THREAD

**Issue by ggtylerr** [PolyMC/PolyMC#790]
### Operating System

Windows

### Version of PolyMC

PolyMC 1.3.2-404b9599

### Description of bug

Whenever trying to launch any instance, PolyMC can't detect that the account playing is legitimate.

![polymc_fyq66c9USr](https://user-images.githubusercontent.com/28498877/173274491-9289bf8e-a1ec-48a8-9ff5-60fca722d9e2.png)

And yes, [I do own Minecraft.](https://namemc.com/profile/ggtyler.2) I have for several years.

### Steps to reproduce

* Login using a Microsoft (?) account
* Launch any instance
* Error

### Suspected cause

Opening PolyMC using command prompt reveals this:
```
   64.178 W QCoreApplication::postEvent: Unexpected null receiver
   64.179 D Task "LaunchController(0x12241079e00)" starting for the first time
   69.779 C Task "LaunchController(0x12241079e00)" failed:  "Launch cancelled - account does not own Minecraft."
   69.782 W QCoreApplication::postEvent: Unexpected null receiver
```

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by aethaerya** [comment]
I as well
![image](https://user-images.githubusercontent.com/28931355/173275961-854e8fe9-3cde-4d08-ba0e-f1495974d803.png)

**Comment by Gingeh** [comment]
Microsoft account authentication is currently down:
https://twitter.com/MojangStatus/status/1536181567986475008

This is not a problem with PolyMC. We just need to wait for Microsoft to fix their auth servers.

**Comment by ggtylerr** [comment]
> Microsoft account authentication is currently down: https://twitter.com/MojangStatus/status/1536181567986475008
> 
> This is not a problem with PolyMC.

Ah, okay, thank you. But it should 100% say that instead of saying you don't own it.

**Comment by aethaerya** [comment]
Is there any way I can play on my local server hosted on my computer *right now?* and bypass launching the demo?

**Comment by Gingeh** [comment]
@aethaerya You could try launching in offline mode, I don't actually know if that would work though.

**Comment by aethaerya** [comment]
It doesn't.

**Comment by ggtylerr** [comment]
> You could try launching in offline mode, I don't actually know if that would work though.

It does not. You can't even turn on airplane mode.

**Comment by timoreo22** [comment]
Closing this as the only way to fix this is to wait for microsoft auth to be back up

**Comment by ggtylerr** [comment]
> Closing this as the only way to fix this is to wait for microsoft auth to be back up

Like I said, there should at least be a string change that says the authentication is down. Or better yet allow offline play.
