### ISSUE TITLE
Improve automatic focus in the mod downloader

### ISSUE THREAD

**Issue by flowln** [PolyMC/PolyMC#803]
### Role

I use the built-in mod downloader a lot

### Suggestion

Change the way the focused element changes with certain actions

### Benefit

Better UX for adding lots of mods in a row

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

It gets kind of boring / time-consuming moving your cursor from side to side in the mod downloader to (Select mod -> Select version -> Repeat 10+ times). My suggestion is that, when you select a new mod, the focus automatically goes to the "Select mod for download" button, so that you can just press "Enter" to select it. After that, we could move the focus to the "Ok" button, or maybe leave it at the deselect button, i don't know :v

**Comment by jn64** [comment]
Focus definitely shouldn't change *away* from what you selected, that would break basic uses like moving through the search results using arrow keys.

A better solution would be some way to toggle the mod for download without moving the cursor or changing focus, like a hotkey or double-clicking the mod name.

**Comment by flowln** [comment]
Indeed, you have a point. I guess, instead of changing the focus so that the "Enter" key presses the "Select mod for download" button, we could have it be a hotkey that does the same action without changing the focus.

**Comment by Scrumplex** [comment]
Yes that sounds interesting. So maybe it should autoselect the latest version when double clicking a mod or pressing enter?

Then selected mods should probably be marked as such in a very clear way

**Comment by jn64** [comment]
> Then selected mods should probably be marked as such in a very clear way

I'd suggest **bolding** the mod name.

Other possibilities:

- Change the font colour
   - Make sure it doesn't clash with focus background colour
   - How does it interact with custom themes, Qt themes
- Change the background colour
   - Focus colour should take priority, so you can't tell if the focused item is also selected for download
   - Might look bad with some transparent mod icons
- Add an icon
   - Needs more space

**Comment by flowln** [comment]
Hmm https://github.com/PolyMC/PolyMC/pull/505?
