### ISSUE TITLE
Forge fails to generate its version files due to checksum missmatch

### ISSUE THREAD

**Issue by big-lip-bob** [PolyMC/PolyMC#809]
### Operating System

Linux

### Version of PolyMC

PolyMC 1.3.2 (`aur/polymc-bin`)

### Description of bug

Creating an instance with Forge on a MC version above 1.16.5 is impossible.
For some reason it complains about a checksum mismatch with the generated artifacts against a known sum.
I've tried installing PolyMC and those instances on a different drive to no avail.
Made and tried launching the game with purely new instances.

MC Version/Forge Version
[1.17.1/37.1.1](https://mclo.gs/6UNprvF)
[1.18.2/40.1.31](https://mclo.gs/2khipg6)
[1.19/41.0.37](https://mclo.gs/mT8P7eP)

The thing is that the same pack used for 1.18.2 works just fine in another launcher hence this being a PolyMC related issue ?
I've tried wiping the directories as well.

### Steps to reproduce

Create an instance with any MC version above 1.16.5 and install Forge.
Launch, expect a checksum mismatch ?

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Scrumplex** [comment]
Hmm. Interesting issue.

Can not reproduce on my end:

```
  Output: /home/scrumplex/.local/share/polymc/libraries/net/minecraft/client/1.17.1-20210706.113038/client-1.17.1-20210706.113038-extra.jar Checksum Validated: 483cfeb6029f2d180f740af4ea7ecb3613182772
  Output: /home/scrumplex/.local/share/polymc/libraries/net/minecraft/client/1.17.1-20210706.113038/client-1.17.1-20210706.113038-slim.jar Checksum Validated: b8de6b6dc0fc88232d974bdaaf085c56145277b1
```

(freshly generated)

**Comment by Scrumplex** [comment]
Have you tried clearing/deleting the `libraries` directory in `~/.local/share/polymc`?

**Comment by big-lip-bob** [comment]
After `rm -fr ./libraries`, and rerunning my 1.18.2/40.1.51 instance, had the getting libraries from Mojang dialog box, it still [mismatches](https://mclo.gs/lxJmrdH)

**Comment by Scrumplex** [comment]
Would you mind sending the files it mentions there? I would like to compare it to my local jar

**Comment by big-lip-bob** [comment]
After some quick `chattr +a *` (didn't compromise the integrity of the generated `.jar`s (matching hashes across logs: [(1)](https://mclo.gs/jQSwS5L) [(2)](https://mclo.gs/dTOSyD6))).
Here are the files in [1.18.2-20220404.173914.tar.gz](https://github.com/PolyMC/PolyMC/files/8934540/1.18.2-20220404.173914.tar.gz) from `/home/bob/.local/share/polymc/libraries/net/minecraft/client/1.18.2-20220404.173914/`

**Comment by Scrumplex** [comment]
Okay. Finally got around to checking this. It seems like the extracted contents of the archives are identical to my local archives. BUT! For some reason your archive's compression ratio is different? Your `-extra.jar` is 0.3% larger than mine. Which explains why yours has a different hash than mine.

So… Now the elephant in the room: Why? Can you send some information about your system? Distro, enabled custom repos (if applicable), PolyMC distribution method (Flatpak, official packaging (AUR, MPR), AppImage or custom build)

**Comment by big-lip-bob** [comment]
I have absolutely no idea, i just use Arch Linux and nothing too crazy ? And as I've said in the beginning, got PolyMC from AUR (`polymc-bin 1.3.2-1` (I use precompiled packages cause my i3-3220 is a slug at anything remotely intensive)).

**Comment by big-lip-bob** [comment]
even with the `aur/polymc 1.3.2-1` package that I manually compiled, took a good hour, it still errors out the same way, what does the Forge generator use to pack up the jars ?

**Comment by DilithiumNitrate** [comment]
I seem to have a similar issue with PolyMC, also on Arch Linux, with Forge on 1.16.5 specifically (might be higher versions too but I haven't tested), while Quilt and Fabric work. Do you get message boxes like this?
![polymc_checksum_failure](https://user-images.githubusercontent.com/38111406/176174200-ecb967e8-8c51-42b5-8edf-cd477e929dcc.png)

**Comment by big-lip-bob** [comment]
> I seem to have a similar issue with PolyMC, also on Arch Linux, with Forge on 1.16.5 specifically (might be higher versions too but I haven't tested), while Quilt and Fabric work. Do you get message boxes like this? ![polymc_checksum_failure](https://user-images.githubusercontent.com/38111406/176174200-ecb967e8-8c51-42b5-8edf-cd477e929dcc.png)

Yeah but on my end, it only affects versions of Forge above 1.16.5, neither Fabric or Quilt have this problem

**Comment by big-lip-bob** [comment]
Tested with the vanilla launcher and same story, so it **IS** in fact an issue on Forge's end, time to throw bricks at them instead

**Comment by big-lip-bob** [comment]
Fixed by https://github.com/MinecraftForge/JarSplitter/pull/2 (at least on my end)
