### ISSUE TITLE
Odd modrinth project

### ISSUE THREAD

**Issue by Ecorous** [PolyMC/PolyMC#813]
Modrinth mod "Matchbox" looks weird in PolyMC's modrinth search
![Image of weird mod](https://media.discordapp.net/attachments/923671181020766233/987735411289915422/unknown.png)

Reproduce:
1. Create an instance with Quilt 1.18.2
2. Search for `patch` in the modrinth search

**Comment by jn64** [comment]
It's 16x16 https://cdn-raw.modrinth.com//data/MwnoKRtL/icon.png

Modrinth isn't enforcing a minimum modrinth/code#2764

(or a maximum. I found a [1920x1920 "icon"](https://cdn-raw.modrinth.com//data/AFirzqTJ/icon.png) in my PolyMC cache)

What to do when icon is smaller than expected? Upscale or display as is?

**Comment by Scrumplex** [comment]
Modrinth's knossos UI doesn't do anything special with low-res icons (browser scales it up to fit into the image element), so I think we should just scale it up as well. Though in this case it would be pretty ugly, just let Qt use bilinear interpolation
