### ISSUE TITLE
Offline Mode Support

### ISSUE THREAD

**Issue by LennyMcLennington** [PolyMC/PolyMC#83]
The PR for Offline Mode Support #50 was reverted for the time being because myself and some others felt that it was merged too quickly without a proper discussion taking place about something so controversial. We still want to have a proper discussion about the feature, I'm making this issue to give it visibility. Please see #50 for the original proposal and previous discussion, and if you want to contribute to the discussion over there please do .

**Comment by ghost** [comment]
see #84
