### ISSUE TITLE
modrinth modpack sort is completely broken

### ISSUE THREAD

**Issue by DioEgizio** [PolyMC/PolyMC#833]
### Operating System

Windows, macOS, Linux, Other

### Version of PolyMC

every polymc release with modrinth pack downloader

### Description of bug

go to the modrinth pack downloader
change sort
see mess

eg
<img width="1126" alt="polymc" src="https://user-images.githubusercontent.com/83089242/175265160-f03140e6-b7a9-4558-9e1d-8b07a9cdce1d.png">

but on knossos

<img width="1521" alt="knossos" src="https://user-images.githubusercontent.com/83089242/175265375-efc36fa1-1f8e-43c0-9cbb-001ee0f985a4.png">

### Steps to reproduce

- go to the modrinth pack downloader
- change sort
- see mess

### Suspected cause

🤷 

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by jn64** [comment]
"Last updated" is getting recently created https://modrinth.com/modpacks?s=newest

"Newest" is getting follow count https://modrinth.com/modpacks?s=follows

Off by 1 somewhere?

**Comment by kthchew** [comment]
https://github.com/PolyMC/PolyMC/blob/349fc4143d4c83c50aa6340bbe7dc537a6fbf949/launcher/ui/pages/modplatform/modrinth/ModrinthModel.cpp#L159-L176

arrays start at 0

**Comment by jn64** [comment]
```cpp
#define 1 0
```

**Comment by Scrumplex** [comment]
> ```c++
> #define 1 0
> ```

While we are at it:

```cpp
#define 1 0
#define 2 1
#define 3 2
#define 4 3
#define 5 4
```
