### ISSUE TITLE
Old Minecraft Version are glitched

### ISSUE THREAD

**Issue by BGamerManu** [PolyMC/PolyMC#835]
### Operating System

Windows, Linux

### Version of PolyMC

PolyMC 1.3.2

### Description of bug

The istances created with an old version of are glitched or laggy

![2022-06-23_14 36 41](https://user-images.githubusercontent.com/63466244/175356619-7e4d893d-cda5-4d9a-8fec-343cb288e4f0.png)
![2022-06-23_18 34 21](https://user-images.githubusercontent.com/63466244/175356627-34e9836b-736a-4d17-ba0d-4eca77dc0fc5.png)

### Steps to reproduce

1. Create an istance with an old version of minecraft (like 1.6.4)
2. Launch the istance
3. Create a new world
4. Pick a block and put it in your hotbar
5. Take it on your hand

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by DioEgizio** [comment]
Not PolyMC-related, lol

**Comment by forkiesassds** [comment]
It's the good  old case of Windows being Windows and Intel being Intel.

**Comment by Frozenman-cell** [comment]
ik im late but this bug is caused by the newer intel drivers since late 2021 (november 2021?) and it has something to do with Opengl. Currently you can't fix this
