### ISSUE TITLE
(Latest Version) List update failed

### ISSUE THREAD

**Issue by xhatz** [PolyMC/PolyMC#838]
### Operating System

Windows 10 Ameliorated (AME)

### Version of PolyMC

1.3.2

### Description of bug

Whenever I try to create a new instance, I get the following message:

```
List update failed:
Job 'Download of meta file net.minecraft/index.json' failed to process:
https://meta.polymc.org/v1/net.minecraft/index.json
```

I don't know if it's because of the custom OS I'm using (Windows AME) or if the problem is global...

### Steps to reproduce

Create a new instance, or when trying to download Minecraft or Forge versions (requesting json)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by DioEgizio** [comment]
likely a network issue, but can you send PolyMC-0.log?

**Comment by xhatz** [comment]
Sure!
[PolyMC-0.log](https://github.com/PolyMC/PolyMC/files/8976268/PolyMC-0.log)

**Comment by DioEgizio** [comment]
> "The issuer certificate of a locally looked up certificate could not be found"

Likely your custom OS has outdated certs

**Comment by xhatz** [comment]
Is it because this version of Windows doesn't have any trace of Edge or Internet Explorer perhaps? I don't really know how to fix this :(

**Comment by DioEgizio** [comment]
no, it's a certificate issue

**Comment by xhatz** [comment]
For future users having this problem: the solution is to manually download the LetsEncrypt certificates from [their website](https://letsencrypt.org/certificates/).
Download the cross-signed der file, install it, and voila!

Thanks to **timoreo** for the solution <3
