### ISSUE TITLE
PolyMC Updater

### ISSUE THREAD

**Issue by Stellini101** [PolyMC/PolyMC#840]
### Role

I play modded minecraft

### Suggestion

Updater for Polymc

### Benefit

to make updating easier

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by DioEgizio** [comment]
Mod updating? #274, being worked on in #588 
Pack updating? #65 
Updating of PolyMC itself? #60
