### ISSUE TITLE
Re-write the man page in a format which will actually render correctly in a man-page viewer.

### ISSUE THREAD

**Issue by EliteTK** [PolyMC/PolyMC#844]
### Role

I read man pages.

### Suggestion

Either provide a man page in raw man troff, mdocml or probably preferrably scdoc format (which then gets converted at build time to the style of troff which man consumes). Currently it's some form of markdown.

### Benefit

When opening the man page it will look like a man page and not like I have accidentally opened a text file, it will also be rendered correctly.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Let me know which of the 3 options you would prefer and I will be happy to send a PR implementing it (unless it's the first option in which case I will not send a PR and will be sad).

I can provide the following benefits/drawbacks of using each format:

- Sticking with the current format
  - Benefits:
    - You don't have to do anything. It is simple to maintain. You already know the syntax (presumably).
    - Github renders this format for you nicely in its UI so it is readable when browsing the repository.
  - Drawbacks:
    - This is not the format man pages are written in and it doesn't look correct on linux systems.
    - I will be sad.
- Raw man troff format:
  - Benefits:
    - The man page will look correct and render correctly on all linux and also other unix and unix-like systems.
    - You will actually get to see the styling information in man page viewers.
    - I will be happy.
  - Drawbacks:
    - While I can happily do it as I know the format, the raw man troff format is horrific. Example here: https://the-tk.com/cgit/hktool/tree/hktool.1 This may not be the most maintainable as most people don't know troff.
- mdocml (http://mandoc.bsd.lv/):
  - Benefits:
    - The man page will look correct and render correctly on most linux and many other unix and unix-like systems as long as they support the mdocml format.
    - You will actually get to see the styling information in man page viewers.
    - It is a bit easier to write than the pure man troff format.
    - I will be happy.
  - Drawbacks:
    - While I can happily do it as I know the format, the mdocml format is a bit meh and not very intuitive either. Example here: https://raw.githubusercontent.com/openbsd/src/master/share/man/man1/intro.1 This may not be the most maintainable as most people don't know mdocml.
- scdoc (https://drewdevault.com/2018/05/13/scdoc.html):
  - Benefits:
    - The man page will look correct and render correctly on all linux and other unix and unix-like systems as long as the package is built on a system which contains a copy of the very portable and easily built scdoc binary.
    - You will actually get to see the styling information in man page viewers.
    - Github renders this format for you nicely in its UI so it is readable when browsing the repository. (https://github.com/swaywm/sway/blob/master/sway/sway.1.scd)
    - It is as easy to write as the current format and will actually not require much of a change.
    - I will be happy.
  - Drawbacks:
    - Your build will (optionally) depend on an installed copy of scdoc, that being said, scdoc is packaged in an awful lot of places (https://repology.org/project/scdoc/versions).

**Comment by jn64** [comment]
[The manpage is written in asciidoc](https://raw.githubusercontent.com/PolyMC/PolyMC/develop/program_info/polymc.6.txt) and clearly *meant* to be a manpage as you can see by the `:doctype: manpage` at the top. It just needs to be converted with [asciidoctor](https://docs.asciidoctor.org/asciidoctor/latest/manpage-backend/).

Small oversight, no rewriting needed.

**Comment by Scrumplex** [comment]
My vote also goes to `scdoc`.

**Comment by EliteTK** [comment]
@jn64 my mistake, that being said asciidoctor seems to be a much bigger build time dependency than scdoc (the former depends on a ruby implementation, the latter has no dependencies and is written in C). If I were to add it as an option to the list of options and pros/cons then it would look like this:

* Use asciidoctor to convert the current format into man troff:
  * Benefits:
    * The man page will look correct and render correctly on all linux and other unix and unix-like systems as long as the package is built on a system which contains a copy of asciidoctor.
    * You will actually get to see the styling information in man page viewers.
    * Github renders this format for you nicely in its UI so it is readable when browsing the repository.
    * It will not require any re-writing.
  * Drawbacks:
    * Your build will (optionally) depend on an installed copy of asciidoctor.
    * Depending on asciidoctor at build time implies depending on ruby which is a massive build time dependency in comparison to the alternatives.

@Scrumplex in light of the above, do you still feel like it would make sense to switch to scdoc or would you prefer, as @jn64 suggested, to make use of asciidoctor instead?

Edit: There also seems to be the plain "asciidoc" program which can do the same thing as asciidoctor presumably but instead it depends on python. That's still a big dependency but certainly more likely to be shipped in as many places as scdoc.

**Comment by EliteTK** [comment]
I've created a draft pull request in the meanwhile for the scdoc change, once it's clear what the chosen solution is I will mark it as a non-draft PR.
