### ISSUE TITLE
Play Offline not working with MSA when servers are offline

### ISSUE THREAD

**Issue by Scrumplex** [PolyMC/PolyMC#85]
### Operating System

Windows, macOS, Linux, Other

### Description of bug

When `https://api.minecraftservices.com/launcher/login` isn't reachable, *Play offline* doesn't work when logged in with MSA.

This dialog closes and re-appears every now and then.
![](https://scrumplex.rocks/img/1642502187.png)

```
   15.379 D "Mojang" is valid.
   15.379 D AuthFlow: "Accessing Mojang services."
   15.379 D Getting Minecraft access token...
   25.589 W AuthRequest::onRequestError: Error 499
   25.589 W AuthRequest::onRequestError: Error string:  "Error transferring https://api.minecraftservices.com/launcher/login - server replied: Gateway Time-out"
   25.590 W AuthRequest::onRequestError: HTTP status 504 "Gateway Time-out"
   25.590 D "<html>\r\n<head><title>504 Gateway Time-out</title></head>\r\n<body>\r\n<center><h1>504 Gateway Time-out</h1></center>\r\n</body>\r\n</html>\r\n"
   25.590 W Reply error: QNetworkReply::UnknownServerError
   25.590 D "<html>\r\n<head><title>504 Gateway Time-out</title></head>\r\n<body>\r\n<center><h1>504 Gateway Time-out</h1></center>\r\n</body>\r\n</html>\r\n"
   25.590 C Task "MSASilent(0x562df882aed0)" failed:  "Failed to get Minecraft access token: Error transferring https://api.minecraftservices.com/launcher/login - server replied: Gateway Time-out"
```

Related https://github.com/MultiMC/Launcher/issues/4433

### Steps to reproduce

1. Make sure `https://api.minecraftservices.com/launcher/login` isn't reachable
2. Open PolyMC
3. Click *Play offline* for any instance

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by PanoptesDreams** [comment]
I found a workaround for MultiMC that I hope applies here.

Simply completely block MultiMC (Poly in this case) in your firewall
After some thinking MultiMC will prompt for your Offline name then launch

I do not use Poly (I will in future) so I can't validate if this works here

**Comment by Scrumplex** [comment]
> I found a workaround for MultiMC that I hope applies here.

Thanks for taking your time, to report this here as well :D

It probably works here as well, as there isn't much (if any) difference between Multi and Poly when it comes to authentication

**Comment by PanoptesDreams** [comment]
> > I found a workaround for MultiMC that I hope applies here.
> 
> Thanks for taking your time, to report this here as well :D
> 
> It probably works here as well, as there isn't much (if any) difference between Multi and Poly when it comes to authentication

You're welcome, it seems the servers are back up so I wasn't even able to document it all properly 🤷‍♀️
Always next time..

**Comment by ezra-351** [comment]
This issue also arises on filtered network connections. Even when attempting to launch offline, I get an error saying "The account has expired and needs to be logged into manually again." I am able to relogin up until I authorize the program's access, and then I get an error from PolyMC saying "XBox user authentication failed." This is fixed when I use an unfiltered connection, but that's not always available to me. The workaround works until I forget to use it once, and I am no longer able to use the workaround until I can login on an unfiltered connection.

**Comment by SFort** [comment]
I'm usure if this is the same issue, but i'm assuming it's got an identical fix.
Clicking `play offline` on a MS account will not work.
While clicking `play` or `play offline` on a offline account works fine.
presumibly this is a mistake and `play offline` should be behaving  the same as an offline account

https://user-images.githubusercontent.com/1879846/166297037-5a34885e-6aa8-4ab9-97d8-d78f5cd20535.mp4


Glancing at the multimc issue suggests that this happened as an anti-piracy measure.
the thought that someone thinks minecraft piracy could be made easier got a good laugh out of me.
