### ISSUE TITLE
Show Minecraft Instance Version on Home Screen

### ISSUE THREAD

**Issue by bassistracer** [PolyMC/PolyMC#854]
### Role

I use multiple versions of Minecraft instances.

### Suggestion

Show the MC version of the current selected instance.

### Benefit

So I can quickly see which Minecraft version I'm working with.

### This suggestion is unique

- [x] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

As far as I know this hasn't been suggested before, unless my search-fu's gotten weak.
To the right of the home screen, showing off which version of Minecraft is being selected when you select an instance, preferably under the instance name, would be incredibly convent, and saves me about 5 seconds on going in manually to check the version or rename the instance to the version. This'll save time on me wondering if I'm working with something like 1.12.2, 1.16.5, or like, 1.18.2.

Thanks for reading.

**Comment by kthchew** [comment]
This actually seems like a bug. It seems like it is supposed to show in the status bar at the bottom, but doesn't for some reason:

https://github.com/PolyMC/PolyMC/blob/349fc4143d4c83c50aa6340bbe7dc537a6fbf949/launcher/minecraft/MinecraftInstance.cpp#L830

**Comment by zeroxoneafour** [comment]
I tested this and it does show the versions _if_ the instance has been launched before and the library/asset files have been downloaded
