### ISSUE TITLE
Instance becomes unusable if launch is aborted

### ISSUE THREAD

**Issue by zeroxoneafour** [PolyMC/PolyMC#856]
### Operating System

Arch Linux

### Version of PolyMC

PolyMC latest commit ([774ed04](https://github.com/PolyMC/PolyMC/commit/774ed044fcac9c444f41e0f93435089338e8366c))

### Description of bug

When launching the game, if the abort button is pressed at any stage (library download, asset download, initialization, etc), the launch will abort but the "Kill" button will not turn back into a "Launch" button. Restarting PolyMC does not work and killing the instance using the button does not work (you cannot open the kill dialog more than once after pressing kill). The only way to get out of it is to copy the instance and delete the bugged instance

### Steps to reproduce

* Install new instance with libraries that have not been downloaded yet
* Launch the instance and abort while downloading
* Try to launch it again

### Suspected cause

The abort button does not seem to be tied to the instance stopping, so maybe do that. The kill button presumably only works on the unlaunched command, so since the command never executes, the kill button never works. If the abort button was also tied to the instance stopping, the instance would return to a launchable state if it was aborted.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by DioEgizio** [comment]
#831
