### ISSUE TITLE
Remove the cat button

### ISSUE THREAD

**Issue by Bitwolfies** [PolyMC/PolyMC#86]
### Role

I play Minecraft

### Suggestion

Remove the cat button

### Benefit

I just dont see a need for it.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Maybe if it was better integrated as some sorta Easter egg, but it taking up real estate on the topbar just seems silly. 

~~inb4 this is some beloved feature no one wants to see removed~~

**Comment by DioEgizio** [comment]
But the cat is nice lol

**Comment by ZekeZDev** [comment]
Cet

**Comment by ZekeZDev** [comment]
In all seriousness though it doesnt take up used space its practically in white space. Perhaps we could make it a button for a custom background tho that would be pretty cool and make it more useful.

**Comment by ghost** [comment]
cringe

**Comment by d-513** [comment]
I say we replace it with dog button

**Comment by LennyMcLennington** [comment]
I like the cat, how small is your screen that it takes up too much space?

**Comment by ghost** [comment]
480p screen moment

**Comment by TheEssem** [comment]
heavily disagree with this

**Comment by ghost** [comment]
Given the backlash so far, this should not be considered.

**Comment by Scrumplex** [comment]
this was probably the most controversial feature request yet

**Comment by ZekeZDev** [comment]
@Scrumplex yeah
