### ISSUE TITLE
Add button when installing Fabric or Forge to automatically install "No Chat Reports" alongside instance.

### ISSUE THREAD

**Issue by mwnci9380** [PolyMC/PolyMC#861]
### Role

Replacing the vanilla launcher.

### Suggestion

Add a checkbox option when installing Fabric or Forge instances on 1.19 or higher that would automatically install "No Chat Reports" alongside the instance.

### Benefit

This would disable telemetry for Microsoft and immunize many people against unfair game-wide bans.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by DioEgizio** [comment]
No, this is something that should be done manually, it doesn't make any sense to do it automatically imo

**Comment by mwnci9380** [comment]
You have to consider there is a group of people who aren't aware enough to go out of their way to install the mod. A checkbox and a short explanation could potentially save a considerable amount of people.

**Comment by mwnci9380** [comment]
Idk if it's too much work than you find it to be worth, that's fair enough; simply a suggestion that I think could benefit a good few people.

**Comment by Heath123** [comment]
I feel like it would be better to have a general “featured modpacks” thing so it could also prompt people to get controller mods on the Steam Deck and performance mods

**Comment by DioEgizio** [comment]
I don't feel like officially endorcing modpacks like that in the launcher is the right thing to do; it can be demotivating and at the end big modpacks on modrinth like FO have both controller and performance mods

**Comment by Madis0** [comment]
1. As good as it is, it is just a one implementation of the feature
2. People unaware with mods may start asking about this in official support forums/bugtracker, which may rather negatively affect the mod itself
3. The mod is not perfect, it may have bugs that affect other mods etc.
4. Where do you draw the line of mods the launcher should suggest? Maybe Sodium is also essential? Or Roughly Enough Items? You get the point.

You're better off creating a modpack that just contains this mod, if you want people to be able to easily install it.

**Comment by Sneedplex** [comment]
People who don't know about mods probably aren't using PolyMC.
