### ISSUE TITLE
PolyMC launcher lagging bad

### ISSUE THREAD

**Issue by ghost** [PolyMC/PolyMC#866]
### Operating System

Windows

### Version of PolyMC

PolyMC 1.3.2

### Description of bug

I am running the portable x86_64 windows version and it lags so bad just in the PolyMC launcher (not in game) its so bad i cant click things properly nor can I even create a instance due to the lag. My pc isn't crap either it has a 12th gen intel i9-12900f and a rtx 3080 in it. Its really weird as MultiMC runs fine with no lag on the same pc but when I try PolyMC it just lags.

### Steps to reproduce

Start PolyMC and it lags.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by ghost** [comment]
Is there any dependency's I need?

**Comment by DioEgizio** [comment]
Try the i686 build, #484

**Comment by ghost** [comment]
that works perfect thanks <3
