### ISSUE TITLE
Cannot launch Demo Mode

### ISSUE THREAD

**Issue by MMK21Hub** [PolyMC/PolyMC#867]
### Version of PolyMC

1.3.1

### Description of bug

Previously, you could play Minecraft's Demo Mode by launching an instance while signed in to an account that doesn't own the game ("No Profile" accounts). However, since the account's session has expired, it is now impossible to use it (since you cannot re-add the account due to #422).

In addition, trying to log in with a Microsoft account that doesn't own Minecraft is not allowed:
![Error message](https://user-images.githubusercontent.com/50421330/177028260-4c3af38d-856b-42d0-a5f5-9471f5ffff81.png)

Therefore, there is no way to launch Demo Mode through PloyMC, without waiting for forced migration to end on 1 January 2099 or bypassing authentication somehow.

### Steps to reproduce

Try to add a Microsoft account (that doesn't own MC) to PolyMC

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by ryanccn** [comment]
Launching the game without buying it is piracy...? Demo mode is not really useful after all

**Comment by MMK21Hub** [comment]
> Launching the game without buying it is piracy...?

You indeed have to pay to access the full game, but Mojang provides a Demo Mode specifically for people who haven't bought the game. The vanilla launcher provides this functionality, and so did PolyMC back when Mojang accounts were functional.

> Demo mode is not really useful after all

I'll admit that most people using a 3rd-party launcher have probably already bought the game, but I don't think that the developers intended to remove this functionality when they implemented MS accounts.

My personal use case is testing MC bugs that can only be reproduced in Demo Mode. Another likely user is mod developers who need to check that their mod doesn't crash in Demo Mode.

**Comment by ryanccn** [comment]
Hmm. Would implementing Demo Mode specifically for PolyMC (e.g. a separate profile?) be worth it?

**Comment by MMK21Hub** [comment]
That looks like it would be one way to solve the problem, and it wouldn't require rethinking how MS accounts without profiles are handled.

**Comment by LennyMcLennington** [comment]
Do you specifically want a way to play Demo mode for people who *don't* own Minecraft? Or do you just want to play Demo mode and you already own Minecraft? We could probably add something in the instance settings that makes it possible to launch the game in demo mode.

**Comment by MMK21Hub** [comment]
Adding an option in the instance settings to launch the game in Demo mode would likely be the most useful, since very few people would install PolyMC before they've bought the game.
