### ISSUE TITLE
BeautyLine icon

### ISSUE THREAD

**Issue by RaptaG** [PolyMC/PolyMC#889]
### Role

I use the BeautyLine icon theme pack

### Suggestion

Create a PolyMC icon for the BeautyLine icon theme

### Benefit

It would match the rest of the icons (+ MultiMC has its own)

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by txtsd** [comment]
Can't tell if trolling or not with the typos :sweat_smile: 
> BeutyLine
> BeatyLine

But ask the BeautyLine maintainer at https://store.kde.org/p/1425426/
They don't seem to have an upstream code repo

**Comment by RaptaG** [comment]
> Can't tell if trolling or not with the typos

No, my bad 😬

> But ask the BeautyLine maintainer at https://store.kde.org/p/1425426/ 

Well, I once did on the link below, but they told to make one :C

> They don't seem to have an upstream code repo

https://gitlab.com/garuda-linux/themes-and-settings/artwork/beautyline

**Comment by txtsd** [comment]
Oh wow Garuda forked it.

We do have a few artists amongst our contributors that might be able to do it, but it would have to be on that repo, not here.

**Comment by RaptaG** [comment]
> Oh wow Garuda forked it.
> 
> 
> 
> We do have a few artists amongst our contributors that might be able to do it, but it would have to be on that repo, not here.

So, should I wait for response from contributors or should I close the issue?

**Comment by txtsd** [comment]
It's okay to keep it open.

**Comment by iSeth500** [comment]
![image](https://user-images.githubusercontent.com/15620903/179072309-eb9be6bd-184d-4e6c-b6a1-b5a331a94906.svg)

**Comment by txtsd** [comment]
Needs that sweet gradient in the green

**Comment by RaptaG** [comment]
> ![image](https://user-images.githubusercontent.com/15620903/179072309-eb9be6bd-184d-4e6c-b6a1-b5a331a94906.svg)

Very cool, but it should be a bit more neon I think

**Comment by iSeth500** [comment]
![image(1)](https://user-images.githubusercontent.com/15620903/179267403-d83b44ee-9379-4de5-82eb-e594f2167c24.svg)
Gradient?

**Comment by RaptaG** [comment]
It's fine nvm

**Comment by iSeth500** [comment]
I'll talk to the Beautylines guy and see what needs changing

**Comment by RaptaG** [comment]
Added in the latest update!

![](https://user-images.githubusercontent.com/77157639/194763786-415bde53-4e2a-4309-9179-535b8f6833af.png)
