### ISSUE TITLE
Bedrock Edition Instance

### ISSUE THREAD

**Issue by TeggolT** [PolyMC/PolyMC#891]
### Role

I play Java and Bedrock edition

### Suggestion

Add a way to launch bedrock edition (+dungeons,maybe?)

### Benefit

It grants easier switching and better sorting for players of java+bedrock.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

I just want a button to add an instance that links to the bedrock edition install. It'd work like any other instance, exept it wouldn't link to any java edition.

All I want is a way to launch the bedrock edition inside polymc, but features like mcpack support and polymc features could be ported to bedrock in the future.

Maybe some people would also enjoy that for Minecraft dungeons (and legends when it arrives).

**Comment by j0lol** [comment]
this would only work on windows, unless people are willing to reimplement mcpelauncher within polymc which seems kinda out of scope

**Comment by Scrumplex** [comment]
Not really possible. Apart from Bedrock edition being tied to the Windows Store, making it hard to manage from a third-party launcher like PolyMC, there is nothing we can reuse from our codebase for Bedrock Edition. PolyMC is a package manager for Java-based games. Anything not Java will be out of scope.
