### ISSUE TITLE
Global mod search

### ISSUE THREAD

**Issue by TeggolT** [PolyMC/PolyMC#892]
### Role

I use the mods tab and install mods using PolyMC's menu.

### Suggestion

Make it possible to search modrinth amd forge simultaneously 

### Benefit

It speeds up mod-searching

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

I want to have 3 tabs after clicking "downloas mods":
All
Modrinth
Forge
(Maybe new ones later)

The "all" tab would enable searching globally on both platforms. It's really nice to not have to type everything twice.
Settings for this feature could include:
Download priority
(Where do you download a mod that is on both sites (default))
Exclusion of sites in global search

This is a medium issue now, but if any new mods site was added to PolyMC this feature would be a life-saver.

**Comment by CodexNotFound** [comment]
To avoid having to filter out duplicates (and which one should take priority), an alternative could be just remembering the search term between each mod source. That way, if it's not on Modrinth, the user can just click on Curseforge and it will start searching with that same term.

**Comment by Un1q32** [comment]
> (and which one should take priority)
modrinth would take priority obviously, but I do agree it would be better to just remember the search term.

**Comment by CodexNotFound** [comment]
> modrinth would take priority obviously, but I do agree it would be better to just remember the search term.

Is it that simple though? Should Modrinth take priority in a case where the version on Curseforge would be newer?
