### ISSUE TITLE
Flatpak: Pack Java 8u312 instead of 8u322

### ISSUE THREAD

**Issue by unilock** [PolyMC/PolyMC#895]
### Role

I'm looking to play modded Minecraft < 1.17 using Forge.

### Suggestion

I want the Flatpak version of PolyMC to package Java 8 version 312 instead of version 322. (8u312 vs 8u322, 1.8.0_312 vs 1.8.0_322, etc.)

### Benefit

This will allow older versions of Forge to work properly.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

In particular, I'm trying to run a modpack based on Minecraft version 1.7.10, which requires a version of Forge that's at least 7 years old and will most definitely never receive an update to support newer versions of Java 8. Without allowing PolyMC to access my own copy of Java 8u312 (via `flatpak override --user org.polymc.PolyMC --filesystem=~/java`), the modpack simply will not run, crashing with a "GL ERROR" during initialization.

**Comment by DioEgizio** [comment]
Update your forge, not on our side because the flatpak just uses flathub's java 8

**Comment by txtsd** [comment]
> Without allowing PolyMC to access my own copy of Java 8u312 (via flatpak override --user org.polymc.PolyMC --filesystem=~/java), the modpack simply will not run, crashing with a "GL ERROR" during initialization.

Sounds like you have the solution in hand.

**Comment by unilock** [comment]
@DioEgizio
The latest version of Forge for 1.7.10 was released 7 years ago, and only supports Java 8u312, which will probably remain the case until the end of time.

@txtsd
Yes, it's a solution, but it's not ideal. It requires me to manually grant PolyMC access to a directory outside of its scope every time I install it (which I will admit is not very often), as well as maintain a second, unnecessary copy of Java 8.

Overall, it's an issue of ease of use.
Most people, I imagine, won't know that they need an older version of Java in order to run older versions of Forge.
Even if they do, they'll still have to go through the (relatively) complicated steps of downloading a specific version of Java 8, extracting it and keeping it permanently accessible in some directory, granting PolyMC access to the root of that directory, manually selecting that version of Java within PolyMC... etc.

Maybe I should take it up with Flatpak, but I'm not sure of the implications of having every Java 8 application they distribute use an older version of Java, only to satisfy this single use case. (Thus I doubt they would do anything.)

**Comment by Scrumplex** [comment]
> The latest version of Forge for 1.7.10 was released 7 years ago, and only supports Java 8u312, which will probably remain the case until the end of time.

Latest Forge for 1.7.10 works fine using Java 8u332 for me

**Comment by DioEgizio** [comment]
> The latest version of Forge for 1.7.10 was released 7 years ago, and only supports Java 8u312, which will probably remain the case until the end of time

That's just false. The only version affected by that was 1.16.5, but it was fixed in forge 36.2.26

**Comment by unilock** [comment]
> Latest Forge for 1.7.10 works fine using Java 8u332 for me

> That's just false. The only version affected by that was 1.16.5, but it was fixed in forge 36.2.26

Sorry, I assumed it wasn't working at all due to the majority of the 1.7.10 modpacks I've tested only working with Java 8u312.
You're both right; a stock installation of Forge 10.13.4.1614 on 1.7.10 starts just fine.

Perhaps it's a mod conflict? The modpack I'm testing in particular is [Dragon Realm](https://dragonrealm.overminddl1.com/index.php), which is very picky about the way it's set up, so it's not unlikely that it in particular requires the version of Java 8 most broadly used at the time 1.7.10 was a popular modding platform.

I recall [Regrowth](https://forum.feed-the-beast.com/threads/1-7-10-regrowth-a-wip-hqm-pack-now-listed.57184/) requiring Java 8u312 as well.

I'm not familiar with Flatpak, but maybe it's possible to specify an older version of [`org.freedesktop.Sdk.Extension.openjdk8`](https://github.com/flathub/org.freedesktop.Sdk.Extension.openjdk8) when building the package? Or create a branch of said extension that supplies Java 8u312?

**Comment by unilock** [comment]
> The modpack I'm testing in particular is [Dragon Realm](https://dragonrealm.overminddl1.com/index.php), which is very picky about the way it's set up, so it's not unlikely that it in particular requires the version of Java 8 most broadly used at the time 1.7.10 was a popular modding platform.

It works fine with Java 1.8.0_345. I am simply insane.
