### ISSUE TITLE
instant searching

### ISSUE THREAD

**Issue by DioEgizio** [PolyMC/PolyMC#908]
### Role

i use polymc

### Suggestion

i'd like search in mod/-pack to be instant and not require me to press enter every time, like on modrinth.com

### Benefit

better and cooler

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

idk if it's possible though :(

**Comment by txtsd** [comment]
I'd like to see this, but I also wonder what the resource usage will be like with fast updates of lists with images.

**Comment by DioEgizio** [comment]
I guess we could have an opt out

**Comment by kthchew** [comment]
> I'd like to see this, but I also wonder what the resource usage will be like with fast updates of lists with images.

Apps usually handle that problem by waiting for the user to stop typing for x amount of time before actually doing the search. So instead of searching with every keystroke, if the user stops typing for, say, 200 ms, then a network request is sent for the search and the list is updated.

**Comment by luni3359** [comment]
There should be some sort of way to indicate that the search is currently being done. I have connection issues sometimes where curseforge mods don't load and the search refuses to work altogether so I have to close and reopen the window, but to the user it would appear like there's no results after the search. This problem will be even worse with an automatic search.

**Comment by ryanccn** [comment]
> There should be some sort of way to indicate that the search is currently being done. I have connection issues sometimes where curseforge mods don't load and the search refuses to work altogether so I have to close and reopen the window, but to the user it would appear like there's no results after the search. This problem will be even worse with an automatic search.

same

**Comment by ryanccn** [comment]
we should probably do some throttling, debouncing, whatever it's called in UX with this thing

in Moddermore I originally made it use `react-debounced-input` but then I got lazy and made it be like PolyMC :trollface:

**Comment by DioEgizio** [comment]
#939
