### ISSUE TITLE
Use GPLv3

### ISSUE THREAD

**Issue by flexagoon** [PolyMC/PolyMC#91]
Your LICENSE file currently contains the text of GPLv1, which is old, and you should use GPLv3 instead. You should switch the license now before this project gets big and has a lot of contributors, because after that, switching a license would be pretty hard.

**Comment by Scrumplex** [comment]
Huh? `LICENSE` looks good
https://github.com/PolyMC/PolyMC/blob/35caa3c21afed378c73e2a448ac92e356f502281/LICENSE#L1-L2

`COPYING` as well

https://github.com/PolyMC/PolyMC/blob/35caa3c21afed378c73e2a448ac92e356f502281/COPYING.md#L6-L8

**Comment by flexagoon** [comment]
@Scrumplex Oh yeah, my bad. The license wasn't getting recognized by GitHub, so I assumed that it was GPL. Sorry.

**Comment by Scrumplex** [comment]
Oh. I think that's because GitHub prefers the COPYING.md over LICENSE. Not sure if we can override that
