### ISSUE TITLE
Download Requires/Related mods

### ISSUE THREAD

**Issue by CitizenFoffie** [PolyMC/PolyMC#910]
### Role

I like to download mods quickly without taking a million tabs to also download and find the required mods.

### Suggestion

Selected Related Mods and let me select versions.

### Benefit

It would allow people to not have to find related mods elsewhere

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by nitrog0d** [comment]
I was gonna suggest this into an issue, to make Curseforge download the required mods automatically when you download a mod, since someone already did it, I'll ask about my other question too. Would it be possible to add Cursefoge mod update check?

**Comment by DioEgizio** [comment]
Duplicate of #211

**Comment by DioEgizio** [comment]
> I was gonna suggest this into an issue, to make Curseforge download the required mods automatically when you download a mod, since someone already did it, I'll ask about my other question too. Would it be possible to add Cursefoge mod update check?

Soon™ #588

**Comment by timoreo22** [comment]
Duplicate of #211
