### ISSUE TITLE
Direct download for texturepacks.

### ISSUE THREAD

**Issue by elchupe123** [PolyMC/PolyMC#912]
### Role

I play modded and vanilla minecraft.

### Suggestion

I want a downloader for texturepacks from curseforge (or form another source) like the downloader of mods.

### Benefit

This would make easier to download texturepacks, so we woud not have to open the browser, download the texturepack and then put it in the folder. 

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by flowln** [comment]
Duplicate of #256
