### ISSUE TITLE
Modpack refusing to launch - Vault Hunters

### ISSUE THREAD

**Issue by ralancee** [PolyMC/PolyMC#926]
### Version of PolyMC

PolyMC 1.3.2

### Description of bug

The modpack launches for a couple seconds then closes the minecraft window.  

https://mclo.gs/XkK8Gok

### Steps to reproduce

Clicked launched. Then wait a couple of seconds and crashes. 

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by DioEgizio** [comment]
update your forge

**Comment by Scrumplex** [comment]
As @DioEgizio already mentioned, this can be fixed by updating Forge in that instance
