### ISSUE TITLE
Use makedeb for Debian packaging

### ISSUE THREAD

**Issue by hwittenborn** [PolyMC/PolyMC#93]
### Role

N/A

### Suggestion

Use makedeb to create the Debian packages

### Benefit

It will create a more solid workflow against a build specification that is known and guaranteed to work.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Hi! I was just looking across the repositories GitHub had in my recommended feed, and I noticed y'all were using [a custom script](https://github.com/PolyMC/PolyMC/blob/develop/packages/debian/makedeb.sh) for your Debian packaging.

It all looked fine, but I wanted to see if y'all would be interested in using [makedeb](https://github.com/makedeb/makedeb) instead, as I thought it might help make things more maintainable.

It's a product I've personally created, but I thought it could provide a lot of benefits for your Debian packaging. You'd be able to maintain everything in a single file, the build file itself would be against a known specification that others would know (makedeb is a recent project I've made in the last year, though quite a few people are already using it), and I feel like it would just be less hacky in general than maintaining a custom script.

Looking at the current setup, you'd only need the following to build the package with makedeb (the `build()` function may need to be altered a bit though):

```sh
# Maintainer: PolyMC Team
pkgname=polymc
pkgver=
pkgrel=1
pkgdesc='A custom launcher for Minecraft that allows you to easily manage multiple installations of Minecraft at once'
arch=('x86_64')
depends=('libqt5core5a' 'libqt5network5' 'libqt5gui5')

build() {
    cmake -DLauncher_LAYOUT=lin-system -DCMAKE_INSTALL_PREFIX="${pkgdir}/usr}" ../../../
}

package() {
    make "-j$(nproc)" install
}
```

I also saw in https://github.com/PolyMC/PolyMC/issues/53 that you guys created an Arch Linux package - makedeb would allow you to keep using that file just fine for the Debian package (makedeb uses the same PKGBUILD format with some minor alterations), with the only thing that would likely need changing would be the dependency names.

Any thoughts?

**Comment by d-513** [comment]
good idea, I made the debian package originally so I'll try turning that to makedeb
the reason it originally used the script was just to always have the correct version. Since this looks like a shell script, I should be able to set version to `$(git describe --tags | sed 's/-.*//')` like the script does, right?

**Comment by hwittenborn** [comment]
Great! Yeah, your proposed method for setting the version should work just fine as long as it worked previously. Everything is indeed a shell script like you said.

**Comment by LennyMcLennington** [comment]
> good idea, I made the debian package originally so I'll try turning that to makedeb the reason it originally used the script was just to always have the correct version. Since this looks like a shell script, I should be able to set version to `$(git describe --tags | sed 's/-.*//')` like the script does, right?

If it's like makepkg then you should define the pkgver function

**Comment by d-513** [comment]
Ok, i'm finally home on my debian-based machine so i'll work on it today and PR it if it works nicely

**Comment by d-513** [comment]
Made a PR. I also added the PKGBUILD to the Makedeb package repository (MPR) as polymc

**Comment by djmattyg007** [comment]
You might wanna consider using `fpm` instead, which will allow you to more easily build packages for many common distributions with a common CLI interface.

**Comment by hwittenborn** [comment]
Added a tiny review to your PR @dada513 :)

**Comment by ghost** [comment]
packages are in MPR
