### ISSUE TITLE
Adding custom jars

### ISSUE THREAD

**Issue by Ahptt** [PolyMC/PolyMC#940]
### Role

I play really old versions of minecraft. (Infdev, Alpha, Beta)

### Suggestion

The only version of infdev available in PolyMC is inf-20100618. I need to run a slightly newer version, inf-20100624

### Benefit

So that I can run these versions through PolyMC with ease.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Hello, earlier this morning I was messing around in PolyMC to create an instance for an old Minecraft Infdev release. The furthest I was able to get was to create a Minecraft instance for a version below, and then attempt to add a custom jar, and replace that with the older infdev jar. I also attempted to modify the .json files to redirect the client jar to load but also found no success.

Maybe I could use some educating, but I do think that it would be a nice feature to have for the one-off cases such like this where I do need to run a minecraft jar not found natively in PolyMC. Many thanks for reviewing this!

**Comment by Scrumplex** [comment]
On the `Version` page of your instance, you can click on `Replace Minecraft.jar` on the sidebar. Then just select the JAR you actually want to run and it should be using that instead

Edit: Looks like this for me
![Custom Minecraft.jar](https://scrumplex.rocks/img/1658323170.png)

**Comment by Ahptt** [comment]
Thanks Scumplex! I had initially messed with the custom jar just like you did, but I didn't leave it in the configuration you had. It worked flawlessly with your setup.
