### ISSUE TITLE
I can't add more than one Microsoft account

### ISSUE THREAD

**Issue by StarskyXIII** [PolyMC/PolyMC#946]
### Operating System

Windows 11

### Version of PolyMC

PolyMC 1.4.0 (develop)

### Description of bug

If there already a Microsoft account, we can't add the other one.

### Steps to reproduce

Add a Microsoft account.

Then add an other one, it will do nothing

### Suspected cause

Maybe Qt6

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Scrumplex** [comment]
Maybe try to run a "Windows-Legacy" build from develop? Those use Qt 5 instead of Qt 6. If it also happens there then it's not related to Qt 6

https://github.com/PolyMC/PolyMC/actions/runs/2703213961

**Comment by flowln** [comment]
I must add that this also happens in the AppImage in Qt6 (from the latest GHA), but the develop branch built from source in Qt5 works fine.

**Comment by StarskyXIII** [comment]
Qt 5 works well for me.
![image](https://user-images.githubusercontent.com/71606873/180581861-b00e7247-b803-44b5-9998-8aec8eec2a50.png)
