### ISSUE TITLE
Instances with jar mods causes launcher to segfault

### ISSUE THREAD

**Issue by forkiesassds** [PolyMC/PolyMC#954]
### Operating System

Linux

### Version of PolyMC

1.4.0

### Description of bug

Instances that have jar mods cause the whole launcher to segfault

### Steps to reproduce

1.  Make instance
2. Add jar mod to it
3. Launch game
4. ????

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by forkiesassds** [comment]
This issue was caused some time in 1.4.0 development.

**Comment by Scrumplex** [comment]
Can confirm
