### ISSUE TITLE
instance not launching with the custom command environment variables

### ISSUE THREAD

**Issue by pinchese** [PolyMC/PolyMC#960]
### Operating System

Linux

### Version of PolyMC

PolyMC 1.4.0

### Description of bug

using the environment variables described in the custom commands settings,
![image](https://user-images.githubusercontent.com/82222883/180626236-3c0d83dc-350a-41ed-bc83-5f2c91c6d697.png)
causes the command to exit with a code 0
![image](https://user-images.githubusercontent.com/82222883/180626264-0d744d1f-8570-41c0-944c-5e7eff4eca6b.png)

i am using the normal java vm 
![image](https://user-images.githubusercontent.com/82222883/180626283-0cb4b076-a085-45ac-bfd9-926d95fcffd5.png)
so i don't think it has anything to do with the java vm i'm using,
as i've tested it with another java vm and it's done the same thing

however, if i remove the environment variable, and replace it with just "java", it works fine
![image](https://user-images.githubusercontent.com/82222883/180626320-0e5d94d2-e205-4d42-8114-f3e6884621c1.png)

it also works with the other java vm
![image](https://user-images.githubusercontent.com/82222883/180626367-8f24798e-34f2-4e4e-98d5-c0b921390eee.png)

### Steps to reproduce

assuming this isn't just a thing with packwiz, or the INST_JAVA variable,

* assign any launch command
* use one of the environment variables
* watch as the game just doesn't launch

after you do that

* replace the environment variable with a direct path or argument or whatever
* watch as it works

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by pinchese** [comment]
this is how the launch command looks in the settings btw 
![image](https://user-images.githubusercontent.com/82222883/180626490-5d2edbc5-ffe4-4072-8604-18db2a4866d0.png)

the same thing also happens if i surround the env variable in quotation marks

**Comment by flowln** [comment]
fixed in https://github.com/PolyMC/PolyMC/commit/ba7dfb360c53b717b76ba7197ae40d2f9f59a659, i'll keep this open until we release 1.4.1 (soon :tm:)

**Comment by pinchese** [comment]
ah okay, thank you!

**Comment by flowln** [comment]
Should be fixed now!
