### ISSUE TITLE
PacStall

### ISSUE THREAD

**Issue by Lolothepro** [PolyMC/PolyMC#962]
### Role

To allow PolyMC to be used without using Una or Makedeb

### Suggestion

Add a pacstall repository

### Benefit

To allow downloading PolyMC from Pacstall without using una or makedeb.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by DioEgizio** [comment]
Duplicate of #266
