### ISSUE TITLE
Support Replay Mod in mod downloader / updater

### ISSUE THREAD

**Issue by ryanccn** [PolyMC/PolyMC#977]
### Role

Yay!

### Suggestion

Maybe support Replay Mod as a special case in the mod downloader and updater?

### Benefit

A lot of people do use Replay Mod, and it is not distributed on any of the major platforms.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

There is a version manifest at https://github.com/ReplayMod/ReplayMod/blob/master/versions.json.

Download links are in the format `https://www.replaymod.com/download/download_new.php?version=${version}`.

**Comment by ryanccn** [comment]
I do realize this would deviate from standard packwiz as packwiz does *not* support Replay Mod

**Comment by DioEgizio** [comment]
Why should we add support for a single mod? Makes no sense to me, replaymod should just be distribed in mod hosting platforms

**Comment by ryanccn** [comment]
> Why should we add support for a single mod? Makes no sense to me, replaymod should just be distribed in mod hosting platforms

There's also the Replay Mod fork of Sodium

**Comment by Scrumplex** [comment]
There is no value in creating a solution just for ReplayMod, or OptiFine for that matter. If you want to download those mods from the launcher, then tell the developers of those mods to publish to Modrinth or Curseforge

**Comment by DioEgizio** [comment]
Btw they also could release on GH releases, and that's covered by #424

**Comment by ryanccn** [comment]
That is a good idea
