### ISSUE TITLE
Icon theme switching when closing settings menu

### ISSUE THREAD

**Issue by kumquat-ir** [PolyMC/PolyMC#98]
### Description of bug

On certain icon theme settings, opening and closing the settings menu causes the icons to flip between two different icon sets

### Steps to reproduce

Set theme settings to this:
![image](https://user-images.githubusercontent.com/66188216/150830976-55614d5f-65b7-4185-a55b-ba44fe0d38b0.png)

and then just open and close the settings menu -

https://user-images.githubusercontent.com/66188216/150831755-f0d72a75-f236-47e0-9fc3-d9be67f5def1.mp4

(bad video quality because i haven't bothered to fix my obs settings, should still show the bug clearly enough)
I am using X11 (XFCE) on Linux, if that matters

### Suspected cause

Likely caused by 81fe41a038ee12ff2ee0200525b39e4ad650bec2

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Scrumplex** [comment]
I have the same issue btw.

Interestingly enough, if I close the settings with the escape key it doesn't toggle the icon theme.

**Comment by ghost** [comment]
Probably because a default was forgotten to be changed.

I'll grep for it when I'm home from el roboto

**Comment by DioEgizio** [comment]
I can reproduce
