### ISSUE TITLE
clicking more news before news have loaded causes a segfault

### ISSUE THREAD

**Issue by DioEgizio** [PolyMC/PolyMC#980]
### Operating System

Windows, macOS, Linux, Other

### Version of PolyMC

PolyMC 1.4.0

### Description of bug

clicking more news before news have loaded causes a segfault

### Steps to reproduce

- click more news before news have loaded
- see 

### Suspected cause

#845 

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by txtsd** [comment]
CC @flowln

**Comment by flowln** [comment]
I'm thinking of just removing the "More news..." button, it's superfluous to the other one imo

**Comment by txtsd** [comment]
> I'm thinking of just removing the "More news..." button, it's superfluous to the other one imo

The More News button opens it with the articles list loaded, while the news line itself does not.

But yea, might make sense to remove the button altogether. And possibly do a "Loading..." in the news articles while they load.

**Comment by DioEgizio** [comment]
> I'm thinking of just removing the "More news..." button, it's superfluous to the other one imo

Imo it might make sense to make a section for Minecraft news and yeet more news
