### ISSUE TITLE
Mods missing in "Download mods"

### ISSUE THREAD

**Issue by JustCryen** [PolyMC/PolyMC#983]
### Operating System

ArchLinux

### Version of PolyMC

PolyMC 1.3.2-404b9599

### Description of bug

A lot of mods are missing in the online search.
In my case, I was going to setup a fresh 1.16.5 Fabric instance. I was looking for Sodium, Indium, OptiFabric, Mod Menu and so on.
There were no mods in the list, I tried changing filters and only "any version" option showed the mods but did not allow me to download them.
It turns out that all of these mods do in fact work with 1.16.5 and are available in CurseForge with corresponding version but for some reason all of them were excluded in search.
Some other mods work without any issues so I'm not sure what's up with that.

This issue obviously did not occur with the newest 1.19 version of MC 

### Steps to reproduce

1. Create a new 1.16.5 Fabric instance. [Forge 36.2.39]
2. Enter "Mods" tab and click "Download mods"
3. Search for any of these mods [Sodium, Indium, OptiFabric, Mod Menu]
4. Do the same manually on the website, since they have 1.16.5 versions I'd think the mods should appear in the PolyMC "Download mods" window.

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by flowln** [comment]
> Create a new 1.16.5 Fabric instance. [Forge 36.2.39]

Are you using Fabric or Forge?

**Comment by JustCryen** [comment]
Sorry, I missclicked and ended up installing Forge version instead of Fabric.
