### ISSUE TITLE
Cannot add a second Microsoft account

### ISSUE THREAD

**Issue by shadowcatzero** [PolyMC/PolyMC#984]
### Operating System

Linux

### Version of PolyMC

PolyMC 1.4.0

### Description of bug

I tried to log in through a second Microsoft account, so I opened the link in a browser, entered the code, signed in, and hit allow, and it appeared to work. However, the account did not appear in the list of accounts, and therefore I could not use it.

I tried running it in my terminal (I'm on arch) and it even appeared to work in the terminal output:
[log.txt](https://github.com/PolyMC/PolyMC/files/9194417/log.txt)

However, like I said, the account did not get added to the list of accounts:
![image](https://user-images.githubusercontent.com/79327866/181144332-c799dbc6-924f-4170-9c42-02f164ab37c1.png)

I've tried deleting `accounts.json` to reset the accounts, and that didn't work; I was able to add either of my two accounts for the first time, but when I tried to add the other it would not work.

### Steps to reproduce

* add a microsoft account for the first time (works)
  * click on add microsoft
  * open the webpage
  * go through it until it says it can be closed
* add a second microsoft account (same steps, does not work)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by timoreo22** [comment]
Known issue, fixed in develop

**Comment by timoreo22** [comment]
See #946 for temporary workaround

**Comment by shadowcatzero** [comment]
Sorry, somehow I didn't see that while searching, thanks.
