### ISSUE TITLE
Add high process priority option 

### ISSUE THREAD

**Issue by brucethemoose** [PolyMC/PolyMC#987]
### Role

Playing performance-intensive modpacks

### Suggestion

Add an option to run Minecraft at a high priority

### Benefit

This can increase framerates and reduce stutters, particularly on congested or heavily loaded systems.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Unfortunately the implementation must be platform specific. For instance, on windows, this can be done with `start /high ...`, and on linux with `nice -n -19 ...`

I can't find a way to get this to work via a wrapper command on Windows 10. For instance,  `start` simply isn't recognized, and  `cmd /c start /high ...` errors our because of the character limit. But even if this is possible via a wrapper command, exposing this option to users more directly would be beneficial.

**Comment by ZekeZDev** [comment]
This is very system specific and I would argue its out of scope for a launcher. I am going to close this issue for now
