### ISSUE TITLE
[Feature Request] Add option to keep "global" Resource folders (Resourcepacks, Shaderpacks, maybe saves, maybe mods) via symlinks/hardlinks

### ISSUE THREAD

**Issue by TayouVR** [PolyMC/PolyMC#989]
### Role

I play Minecraft

### Suggestion

have a way to use the same folder for various resources

### Benefit

save on storage space and copy/paste efforts

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Currently for every instance I manually symlink my global resourcepack and shaderpack folders. 
This logic could be applied to saves and mods too, although that is a bit more difficult as you generally don't have two instances with the same mods folders... Saves, maybe

Though for mods, they could be stored somewhere centrally and symlinked into the various instances individually. That is more of a thing for a second issue though. This is more about shader- and resourcepack folders

**Comment by DioEgizio** [comment]
#73

**Comment by TayouVR** [comment]
ah, different title and generally wording... I tried to search for a few keywords, but not the ones in use there x3
