### ISSUE TITLE
mod download version match is buggy/non-intuitive

### ISSUE THREAD

**Issue by drwoops** [PolyMC/PolyMC#995]
### Operating System

Linux

### Version of PolyMC

PolyMC 1.4.1

### Description of bug

on an 1.19 instance, when i search modrinth for mods, i do not get matches for 1.19.1 even when selecting to filter for major version.  I do not know if this is a bug or intended behaviour.  if the latter, then clarification is needed.

### Steps to reproduce

on 1.19 instance, click download mods, filter for major version, search for lithium the most recent version for 1.19.1 (0.8.3) is not among the matches.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Scrumplex** [comment]
We are shifting this fix to 5.0 (formerly 1.5.0), as it is incompatible with the 1.4.1 codebase

**Comment by flowln** [comment]
We backported it to 1.4.2 :)
