### ISSUE TITLE
packwiz-installer updating mods causes issues with generated metadata

### ISSUE THREAD

**Issue by DioEgizio** [PolyMC/PolyMC#996]
### Operating System

Windows, macOS, Linux, Other

### Version of PolyMC

PolyMC 1.4.0/1.4.1

### Description of bug

If packwiz-installer updates a mod that EnsureMetadataTask generated metadata for, it gets duplicated 

![](https://media.discordapp.net/attachments/923671344921600201/1003023466133454988/unknown.png?width=1129&height=1170)

### Steps to reproduce

.

### Suspected cause

#426 

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by flowln** [comment]
is there a way to get the list of updated mods from packwiz-installer :thinking:? if not, i'd probably just hide or delete metadata files that don't have a corresponding jar file
