### ISSUE TITLE
Forge Instant Crash

### ISSUE THREAD

**Issue by trilliam25** [PolyMC/PolyMC#999]
### Operating System

Windows

### Version of PolyMC

PolyMC 1.4.0

### Description of bug

The launcher attempts to launch the instance, but immediately crashes after opening the console. 

### Steps to reproduce

Any version of forge for 1.2.5 reproduces this issue. Vanilla MC does not.

### Suspected cause

May be related to #986, but the issue is not intermittent, and happens on any forge version associated with Minecraft 1.2.5

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by flowln** [comment]
Try updating to version 1.4.1, to see if that fixes the issue

**Comment by trilliam25** [comment]
Update to 1.4.1 fixed the issue. Thank you for your help and patience.
